"""Guilt, innocence and a shrink-only ledger for gold's `**PMA:**` sentence.

The defect this pins: `apps/mouth/data/kbli-gold-all.json` OVERRIDES canonical
on every rendered page, and its `whatYouNeed` restates the foreign-ownership
cap — a fact it does not own. On 2026-08-07 that restatement disagreed with the
canonical record on 20 comparable codes, sixteen of them promising MORE foreign
ownership than the law allows, live, including scheduled airlines (`51101`,
cap 49) and Umrah/Hajj travel (`79122`, cap 0).

Why a test and not just a cure: the sentence is machine-generated by three
different enrichment scripts, so the next regeneration re-creates it. A cure
without a guard is a cure with a countdown.

The exception list is NAMED and may only SHRINK. Each entry says why a compiler
must not touch it — "needs adjudication" is a state, not a licence, and the
count in `test_exception_list_only_shrinks` is the ratchet.
"""

from __future__ import annotations

import copy
import json
import sys
from pathlib import Path

import pytest

_FILIERA = Path(__file__).resolve().parents[1]
if str(_FILIERA) not in sys.path:
    sys.path.insert(0, str(_FILIERA))

import cure_gold_pma_line as C  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[3]

# Codes whose gold PMA sentence disagrees with canonical and which a COMPILER
# must not rewrite. Every one needs a per-code adjudication, not a deduction.
# This list may only shrink.
# 2026-08-07: 5 of the original 7 were adjudicated against the vaulted Perpres
# 10/2021-as-amended-by-49/2021 instruments; the adjudication survived a
# cross-family adversarial review (Gemini agy, instructed to refute). Four
# were cured (73100, 47221, 86202, 47222 — see
# cure_gold_pma_line.py::AUTHORED_SENTENCES and, for 47222's canonical
# pma_status, cure_canonical_47222_reservation.py).
# 2026-08-08: the last two closed the ledger to EMPTY. 41011's earlier
# "permissive cure REFUTED" note is superseded — the primary-source read it
# asked for was done this session (Perpres 49/2021 Lampiran II p.6,
# dialokasikan column, segment-qualified bucket: only the sederhana/madya
# residential-building slice is UMKM/Koperasi-allocated, not the whole code)
# and the two-part truth is now authored in cure_gold_pma_line.py::
# AUTHORED_SENTENCES["41011"]. 65121 is cured under PP 14/2018 Pasal 5(1) jo.
# PP 3/2020 (Perpres 10/2021 Pasal 11(2) sector-law carve-out) — see
# AUTHORED_SENTENCES["65121"] and cure_canonical_asuransi_pp14_cap.py for the
# matching canonical flip. 86101 remains cured (2026-08-07, see below).
ADJUDICATION_BACKLOG: dict[str, str] = {}
# 86101 cured 2026-08-07: the whole card described a PRIVATE hospital on the
# STATE hospital code and was replaced field-by-field (not a sentence swap —
# see cure_gold_86101_government_hospital.py + cure_specs/
# gold_86101_government_hospital_2026_08_07.json). The new text carries no
# `**PMA:**` sentence at all, so it no longer registers with C.scan() —
# confirmed below rather than assumed.


@pytest.fixture(scope="module")
def stores():
    canon = json.loads(
        (REPO_ROOT / "data/source_documents/KBLI_2025_FINAL_CLEAN.json").read_text(
            encoding="utf-8"
        )
    )
    gold_raw = json.loads(
        (REPO_ROOT / "apps/mouth/data/kbli-gold-all.json").read_text(encoding="utf-8")
    )
    return {r["kode_kbli_2025"]: r for r in canon["data"]}, gold_raw.get(
        "data", gold_raw
    )


# ── the live ledger ─────────────────────────────────────────────────────────


def _backlog_mismatch(gold: dict, by_code: dict, backlog: dict | None = None) -> set[str]:
    """Symmetric difference between what the scanner flags (findings ∪
    incomparable) and the backlog's keys — empty iff they agree exactly.
    `backlog` defaults to the live ADJUDICATION_BACKLOG; a test may pass a
    synthetic one to exercise the detector without depending on real gold
    wording that a cure could change out from under it.

    A one-directional check (findings ⊆ backlog) only catches a NEW,
    unnamed divergence; it says nothing if a NAMED backlog entry stops
    producing a finding — e.g. its wrong sentence is silently deleted or
    rewritten to agree with canonical without going through adjudication.
    That is a real event (the ledger's own claim about the file is now
    false) and round-4 review caught it as a hole: the old test would stay
    green while ADJUDICATION_BACKLOG quietly went stale. Set-EQUALITY closes
    both directions with one assertion.
    """
    if backlog is None:
        backlog = ADJUDICATION_BACKLOG
    incomparable: list = []
    findings = C.scan(gold, by_code, incomparable)
    found_or_incomparable = set(findings) | {c for c, *_ in incomparable}
    return found_or_incomparable ^ set(backlog)


def test_no_gold_pma_sentence_contradicts_canonical(stores):
    by_code, gold = stores
    incomparable: list = []
    findings = C.scan(gold, by_code, incomparable)
    unexpected = {c: f for c, f in findings.items() if c not in ADJUDICATION_BACKLOG}
    assert unexpected == {}, (
        "gold restates the cap and now disagrees with the record on a code that "
        f"is not on the adjudication backlog: {sorted(unexpected)}. Re-derive it "
        "with scripts/kbli_filiera/cure_gold_pma_line.py --apply, or add it to "
        "ADJUDICATION_BACKLOG with the reason a compiler must not touch it."
    )
    for code, _stated, _cap, _s in incomparable:
        assert code in ADJUDICATION_BACKLOG, (
            f"{code}: gold states a figure the canonical cap cannot be compared "
            "against. Not comparable is not clean — name it."
        )
    mismatch = _backlog_mismatch(gold, by_code)
    assert mismatch == set(), (
        f"the scanner's findings/incomparable keys and ADJUDICATION_BACKLOG's "
        f"keys no longer match exactly — symmetric difference {sorted(mismatch)}. "
        "A backlog entry that stops producing a finding did not get adjudicated "
        "— its wrong sentence vanished without a cure being recorded. "
        "Investigate; do not shrink ADJUDICATION_BACKLOG to make this pass."
    )


def test_backlog_mismatch_detector_catches_a_vanished_finding(stores):
    """Guilt for `_backlog_mismatch`, on a SYNTHETIC scenario rather than a
    real code's live wording — with ADJUDICATION_BACKLOG now empty (2026-08-08:
    41011 and 65121 both cured), pinning this test to 41011's actual sentence
    would make it depend on text a future cure is free to change again. A
    synthetic code exercises the same detector logic without that coupling.

    A fake backlog names a code whose gold text does NOT diverge from
    canonical (as if a real divergence had been silently fixed without going
    through adjudication) — the detector must report that entry as a
    vanished finding, proving the set-equality guard is not a decoration.
    """
    by_code, gold = stores
    synthetic_canon = dict(by_code)
    synthetic_canon["99001"] = {
        "kode_kbli_2025": "99001",
        "pma_max_asing": 100,
        "pma_status": "TERBUKA",
        "judul": "Synthetic test code — never a real KBLI",
    }
    synthetic_gold = copy.deepcopy(gold)
    synthetic_gold["99001"] = {
        "whatYouNeed": "**PMA:** Fully open — 100% foreign ownership allowed."
    }
    # This sentence AGREES with canonical (cap 100, stated 100%) — no real
    # divergence — yet a fake backlog names it anyway, as if a cure had
    # already silently resolved it without going through adjudication.
    fake_backlog = {"99001": "synthetic: pretend this needed adjudication"}
    mismatch = _backlog_mismatch(synthetic_gold, synthetic_canon, backlog=fake_backlog)
    assert mismatch == {"99001"}


def test_backlog_mismatch_detector_is_innocent_when_backlog_is_empty(stores):
    """Innocence for the same detector: the real, live stores with the real
    (now-empty) ADJUDICATION_BACKLOG must show zero mismatch — proving the
    ledger is not just "empty" but actually EMPTY-AND-CORRECT against live
    gold/canonical data."""
    by_code, gold = stores
    assert _backlog_mismatch(gold, by_code) == set()


def test_exception_list_only_shrinks():
    # 2026-08-07: 7 -> 3 -> 2. 2026-08-08: 2 -> 0 (41011 and 65121 both
    # adjudicated and cured). This number may only shrink further; it can
    # never go back up.
    assert len(ADJUDICATION_BACKLOG) <= 0
    assert set(ADJUDICATION_BACKLOG) == set()
    assert all(v.strip() for v in ADJUDICATION_BACKLOG.values()), "a reason is required"


def test_86101_card_replacement_left_no_pma_sentence_for_the_scanner(stores):
    """86101 was cured by a whole-field replacement, not a sentence swap — the
    new text names no percentage at all. Guards against a future re-author
    silently reintroducing a `**PMA:**` sentence the scanner would have to
    judge: if that happens this test goes red before the ledger does."""
    by_code, gold = stores
    findings = C.scan(gold, by_code)
    assert "86101" not in findings
    prose = C.prose_scan(gold, by_code)
    assert "86101" not in prose


def test_the_sixteen_more_open_codes_are_gone_from_the_live_file(stores):
    """The cure's own claim, asserted against the file rather than the log.

    These sixteen promised more foreign ownership than the record allows. One
    stays on the backlog (86101 — the whole record needs a rewrite, not a
    sentence swap); the other fifteen (including 47222, cured 2026-08-07 via
    AUTHORED_SENTENCES) must be gone.
    """
    by_code, gold = stores
    cured = [
        "41016", "41018", "50131", "50132", "50133", "50213", "51101",
        "51102", "53200", "55105", "59111", "59121", "79122", "91221",
    ]
    findings = C.scan(gold, by_code)
    assert [c for c in cured if c in findings] == []
    # and the direction is right on the two that matter most to a client
    assert "Restricted — max 49%" in gold["51101"]["whatYouNeed"]
    assert "Closed to foreign investment" in gold["79122"]["whatYouNeed"]


# ── the prose net, and the acquittal it must not overturn ───────────────────


def test_prose_openness_on_capped_codes_is_only_the_named_ones(stores):
    by_code, gold = stores
    found = set(C.prose_scan(gold, by_code))
    allowed = set(C.PROSE_ACQUITTED) | set(ADJUDICATION_BACKLOG)
    assert found <= allowed, (
        f"gold asserts openness in words on a capped code nobody has named: "
        f"{sorted(found - allowed)}"
    )


def test_47111_keeps_the_sentence_that_belongs_to_another_code(stores):
    """The innocence that matters most here.

    `47111` is cap 0 and its `baliContext` says "All fully open to 100% PMA" —
    about **47191**, named two lines above as "The PMA alternative", in a
    passage that also says "foreigners cannot own 47111". A sweep that reads the
    percentage and not the entity would rewrite a correct paragraph into a wrong
    one. It is on PROSE_ACQUITTED, and this test is what keeps it there.
    """
    _by_code, gold = stores
    ctx = gold["47111"]["baliContext"]
    assert "47191" in ctx and "fully open to 100% PMA" in ctx
    assert "foreigners cannot own 47111" in ctx
    assert "47111" in C.PROSE_ACQUITTED


def test_guilt_prose_openness_three_fields_from_the_pma_sentence():
    canon = {"90001": {"kode_kbli_2025": "90001", "pma_max_asing": 49,
                       "pma_status": "TERBATAS", "judul": "Test"}}
    gold = {"90001": {
        "whatYouNeed": "**PMA:** Restricted — max 49% foreign ownership.",
        "baliContext": "Since this is fully open to foreign investment, budget IDR 10bn.",
    }}
    hits = C.prose_scan(gold, canon)
    assert "90001" in hits and hits["90001"][0][1] == "baliContext"


def test_innocence_prose_net_ignores_a_code_that_is_actually_open():
    canon = {"90001": {"kode_kbli_2025": "90001", "pma_max_asing": 100,
                       "pma_status": "TERBUKA", "judul": "Test"}}
    gold = {"90001": {"baliContext": "This activity is fully open to foreign investment."}}
    assert C.prose_scan(gold, canon) == {}


def test_the_authored_sentences_are_in_the_live_file(stores):
    """DECLARED (round-4 review, no change requested): this exact-sentence pin
    is deliberately kept word-for-word rather than loosened to a substring or
    fact-based check — `AUTHORED_SENTENCES`'s `old`/`new` pair IS the archive
    of what changed and why (see cure_gold_pma_line.py's module docstring);
    a looser check would stop proving the archived text is what actually
    shipped."""
    _by_code, gold = stores
    for code, a in C.AUTHORED_SENTENCES.items():
        live = gold[code][a["field"]]
        assert a["new"] in live, f"{code}: the authored sentence is not in the file"
        assert a["old"] not in live, f"{code}: the sentence it replaced is still there"


# ── guilt ───────────────────────────────────────────────────────────────────


def test_guilt_a_pma_marker_with_the_colon_inside_the_bold_is_seen():
    """`41020` wrote `**PMA: TERBUKA 100% — …**`. The first version of the
    sentence pattern was written from the `**PMA:**` shape already in hand and
    was blind to this one, on a cap-0 code."""
    canon, gold = _mini(0, "**PMA: TERBUKA 100% — fully open to foreign ownership.**")
    f = C.scan(gold, canon)
    assert "90001" in f and f["90001"]["stated"] == 100 and f["90001"]["more_open"]


def _mini(cap, sentence, status="TERBATAS"):
    canon = {"90001": {"kode_kbli_2025": "90001", "pma_max_asing": cap,
                       "pma_status": status, "judul": "Test"}}
    gold = {"90001": {"whatYouNeed": f"1. **NIB via OSS**\n\n{sentence}\n\nmore text"}}
    return canon, gold


def test_guilt_a_more_open_figure_is_caught():
    canon, gold = _mini(49, "**PMA:** Fully open — 100% foreign ownership allowed.")
    f = C.scan(gold, canon)
    assert "90001" in f and f["90001"]["more_open"] is True
    assert f["90001"]["is_default"] is True


def test_guilt_a_more_restrictive_figure_is_caught_but_refused():
    canon, gold = _mini(100, "**PMA:** Restricted — max 49% foreign ownership.", "TERBUKA")
    f = C.scan(gold, canon)
    assert "90001" in f and f["90001"]["more_open"] is False
    patch, refused = C.plan(f, gold)
    assert patch == {} and "90001" in refused


def test_guilt_closed_wording_counts_as_zero_not_as_no_figure():
    """`Closed to foreign investment` states 0% without writing a digit — a
    reader of the sentence knows that, and so must the scan."""
    canon, gold = _mini(100, "**PMA:** Closed to foreign investment — domestic entities only.", "TERBUKA")
    assert C.scan(gold, canon)["90001"]["stated"] == 0


def test_guilt_a_hand_authored_sentence_is_refused_not_rewritten():
    canon, gold = _mini(
        0, "**PMA:** Fully open — 100% foreign ownership, WITH mandatory Kemenkes authorization."
    )
    f = C.scan(gold, canon)
    assert f["90001"]["is_default"] is False
    patch, refused = C.plan(f, gold)
    assert patch == {} and "90001" in refused


# ── innocence ───────────────────────────────────────────────────────────────


def test_innocence_an_agreeing_sentence_is_not_a_finding():
    canon, gold = _mini(49, "**PMA:** Restricted — max 49% foreign ownership.")
    assert C.scan(gold, canon) == {}


def test_innocence_a_percentage_elsewhere_in_the_field_is_not_the_pma_figure():
    """The field is full of numbers — capital, timelines, other percentages.
    Only the PMA sentence's own figure may convict it."""
    canon = {"90001": {"kode_kbli_2025": "90001", "pma_max_asing": 100,
                       "pma_status": "TERBUKA", "judul": "Test"}}
    gold = {"90001": {"whatYouNeed":
        "Foreign staff may not exceed 30% of headcount.\n"
        "**PMA:** Fully open — 100% foreign ownership allowed.\n"
        "Local content target: 40%."}}
    assert C.scan(gold, canon) == {}


def test_innocence_a_code_with_no_pma_sentence_is_not_a_finding():
    canon = {"90001": {"kode_kbli_2025": "90001", "pma_max_asing": 49,
                       "pma_status": "TERBATAS", "judul": "Test"}}
    gold = {"90001": {"whatYouNeed": "1. **NIB via OSS** — auto-issued."}}
    assert C.scan(gold, canon) == {}


def test_innocence_replacement_never_touches_the_rest_of_the_field():
    canon, gold = _mini(49, "**PMA:** Fully open — 100% foreign ownership allowed.")
    patch, _ = C.plan(C.scan(gold, canon), gold)
    new = patch["90001"]["new"]
    assert new.startswith("1. **NIB via OSS**") and new.endswith("more text")
    assert "Fully open" not in new


# ── the resolver ladder, kept in step with the TypeScript one ───────────────


@pytest.mark.parametrize(
    "rec,expected",
    [
        ({"pma_max_asing": 49}, 49),
        ({"pma_max_asing": "49"}, 49),
        ({"pma_max_asing": "special"}, "special"),
        ({"pma_max_asing": None, "pma_status": "TERBUKA"}, 100),
        ({"pma_max_asing": None, "pma_status": "TERTUTUP"}, 0),
        # TERBATAS spans 0/49/100 and a non-percentage regime: inventing a
        # figure is the defect the resolver exists to prevent.
        ({"pma_max_asing": None, "pma_status": "TERBATAS"}, "special"),
    ],
)
def test_resolve_cap_mirrors_the_typescript_resolver(rec, expected):
    assert C.resolve_cap(rec) == expected


def test_derived_sentence_states_only_the_records_own_cap():
    assert C.derived_sentence(0) == "**PMA:** Closed to foreign investment — domestic entities only."
    assert "49%" in C.derived_sentence(49) and "100" not in C.derived_sentence(49)
    assert "100% foreign ownership allowed" in C.derived_sentence(100)
