"""Guilt, innocence and a shrink-only ledger for gold's `**PMA:**` sentence.

The defect this pins: `apps/mouth/data/kbli-gold-all.json` OVERRIDES canonical
on every rendered page, and its `whatYouNeed` restates the foreign-ownership
cap — a fact it does not own. On 2026-08-07 that restatement disagreed with the
canonical record on 20 comparable codes, sixteen of them promising MORE foreign
ownership than the law allows, live, including scheduled airlines (`51101`,
cap 49) and Umrah/Hajj travel (`79122`, cap 0).

Why a test and not just a cure: the sentence is machine-generated by three
different enrichment scripts, so the next regeneration re-creates it. A cure
without a guard is a cure with a countdown.

The exception list is NAMED and may only SHRINK. Each entry says why a compiler
must not touch it — "needs adjudication" is a state, not a licence, and the
count in `test_exception_list_only_shrinks` is the ratchet.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

_FILIERA = Path(__file__).resolve().parents[1]
if str(_FILIERA) not in sys.path:
    sys.path.insert(0, str(_FILIERA))

import cure_gold_pma_line as C  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[3]

# Codes whose gold PMA sentence disagrees with canonical and which a COMPILER
# must not rewrite. Every one needs a per-code adjudication, not a deduction.
# This list may only shrink.
# 2026-08-07: 5 of the original 7 were adjudicated against the vaulted Perpres
# 10/2021-as-amended-by-49/2021 instruments; the adjudication survived a
# cross-family adversarial review (Gemini agy, instructed to refute). Four
# were cured (73100, 47221, 86202, 47222 — see
# cure_gold_pma_line.py::AUTHORED_SENTENCES and, for 47222's canonical
# pma_status, cure_canonical_47222_reservation.py). 41011's permissive cure
# was REFUTED and its reason below replaces the earlier one. 65121 and 86101
# are untouched.
ADJUDICATION_BACKLOG = {
    "41011": (
        "gold 67% vs canonical 100% — permissive cure REFUTED by cross-family "
        "review 2026-08-07: a sectoral construction JV cap (67%/70% ASEAN, "
        "BUJKN partnership, Besar-only qualification) may survive the Perpres "
        "via UU 2/2017/PUPR instruments; needs a primary-source read before "
        "any change"
    ),
    "65121": "gold cites a historical 80% acquisition cap vs canonical 100%",
}
# 86101 cured 2026-08-07: the whole card described a PRIVATE hospital on the
# STATE hospital code and was replaced field-by-field (not a sentence swap —
# see cure_gold_86101_government_hospital.py + cure_specs/
# gold_86101_government_hospital_2026_08_07.json). The new text carries no
# `**PMA:**` sentence at all, so it no longer registers with C.scan() —
# confirmed below rather than assumed.


@pytest.fixture(scope="module")
def stores():
    canon = json.loads(
        (REPO_ROOT / "data/source_documents/KBLI_2025_FINAL_CLEAN.json").read_text(
            encoding="utf-8"
        )
    )
    gold_raw = json.loads(
        (REPO_ROOT / "apps/mouth/data/kbli-gold-all.json").read_text(encoding="utf-8")
    )
    return {r["kode_kbli_2025"]: r for r in canon["data"]}, gold_raw.get(
        "data", gold_raw
    )


# ── the live ledger ─────────────────────────────────────────────────────────


def test_no_gold_pma_sentence_contradicts_canonical(stores):
    by_code, gold = stores
    incomparable: list = []
    findings = C.scan(gold, by_code, incomparable)
    unexpected = {c: f for c, f in findings.items() if c not in ADJUDICATION_BACKLOG}
    assert unexpected == {}, (
        "gold restates the cap and now disagrees with the record on a code that "
        f"is not on the adjudication backlog: {sorted(unexpected)}. Re-derive it "
        "with scripts/kbli_filiera/cure_gold_pma_line.py --apply, or add it to "
        "ADJUDICATION_BACKLOG with the reason a compiler must not touch it."
    )
    for code, _stated, _cap, _s in incomparable:
        assert code in ADJUDICATION_BACKLOG, (
            f"{code}: gold states a figure the canonical cap cannot be compared "
            "against. Not comparable is not clean — name it."
        )


def test_exception_list_only_shrinks():
    # 2026-08-07: 7 -> 3 -> 2 (five adjudicated and cured, 86101 last). Lower
    # this number when one is adjudicated; never raise it.
    assert len(ADJUDICATION_BACKLOG) <= 2
    assert all(v.strip() for v in ADJUDICATION_BACKLOG.values()), "a reason is required"


def test_86101_card_replacement_left_no_pma_sentence_for_the_scanner(stores):
    """86101 was cured by a whole-field replacement, not a sentence swap — the
    new text names no percentage at all. Guards against a future re-author
    silently reintroducing a `**PMA:**` sentence the scanner would have to
    judge: if that happens this test goes red before the ledger does."""
    by_code, gold = stores
    findings = C.scan(gold, by_code)
    assert "86101" not in findings
    prose = C.prose_scan(gold, by_code)
    assert "86101" not in prose


def test_the_sixteen_more_open_codes_are_gone_from_the_live_file(stores):
    """The cure's own claim, asserted against the file rather than the log.

    These sixteen promised more foreign ownership than the record allows. One
    stays on the backlog (86101 — the whole record needs a rewrite, not a
    sentence swap); the other fifteen (including 47222, cured 2026-08-07 via
    AUTHORED_SENTENCES) must be gone.
    """
    by_code, gold = stores
    cured = [
        "41016", "41018", "50131", "50132", "50133", "50213", "51101",
        "51102", "53200", "55105", "59111", "59121", "79122", "91221",
    ]
    findings = C.scan(gold, by_code)
    assert [c for c in cured if c in findings] == []
    # and the direction is right on the two that matter most to a client
    assert "Restricted — max 49%" in gold["51101"]["whatYouNeed"]
    assert "Closed to foreign investment" in gold["79122"]["whatYouNeed"]


# ── the prose net, and the acquittal it must not overturn ───────────────────


def test_prose_openness_on_capped_codes_is_only_the_named_ones(stores):
    by_code, gold = stores
    found = set(C.prose_scan(gold, by_code))
    allowed = set(C.PROSE_ACQUITTED) | set(ADJUDICATION_BACKLOG)
    assert found <= allowed, (
        f"gold asserts openness in words on a capped code nobody has named: "
        f"{sorted(found - allowed)}"
    )


def test_47111_keeps_the_sentence_that_belongs_to_another_code(stores):
    """The innocence that matters most here.

    `47111` is cap 0 and its `baliContext` says "All fully open to 100% PMA" —
    about **47191**, named two lines above as "The PMA alternative", in a
    passage that also says "foreigners cannot own 47111". A sweep that reads the
    percentage and not the entity would rewrite a correct paragraph into a wrong
    one. It is on PROSE_ACQUITTED, and this test is what keeps it there.
    """
    _by_code, gold = stores
    ctx = gold["47111"]["baliContext"]
    assert "47191" in ctx and "fully open to 100% PMA" in ctx
    assert "foreigners cannot own 47111" in ctx
    assert "47111" in C.PROSE_ACQUITTED


def test_guilt_prose_openness_three_fields_from_the_pma_sentence():
    canon = {"90001": {"kode_kbli_2025": "90001", "pma_max_asing": 49,
                       "pma_status": "TERBATAS", "judul": "Test"}}
    gold = {"90001": {
        "whatYouNeed": "**PMA:** Restricted — max 49% foreign ownership.",
        "baliContext": "Since this is fully open to foreign investment, budget IDR 10bn.",
    }}
    hits = C.prose_scan(gold, canon)
    assert "90001" in hits and hits["90001"][0][1] == "baliContext"


def test_innocence_prose_net_ignores_a_code_that_is_actually_open():
    canon = {"90001": {"kode_kbli_2025": "90001", "pma_max_asing": 100,
                       "pma_status": "TERBUKA", "judul": "Test"}}
    gold = {"90001": {"baliContext": "This activity is fully open to foreign investment."}}
    assert C.prose_scan(gold, canon) == {}


def test_the_authored_sentences_are_in_the_live_file(stores):
    _by_code, gold = stores
    for code, a in C.AUTHORED_SENTENCES.items():
        live = gold[code][a["field"]]
        assert a["new"] in live, f"{code}: the authored sentence is not in the file"
        assert a["old"] not in live, f"{code}: the sentence it replaced is still there"


# ── guilt ───────────────────────────────────────────────────────────────────


def test_guilt_a_pma_marker_with_the_colon_inside_the_bold_is_seen():
    """`41020` wrote `**PMA: TERBUKA 100% — …**`. The first version of the
    sentence pattern was written from the `**PMA:**` shape already in hand and
    was blind to this one, on a cap-0 code."""
    canon, gold = _mini(0, "**PMA: TERBUKA 100% — fully open to foreign ownership.**")
    f = C.scan(gold, canon)
    assert "90001" in f and f["90001"]["stated"] == 100 and f["90001"]["more_open"]


def _mini(cap, sentence, status="TERBATAS"):
    canon = {"90001": {"kode_kbli_2025": "90001", "pma_max_asing": cap,
                       "pma_status": status, "judul": "Test"}}
    gold = {"90001": {"whatYouNeed": f"1. **NIB via OSS**\n\n{sentence}\n\nmore text"}}
    return canon, gold


def test_guilt_a_more_open_figure_is_caught():
    canon, gold = _mini(49, "**PMA:** Fully open — 100% foreign ownership allowed.")
    f = C.scan(gold, canon)
    assert "90001" in f and f["90001"]["more_open"] is True
    assert f["90001"]["is_default"] is True


def test_guilt_a_more_restrictive_figure_is_caught_but_refused():
    canon, gold = _mini(100, "**PMA:** Restricted — max 49% foreign ownership.", "TERBUKA")
    f = C.scan(gold, canon)
    assert "90001" in f and f["90001"]["more_open"] is False
    patch, refused = C.plan(f, gold)
    assert patch == {} and "90001" in refused


def test_guilt_closed_wording_counts_as_zero_not_as_no_figure():
    """`Closed to foreign investment` states 0% without writing a digit — a
    reader of the sentence knows that, and so must the scan."""
    canon, gold = _mini(100, "**PMA:** Closed to foreign investment — domestic entities only.", "TERBUKA")
    assert C.scan(gold, canon)["90001"]["stated"] == 0


def test_guilt_a_hand_authored_sentence_is_refused_not_rewritten():
    canon, gold = _mini(
        0, "**PMA:** Fully open — 100% foreign ownership, WITH mandatory Kemenkes authorization."
    )
    f = C.scan(gold, canon)
    assert f["90001"]["is_default"] is False
    patch, refused = C.plan(f, gold)
    assert patch == {} and "90001" in refused


# ── innocence ───────────────────────────────────────────────────────────────


def test_innocence_an_agreeing_sentence_is_not_a_finding():
    canon, gold = _mini(49, "**PMA:** Restricted — max 49% foreign ownership.")
    assert C.scan(gold, canon) == {}


def test_innocence_a_percentage_elsewhere_in_the_field_is_not_the_pma_figure():
    """The field is full of numbers — capital, timelines, other percentages.
    Only the PMA sentence's own figure may convict it."""
    canon = {"90001": {"kode_kbli_2025": "90001", "pma_max_asing": 100,
                       "pma_status": "TERBUKA", "judul": "Test"}}
    gold = {"90001": {"whatYouNeed":
        "Foreign staff may not exceed 30% of headcount.\n"
        "**PMA:** Fully open — 100% foreign ownership allowed.\n"
        "Local content target: 40%."}}
    assert C.scan(gold, canon) == {}


def test_innocence_a_code_with_no_pma_sentence_is_not_a_finding():
    canon = {"90001": {"kode_kbli_2025": "90001", "pma_max_asing": 49,
                       "pma_status": "TERBATAS", "judul": "Test"}}
    gold = {"90001": {"whatYouNeed": "1. **NIB via OSS** — auto-issued."}}
    assert C.scan(gold, canon) == {}


def test_innocence_replacement_never_touches_the_rest_of_the_field():
    canon, gold = _mini(49, "**PMA:** Fully open — 100% foreign ownership allowed.")
    patch, _ = C.plan(C.scan(gold, canon), gold)
    new = patch["90001"]["new"]
    assert new.startswith("1. **NIB via OSS**") and new.endswith("more text")
    assert "Fully open" not in new


# ── the resolver ladder, kept in step with the TypeScript one ───────────────


@pytest.mark.parametrize(
    "rec,expected",
    [
        ({"pma_max_asing": 49}, 49),
        ({"pma_max_asing": "49"}, 49),
        ({"pma_max_asing": "special"}, "special"),
        ({"pma_max_asing": None, "pma_status": "TERBUKA"}, 100),
        ({"pma_max_asing": None, "pma_status": "TERTUTUP"}, 0),
        # TERBATAS spans 0/49/100 and a non-percentage regime: inventing a
        # figure is the defect the resolver exists to prevent.
        ({"pma_max_asing": None, "pma_status": "TERBATAS"}, "special"),
    ],
)
def test_resolve_cap_mirrors_the_typescript_resolver(rec, expected):
    assert C.resolve_cap(rec) == expected


def test_derived_sentence_states_only_the_records_own_cap():
    assert C.derived_sentence(0) == "**PMA:** Closed to foreign investment — domestic entities only."
    assert "49%" in C.derived_sentence(49) and "100" not in C.derived_sentence(49)
    assert "100% foreign ownership allowed" in C.derived_sentence(100)
