"""Guilt, innocence and a shrink-only ledger for gold's `**PMA:**` sentence.

The defect this pins: `apps/mouth/data/kbli-gold-all.json` OVERRIDES canonical
on every rendered page, and its `whatYouNeed` restates the foreign-ownership
cap — a fact it does not own. On 2026-08-07 that restatement disagreed with the
canonical record on 20 comparable codes, sixteen of them promising MORE foreign
ownership than the law allows, live, including scheduled airlines (`51101`,
cap 49) and Umrah/Hajj travel (`79122`, cap 0).

Why a test and not just a cure: the sentence is machine-generated by three
different enrichment scripts, so the next regeneration re-creates it. A cure
without a guard is a cure with a countdown.

The exception list is NAMED and may only SHRINK. Each entry says why a compiler
must not touch it — "needs adjudication" is a state, not a licence, and the
count in `test_exception_list_only_shrinks` is the ratchet.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

_FILIERA = Path(__file__).resolve().parents[1]
if str(_FILIERA) not in sys.path:
    sys.path.insert(0, str(_FILIERA))

import cure_gold_pma_line as C  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[3]

# Codes whose gold PMA sentence disagrees with canonical and which a COMPILER
# must not rewrite. Every one needs a per-code adjudication, not a deduction.
# This list may only shrink.
ADJUDICATION_BACKLOG = {
    "41011": "gold 67% vs canonical 100% — gold is more restrictive; which is right is a ruling",
    "47221": "canonical cap is `special`; gold states 49% — no figure to compare against",
    "47222": "gold 49% + kemitraan condition vs canonical 0%/TERTUTUP; the note also cites alcoholic retail on a non-alcoholic code",
    "65121": "gold cites a historical 80% acquisition cap vs canonical 100%",
    "73100": "gold 49% + kemitraan vs canonical 100%; canonical's own locator for this family is unverifiable (10/2021 lampiran are text-layer-dead)",
    "86101": "whole record is written about a PRIVATE hospital on the STATE hospital code (cap 0/TERTUTUP) — a sentence swap would leave a closed line above a PT PMA step-by-step",
    "86202": "gold points the reader at 86103 'capped at 67%' while 86103's own canonical cap is 100",
}


@pytest.fixture(scope="module")
def stores():
    canon = json.loads(
        (REPO_ROOT / "data/source_documents/KBLI_2025_FINAL_CLEAN.json").read_text(
            encoding="utf-8"
        )
    )
    gold_raw = json.loads(
        (REPO_ROOT / "apps/mouth/data/kbli-gold-all.json").read_text(encoding="utf-8")
    )
    return {r["kode_kbli_2025"]: r for r in canon["data"]}, gold_raw.get(
        "data", gold_raw
    )


# ── the live ledger ─────────────────────────────────────────────────────────


def test_no_gold_pma_sentence_contradicts_canonical(stores):
    by_code, gold = stores
    incomparable: list = []
    findings = C.scan(gold, by_code, incomparable)
    unexpected = {c: f for c, f in findings.items() if c not in ADJUDICATION_BACKLOG}
    assert unexpected == {}, (
        "gold restates the cap and now disagrees with the record on a code that "
        f"is not on the adjudication backlog: {sorted(unexpected)}. Re-derive it "
        "with scripts/kbli_filiera/cure_gold_pma_line.py --apply, or add it to "
        "ADJUDICATION_BACKLOG with the reason a compiler must not touch it."
    )
    for code, _stated, _cap, _s in incomparable:
        assert code in ADJUDICATION_BACKLOG, (
            f"{code}: gold states a figure the canonical cap cannot be compared "
            "against. Not comparable is not clean — name it."
        )


def test_exception_list_only_shrinks():
    # 2026-08-07: 7. Lower this number when one is adjudicated; never raise it.
    assert len(ADJUDICATION_BACKLOG) <= 7
    assert all(v.strip() for v in ADJUDICATION_BACKLOG.values()), "a reason is required"


def test_the_sixteen_more_open_codes_are_gone_from_the_live_file(stores):
    """The cure's own claim, asserted against the file rather than the log.

    These sixteen promised more foreign ownership than the record allows. Two
    stay on the backlog (47222, 86101); the other fourteen must be gone.
    """
    by_code, gold = stores
    cured = [
        "41016", "41018", "50131", "50132", "50133", "50213", "51101",
        "51102", "53200", "55105", "59111", "59121", "79122", "91221",
    ]
    findings = C.scan(gold, by_code)
    assert [c for c in cured if c in findings] == []
    # and the direction is right on the two that matter most to a client
    assert "Restricted — max 49%" in gold["51101"]["whatYouNeed"]
    assert "Closed to foreign investment" in gold["79122"]["whatYouNeed"]


# ── guilt ───────────────────────────────────────────────────────────────────


def _mini(cap, sentence, status="TERBATAS"):
    canon = {"90001": {"kode_kbli_2025": "90001", "pma_max_asing": cap,
                       "pma_status": status, "judul": "Test"}}
    gold = {"90001": {"whatYouNeed": f"1. **NIB via OSS**\n\n{sentence}\n\nmore text"}}
    return canon, gold


def test_guilt_a_more_open_figure_is_caught():
    canon, gold = _mini(49, "**PMA:** Fully open — 100% foreign ownership allowed.")
    f = C.scan(gold, canon)
    assert "90001" in f and f["90001"]["more_open"] is True
    assert f["90001"]["is_default"] is True


def test_guilt_a_more_restrictive_figure_is_caught_but_refused():
    canon, gold = _mini(100, "**PMA:** Restricted — max 49% foreign ownership.", "TERBUKA")
    f = C.scan(gold, canon)
    assert "90001" in f and f["90001"]["more_open"] is False
    patch, refused = C.plan(f, gold)
    assert patch == {} and "90001" in refused


def test_guilt_closed_wording_counts_as_zero_not_as_no_figure():
    """`Closed to foreign investment` states 0% without writing a digit — a
    reader of the sentence knows that, and so must the scan."""
    canon, gold = _mini(100, "**PMA:** Closed to foreign investment — domestic entities only.", "TERBUKA")
    assert C.scan(gold, canon)["90001"]["stated"] == 0


def test_guilt_a_hand_authored_sentence_is_refused_not_rewritten():
    canon, gold = _mini(
        0, "**PMA:** Fully open — 100% foreign ownership, WITH mandatory Kemenkes authorization."
    )
    f = C.scan(gold, canon)
    assert f["90001"]["is_default"] is False
    patch, refused = C.plan(f, gold)
    assert patch == {} and "90001" in refused


# ── innocence ───────────────────────────────────────────────────────────────


def test_innocence_an_agreeing_sentence_is_not_a_finding():
    canon, gold = _mini(49, "**PMA:** Restricted — max 49% foreign ownership.")
    assert C.scan(gold, canon) == {}


def test_innocence_a_percentage_elsewhere_in_the_field_is_not_the_pma_figure():
    """The field is full of numbers — capital, timelines, other percentages.
    Only the PMA sentence's own figure may convict it."""
    canon = {"90001": {"kode_kbli_2025": "90001", "pma_max_asing": 100,
                       "pma_status": "TERBUKA", "judul": "Test"}}
    gold = {"90001": {"whatYouNeed":
        "Foreign staff may not exceed 30% of headcount.\n"
        "**PMA:** Fully open — 100% foreign ownership allowed.\n"
        "Local content target: 40%."}}
    assert C.scan(gold, canon) == {}


def test_innocence_a_code_with_no_pma_sentence_is_not_a_finding():
    canon = {"90001": {"kode_kbli_2025": "90001", "pma_max_asing": 49,
                       "pma_status": "TERBATAS", "judul": "Test"}}
    gold = {"90001": {"whatYouNeed": "1. **NIB via OSS** — auto-issued."}}
    assert C.scan(gold, canon) == {}


def test_innocence_replacement_never_touches_the_rest_of_the_field():
    canon, gold = _mini(49, "**PMA:** Fully open — 100% foreign ownership allowed.")
    patch, _ = C.plan(C.scan(gold, canon), gold)
    new = patch["90001"]["new"]
    assert new.startswith("1. **NIB via OSS**") and new.endswith("more text")
    assert "Fully open" not in new


# ── the resolver ladder, kept in step with the TypeScript one ───────────────


@pytest.mark.parametrize(
    "rec,expected",
    [
        ({"pma_max_asing": 49}, 49),
        ({"pma_max_asing": "49"}, 49),
        ({"pma_max_asing": "special"}, "special"),
        ({"pma_max_asing": None, "pma_status": "TERBUKA"}, 100),
        ({"pma_max_asing": None, "pma_status": "TERTUTUP"}, 0),
        # TERBATAS spans 0/49/100 and a non-percentage regime: inventing a
        # figure is the defect the resolver exists to prevent.
        ({"pma_max_asing": None, "pma_status": "TERBATAS"}, "special"),
    ],
)
def test_resolve_cap_mirrors_the_typescript_resolver(rec, expected):
    assert C.resolve_cap(rec) == expected


def test_derived_sentence_states_only_the_records_own_cap():
    assert C.derived_sentence(0) == "**PMA:** Closed to foreign investment — domestic entities only."
    assert "49%" in C.derived_sentence(49) and "100" not in C.derived_sentence(49)
    assert "100% foreign ownership allowed" in C.derived_sentence(100)
