import asyncio
import contextlib
import json
import logging
import os

import asyncpg

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

VISA_TYPES = [
    {
        "code": "A1",
        "name": "Visa Free Tourism",
        "category": "Visa Free/VOA",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Bebas Visa Wisata",
        },
    },
    {
        "code": "A4",
        "name": "Visa Free Government Assignment",
        "category": "Visa Free/VOA",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Bebas Visa Penugasan Pemerintah",
        },
    },
    {
        "code": "A36",
        "name": "Visa Free Ship and Aircraft Crew",
        "category": "Visa Free/VOA",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Bebas Visa Kru Kapal dan Pesawat",
        },
    },
    {
        "code": "A37",
        "name": "Visa Free Ship Crew in Indonesian Waters",
        "category": "Visa Free/VOA",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Bebas Visa Kru Kapal di Perairan Indonesia",
        },
    },
    {
        "code": "B1",
        "name": "Visit Visa Tourism",
        "category": "VOA",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Wisata",
        },
    },
    {
        "code": "B4",
        "name": "Visit Visa Government Assignmentan",
        "category": "VOA",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Penugasan Pemerintahan",
        },
    },
    {
        "code": "F1",
        "name": "Visit Visa Tourism",
        "category": "Visa Free/VOA",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Wisata",
        },
    },
    {
        "code": "F4",
        "name": "Visit Visa Government Assignmentan",
        "category": "Visa Free/VOA",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Penugasan Pemerintahan",
        },
    },
    {
        "code": "C1",
        "name": "Visit Visa Tourism",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "IDR 2.300.000 (All-inclusive pricing)",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "Visa Kunjungan Wisata",
        },
    },
    {
        "code": "C2",
        "name": "Visit Visa Business",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "IDR 3.600.000 (All-inclusive pricing)",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "Visa Kunjungan Bisnis",
        },
    },
    {
        "code": "C3",
        "name": "Visit Visa Medical Treatment",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Perawatan Kesehatan",
        },
    },
    {
        "code": "C4",
        "name": "Visit Visa Government Assignment",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Penugasan Pemerintah",
        },
    },
    {
        "code": "C5",
        "name": "Visit Visa Media dan Pers",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Media dan Pers",
        },
    },
    {
        "code": "C5A",
        "name": "Visit Visa Content Creator",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Visit Visa Content Creator",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Konten Kreator",
        },
    },
    {
        "code": "C6",
        "name": "Visit Visa Social Activity",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Kegiatan Sosial",
        },
    },
    {
        "code": "C7",
        "name": "Visit Visa Penampilan Seni dan Budaya",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "IDR 4.500.000",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "Visa Kunjungan Penampilan Seni dan Budaya",
        },
    },
    {
        "code": "C7A",
        "name": "Visit Visa Music Performance",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Penampilan Musik",
        },
    },
    {
        "code": "C7B",
        "name": "Visit Visa Kru Music Performance",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Kru Penampilan Musik",
        },
    },
    {
        "code": "C7C",
        "name": "Visit Visa Penampilan Bakat dan Seni",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Visit Visa Penampilan Bakat dan Seni",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Penampilan Bakat dan Seni",
        },
    },
    {
        "code": "C8",
        "name": "Visit Visa Sports Activity",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Visit Visa Sports Activity",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Kegiatan Olahraga",
        },
    },
    {
        "code": "C8A",
        "name": "Visit Visa Athlete",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Atlet Olahraga",
        },
    },
    {
        "code": "C8B",
        "name": "Visit Visa Sports Official",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Visit Visa Sports Official",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Ofisial Olahraga",
        },
    },
    {
        "code": "C9",
        "name": "Visit Visa Short Study",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Studi Singkat",
        },
    },
    {
        "code": "C9A",
        "name": "Visit Visa Short Religious Training",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Visit Visa Short Religious Training",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Pelatihan Singkat Keagamaan",
        },
    },
    {
        "code": "C9B",
        "name": "Visit Visa Short Indonesian Language Training",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Visit Visa Short Indonesian Language Training",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Pelatihan Singkat Bahasa Indonesia",
        },
    },
    {
        "code": "C10",
        "name": "Visit Visa Narasumber Kegiatan Business",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Narasumber Kegiatan Bisnis",
        },
    },
    {
        "code": "C10A",
        "name": "Visit Visa Religious Lecturer",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Visit Visa Religious Lecturer",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Penceramah Agama",
        },
    },
    {
        "code": "C11",
        "name": "Visit Visa Promosi Produk dan Jasa",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Promosi Produk dan Jasa",
        },
    },
    {
        "code": "C11A",
        "name": "Visit Visa Promosi Produk dan Jasa",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Visit Visa Promosi Produk dan Jasa",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Promosi Produk dan Jasa",
        },
    },
    {
        "code": "C12",
        "name": "Visit Visa Pre-Investment",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Pra-Investasi",
        },
    },
    {
        "code": "C13",
        "name": "Visit Visa Awak Bergabung dengan Alat Angkut",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Awak Bergabung dengan Alat Angkut",
        },
    },
    {
        "code": "C14",
        "name": "Visit Visa Pembuatan dan Produksi Film",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Pembuatan dan Produksi Film",
        },
    },
    {
        "code": "C15",
        "name": "Visit Visa Emergency Handling",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Penanganan Keadaan Darurat",
        },
    },
    {
        "code": "C16",
        "name": "Visit Visa Industrial Development Instructor",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Instruktur Pengembangan Industri",
        },
    },
    {
        "code": "C17",
        "name": "Visit Visa Audit, Kendali Mutu, dan Inspeksi Perusahaan",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Audit, Kendali Mutu, dan Inspeksi Perusahaan",
        },
    },
    {
        "code": "C18",
        "name": "Visit Visa Foreign Worker Competency Test",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "IDR 5.500.000",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "Visa Kunjungan Uji Kemampuan Tenaga Kerja Asing",
        },
    },
    {
        "code": "C19",
        "name": "Visit Visa After-Sales Service",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Layanan Purna Jual",
        },
    },
    {
        "code": "C20",
        "name": "Visit Visa Pemasangan dan Perbaikan Mesin",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Pemasangan dan Perbaikan Mesin",
        },
    },
    {
        "code": "C21",
        "name": "Visit Visa Menghadiri Proses Peradilan",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Visit Visa Menghadiri Proses Peradilan",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Menghadiri Proses Peradilan",
        },
    },
    {
        "code": "C22",
        "name": "Visit Visa Internship",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Visit Visa Internship",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Pemagangan",
        },
    },
    {
        "code": "C22A",
        "name": "Visit Visa Internship Akademik",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "IDR 4.800.000",
        "requirements": [],
        "description": "Official title: Visit Visa Internship Akademik",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "Visa Kunjungan Pemagangan Akademik",
        },
    },
    {
        "code": "C22B",
        "name": "Visit Visa Internship Kompetensi",
        "category": "Visit Visa",
        "duration": "See details",
        "cost_visa": "IDR 4.800.000",
        "requirements": [],
        "description": "Official title: Visit Visa Internship Kompetensi",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "Visa Kunjungan Pemagangan Kompetensi",
        },
    },
    {
        "code": "D1",
        "name": "Visit Visa Tourism (Multiple Entry)",
        "category": "Multiple Entry",
        "duration": "1 / 2 / 5 Years",
        "cost_visa": "IDR 6.000.000 (1 Year) / 8.000.000 (2 Years) / 14.000.000 (5 Years)",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "Visa Kunjungan Wisata",
            "tiers": [
                {"validity": "1 Year", "price_idr": 6000000},
                {"validity": "2 Years", "price_idr": 8000000},
                {"validity": "5 Years", "price_idr": 14000000},
            ],
        },
    },
    {
        "code": "D2",
        "name": "Visit Visa Business",
        "category": "Multiple Entry",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Bisnis",
        },
    },
    {
        "code": "D3",
        "name": "Visit Visa Medical Treatment",
        "category": "Multiple Entry",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Visit Visa Medical Treatment",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Perawatan Kesehatan",
        },
    },
    {
        "code": "D4",
        "name": "Visit Visa Government Assignment",
        "category": "Multiple Entry",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Visit Visa Government Assignment",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Penugasan Pemerintah",
        },
    },
    {
        "code": "D7",
        "name": "Visit Visa Penampilan Seni dan Budaya",
        "category": "Multiple Entry",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Visit Visa Penampilan Seni dan Budaya",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Penampilan Seni dan Budaya",
        },
    },
    {
        "code": "D8",
        "name": "Visit Visa Sports Activity",
        "category": "Multiple Entry",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Visit Visa Sports Activity",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Kegiatan Olahraga",
        },
    },
    {
        "code": "D12",
        "name": "Visit Visa Pre-Investment",
        "category": "Multiple Entry",
        "duration": "See details",
        "cost_visa": "IDR 7.500.000",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "Visa Kunjungan Pra-Investasi",
        },
    },
    {
        "code": "D14",
        "name": "Visit Visa Pembuatan and Produksi Film",
        "category": "Multiple Entry",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Visit Visa Pembuatan and Produksi Film",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Pembuatan and Produksi Film",
        },
    },
    {
        "code": "D17",
        "name": "Visit Visa Audit, Kendali Mutu, dan Inspeksi Perusahaan",
        "category": "Multiple Entry",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Visit Visa Audit, Kendali Mutu, dan Inspeksi Perusahaan",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kunjungan Audit, Kendali Mutu, dan Inspeksi Perusahaan",
        },
    },
    {
        "code": "E23",
        "name": "Working Visa",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "IDR 34.500.000 (Offshore) / 36.000.000 (Onshore)",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "Visa Kerja",
        },
    },
    {
        "code": "E23A",
        "name": "Working Visa Special Economic Zone",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "IDR 34.500.000 (Offshore) / 36.000.000 (Onshore)",
        "requirements": [],
        "description": "Official title: Working Visa Special Economic Zone",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "Visa Kerja Kawasan Ekonomi Khusus",
            "inherited_from": "E23",
        },
    },
    {
        "code": "E23U",
        "name": "Working Visa Foreign Diplomat House Assistant",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "IDR 34.500.000 (Offshore) / 36.000.000 (Onshore)",
        "requirements": [],
        "description": "Official title: Working Visa Foreign Diplomat House Assistant",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "Visa Kerja Asisten Rumah Tangga Diplomat Asing",
            "inherited_from": "E23",
        },
    },
    {
        "code": "E23V",
        "name": "Working Visa Kantor Dagang dan Ekonomi",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "IDR 34.500.000 (Offshore) / 36.000.000 (Onshore)",
        "requirements": [],
        "description": "Official title: Working Visa Kantor Dagang dan Ekonomi",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "Visa Kerja Kantor Dagang dan Ekonomi",
            "inherited_from": "E23",
        },
    },
    {
        "code": "E23X",
        "name": "Working Visa Indonesian Government Expert",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "IDR 34.500.000 (Offshore) / 36.000.000 (Onshore)",
        "requirements": [],
        "description": "Official title: Working Visa Indonesian Government Expert",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "Visa Kerja Tenaga Ahli Pemerintah Indonesia",
            "inherited_from": "E23",
        },
    },
    {
        "code": "E23Y",
        "name": "Working Visa Digital Field Expert",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "IDR 34.500.000 (Offshore) / 36.000.000 (Onshore)",
        "requirements": [],
        "description": "Official title: Working Visa Digital Field Expert",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "Visa Kerja Tenaga Ahli Bidang Digital",
            "inherited_from": "E23",
        },
    },
    {
        "code": "E25",
        "name": "Working Visa Komisaris dan Eksekutif Perusahaan",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Working Visa Komisaris dan Eksekutif Perusahaan",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kerja Komisaris dan Eksekutif Perusahaan",
        },
    },
    {
        "code": "E25A",
        "name": "Working Visa Company Commissioner",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Working Visa Company Commissioner",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kerja Komisaris Perusahaan",
        },
    },
    {
        "code": "E25B",
        "name": "Working Visa Company Director",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Working Visa Company Director",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kerja Direktur Perusahaan",
        },
    },
    {
        "code": "E25C",
        "name": "Working Visa Wakil Company Director",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Working Visa Wakil Company Director",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kerja Wakil Direktur Perusahaan",
        },
    },
    {
        "code": "E25D",
        "name": "Working Visa Company General Manager",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Working Visa Company General Manager",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kerja Manajer Umum Perusahaan",
        },
    },
    {
        "code": "E25E",
        "name": "Working Visa Company Manager",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Working Visa Company Manager",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kerja Manajer Perusahaan",
        },
    },
    {
        "code": "E25F",
        "name": "Working Visa Company Supervisor",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Working Visa Company Supervisor",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kerja Supervisor Perusahaan",
        },
    },
    {
        "code": "E26",
        "name": "Working Visa Awak Kapal, Alat Apung, dan Instalasi Lepas Pantai",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Working Visa Awak Kapal, Alat Apung, dan Instalasi Lepas Pantai",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kerja Awak Kapal, Alat Apung, dan Instalasi Lepas Pantai",
        },
    },
    {
        "code": "E27",
        "name": "Working Visa Cleric",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Working Visa Cleric",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kerja Rohaniwan",
        },
    },
    {
        "code": "E29",
        "name": "Working Visa Researcher",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Working Visa Researcher",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kerja Peneliti",
        },
    },
    {
        "code": "E28",
        "name": "Investor Visa",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Investor Visa",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Investor",
        },
    },
    {
        "code": "E28A",
        "name": "Investor Visa",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "IDR 17.000.000 (Offshore) / 19.000.000 (Onshore)",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "Visa Investor",
        },
    },
    {
        "code": "E28B",
        "name": "Investor Visa Company Establishment Golden Visa",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Investor Pendirian Perusahaan Golden Visa",
        },
    },
    {
        "code": "E28C",
        "name": "Investor Visa Capital Market Golden Visa",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Investor Visa Capital Market Golden Visa",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Investor Pasar Modal Golden Visa",
        },
    },
    {
        "code": "E28D",
        "name": "Investor Visa Pendirian Cabang atau Anak Perusahaan Golden Visa",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Investor Visa Pendirian Cabang atau Anak Perusahaan Golden Visa",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Investor Pendirian Cabang atau Anak Perusahaan Golden Visa",
        },
    },
    {
        "code": "E28E",
        "name": "Investor Visa Special Economic Zone",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Investor Visa Special Economic Zone",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Investor Kawasan Ekonomi Khusus",
        },
    },
    {
        "code": "E28F",
        "name": "Investor Visa Pendirian Cabang atau Anak Perusahaan di Indonesian New Capital (IKN)",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Investor Visa Pendirian Cabang atau Anak Perusahaan di Indonesian New Capital (IKN)",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Investor Pendirian Cabang atau Anak Perusahaan di Ibu Kota Nusantara",
        },
    },
    {
        "code": "E28G",
        "name": "Investor Visa Parent Company Representative",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Investor Visa Parent Company Representative",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Investor Perwakilan Perusahaan Induk",
        },
    },
    {
        "code": "E30",
        "name": "Education Visa",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Education Visa",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Pendidikan",
        },
    },
    {
        "code": "E30A",
        "name": "Education Visa Dasar dan Menengah",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Education Visa Dasar dan Menengah",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Pendidikan Dasar dan Menengah",
        },
    },
    {
        "code": "E30B",
        "name": "Education Visa Tinggi",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Education Visa Tinggi",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Pendidikan Tinggi",
        },
    },
    {
        "code": "E30E",
        "name": "Education Visa Special Economic Zone",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Education Visa Special Economic Zone",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Pendidikan Kawasan Ekonomi Khusus",
        },
    },
    {
        "code": "E30F",
        "name": "Visa Student Exchange",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Visa Student Exchange",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Pertukaran Pelajar",
        },
    },
    {
        "code": "E31",
        "name": "Family Visa",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Family Visa",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Keluarga",
        },
    },
    {
        "code": "E31A",
        "name": "Family Visa Spouse of Indonesian Citizen",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "IDR 11.000.000 (1 Year) / 15.000.000 (2 Years)",
        "requirements": [],
        "description": "Official title: Family Visa Spouse of Indonesian Citizen",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "Visa Keluarga Suami/Istri WNI",
        },
    },
    {
        "code": "E31B",
        "name": "Family Visa Spouse of ITAS/ITAP Holder",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "IDR 11.000.000 (1 Year) / 15.000.000 (2 Years)",
        "requirements": [],
        "description": "Official title: Family Visa Spouse of ITAS/ITAP Holder",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "Visa Keluarga Suami/Istri Pemegang ITAS/ITAP",
        },
    },
    {
        "code": "E31C",
        "name": "Family Visa Child of Legal Mixed Marriage",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Family Visa Child of Legal Mixed Marriage",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Keluarga Anak Hasil Perkawinan Sah WNA-WNI",
        },
    },
    {
        "code": "E31D",
        "name": "Family Visa Stepchild of Foreigner in Legal Mixed Marriage",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Family Visa Stepchild of Foreigner in Legal Mixed Marriage",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Keluarga Anak Bawaan WNA Perkawinan Sah WNA-WNI",
        },
    },
    {
        "code": "E31E",
        "name": "Family Visa Child of ITAS/ITAP Holder",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Family Visa Child of ITAS/ITAP Holder",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Keluarga Anak Pemegang ITAS/ITAP",
        },
    },
    {
        "code": "E31F",
        "name": "Family Visa Anak Dengan Orang Tua WNI",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "IDR 11.000.000 (1 Year) / 15.000.000 (2 Years)",
        "requirements": [],
        "description": "Official title: Family Visa Anak Dengan Orang Tua WNI",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "Visa Keluarga Anak Dengan Orang Tua WNI",
        },
    },
    {
        "code": "E31G",
        "name": "Family Visa Parent of Indonesian Child",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Family Visa Parent of Indonesian Child",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Keluarga Orang Tua dari Anak WNI",
        },
    },
    {
        "code": "E31H",
        "name": "Family Visa Orang Tua dari Child of ITAS/ITAP Holder",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Family Visa Orang Tua dari Child of ITAS/ITAP Holder",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Keluarga Orang Tua dari Anak Pemegang ITAS/ITAP",
        },
    },
    {
        "code": "E31J",
        "name": "Family Visa Anak yang Bergabung dengan Saudara Kandung Pemegang ITAS/ITAP",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Family Visa Anak yang Bergabung dengan Saudara Kandung Pemegang ITAS/ITAP",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Keluarga Anak yang Bergabung dengan Saudara Kandung Pemegang ITAS/ITAP",
        },
    },
    {
        "code": "E32",
        "name": "Repatriation Visa dan Former Indonesian Citizen Descendant",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Repatriation Visa dan Former Indonesian Citizen Descendant",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Repatriasi dan Keturunan EX-WNI",
        },
    },
    {
        "code": "E32A",
        "name": "Repatriation Visa 5 Tahun",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Repatriation Visa 5 Tahun",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Repatriasi 5 Tahun",
        },
    },
    {
        "code": "E32B",
        "name": "Visa Former Indonesian Citizen Descendant 5 Atau 10 Tahun Golden Visa",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Visa Former Indonesian Citizen Descendant 5 Atau 10 Tahun Golden Visa",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Keturunan EX-WNI 5 Atau 10 Tahun Golden Visa",
        },
    },
    {
        "code": "E32C",
        "name": "Repatriation Visa 2 Tahun",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Repatriation Visa 2 Tahun",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Repatriasi 2 Tahun",
        },
    },
    {
        "code": "E32D",
        "name": "Repatriation Visa 1 Tahun Golden Visa",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Repatriation Visa 1 Tahun Golden Visa",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Repatriasi 1 Tahun Golden Visa",
        },
    },
    {
        "code": "E32E",
        "name": "Repatriation Visa Permanent Residence Global Citizen of Indonesia",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Repatriation Visa Permanent Residence Global Citizen of Indonesia",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Repatriasi Tinggal Tetap Global Citizen of Indonesia",
        },
    },
    {
        "code": "E32F",
        "name": "Repatriation Visa Special Expertise Global Citizen of Indonesia",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Repatriation Visa Special Expertise Global Citizen of Indonesia",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Repatriasi Keahlian Khusus Global Citizen of Indonesia",
        },
    },
    {
        "code": "E32G",
        "name": "Visa Former Indonesian Citizen Descendant Permanent Residence Global Citizen of Indonesia",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Visa Former Indonesian Citizen Descendant Permanent Residence Global Citizen of Indonesia",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Keturunan EX-WNI Tinggal Tetap Global Citizen of Indonesia",
        },
    },
    {
        "code": "E32H",
        "name": "Visa Former Indonesian Citizen Descendant Special Expertise Global Citizen of Indonesia",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Visa Former Indonesian Citizen Descendant Special Expertise Global Citizen of Indonesia",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Keturunan EX-WNI Keahlian Khusus Global Citizen of Indonesia",
        },
    },
    {
        "code": "E33",
        "name": "Second Home Visa",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Rumah Kedua",
        },
    },
    {
        "code": "E33A",
        "name": "Second Home Visa Tenaga Ahli Government Invitation",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Second Home Visa Tenaga Ahli Government Invitation",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Rumah Kedua Tenaga Ahli Undangan Pemerintah",
        },
    },
    {
        "code": "E33B",
        "name": "Second Home Visa Kolaborasi Special Expertise Golden Visa",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Second Home Visa Kolaborasi Special Expertise Golden Visa",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Rumah Kedua Kolaborasi Keahlian Khusus Golden Visa",
        },
    },
    {
        "code": "E33C",
        "name": "Second Home Visa World Figure Government Invitation",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Second Home Visa World Figure Government Invitation",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Rumah Kedua Tokoh Dunia Undangan Pemerintah",
        },
    },
    {
        "code": "E33D",
        "name": "Second Home Visa World Figure Company Establishment",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Second Home Visa World Figure Company Establishment",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Rumah Kedua Tokoh Dunia Pendirian Perusahaan",
        },
    },
    {
        "code": "E33E",
        "name": "Second Home Visa Elderly for 5 Years Golden Visa",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "IDR 14.000.000 (Offshore) / 16.000.000 (Onshore)",
        "requirements": [],
        "description": "Official title: Second Home Visa Elderly for 5 Years Golden Visa",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "Visa Rumah Kedua Lansia Untuk 5 Tahun Golden Visa",
        },
    },
    {
        "code": "E33F",
        "name": "Second Home Visa Elderly for 1 Year",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "IDR 14.000.000 (Offshore) / 16.000.000 (Onshore)",
        "requirements": [],
        "description": "Official title: Second Home Visa Elderly for 1 Year",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "Visa Rumah Kedua Lansia Untuk 1 Tahun",
        },
    },
    {
        "code": "E33G",
        "name": "Second Home Visa Remote Worker / Digital Nomad Golden Visa",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "IDR 13.000.000 (Offshore) / 14.000.000 (Onshore)",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "Visa Rumah Kedua Pekerja Jarak Jauh Golden Visa",
        },
    },
    {
        "code": "E34",
        "name": "Visa Medical Treatment",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Visa Medical Treatment",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Perawatan Kesehatan",
        },
    },
    {
        "code": "E35",
        "name": "Working Holiday Visa",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Working Holiday Visa",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "Visa Kemudahan Bekerja Saat Berlibur",
        },
    },
    {
        "code": "E35A",
        "name": "Working Holiday Visa Australia",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "Contact for Quote",
        "requirements": [],
        "description": "Official title: Working Holiday Visa Australia",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": False,
            "name_id": "Visa Kemudahan Bekerja Saat Berlibur Australia",
        },
    },
    {
        "code": "E23-FREELANCE",
        "name": "Freelance KITAS (E23)",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "IDR 25.800.000 (Offshore) / 27.500.000 (Onshore)",
        "requirements": [],
        "description": "",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "Freelance KITAS (E23)",
        },
    },
    {
        "code": "EPO",
        "name": "EPO (Exit Permit Only)",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "IDR 700.000",
        "requirements": [],
        "description": "Official title: EPO (Exit Permit Only)",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "EPO (Exit Permit Only)",
        },
    },
    {
        "code": "ERP",
        "name": "ERP (Exit Re-entry Permit)",
        "category": "KITAS/Limited Stay",
        "duration": "See details",
        "cost_visa": "IDR 800.000",
        "requirements": [],
        "description": "Official title: ERP (Exit Re-entry Permit)",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "ERP (Exit Re-entry Permit)",
        },
    },
    {
        "code": "SKTT",
        "name": "SKTT Registration",
        "category": "Immigration Service",
        "duration": "See details",
        "cost_visa": "IDR 1.500.000",
        "requirements": [],
        "description": "Official title: SKTT Registration",
        "metadata": {
            "source": "zantara_curated_2026",
            "is_agency_product": True,
            "name_id": "SKTT Registration",
        },
    },
]


async def seed_visa_types():
    db_url = os.environ.get("DATABASE_URL")
    if not db_url:
        return
    conn = await asyncpg.connect(db_url)
    try:
        logger.info(f"Seeding {len(VISA_TYPES)} Curated Visa Types...")
        await conn.execute(
            "CREATE TABLE IF NOT EXISTS visa_types (code TEXT PRIMARY KEY, name TEXT, category TEXT, description TEXT, duration TEXT, cost_visa TEXT, requirements TEXT[], metadata JSONB, created_at TIMESTAMP DEFAULT NOW(), last_updated TIMESTAMP DEFAULT NOW());",
        )
        with contextlib.suppress(BaseException):
            await conn.execute("ALTER TABLE visa_types ADD COLUMN IF NOT EXISTS description TEXT;")
        for visa in VISA_TYPES:
            exists = await conn.fetchval("SELECT 1 FROM visa_types WHERE code = $1", visa["code"])
            if exists:
                await conn.execute(
                    "UPDATE visa_types SET name=$2, category=$3, description=$4, duration=$5, cost_visa=$6, requirements=$7, metadata=$8, last_updated=NOW() WHERE code=$1",
                    visa["code"],
                    visa["name"],
                    visa["category"],
                    visa["description"],
                    visa["duration"],
                    visa["cost_visa"],
                    visa["requirements"],
                    json.dumps(visa["metadata"]),
                )
            else:
                await conn.execute(
                    "INSERT INTO visa_types (code, name, category, description, duration, cost_visa, requirements, metadata) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)",
                    visa["code"],
                    visa["name"],
                    visa["category"],
                    visa["description"],
                    visa["duration"],
                    visa["cost_visa"],
                    visa["requirements"],
                    json.dumps(visa["metadata"]),
                )
        logger.info("Done.")
    finally:
        await conn.close()


if __name__ == "__main__":
    asyncio.run(seed_visa_types())
