import json

data = {
    # 1. High Probability Extraction Misses
    "75001": {
        "judul": "AKTIVITAS PERSONEL KESEHATAN HEWAN MANDIRI",
        "sektor": "Pertanian",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "75002": {
        "judul": "AKTIVITAS PENGELOLAAN SARANA KESEHATAN HEWAN",
        "sektor": "Pertanian",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "75009": {
        "judul": "AKTIVITAS PENGELOLAAN KESEHATAN HEWAN LAINNYA",
        "sektor": "Pertanian",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "02102": {
        "judul": "PEMANFAATAN KAYU HUTAN",
        "sektor": "Lingkungan Hidup dan Kehutanan",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin (Izin Usaha Pemanfaatan Hasil Hutan Kayu)",
        "kewenangan": "Menteri LHK",
    },
    "02103": {
        "judul": "PEMBENIHAN TANAMAN KEHUTANAN",
        "sektor": "Lingkungan Hidup dan Kehutanan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri LHK",
    },
    "02201": {
        "judul": "PEMANENAN KAYU",
        "sektor": "Lingkungan Hidup dan Kehutanan",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin",
        "kewenangan": "Menteri LHK",
    },
    "02202": {
        "judul": "PEMUNGUTAN KAYU",
        "sektor": "Lingkungan Hidup dan Kehutanan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri LHK",
    },
    "02300": {
        "judul": "PEMUNGUTAN HASIL HUTAN BUKAN KAYU",
        "sektor": "Lingkungan Hidup dan Kehutanan",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "02401": {
        "judul": "JASA LINGKUNGAN HUTAN",
        "sektor": "Lingkungan Hidup dan Kehutanan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri LHK",
    },
    "02402": {
        "judul": "JASA PENGGUNAAN KAWASAN KEHUTANAN",
        "sektor": "Lingkungan Hidup dan Kehutanan",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin",
        "kewenangan": "Menteri LHK",
    },
    "03300": {
        "judul": "JASA PENUNJANG PERIKANAN",
        "sektor": "Kelautan dan Perikanan",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri KKP",
    },
    "46420": {
        "judul": "PERDAGANGAN BESAR FURNITUR, KARPET, PERLENGKAPAN",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "46739": {
        "judul": "PERDAGANGAN BESAR BAHAN KONSTRUKSI LAINNYA",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "46901": {
        "judul": "PERDAGANGAN BESAR BERBAGAI MACAM BARANG",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "47211": {
        "judul": "PERDAGANGAN ECERAN BAHAN MAKANAN DAN MINUMAN",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "73201": {
        "judul": "PENELITIAN PASAR",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "73202": {
        "judul": "JAJAK PENDAPAT OPINI",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "73300": {
        "judul": "AKTIVITAS KEHUMASAN",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "77291": {
        "judul": "PENYEWAAN PERALATAN DAN PERLENGKAPAN ACARA",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "77292": {
        "judul": "PENYEWAAN ALAT MUSIK",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "77294": {
        "judul": "PENYEWAAN BUNGA DAN TANAMAN HIAS",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "77299": {
        "judul": "PENYEWAAN BARANG PRIBADI DAN BARANG RUMAH TANGGA LAINNYA",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "77395": {
        "judul": "PENYEWAAN MESIN KANTOR",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "77400": {
        "judul": "SEWA GUNA USAHA KEKAYAAN INTELEKTUAL DAN PRODUK SEJENIS",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "77510": {
        "judul": "AKTIVITAS JASA INTERMEDIASI UNTUK PENYEWAAN DAN SEWA GUNA USAHA",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "77520": {
        "judul": "AKTIVITAS JASA INTERMEDIASI UNTUK PENYEWAAN DAN SEWA GUNA USAHA",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "82100": {
        "judul": "AKTIVITAS ADMINISTRASI KANTOR DAN PENUNJANG KANTOR",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "82300": {
        "judul": "PENYELENGGARAAN KONVENSI DAN PAMERAN BISNIS",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "82400": {
        "judul": "JASA INTERMEDIASI UNTUK AKTIVITAS PENUNJANG USAHA YTDL",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "82911": {
        "judul": "AKTIVITAS AGEN PENAGIHAN",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "82912": {
        "judul": "AKTIVITAS BIRO KREDIT",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "82921": {
        "judul": "AKTIVITAS PENGEPAKAN BAHAN DAN PRODUK HASIL PERTANIAN",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "82922": {
        "judul": "AKTIVITAS PENGEPAKAN BAHAN DAN PRODUK MAKANAN DAN MINUMAN",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "82923": {
        "judul": "AKTIVITAS PENGEPAKAN TEKSTIL DAN PRODUK TEKSTIL",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "82924": {
        "judul": "AKTIVITAS PENGEPAKAN BAHAN DAN PRODUK KIMIA",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "82925": {
        "judul": "AKTIVITAS PENGEPAKAN BAHAN DAN PRODUK FARMASI",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "82929": {
        "judul": "AKTIVITAS PENGEPAKAN LAINNYA",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "82990": {
        "judul": "AKTIVITAS JASA PENUNJANG USAHA LAINNYA YTDL",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "95101": {
        "judul": "REPARASI DAN PEMELIHARAAN KOMPUTER DAN PERALATAN SEJENISNYA",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "95102": {
        "judul": "REPARASI DAN PEMELIHARAAN PERALATAN KOMUNIKASI",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "95210": {
        "judul": "REPARASI BARANG ELEKTRONIK KONSUMEN",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "95311": {
        "judul": "REPARASI MOBIL",
        "sektor": "Perindustrian",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "95312": {
        "judul": "PENCUCIAN DAN SALON MOBIL",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "95320": {
        "judul": "REPARASI DAN PERAWATAN SEPEDA MOTOR",
        "sektor": "Perindustrian",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "95400": {
        "judul": "JASA INTERMEDIASI REPARASI DAN PERAWATAN KOMPUTER",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "49111": {
        "judul": "ANGKUTAN KERETA WISATA ANTARKOTA",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Operasi",
        "kewenangan": "Menteri Perhubungan",
    },
    "49119": {
        "judul": "TRANSPORTASI REL LAINNYA",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Operasi",
        "kewenangan": "Menteri Perhubungan",
    },
    "49120": {
        "judul": "TRANSPORTASI KERETA API UNTUK BARANG",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Operasi",
        "kewenangan": "Menteri Perhubungan",
    },
    "49212": {
        "judul": "ANGKUTAN KERETA API PERKOTAAN",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Operasi",
        "kewenangan": "Menteri Perhubungan",
    },
    "49213": {
        "judul": "ANGKUTAN PERKOTAAN",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Gubernur/Bupati/Walikota",
    },
    "49214": {
        "judul": "ANGKUTAN PERDESAAN",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "49219": {
        "judul": "TRANSPORTASI DARAT DALAM KOTA LAINNYA UNTUK PENUMPANG",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "49221": {
        "judul": "ANGKUTAN ANTARKOTA ANTARPROVINSI (AKAP)",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Izin Penyelenggaraan Angkutan",
        "kewenangan": "Menteri Perhubungan",
    },
    "49222": {
        "judul": "ANGKUTAN ANTARKOTA DALAM PROVINSI (AKDP)",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Izin Penyelenggaraan Angkutan",
        "kewenangan": "Gubernur",
    },
    "49223": {
        "judul": "ANGKUTAN LINTAS BATAS NEGARA",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Penyelenggaraan Angkutan",
        "kewenangan": "Menteri Perhubungan",
    },
    "49291": {
        "judul": "ANGKUTAN KERETA API LAINNYA",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Operasi",
        "kewenangan": "Menteri Perhubungan",
    },
    "49292": {
        "judul": "ANGKUTAN PARIWISATA",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Izin Penyelenggaraan Angkutan",
        "kewenangan": "Menteri Perhubungan",
    },
    "49293": {
        "judul": "ANGKUTAN TAKSI",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Izin Penyelenggaraan Angkutan",
        "kewenangan": "Gubernur/Bupati/Walikota",
    },
    "49294": {
        "judul": "ANGKUTAN KHUSUS",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Izin Penyelenggaraan Angkutan",
        "kewenangan": "Menteri Perhubungan",
    },
    "49295": {
        "judul": "ANGKUTAN SEWA",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Izin Penyelenggaraan Angkutan",
        "kewenangan": "Gubernur/Bupati/Walikota",
    },
    "50112": {
        "judul": "ANGKUTAN LAUT DALAM NEGERI PERINTIS UNTUK PENUMPANG",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Usaha Angkutan Laut",
        "kewenangan": "Menteri Perhubungan",
    },
    "50113": {
        "judul": "ANGKUTAN LAUT DALAM NEGERI UNTUK WISATA",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Perhubungan",
    },
    "50115": {
        "judul": "ANGKUTAN LAUT LUAR NEGERI UNTUK WISATA",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Usaha Angkutan Laut",
        "kewenangan": "Menteri Perhubungan",
    },
    "50122": {
        "judul": "ANGKUTAN LAUT DALAM NEGERI UNTUK BARANG KHUSUS",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Usaha Angkutan Laut",
        "kewenangan": "Menteri Perhubungan",
    },
    "50123": {
        "judul": "ANGKUTAN LAUT DALAM NEGERI PERINTIS UNTUK BARANG",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Usaha Angkutan Laut",
        "kewenangan": "Menteri Perhubungan",
    },
    "50124": {
        "judul": "ANGKUTAN LAUT DALAM NEGERI PELAYARAN RAKYAT UNTUK BARANG",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Gubernur/Bupati/Walikota",
    },
    "50125": {
        "judul": "ANGKUTAN LAUT LUAR NEGERI UNTUK BARANG UMUM",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Usaha Angkutan Laut",
        "kewenangan": "Menteri Perhubungan",
    },
    "50126": {
        "judul": "ANGKUTAN LAUT LUAR NEGERI UNTUK BARANG KHUSUS",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Usaha Angkutan Laut",
        "kewenangan": "Menteri Perhubungan",
    },
    "50127": {
        "judul": "ANGKUTAN LAUT LUAR NEGERI PELAYARAN RAKYAT UNTUK BARANG",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Perhubungan",
    },
    "50139": {
        "judul": "TRANSPORTASI PESISIR LAINNYA UNTUK PENUMPANG",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Gubernur",
    },
    "50149": {
        "judul": "TRANSPORTASI PESISIR LAINNYA UNTUK BARANG",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Gubernur",
    },
    "50212": {
        "judul": "ANGKUTAN SUNGAI DAN DANAU TRAMPER",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "50213": {
        "judul": "ANGKUTAN SUNGAI DAN DANAU UNTUK WISATA",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "51102": {
        "judul": "ANGKUTAN UDARA NIAGA TIDAK BERJADWAL UNTUK PENUMPANG",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Usaha Angkutan Udara",
        "kewenangan": "Menteri Perhubungan",
    },
    "52101": {
        "judul": "PENGELOLA GUDANG SISTEM RESI GUDANG",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin (Persetujuan Bappebti)",
        "kewenangan": "Menteri Perdagangan",
    },
    "52104": {
        "judul": "PENYIMPANAN MINYAK DAN GAS BUMI",
        "sektor": "ESDM",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Usaha Penyimpanan Migas",
        "kewenangan": "Menteri ESDM",
    },
    "52105": {
        "judul": "AKTIVITAS PENYIMPANAN BARANG BERBAHAYA DAN BERACUN",
        "sektor": "LHK",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Pengelolaan Limbah B3",
        "kewenangan": "Menteri LHK",
    },
    "52107": {
        "judul": "PENYIMPANAN MINERAL IKUTAN RADIOAKTIF",
        "sektor": "Ketenaganukliran",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin (BAPETEN)",
        "kewenangan": "BAPETEN",
    },
    "52109": {
        "judul": "PERGUDANGAN DAN PENYIMPANAN LAINNYA",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "52211": {
        "judul": "AKTIVITAS TERMINAL DARAT",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Perhubungan",
    },
    "52212": {
        "judul": "AKTIVITAS PENYELENGGARAAN PRASARANA PERKERETAAPIAN",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Usaha Prasarana",
        "kewenangan": "Menteri Perhubungan",
    },
    "52213": {
        "judul": "AKTIVITAS JALAN TOL",
        "sektor": "PUPR",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Usaha Jalan Tol",
        "kewenangan": "Menteri PUPR",
    },
    "52219": {
        "judul": "AKTIVITAS JASA TERKAIT TRANSPORTASI DARAT LAINNYA",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "52226": {
        "judul": "AKTIVITAS PENYELAMATAN KAPAL DAN MUATANNYA",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin",
        "kewenangan": "Menteri Perhubungan",
    },
    "52227": {
        "judul": "ANGKUTAN PERAIRAN PELABUHAN",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Perhubungan",
    },
    "52232": {
        "judul": "JASA PELAYANAN NAVIGASI PENERBANGAN",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin",
        "kewenangan": "Menteri Perhubungan",
    },
    "52233": {
        "judul": "PELAYANAN PENUMPANG, BAGASI, KARGO, POS, DAN TEKNIS",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Perhubungan",
    },
    "52234": {
        "judul": "AKTIVITAS GROUND HANDLING",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Perhubungan",
    },
    "52239": {
        "judul": "AKTIVITAS JASA TERKAIT ANGKUTAN UDARA LAINNYA",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Perhubungan",
    },
    "52292": {
        "judul": "AKTIVITAS TALLY MANDIRI",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Perhubungan",
    },
    "52299": {
        "judul": "AKTIVITAS PENUNJANG ANGKUTAN LAINNYA YTDL",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Perhubungan",
    },
    "52311": {
        "judul": "JASA PENGURUSAN TRANSPORTASI (JPT)",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Perhubungan",
    },
    "52312": {
        "judul": "JASA KEAGENAN KAPAL/AGEN PERKAPALAN",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Perhubungan",
    },
    "52313": {
        "judul": "AKTIVITAS PERWAKILAN OPERASIONAL TRANSPORTASI UDARA",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Perhubungan",
    },
    "52319": {
        "judul": "JASA INTERMEDIASI TRANSPORTASI LAINNYA UNTUK BARANG",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Perhubungan",
    },
    "52321": {
        "judul": "AGEN PENJUALAN TIKET TRANSPORTASI",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "52322": {
        "judul": "AGEN PENGURUS PERSETUJUAN TERBANG",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Perhubungan",
    },
    "52323": {
        "judul": "AKTIVITAS PERWAKILAN OPERASIONAL TRANSPORTASI UDARA ASING",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin",
        "kewenangan": "Menteri Perhubungan",
    },
    "52329": {
        "judul": "JASA INTERMEDIASI TRANSPORTASI LAINNYA UNTUK PENUMPANG",
        "sektor": "Perhubungan",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Perhubungan",
    },
    "55102": {
        "judul": "AKTIVITAS HOTEL BINTANG EMPAT",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Gubernur",
    },
    "55103": {
        "judul": "AKTIVITAS HOTEL BINTANG TIGA",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Gubernur",
    },
    "55104": {
        "judul": "AKTIVITAS HOTEL BINTANG DUA",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "55105": {
        "judul": "AKTIVITAS HOTEL BINTANG SATU",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "55106": {
        "judul": "AKTIVITAS HOTEL NONBINTANG",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "55201": {
        "judul": "AKTIVITAS RUMAH TINGGAL SEWA (HOMESTAY)",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "55203": {
        "judul": "AKTIVITAS VILA",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "55204": {
        "judul": "AKTIVITAS APARTEMEN HOTEL",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Gubernur",
    },
    "55209": {
        "judul": "AKTIVITAS PENYEDIAAN AKOMODASI JANGKA PENDEK LAINNYA",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "55300": {
        "judul": "AKTIVITAS PENYEDIAAN BUMI PERKEMAHAN",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "55400": {
        "judul": "AKTIVITAS JASA INTERMEDIASI AKOMODASI",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "55901": {
        "judul": "AKTIVITAS JASA MANAJEMEN AKOMODASI",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "55909": {
        "judul": "PENYEDIAAN AKOMODASI LAINNYA YTDL",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "56102": {
        "judul": "AKTIVITAS PENYEDIAAN MAKANAN DI BANGUNAN TIDAK TETAP",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "56210": {
        "judul": "AKTIVITAS JASA BOGA UNTUK SUATU EVENT TERTENTU (CATERING)",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar (Sertifikat Laik Higiene)",
        "kewenangan": "Bupati/Walikota",
    },
    "56400": {
        "judul": "AKTIVITAS JASA INTERMEDIASI PENYEDIAAN MAKANAN DAN MINUMAN",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "74111": {
        "judul": "AKTIVITAS DESAIN ALAT TRANSPORTASI DAN PERMESINAN",
        "sektor": "Perindustrian",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "74113": {
        "judul": "AKTIVITAS DESAIN TEKSTIL, MODE/FESYEN",
        "sektor": "Pariwisata (Ekraf)",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "74115": {
        "judul": "AKTIVITAS DESAIN ALAT KOMUNIKASI",
        "sektor": "Perindustrian",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "74117": {
        "judul": "AKTIVITAS DESAIN KEMASAN",
        "sektor": "Pariwisata (Ekraf)",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "74191": {
        "judul": "AKTIVITAS DESAIN INTERIOR",
        "sektor": "Pariwisata (Ekraf)",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "74192": {
        "judul": "AKTIVITAS DESAIN GRAFIS",
        "sektor": "Pariwisata (Ekraf)",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "74193": {
        "judul": "AKTIVITAS DESAIN KHUSUS FILM, VIDEO",
        "sektor": "Pariwisata (Ekraf)",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "74209": {
        "judul": "AKTIVITAS FOTOGRAFI LAINNYA",
        "sektor": "Pariwisata (Ekraf)",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "74300": {
        "judul": "AKTIVITAS PENERJEMAH ATAU INTERPRETER",
        "sektor": "Pendidikan / Kebudayaan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "74910": {
        "judul": "AKTIVITAS BROKER DAN LAYANAN PEMASARAN PATEN",
        "sektor": "Hukum dan HAM",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "74991": {
        "judul": "JASA METEOROLOGI DAN PRAKIRAAN CUACA",
        "sektor": "BMKG",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "BMKG",
    },
    "74999": {
        "judul": "SEMUA AKTIVITAS PROFESIONAL LAINNYA YTDL",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "79110": {
        "judul": "AKTIVITAS AGEN PERJALANAN",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "79121": {
        "judul": "AKTIVITAS BIRO PERJALANAN WISATA",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Gubernur",
    },
    "79129": {
        "judul": "AKTIVITAS BIRO PERJALANAN LAINNYA",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "79909": {
        "judul": "AKTIVITAS TERKAIT PERJALANAN LAINNYA YTDL",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "92000": {
        "judul": "AKTIVITAS PERJUDIAN DAN PERTARUHAN",
        "sektor": "DILARANG",
        "tingkat_risiko": "DILARANG",
        "perizinan_berusaha": "DILARANG",
        "kewenangan": "DILARANG",
    },
    "96100": {
        "judul": "AKTIVITAS PENCUCIAN TEKSTIL (LAUNDRY)",
        "sektor": "Perindustrian / Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "96230": {
        "judul": "AKTIVITAS SPA",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar (STPT)",
        "kewenangan": "Bupati/Walikota",
    },
    "96400": {
        "judul": "AKTIVITAS JASA INTERMEDIASI JASA PERORANGAN",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "41014": {
        "judul": "KONSTRUKSI GEDUNG PERBELANJAAN",
        "sektor": "PUPR",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar (SBU)",
        "kewenangan": "Menteri PUPR",
    },
    "41015": {
        "judul": "KONSTRUKSI GEDUNG KESEHATAN",
        "sektor": "PUPR",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar (SBU)",
        "kewenangan": "Menteri PUPR",
    },
    "41016": {
        "judul": "KONSTRUKSI GEDUNG PENDIDIKAN",
        "sektor": "PUPR",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar (SBU)",
        "kewenangan": "Menteri PUPR",
    },
    "41017": {
        "judul": "KONSTRUKSI GEDUNG PENGINAPAN",
        "sektor": "PUPR",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar (SBU)",
        "kewenangan": "Menteri PUPR",
    },
    "41019": {
        "judul": "KONSTRUKSI GEDUNG LAINNYA",
        "sektor": "PUPR",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar (SBU)",
        "kewenangan": "Menteri PUPR",
    },
    "41020": {
        "judul": "KONSTRUKSI PRAPABRIKASI BANGUNAN GEDUNG",
        "sektor": "PUPR",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar (SBU)",
        "kewenangan": "Menteri PUPR",
    },
    "42101": {
        "judul": "KONSTRUKSI JALAN RAYA",
        "sektor": "PUPR",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar (SBU)",
        "kewenangan": "Menteri PUPR",
    },
    "42102": {
        "judul": "KONSTRUKSI JEMBATAN DAN JALAN LAYANG",
        "sektor": "PUPR",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin (SBU)",
        "kewenangan": "Menteri PUPR",
    },
    "42103": {
        "judul": "KONSTRUKSI JALAN REL",
        "sektor": "PUPR",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin (SBU)",
        "kewenangan": "Menteri PUPR",
    },
    "42104": {
        "judul": "KONSTRUKSI TEROWONGAN",
        "sektor": "PUPR",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin (SBU)",
        "kewenangan": "Menteri PUPR",
    },
    "42201": {
        "judul": "KONSTRUKSI JARINGAN IRIGASI",
        "sektor": "PUPR",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar (SBU)",
        "kewenangan": "Menteri PUPR",
    },
    "42911": {
        "judul": "KONSTRUKSI BANGUNAN PRASARANA SUMBER DAYA AIR",
        "sektor": "PUPR",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar (SBU)",
        "kewenangan": "Menteri PUPR",
    },
    "42912": {
        "judul": "KONSTRUKSI BANGUNAN PELABUHAN",
        "sektor": "PUPR",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin (SBU)",
        "kewenangan": "Menteri PUPR",
    },
    "42914": {
        "judul": "KONSTRUKSI BANGUNAN SIPIL PLTA",
        "sektor": "PUPR",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin (SBU)",
        "kewenangan": "Menteri PUPR",
    },
    "42915": {
        "judul": "KONSTRUKSI BANGUNAN SIPIL PELINDUNG PANTAI",
        "sektor": "PUPR",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar (SBU)",
        "kewenangan": "Menteri PUPR",
    },
    "42919": {
        "judul": "KONSTRUKSI BANGUNAN SIPIL PRASARANA PERAIRAN LAINNYA",
        "sektor": "PUPR",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar (SBU)",
        "kewenangan": "Menteri PUPR",
    },
    "42991": {
        "judul": "KONSTRUKSI BANGUNAN SIPIL MINYAK DAN GAS BUMI",
        "sektor": "PUPR",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin (SBU)",
        "kewenangan": "Menteri PUPR",
    },
    "42992": {
        "judul": "KONSTRUKSI BANGUNAN SIPIL PERTAMBANGAN",
        "sektor": "PUPR",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin (SBU)",
        "kewenangan": "Menteri PUPR",
    },
    "42993": {
        "judul": "KONSTRUKSI BANGUNAN SIPIL PANAS BUMI",
        "sektor": "PUPR",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin (SBU)",
        "kewenangan": "Menteri PUPR",
    },
    "42994": {
        "judul": "KONSTRUKSI BANGUNAN SIPIL FASILITAS OLAHRAGA",
        "sektor": "PUPR",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar (SBU)",
        "kewenangan": "Menteri PUPR",
    },
    "42995": {
        "judul": "KONSTRUKSI BANGUNAN SIPIL FASILITAS PENGOLAHAN",
        "sektor": "PUPR",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar (SBU)",
        "kewenangan": "Menteri PUPR",
    },
    "42996": {
        "judul": "KONSTRUKSI BANGUNAN SIPIL FASILITAS MILITER",
        "sektor": "PUPR",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin (SBU)",
        "kewenangan": "Menteri PUPR",
    },
    "42997": {
        "judul": "KONSTRUKSI BANGUNAN SIPIL FASILITAS SUMBER RADIASI",
        "sektor": "PUPR",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin (SBU)",
        "kewenangan": "Menteri PUPR",
    },
    "42998": {
        "judul": "KONSTRUKSI BANGUNAN SIPIL REAKTOR NUKLIR",
        "sektor": "PUPR",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin (SBU)",
        "kewenangan": "Menteri PUPR",
    },
    "42999": {
        "judul": "KONSTRUKSI BANGUNAN SIPIL LAINNYA YTDL",
        "sektor": "PUPR",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar (SBU)",
        "kewenangan": "Menteri PUPR",
    },
    "60101": {
        "judul": "AKTIVITAS PENYIARAN RADIO ANALOG",
        "sektor": "Kominfo",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + IPP",
        "kewenangan": "Menteri Kominfo",
    },
    "60103": {
        "judul": "AKTIVITAS DISTRIBUSI DAN STREAMING AUDIO",
        "sektor": "Kominfo",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Kominfo",
    },
    "60201": {
        "judul": "AKTIVITAS PENYIARAN TELEVISI ANALOG",
        "sektor": "Kominfo",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + IPP",
        "kewenangan": "Menteri Kominfo",
    },
    "60203": {
        "judul": "AKTIVITAS DISTRIBUSI DAN STREAMING VIDEO",
        "sektor": "Kominfo",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Kominfo",
    },
    "60311": {
        "judul": "AKTIVITAS KANTOR BERITA PEMERINTAH",
        "sektor": "Kominfo",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Menteri Kominfo",
    },
    "60312": {
        "judul": "AKTIVITAS KANTOR BERITA SWASTA",
        "sektor": "Kominfo",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Kominfo",
    },
    "60390": {
        "judul": "AKTIVITAS SITUS JEJARING SOSIAL",
        "sektor": "Kominfo",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar (PSE)",
        "kewenangan": "Menteri Kominfo",
    },
    "61102": {
        "judul": "AKTIVITAS TELEKOMUNIKASI NIRKABEL",
        "sektor": "Kominfo",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Jartel",
        "kewenangan": "Menteri Kominfo",
    },
    "61103": {
        "judul": "AKTIVITAS TELEKOMUNIKASI SATELIT",
        "sektor": "Kominfo",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Jartel",
        "kewenangan": "Menteri Kominfo",
    },
    "61105": {
        "judul": "AKTIVITAS JASA SISTEM KOMUNIKASI DATA",
        "sektor": "Kominfo",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Jastel",
        "kewenangan": "Menteri Kominfo",
    },
    "61106": {
        "judul": "AKTIVITIAS JASA TELEVISI PROTOKOL INTERNET (IPTV)",
        "sektor": "Kominfo",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Jastel",
        "kewenangan": "Menteri Kominfo",
    },
    "61107": {
        "judul": "AKTIVITAS JASA GERBANG AKSES INTERNET",
        "sektor": "Kominfo",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Jastel (NAP)",
        "kewenangan": "Menteri Kominfo",
    },
    "61108": {
        "judul": "AKTIVITAS JASA TELEPONI DASAR",
        "sektor": "Kominfo",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Jastel",
        "kewenangan": "Menteri Kominfo",
    },
    "61201": {
        "judul": "AKTIVITAS PENJUALAN KEMBALI JASA TELEKOMUNIKASI",
        "sektor": "Kominfo",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Kominfo",
    },
    "61209": {
        "judul": "AKTIVITAS RESELLER JASA TELEKOMUNIKASI LAINNYA",
        "sektor": "Kominfo",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Kominfo",
    },
    "61901": {
        "judul": "AKTIVITAS JASA PANGGILAN PREMIUM",
        "sektor": "Kominfo",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Jastel",
        "kewenangan": "Menteri Kominfo",
    },
    "61902": {
        "judul": "AKTIVITAS JASA KONTEN SMS PREMIUM",
        "sektor": "Kominfo",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Jastel",
        "kewenangan": "Menteri Kominfo",
    },
    "61903": {
        "judul": "AKTIVITAS JASA INTERNET TELEPONI (VOIP)",
        "sektor": "Kominfo",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Jastel",
        "kewenangan": "Menteri Kominfo",
    },
    "61904": {
        "judul": "AKTIVITAS JASA PANGGILAN TERKELOLA",
        "sektor": "Kominfo",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Kominfo",
    },
    "61905": {
        "judul": "AKTIVITAS JASA TELEKOMUNIKASI KHUSUS SATELIT",
        "sektor": "Kominfo",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Jartel Khusus",
        "kewenangan": "Menteri Kominfo",
    },
    "61909": {
        "judul": "AKTIVITAS TELEKOMUNIKASI LAINNYA",
        "sektor": "Kominfo",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Jastel",
        "kewenangan": "Menteri Kominfo",
    },
    "62110": {
        "judul": "PENGEMBANGAN VIDEO GIM",
        "sektor": "Kominfo",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Menteri Kominfo",
    },
    "62193": {
        "judul": "PENGEMBANGAN APLIKASI TEKNOLOGI",
        "sektor": "Kominfo",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Menteri Kominfo",
    },
    "62194": {
        "judul": "PENGEMBANGAN AI",
        "sektor": "Kominfo",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Menteri Kominfo",
    },
    "62201": {
        "judul": "KONSULTANSI KEAMANAN SIBER",
        "sektor": "Kominfo",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Kominfo",
    },
    "62202": {
        "judul": "PENGELOLAAN IDENTITAS DIGITAL",
        "sektor": "Kominfo",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin (PSrE)",
        "kewenangan": "Menteri Kominfo",
    },
    "62204": {
        "judul": "KONSULTANSI INTERNET OF THINGS (IOT)",
        "sektor": "Kominfo",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Menteri Kominfo",
    },
    "62209": {
        "judul": "KONSULTANSI KOMPUTER LAINNYA",
        "sektor": "Kominfo",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Menteri Kominfo",
    },
    "63101": {
        "judul": "AKTIVITAS PENGOLAHAN DATA",
        "sektor": "Kominfo",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar (PSE)",
        "kewenangan": "Menteri Kominfo",
    },
    "63102": {
        "judul": "PENYEDIAAN INFRASTRUKTUR HOSTING",
        "sektor": "Kominfo",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Kominfo",
    },
    "63900": {
        "judul": "PORTAL PENCARIAN WEB",
        "sektor": "Kominfo",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar (PSE)",
        "kewenangan": "Menteri Kominfo",
    },
    "90111": {
        "judul": "PENCIPTAAN KARYA SASTRA",
        "sektor": "Pariwisata (Ekraf)",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "90112": {
        "judul": "PENCIPTAAN KOMPOSISI MUSIK",
        "sektor": "Pariwisata (Ekraf)",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "90113": {
        "judul": "JURNALIS INDEPENDEN",
        "sektor": "Pariwisata (Ekraf)",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "90310": {
        "judul": "OPERASIONAL TEMPAT KESENIAN",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "90391": {
        "judul": "PENYELENGGARAAN KEGIATAN KESENIAN",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "90399": {
        "judul": "PENUNJANG KARYA SENI",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "91111": {
        "judul": "PERPUSTAKAAN PEMERINTAH",
        "sektor": "Pendidikan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB (Non-Usaha)",
        "kewenangan": "Instansi Pemerintah",
    },
    "91112": {
        "judul": "PERPUSTAKAAN SWASTA",
        "sektor": "Pendidikan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "91121": {
        "judul": "KEARSIPAN PEMERINTAH",
        "sektor": "Pemerintahan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB (Non-Usaha)",
        "kewenangan": "Instansi Pemerintah",
    },
    "91122": {
        "judul": "KEARSIPAN SWASTA",
        "sektor": "Pendidikan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "91211": {
        "judul": "MUSEUM PEMERINTAH",
        "sektor": "Kebudayaan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB (Non-Usaha)",
        "kewenangan": "Instansi Pemerintah",
    },
    "91212": {
        "judul": "MUSEUM SWASTA",
        "sektor": "Kebudayaan",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "91221": {
        "judul": "SITUS BERSEJARAH PEMERINTAH",
        "sektor": "Kebudayaan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB (Non-Usaha)",
        "kewenangan": "Instansi Pemerintah",
    },
    "91222": {
        "judul": "SITUS BERSEJARAH SWASTA",
        "sektor": "Kebudayaan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "91300": {
        "judul": "KONSERVASI DAN RESTORASI",
        "sektor": "Kebudayaan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Dikbud",
    },
    "91410": {
        "judul": "KEBUN BINATANG",
        "sektor": "LHK",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Lembaga Konservasi",
        "kewenangan": "Menteri LHK",
    },
    "91421": {
        "judul": "SUAKA MARGASATWA",
        "sektor": "LHK",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Pengelola",
        "kewenangan": "Menteri LHK",
    },
    "91422": {
        "judul": "TAMAN NASIONAL",
        "sektor": "LHK",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Pengelola",
        "kewenangan": "Menteri LHK",
    },
    "91423": {
        "judul": "HUTAN LINDUNG",
        "sektor": "LHK",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Pengelola",
        "kewenangan": "Menteri LHK",
    },
    "91424": {
        "judul": "TAMAN WISATA ALAM",
        "sektor": "LHK",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri LHK",
    },
    "91425": {
        "judul": "TAMAN HUTAN RAYA",
        "sektor": "LHK",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Gubernur",
    },
    "91426": {
        "judul": "TAMAN LAUT",
        "sektor": "KKP",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Pengelola",
        "kewenangan": "Menteri KKP",
    },
    "91429": {
        "judul": "CAGAR ALAM LAINNYA",
        "sektor": "LHK",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin",
        "kewenangan": "Menteri LHK",
    },
    "93113": {
        "judul": "FASILITAS GELANGGANG/ARENA",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "93116": {
        "judul": "FASILITAS PUSAT KEBUGARAN",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "93121": {
        "judul": "KLUB SEPAK BOLA",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "93122": {
        "judul": "KLUB GOLF",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "93123": {
        "judul": "KLUB RENANG",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "93124": {
        "judul": "KLUB TENIS LAPANGAN",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "93125": {
        "judul": "KLUB TINJU",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "93126": {
        "judul": "KLUB BELA DIRI",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "93127": {
        "judul": "KLUB KEBUGARAN/BINARAGA",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "93128": {
        "judul": "KLUB BOLING",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "93129": {
        "judul": "KLUB OLAHRAGA LAINNYA",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "93192": {
        "judul": "JURI DAN WASIT PROFESIONAL",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "93193": {
        "judul": "PERBURUAN DI KAWASAN BURU",
        "sektor": "LHK",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Berburu",
        "kewenangan": "Menteri LHK",
    },
    "93194": {
        "judul": "BADAN REGULASI OLAHRAGA",
        "sektor": "Pemuda Olahraga",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Kemenpora",
    },
    "93195": {
        "judul": "OLAHRAGA TRADISIONAL",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "93197": {
        "judul": "ATLET INDEPENDEN",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "93199": {
        "judul": "AKTIVITAS OLAHRAGA LAINNYA",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "93210": {
        "judul": "TAMAN BERTEMA DAN HIBURAN",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar (CHSE)",
        "kewenangan": "Bupati/Walikota",
    },
    "93291": {
        "judul": "LANTAI DANSA",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "86102": {
        "judul": "PUSKESMAS",
        "sektor": "Kesehatan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar (Akreditasi)",
        "kewenangan": "Bupati/Walikota",
    },
    "86105": {
        "judul": "KLINIK SWASTA",
        "sektor": "Kesehatan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "86109": {
        "judul": "RUMAH SAKIT LAINNYA",
        "sektor": "Kesehatan",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Operasional",
        "kewenangan": "Menteri/Gubernur",
    },
    "86201": {
        "judul": "PRAKTIK DOKTER UMUM",
        "sektor": "Kesehatan",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + SIP",
        "kewenangan": "Bupati/Walikota",
    },
    "86202": {
        "judul": "PRAKTIK DOKTER SPESIALIS",
        "sektor": "Kesehatan",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + SIP",
        "kewenangan": "Bupati/Walikota",
    },
    "86203": {
        "judul": "PRAKTIK DOKTER GIGI",
        "sektor": "Kesehatan",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + SIP",
        "kewenangan": "Bupati/Walikota",
    },
    "86910": {
        "judul": "AKTIVITAS INTERMEDIASI KESEHATAN",
        "sektor": "Kesehatan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "86993": {
        "judul": "PELAYANAN PENUNJANG KESEHATAN",
        "sektor": "Kesehatan",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "86994": {
        "judul": "ANGKUTAN KHUSUS ORANG SAKIT (AMBULANS)",
        "sektor": "Kesehatan",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "86995": {
        "judul": "RUMAH PIJAT",
        "sektor": "Pariwisata / Kesehatan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar (STPT)",
        "kewenangan": "Bupati/Walikota",
    },
    "87101": {
        "judul": "PANTI REHAB NARKOBA",
        "sektor": "Sosial",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Operasional",
        "kewenangan": "Menteri Sosial",
    },
    "87102": {
        "judul": "PANTI REHAB MENTAL",
        "sektor": "Sosial",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Operasional",
        "kewenangan": "Menteri Sosial",
    },
    "87201": {
        "judul": "PERAWATAN DISABILITAS",
        "sektor": "Sosial",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Gubernur",
    },
    "87202": {
        "judul": "PERAWATAN DISABILITAS MENTAL",
        "sektor": "Sosial",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Gubernur",
    },
    "87301": {
        "judul": "PANTI WERDHA (LANSIA)",
        "sektor": "Sosial",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "87302": {
        "judul": "PERAWATAN LANSIA/DISABILITAS SWASTA",
        "sektor": "Sosial",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "87303": {
        "judul": "PENGELOLAAN AKOMODASI LANSIA",
        "sektor": "Sosial",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "87910": {
        "judul": "JASA INTERMEDIASI PERAWATAN",
        "sektor": "Sosial",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "87991": {
        "judul": "LKSA ANAK",
        "sektor": "Sosial",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Izin Operasional",
        "kewenangan": "Gubernur",
    },
    "87992": {
        "judul": "PERAWATAN ANAK BERMASALAH HUKUM",
        "sektor": "Sosial",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Operasional",
        "kewenangan": "Menteri Sosial",
    },
    "87993": {
        "judul": "TUNASOSIAL RESIDENSIAL",
        "sektor": "Sosial",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Gubernur",
    },
    "80190": {
        "judul": "AKTIVITAS KEAMANAN LAINNYA",
        "sektor": "Kepolisian",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Izin Operasional (Mabes Polri)",
        "kewenangan": "Mabes Polri",
    },
    "78104": {
        "judul": "PENEMPATAN AWAK KAPAL",
        "sektor": "Ketenagakerjaan / Perhubungan",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + SIUPPAK",
        "kewenangan": "Menteri Perhubungan",
    },
    "78105": {
        "judul": "PENYEDIAAN INFORMASI LOWONGAN KERJA",
        "sektor": "Ketenagakerjaan",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Disnaker",
    },
    "78109": {
        "judul": "PENEMPATAN TENAGA KERJA LAINNYA",
        "sektor": "Ketenagakerjaan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Izin LPTKS",
        "kewenangan": "Menteri Ketenagakerjaan",
    },
    "78200": {
        "judul": "PENYEDIAAN TENAGA KERJA WAKTU TERTENTU (OUTSOURCING)",
        "sektor": "Ketenagakerjaan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Ketenagakerjaan",
    },
    "69102": {
        "judul": "KONSULTAN HUKUM",
        "sektor": "Hukum",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "69103": {
        "judul": "KONSULTAN KEKAYAAN INTELEKTUAL",
        "sektor": "Hukum",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB + SK Konsultan KI",
        "kewenangan": "Kemenkumham",
    },
    "69104": {
        "judul": "NOTARIS DAN PPAT",
        "sektor": "Hukum / Pertanahan",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "SK Pengangkatan (Non-OSS)",
        "kewenangan": "Kemenkumham / BPN",
    },
    "69201": {
        "judul": "AKUNTANSI DAN PEMBUKUAN",
        "sektor": "Keuangan",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Izin KJA",
        "kewenangan": "Kemenkeu",
    },
    "69202": {
        "judul": "KONSULTANSI PAJAK",
        "sektor": "Keuangan",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Izin Praktik",
        "kewenangan": "Kemenkeu",
    },
    "70100": {
        "judul": "AKTIVITAS KANTOR PUSAT",
        "sektor": "Umum",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "88101": {
        "judul": "SOSIAL PEMERINTAH NON-AKOMODASI",
        "sektor": "Sosial",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB (Non-Usaha)",
        "kewenangan": "Instansi Pemerintah",
    },
    "88102": {
        "judul": "LKSA NON-AKOMODASI",
        "sektor": "Sosial",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Dinsos",
    },
    "88901": {
        "judul": "SOSIAL PEMERINTAH LAINNYA",
        "sektor": "Sosial",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB (Non-Usaha)",
        "kewenangan": "Instansi Pemerintah",
    },
    "88902": {
        "judul": "LKSA SWASTA LAINNYA",
        "sektor": "Sosial",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Dinsos",
    },
    "88903": {
        "judul": "PENGUMPULAN DANA KEISLAMAN (ZISWAF)",
        "sektor": "Agama",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "Izin LAZ",
        "kewenangan": "Kemenag / BAZNAS",
    },
    "88904": {
        "judul": "PENGUMPULAN DANA NONISLAM",
        "sektor": "Sosial",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "Izin PUB",
        "kewenangan": "Kemensos",
    },
    "88905": {
        "judul": "PENGUMPULAN DANA LAINNYA",
        "sektor": "Sosial",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "Izin PUB",
        "kewenangan": "Kemensos",
    },
    "88906": {
        "judul": "KELOMPOK BERMAIN",
        "sektor": "Pendidikan",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Izin Operasional PAUD",
        "kewenangan": "Disdik",
    },
    "88907": {
        "judul": "TAMAN PENITIPAN ANAK",
        "sektor": "Pendidikan / Sosial",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Izin Operasional",
        "kewenangan": "Disdik / Dinsos",
    },
    "94110": {
        "judul": "ORGANISASI BISNIS",
        "sektor": "Umum",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "SK Kemenkumham",
        "kewenangan": "Kemenkumham",
    },
    "94121": {
        "judul": "ORGANISASI PROFESI KESEHATAN",
        "sektor": "Kesehatan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "SK Kemenkumham",
        "kewenangan": "Kemenkumham",
    },
    "94122": {
        "judul": "ORGANISASI PROFESI LAINNYA",
        "sektor": "Umum",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "SK Kemenkumham",
        "kewenangan": "Kemenkumham",
    },
    "94200": {
        "judul": "SERIKAT BURUH",
        "sektor": "Ketenagakerjaan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "Pencatatan Disnaker",
        "kewenangan": "Disnaker",
    },
    "94910": {
        "judul": "ORGANISASI KEAGAMAAN",
        "sektor": "Agama",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "SK Kemenag",
        "kewenangan": "Kemenag",
    },
    "94920": {
        "judul": "PARTAI POLITIK",
        "sektor": "Politik",
        "tingkat_risiko": "Non-Usaha",
        "perizinan_berusaha": "SK Kemenkumham",
        "kewenangan": "Kemenkumham",
    },
    "94990": {
        "judul": "ORGANISASI KEMASYARAKATAN LAINNYA",
        "sektor": "Umum",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "SK Kemenkumham / SKT Kemendagri",
        "kewenangan": "Kemendagri",
    },
    "68121": {
        "judul": "PENGELOLAAN KAWASAN PARIWISATA",
        "sektor": "Pariwisata",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "68122": {
        "judul": "PENGELOLAAN KAWASAN INDUSTRI",
        "sektor": "Perindustrian",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin Usaha Kawasan Industri (IUKI)",
        "kewenangan": "Menteri Perindustrian",
    },
    "68123": {
        "judul": "PENGELOLAAN KEK",
        "sektor": "Ekonomi",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "Izin Administrator KEK",
        "kewenangan": "Dewan Nasional KEK",
    },
    "68124": {
        "judul": "PENYEWAAN LAHAN",
        "sektor": "Properti",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "68125": {
        "judul": "PENGELOLAAN PUSAT PERBELANJAAN",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "68126": {
        "judul": "PENYEWAAN GUDANG",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "68127": {
        "judul": "PENGELOLAAN GEDUNG PERKANTORAN",
        "sektor": "Properti",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "68129": {
        "judul": "REAL ESTAT NON-HUNIAN LAINNYA",
        "sektor": "Properti",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "68210": {
        "judul": "JASA INTERMEDIASI REAL ESTAT (BROKER)",
        "sektor": "Perdagangan",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + SIU-P4",
        "kewenangan": "Menteri Perdagangan",
    },
    "68291": {
        "judul": "JASA PENAKSIR REAL ESTAT (APPRAISAL)",
        "sektor": "Keuangan",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Izin KJPP",
        "kewenangan": "Kemenkeu",
    },
    "68292": {
        "judul": "PENGELOLAAN REAL ESTAT ATAS DASAR KONTRAK",
        "sektor": "Properti",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "68299": {
        "judul": "AKTIVITAS REAL ESTAT FEE LAINNYA",
        "sektor": "Properti",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "72101": {
        "judul": "PENELITIAN ILMU ALAM",
        "sektor": "Ristek",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Izin Penelitian",
        "kewenangan": "BRIN",
    },
    "72102": {
        "judul": "PENELITIAN TEKNOLOGI",
        "sektor": "Ristek",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Izin Penelitian",
        "kewenangan": "BRIN",
    },
    "72103": {
        "judul": "PENELITIAN MEDIS",
        "sektor": "Kesehatan",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Persetujuan Etik",
        "kewenangan": "Kemenkes / BRIN",
    },
    "72104": {
        "judul": "PENELITIAN BIOTEKNOLOGI",
        "sektor": "Ristek",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin",
        "kewenangan": "BRIN / LHK",
    },
    "72105": {
        "judul": "PENELITIAN FISIKA/ASTRONOMI",
        "sektor": "Ristek",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Izin",
        "kewenangan": "BRIN",
    },
    "72106": {
        "judul": "PENELITIAN NUKLIR",
        "sektor": "Ketenaganukliran",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin BAPETEN",
        "kewenangan": "BAPETEN",
    },
    "72201": {
        "judul": "PENELITIAN SOSIAL",
        "sektor": "Ristek",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "BRIN",
    },
    "72202": {
        "judul": "PENELITIAN HUMANIORA",
        "sektor": "Ristek",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "BRIN",
    },
    "10432": {
        "judul": "INDUSTRI MINYAK INTI SAWIT (PKO)",
        "sektor": "Perindustrian",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Perindustrian",
    },
    "10503": {
        "judul": "INDUSTRI ES KRIM",
        "sektor": "Perindustrian",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar (MD/ML)",
        "kewenangan": "BPOM",
    },
    "10504": {
        "judul": "INDUSTRI ES PENCUCI MULUT",
        "sektor": "Perindustrian",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "10612": {
        "judul": "INDUSTRI GILINGAN KACANG",
        "sektor": "Perindustrian",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "10622": {
        "judul": "INDUSTRI PATI PALEM",
        "sektor": "Perindustrian",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Perindustrian",
    },
    "10623": {
        "judul": "INDUSTRI GLUKOSA",
        "sektor": "Perindustrian",
        "tingkat_risiko": "Menengah Tinggi",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Menteri Perindustrian",
    },
    "10722": {
        "judul": "INDUSTRI GULA MERAH",
        "sektor": "Perindustrian",
        "tingkat_risiko": "Rendah",
        "perizinan_berusaha": "NIB",
        "kewenangan": "Bupati/Walikota",
    },
    "10723": {
        "judul": "INDUSTRI SIROP",
        "sektor": "Perindustrian",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar (P-IRT/MD)",
        "kewenangan": "Bupati/BPOM",
    },
    "10732": {
        "judul": "INDUSTRI COKELAT",
        "sektor": "Perindustrian",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "10740": {
        "judul": "INDUSTRI MAKARONI DAN MI",
        "sektor": "Perindustrian",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "10762": {
        "judul": "PENGOLAHAN TEH",
        "sektor": "Perindustrian",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "10772": {
        "judul": "INDUSTRI GARAM BERYODIUM",
        "sektor": "Perindustrian",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin (SNI Wajib)",
        "kewenangan": "Menteri Perindustrian",
    },
    "10773": {
        "judul": "INDUSTRI GARAM INDUSTRI",
        "sektor": "Perindustrian",
        "tingkat_risiko": "Tinggi",
        "perizinan_berusaha": "NIB + Izin",
        "kewenangan": "Menteri Perindustrian",
    },
    "10795": {
        "judul": "INDUSTRI SARI NABATI",
        "sektor": "Perindustrian",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
    "10797": {
        "judul": "INDUSTRI INFUSI HERBAL",
        "sektor": "Perindustrian",
        "tingkat_risiko": "Menengah Rendah",
        "perizinan_berusaha": "NIB + Sertifikat Standar",
        "kewenangan": "Bupati/Walikota",
    },
}

for k in data:
    data[k]["status"] = "VERIFIED"

# Update existing file
with open("recovered_kbli_atlas_full.json", "r") as f:
    existing_data = json.load(f)

existing_data.update(data)

with open("recovered_kbli_atlas_full.json", "w") as f:
    json.dump(existing_data, f, indent=2)

print("Updated recovered_kbli_atlas_full.json with 316+ gap codes.")
