import json

data = {
    "11020": {"judul": "INDUSTRI MINUMAN BERALKOHOL HASIL FERMENTASI ANGGUR", "sektor": "Perindustrian", "tingkat_risiko": "Tinggi", "perizinan_berusaha": "NIB + Izin (IUI)", "kewenangan": "Menteri Perindustrian"},
    "11030": {"judul": "INDUSTRI MINUMAN BERALKOHOL HASIL FERMENTASI MALT", "sektor": "Perindustrian", "tingkat_risiko": "Tinggi", "perizinan_berusaha": "NIB + Izin (IUI)", "kewenangan": "Menteri Perindustrian"},
    "11040": {"judul": "INDUSTRI MALT", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "11051": {"judul": "INDUSTRI AIR KEMASAN", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar (SNI)", "kewenangan": "Menteri Perindustrian"},
    "11052": {"judul": "INDUSTRI AIR MINUM ISI ULANG", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "11053": {"judul": "INDUSTRI MINUMAN RINGAN", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "11059": {"judul": "INDUSTRI MINUMAN LAINNYA", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "12001": {"judul": "INDUSTRI SIGARET KRETEK TANGAN", "sektor": "Perindustrian", "tingkat_risiko": "Tinggi", "perizinan_berusaha": "NIB + Izin (NPPBKC)", "kewenangan": "Bea Cukai"},
    "12002": {"judul": "INDUSTRI SIGARET KRETEK MESIN", "sektor": "Perindustrian", "tingkat_risiko": "Tinggi", "perizinan_berusaha": "NIB + Izin (NPPBKC)", "kewenangan": "Bea Cukai"},
    "12003": {"judul": "INDUSTRI ROKOK PUTIH", "sektor": "Perindustrian", "tingkat_risiko": "Tinggi", "perizinan_berusaha": "NIB + Izin (NPPBKC)", "kewenangan": "Bea Cukai"},
    "12004": {"judul": "INDUSTRI PENGERINGAN DAN PENGOLAHAN TEMBAKAU", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "12005": {"judul": "INDUSTRI BUMBU ROKOK", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "12009": {"judul": "INDUSTRI PRODUK TEMBAKAU LAINNYA", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "13112": {"judul": "PEMINTALAN BENANG SELAIN BENANG JAHIT", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "13121": {"judul": "PERTENUNAN TEKSTIL DENGAN MESIN", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "13122": {"judul": "PERTENUNAN TEKSTIL BUKAN DENGAN MESIN", "sektor": "Perindustrian", "tingkat_risiko": "Rendah", "perizinan_berusaha": "NIB", "kewenangan": "Bupati/Walikota"},
    "13139": {"judul": "PENYEMPURNAAN TEKSTIL LAINNYA", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "13911": {"judul": "INDUSTRI KAIN RAJUTAN", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "13912": {"judul": "INDUSTRI KAIN CROCHETED", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "13923": {"judul": "INDUSTRI KARUNG GONI", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "13929": {"judul": "INDUSTRI BARANG TEKSTIL BUKAN PAKAIAN JADI LAINNYA", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "13942": {"judul": "INDUSTRI BARANG DARI TALI", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "13992": {"judul": "INDUSTRI KAIN YANG DILAPISI DAN SEJENISNYA", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "13994": {"judul": "INDUSTRI KAIN BAN", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "14111": {"judul": "INDUSTRI PAKAIAN JADI (KONFEKSI) DARI TEKSTIL", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "14112": {"judul": "INDUSTRI PAKAIAN JADI (KONFEKSI) DARI KULIT DAN TIRUAN", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "14120": {"judul": "INDUSTRI PENJAHITAN DAN PEMBUATAN (BUKAN KONFEKSI)", "sektor": "Perindustrian", "tingkat_risiko": "Rendah", "perizinan_berusaha": "NIB", "kewenangan": "Bupati/Walikota"},
    "14132": {"judul": "INDUSTRI PERLENGKAPAN PAKAIAN DARI KULIT DAN TIRUAN", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "14200": {"judul": "INDUSTRI BARANG DARI KULIT BERBULU", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "14302": {"judul": "INDUSTRI HOSIERY RAJUTAN DAN CROCHETED", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "15112": {"judul": "PENYAMAKAN KULIT", "sektor": "Perindustrian", "tingkat_risiko": "Tinggi", "perizinan_berusaha": "NIB + Izin (IUI)", "kewenangan": "Menteri Perindustrian"},
    "15113": {"judul": "PEWARNAAN KULIT BERBULU", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "15122": {"judul": "INDUSTRI PELANA, ALAT PENGEKANG/HARNESS, DAN BARANG", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "15129": {"judul": "INDUSTRI BARANG LAINNYA DARI KULIT DAN KULIT KOMPOSISI", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "15201": {"judul": "INDUSTRI ALAS KAKI UNTUK KEPERLUAN SEHARI-HARI", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "15202": {"judul": "INDUSTRI SEPATU OLAHRAGA", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "15203": {"judul": "INDUSTRI SEPATU TEKNIK LAPANGAN/KEPERLUAN INDUSTRI", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "15209": {"judul": "INDUSTRI ALAS KAKI LAINNYA", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "17021": {"judul": "INDUSTRI KERTAS DAN PAPAN KERTAS BERGELOMBANG", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "18113": {"judul": "PENCETAKAN TIGA DIMENSI (3D)", "sektor": "Perindustrian", "tingkat_risiko": "Rendah", "perizinan_berusaha": "NIB", "kewenangan": "Bupati/Walikota"},
    "18120": {"judul": "KEGIATAN JASA PENUNJANG PENCETAKAN", "sektor": "Perindustrian", "tingkat_risiko": "Rendah", "perizinan_berusaha": "NIB", "kewenangan": "Bupati/Walikota"},
    "18201": {"judul": "REPRODUKSI MEDIA REKAMAN SUARA DAN PERANGKAT LUNAK", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "18202": {"judul": "REPRODUKSI MEDIA REKAMAN FILM DAN VIDEO", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "19201": {"judul": "INDUSTRI BAHAN BAKAR DARI PEMURNIAN DAN PENGILANGAN", "sektor": "ESDM", "tingkat_risiko": "Tinggi", "perizinan_berusaha": "NIB + Izin", "kewenangan": "Menteri ESDM"},
    "19202": {"judul": "INDUSTRI MINYAK PELUMAS", "sektor": "ESDM", "tingkat_risiko": "Tinggi", "perizinan_berusaha": "NIB + Izin", "kewenangan": "Menteri ESDM"},
    "19203": {"judul": "INDUSTRI PRODUK DARI BAHAN LIMBAH MINYAK PELUMAS", "sektor": "ESDM", "tingkat_risiko": "Tinggi", "perizinan_berusaha": "NIB + Izin", "kewenangan": "Menteri ESDM"},
    "19204": {"judul": "INDUSTRI MINYAK PELUMAS DASAR", "sektor": "ESDM", "tingkat_risiko": "Tinggi", "perizinan_berusaha": "NIB + Izin", "kewenangan": "Menteri ESDM"},
    "19205": {"judul": "INDUSTRI BRIKET", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "19206": {"judul": "INDUSTRI PRODUK DARI PENCAMPURAN HASIL KILANG MINYAK", "sektor": "ESDM", "tingkat_risiko": "Tinggi", "perizinan_berusaha": "NIB + Izin", "kewenangan": "Menteri ESDM"},
    "20112": {"judul": "INDUSTRI GAS INDUSTRI", "sektor": "Perindustrian", "tingkat_risiko": "Tinggi", "perizinan_berusaha": "NIB + Izin (IUI)", "kewenangan": "Menteri Perindustrian"},
    "20113": {"judul": "INDUSTRI KIMIA DASAR ZAT WARNA DAN PIGMEN", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "20114": {"judul": "INDUSTRI KIMIA DASAR RADIOAKTIF", "sektor": "ESDM / Ketenaganukliran", "tingkat_risiko": "Tinggi", "perizinan_berusaha": "NIB + Izin", "kewenangan": "BAPETEN"},
    "20116": {"judul": "INDUSTRI KIMIA DASAR DARI MINYAK BUMI, GAS ALAM, DAN BATU", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "20132": {"judul": "INDUSTRI KARET BUATAN", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "20213": {"judul": "INDUSTRI ZAT PENGATUR TUMBUH", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "20229": {"judul": "INDUSTRI SEDIAAN PEWARNA DAN PELAPIS LAINNYA", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "20231": {"judul": "INDUSTRI BAHAN DAN PRODUK PEMBERSIH", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "20235": {"judul": "INDUSTRI PARFUM SESUAI PESANAN", "sektor": "Perindustrian", "tingkat_risiko": "Rendah", "perizinan_berusaha": "NIB", "kewenangan": "Bupati/Walikota"},
    "20291": {"judul": "INDUSTRI PEREKAT/LEM", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "20297": {"judul": "INDUSTRI BIOFUEL CAIR", "sektor": "ESDM", "tingkat_risiko": "Tinggi", "perizinan_berusaha": "NIB + Izin", "kewenangan": "Menteri ESDM"},
    "20298": {"judul": "INDUSTRI CAIRAN ROKOK ELEKTRIK", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "21012": {"judul": "INDUSTRI PRODUK FARMASI UNTUK MANUSIA", "sektor": "Kesehatan", "tingkat_risiko": "Tinggi", "perizinan_berusaha": "NIB + Izin", "kewenangan": "Menteri Kesehatan"},
    "22111": {"judul": "INDUSTRI BAN LUAR DAN BAN DALAM", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "22112": {"judul": "INDUSTRI PEMBENTUKAN KEMBALI BAN DAN VULKANISASI BAN", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "22123": {"judul": "INDUSTRI KARET REMAH (CRUMB RUBBER)", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "22193": {"judul": "INDUSTRI BARANG KARET LAINNYA", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "22199": {"judul": "INDUSTRI BARANG LAINNYA DARI KARET YTDL", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "22204": {"judul": "INDUSTRI PLASTIK LEMBARAN", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "22209": {"judul": "INDUSTRI BARANG LAINNYA DARI PLASTIK", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "23111": {"judul": "INDUSTRI KACA LEMBARAN", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "23112": {"judul": "INDUSTRI KACA PENGAMAN", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "23119": {"judul": "INDUSTRI KACA LAINNYA", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "23121": {"judul": "INDUSTRI PERLENGKAPAN DAN PERALATAN RUMAH TANGGA DARI KACA", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "23122": {"judul": "INDUSTRI PERALATAN LABORATORIUM DAN KESEHATAN DARI KACA", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "23911": {"judul": "INDUSTRI BATA, MORTAR, SEMEN YANG TAHAN API", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "23921": {"judul": "INDUSTRI BATU BATA DARI TANAH LIAT ATAU KERAMIK", "sektor": "Perindustrian", "tingkat_risiko": "Rendah", "perizinan_berusaha": "NIB", "kewenangan": "Bupati/Walikota"},
    "23941": {"judul": "INDUSTRI SEMEN", "sektor": "Perindustrian", "tingkat_risiko": "Tinggi", "perizinan_berusaha": "NIB + Izin", "kewenangan": "Menteri Perindustrian"},
    "23991": {"judul": "INDUSTRI PRODUK ABRASIF", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "23992": {"judul": "INDUSTRI BATUAN ASPAL DAN BARANG DARI ASPAL", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "23993": {"judul": "INDUSTRI PRODUK HASIL PEMURNIAN MINERAL NONLOGAM", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "23999": {"judul": "INDUSTRI PRODUK MINERAL NONLOGAM LAINNYA YTDL", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "24201": {"judul": "INDUSTRI LOGAM DASAR MULIA", "sektor": "Perindustrian", "tingkat_risiko": "Tinggi", "perizinan_berusaha": "NIB + Izin", "kewenangan": "Menteri Perindustrian"},
    "24202": {"judul": "INDUSTRI LOGAM DASAR BUKAN BESI LAINNYA", "sektor": "Perindustrian", "tingkat_risiko": "Tinggi", "perizinan_berusaha": "NIB + Izin", "kewenangan": "Menteri Perindustrian"},
    "24203": {"judul": "PENGGILINGAN LOGAM BUKAN BESI", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "24310": {"judul": "PENGECORAN BESI DAN BAJA", "sektor": "Perindustrian", "tingkat_risiko": "Tinggi", "perizinan_berusaha": "NIB + Izin", "kewenangan": "Menteri Perindustrian"},
    "25119": {"judul": "INDUSTRI PRODUK LOGAM STRUKTURAL LAINNYA", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "25130": {"judul": "INDUSTRI GENERATOR UAP BUKAN KETEL PEMANAS", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "25951": {"judul": "INDUSTRI BARANG DARI KAWAT LOGAM BUKAN KABEL", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "26110": {"judul": "INDUSTRI KOMPONEN ELEKTRONIK", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "26191": {"judul": "INDUSTRI TABUNG ELEKTRON DAN KONEKTOR ELEKTRONIK", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "26199": {"judul": "INDUSTRI KOMPONEN DAN PAPAN ELEKTRONIK LAINNYA YTDL", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "26210": {"judul": "INDUSTRI KOMPUTER DAN PERAKITAN KOMPUTER", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "26391": {"judul": "INDUSTRI KARTU CERDAS (SMART CARD)", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "26511": {"judul": "INDUSTRI ALAT UKUR DAN ALAT UJI MANUAL", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "26519": {"judul": "INDUSTRI ALAT UKUR, ALAT UJI, DAN PERALATAN NAVIGASI LAINNYA", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "26601": {"judul": "INDUSTRI PERALATAN RADIASI DAN ELEKTROMEDIS", "sektor": "Kesehatan", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Produksi", "kewenangan": "Menteri Kesehatan"},
    "26701": {"judul": "INDUSTRI PERALATAN FOTOGRAFI", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "26702": {"judul": "INDUSTRI PERALATAN SINEMATOGRAFI", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "26703": {"judul": "INDUSTRI LENSA BUKAN KACAMATA", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "26709": {"judul": "INDUSTRI PERALATAN FOTOGRAFI DAN INSTRUMEN OPTIK LAINNYA", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "26800": {"judul": "INDUSTRI MEDIA MAGNETIK DAN MEDIA OPTIK", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "27112": {"judul": "INDUSTRI GENERATOR PEMBANGKIT LISTRIK", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "27113": {"judul": "INDUSTRI TRANSFORMATOR, PENGONTROL DAN PENYALUR LISTRIK", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "27310": {"judul": "INDUSTRI KABEL SERAT OPTIK", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "27401": {"judul": "INDUSTRI BOLA LAMPU PIJAR, LAMPU SOROT, DAN LAMPU LAINNYA", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "27402": {"judul": "INDUSTRI LAMPU GAS DAN DISCHARGE", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "27520": {"judul": "INDUSTRI PERALATAN ELEKTROTERMAL RUMAH TANGGA", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "28111": {"judul": "INDUSTRI MESIN UAP, TURBIN, DAN KINCIR", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "28112": {"judul": "INDUSTRI MOTOR PEMBAKARAN DALAM", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "28152": {"judul": "INDUSTRI OVEN, PERAPIAN DAN TUNGKU PEMBAKAR SEJENIS", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "28172": {"judul": "INDUSTRI MESIN KANTOR DAN AKUNTANSI ELEKTRIK", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "28173": {"judul": "INDUSTRI MESIN KANTOR DAN AKUNTANSI ELEKTRONIK", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "28179": {"judul": "INDUSTRI PERALATAN KANTOR", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "28180": {"judul": "INDUSTRI PERKAKAS TANGAN YANG DIGERAKKAN TENAGA", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "28192": {"judul": "INDUSTRI MESIN TIMBANGAN", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "28199": {"judul": "INDUSTRI MESIN UNTUK KEPERLUAN UMUM LAINNYA YTDL", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "28210": {"judul": "INDUSTRI MESIN PERTANIAN DAN KEHUTANAN", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "28220": {"judul": "INDUSTRI MESIN DAN PERKAKAS MESIN UNTUK PENGERJAAN", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "28230": {"judul": "INDUSTRI MESIN METALURGI", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "28240": {"judul": "INDUSTRI MESIN PENAMBANGAN, PENGGALIAN DAN KONSTRUKSI", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "28261": {"judul": "INDUSTRI MESIN JAHIT, MESIN CUCI, DAN MESIN PENGERING", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "28262": {"judul": "INDUSTRI MESIN TEKSTIL", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "28263": {"judul": "INDUSTRI MESIN PENYIAPAN DAN PEMBUATAN PRODUK KULIT", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "28291": {"judul": "INDUSTRI MESIN PERCETAKAN", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "28292": {"judul": "INDUSTRI MESIN PABRIK KERTAS", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "28299": {"judul": "INDUSTRI MESIN KEPERLUAN KHUSUS LAINNYA YTDL", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "29100": {"judul": "INDUSTRI KENDARAAN BERMOTOR RODA EMPAT ATAU LEBIH", "sektor": "Perindustrian", "tingkat_risiko": "Tinggi", "perizinan_berusaha": "NIB + Izin", "kewenangan": "Menteri Perindustrian"},
    "29200": {"judul": "INDUSTRI KAROSERI KENDARAAN BERMOTOR RODA EMPAT ATAU LEBIH", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "30301": {"judul": "INDUSTRI PESAWAT UDARA BERAWAK DAN MESIN TERKAIT", "sektor": "Perindustrian", "tingkat_risiko": "Tinggi", "perizinan_berusaha": "NIB + Izin", "kewenangan": "Menteri Perindustrian"},
    "30302": {"judul": "INDUSTRI PESAWAT UDARA TANPA AWAK DAN MESIN TERKAIT", "sektor": "Perindustrian", "tingkat_risiko": "Tinggi", "perizinan_berusaha": "NIB + Izin", "kewenangan": "Menteri Perindustrian"},
    "30303": {"judul": "INDUSTRI WAHANA ANTARIKSA DAN MESIN TERKAIT", "sektor": "Perindustrian", "tingkat_risiko": "Tinggi", "perizinan_berusaha": "NIB + Izin", "kewenangan": "Menteri Perindustrian"},
    "31011": {"judul": "INDUSTRI FURNITUR DARI KAYU", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "31021": {"judul": "INDUSTRI FURNITUR DARI PLASTIK", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "31022": {"judul": "INDUSTRI FURNITUR DARI LOGAM", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "31029": {"judul": "INDUSTRI FURNITUR DARI BAHAN LAINNYA YTDL", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "32113": {"judul": "INDUSTRI BARANG BERHARGA DARI LOGAM MULIA BUKAN PERHIASAN", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "32119": {"judul": "INDUSTRI BARANG BERHARGA LAINNYA DARI LOGAM MULIA", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "32501": {"judul": "INDUSTRI FURNITUR UNTUK OPERASI, PERAWATAN KEDOKTERAN", "sektor": "Kesehatan", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Produksi", "kewenangan": "Menteri Kesehatan"},
    "32908": {"judul": "INDUSTRI PEMANTIK API/LIGHTER", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "33121": {"judul": "REPARASI DAN PEMELIHARAAN MESIN UNTUK KEPERLUAN UMUM", "sektor": "Perindustrian", "tingkat_risiko": "Rendah", "perizinan_berusaha": "NIB", "kewenangan": "Bupati/Walikota"},
    "33131": {"judul": "REPARASI DAN PEMELIHARAAN ALAT UKUR, ALAT UJI LAINNYA", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "33132": {"judul": "REPARASI PERALATAN FOTOGRAFI E OPTIK", "sektor": "Perindustrian", "tingkat_risiko": "Rendah", "perizinan_berusaha": "NIB", "kewenangan": "Bupati/Walikota"},
    "33141": {"judul": "REPARASI DAN PEMELIHARAAN MOTOR LISTRIK, GENERATOR", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "33152": {"judul": "REPARASI DAN PEMELIHARAAN LOKOMOTIF DAN GERBONG", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "33201": {"judul": "INSTALASI/PEMASANGAN DAN PERANGKAIAN MESIN INDUSTRI", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Tinggi", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri Perindustrian"},
    "33202": {"judul": "PEMBONGKARAN MESIN, PERALATAN, DAN SISTEM INDUSTRI", "sektor": "Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Bupati/Walikota"},
    "33203": {"judul": "PEMASANGAN PERLENGKAPAN METEOROLOGI, KLIMATOLOGI", "sektor": "ESDM / Perindustrian", "tingkat_risiko": "Menengah Rendah", "perizinan_berusaha": "NIB + Sertifikat Standar", "kewenangan": "Menteri/Gubernur"}
}

for k in data:
    data[k]["status"] = "VERIFIED"

with open('recovered_kbli_atlas_full.json', 'r') as f:
    existing_data = json.load(f)

existing_data.update(data)

with open('recovered_kbli_atlas_full.json', 'w') as f:
    json.dump(existing_data, f, indent=2)

print("Updated recovered_kbli_atlas_full.json with all Industrial codes.")
