"""Interview-walk decisiveness census: what the PUBLIC funnel actually answers.

``test_gold_coverage_floor.py`` proves the pack can support a product when
every fact arrives. This file proves the opposite half, and it is the half
the user lives in: replay the **43 real interview walks** — every distinct
path through ``flow.ts``'s two-arm spine and ``getCategoryQuestionIds``'
ten categories, each answered through the real ``fact-mapper.ts`` — against
the highest signed PRODUCTION pack, and pin the outcome census.

Measured 2026-09-06 on ``rulepack-prod-019.signed.json``, AFTER the PR-2
evaluator reorder: **13 NEEDS_INPUT / 23 NO_SUPPORTED_PATH / 7
SUPPORTED_CANDIDATES**. PR-0 pinned the pre-reorder shape on the same pack —
36 NEEDS_INPUT / 0 NO_SUPPORTED_PATH / 7 SUPPORTED_CANDIDATES — so the
reorder turned 23 dead ends into an honest "no path for you" and left 13
(research/visa/2026-09-06-visa-oracle-decisiveness-investigation.md §1-§2,
§4 PR-2). The engine stays fail-closed: not one walk moved INTO
SUPPORTED_CANDIDATES and the 7 answers are byte-identical, candidates
included — the reachable move is ``NEEDS_INPUT`` → ``NO_SUPPORTED_PATH``,
never anything → ``SUPPORTED_CANDIDATES``.

This table is pinned against seq-19, the highest signed pack on disk today.
It is RE-DERIVED, not hand-edited, when the seq-20 signed bundle lands: that
is the wave PR whose four pack edits retire the remaining
``family.sponsor_status_code`` rows.

The invariant this file exists to arm is one sentence:

    no walk may end in NEEDS_INPUT on a fact for which the interview has no
    reachable question in that walk's own history.

Today it is violated 13 times, so it ships as an EXPLICIT allowlist of the
13 remaining dead ends. Each subsequent PR of the decisiveness wave deletes
the rows it cures (this PR's evaluator reorder deleted 23 of the original
36; the four seq-20 pack edits and the four new interview questions remove
the rest). **When
``WALK_DEAD_END_ALLOWLIST`` is empty the invariant becomes unconditional** —
``_dead_end_violations`` needs no change for that, it simply stops finding
an excuse for any NEEDS_INPUT walk.

The corpus under ``gold_coverage/fixtures/walks/`` is DATA, generated by driving the
real ``computeNextNode``/``getCategoryQuestionIds``/``mapOracleFactsToApplicantFacts``
(first option answered at every question, 121 stay-days), never hand-written:
each file carries the walk's ``asked`` question ids and the exact wire
``overrides`` that walk produced. The expectations live HERE, in one
reviewable table, so a wave PR that moves an outcome must state which
outcome it moved.

Regenerate the corpus with ``npm run visa-oracle:walk-corpus -w apps/mouth``
(``apps/mouth/scripts/visa-oracle/generate-walk-corpus.ts``, proved byte-for-byte
reproducible by ``walk-corpus-determinism.test.ts``): a PR that changes the
interview tree MUST regenerate it and update ``EXPECTED_OUTCOME`` /
``WALK_DEAD_END_ALLOWLIST`` below in that same PR.
"""

from __future__ import annotations

import json
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pytest

from backend.scripts.visa_engine.gold_coverage_eval import _evaluate
from backend.scripts.visa_engine.gold_replay_driver import (
    PACKS_DIR,
    _parse_utc,
    select_highest_repository_pack,
)

CORPUS_DIR = Path(__file__).resolve().parent / "gold_coverage" / "fixtures" / "walks"

# PINNED to the highest signed pack's own `signed_at`, never the wall clock —
# same clock bomb `test_gold_coverage_floor.py` documents at length: the
# selected pack's source_records carry a freshness_policy with as little as a
# 604800s (7-day) window, so evaluating at `datetime.now(UTC)` is guaranteed
# to turn this whole census into HUMAN_REVIEW_REQUIRED seven days after the
# newest source's verified_at, with zero code change. `signed_at` (not
# `payload.created_at`) because the same instant drives `verify_rule_pack`'s
# `observed_at`, which rejects a signature dated after the observation.
_, _HIGHEST_SIGNED_PACK = select_highest_repository_pack(PACKS_DIR)
_AS_OF = _parse_utc(_HIGHEST_SIGNED_PACK["protected"]["signed_at"])

#: Why an allowlisted NEEDS_INPUT is a DEAD END and not a question the funnel
#: could ask. Each value is checked against the walk's own `asked` history.
NO_QUESTION_IN_TREE = "no question in tree.ts can ever set this fact"
QUESTION_NOT_IN_THIS_WALK = "the question exists but this walk's branch never asks it"
ANSWER_NEVER_CERTIFIED = "the question IS asked, and the mapper refuses to certify the answer"


@dataclass(frozen=True)
class DeadEnd:
    """One allowlisted dead end: the blocking fact, its source question in
    ``tree.ts`` (``None`` when no question emits it at all), and the reason
    the funnel cannot supply it."""

    fact: str
    source_question: str | None
    why_unaskable: str


# The three dead-end shapes still measured on seq-19 after the PR-2 reorder,
# with the anchor that explains each. A wave PR retires a shape by deleting
# its rows below, never by loosening a count.
_ONSHORE_CONVERSION = DeadEnd(
    # flow.ts:539-542 emits `wants_onshore_conversion` only when
    # `in_indonesia === "yes"`, so no offshore walk can answer it, and
    # `hf.d12-onshore-conversion-excluded` (safety_critical, on_unknown:
    # NEEDS_INPUT) blocks on behalf of D12.
    #
    # After the PR-2 reorder this shape survives on exactly the six offshore
    # INVESTMENT walks and nowhere else — and there it is a REAL question,
    # not noise: D12's SUPPORT rules do cover INVESTMENT, so D12 is a genuine
    # candidate for these six and the answer would decide them (measured:
    # `wants_onshore_conversion=false` turns `offshore/invest/pt_pma` into
    # SUPPORTED_CANDIDATES ['D12']). The other 20 offshore walks used to
    # inherit this block only because a purpose-infeasible D12 was allowed to
    # choose the global question; the reorder took that away. PR-3 asks the
    # question in the offshore branch and retires the shape.
    "process.wants_onshore_conversion",
    "wants_onshore_conversion",
    QUESTION_NOT_IN_THIS_WALK,
)
_DIASPORA_PURPOSE = DeadEnd(
    # `category` IS asked, but CATEGORY_TO_PURPOSE (fact-mapper.ts:255-266)
    # deliberately has no `diaspora` entry, so `mapPurposes` returns
    # unknownFact(NOT_APPLICABLE) — the answer exists and is refused.
    "intent.purposes",
    "category",
    ANSWER_NEVER_CERTIFIED,
)
_SPONSOR_STATUS_CODE = DeadEnd(
    # asked as `family_sponsor_status_code`, and fact-mapper.ts:505-520
    # returns unknownFact(UNVERIFIED) for EVERY answer by design: a
    # self-declared status label must never satisfy `op: known`. A permanent
    # wall, so the eight rules reading it must not ask (seq-20 edit 3).
    "family.sponsor_status_code",
    "family_sponsor_status_code",
    ANSWER_NEVER_CERTIFIED,
)
_SPONSOR_STATUS_CODE_NOT_ASKED = DeadEnd(
    # Same fact and same permanent wall as `_SPONSOR_STATUS_CODE`, but a
    # DIFFERENT reason and therefore a different row: `offshore/family` with
    # `relation=SIBLING, spNat=ID` never reaches `family_sponsor_status_code`
    # at all, so the mapper is never even given an answer to refuse. Kept
    # distinct because
    # `test_every_allowlisted_dead_end_is_genuinely_unaskable_in_its_own_walk`
    # checks the reason against the walk's own `asked` history: claiming
    # ANSWER_NEVER_CERTIFIED here would be a false statement about this walk.
    "family.sponsor_status_code",
    "family_sponsor_status_code",
    QUESTION_NOT_IN_THIS_WALK,
)

#: The 13 dead ends that survive the PR-2 reorder. DELETE rows as the wave
#: cures them; never add one without an anchor showing the fact is genuinely
#: unaskable in that walk.
WALK_DEAD_END_ALLOWLIST: dict[str, tuple[DeadEnd, ...]] = {
    "offshore/diaspora": (_DIASPORA_PURPOSE,),
    "offshore/family/CHILD/spNat=IT": (_SPONSOR_STATUS_CODE,),
    "offshore/family/SIBLING/spNat=ID": (_SPONSOR_STATUS_CODE_NOT_ASKED,),
    "offshore/family/SIBLING/spNat=IT": (_SPONSOR_STATUS_CODE,),
    "offshore/family/SPOUSE/spNat=IT": (_SPONSOR_STATUS_CODE,),
    "offshore/invest/bank_deposit": (_ONSHORE_CONVERSION,),
    "offshore/invest/family": (_ONSHORE_CONVERSION,),
    "offshore/invest/merit": (_ONSHORE_CONVERSION,),
    "offshore/invest/property": (_ONSHORE_CONVERSION,),
    "offshore/invest/pt_pma": (_ONSHORE_CONVERSION,),
    "offshore/invest/undecided": (_ONSHORE_CONVERSION,),
    "onshore/diaspora": (_DIASPORA_PURPOSE,),
    "onshore/family": (_SPONSOR_STATUS_CODE,),
}

#: Per-walk outcome pin: state plus the candidate products, in rank order.
#: Candidates are pinned too — a pack edit that adds or drops a product for a
#: walk that already had an answer is exactly as much of a shift as a state
#: change, and this table is the only place either becomes visible.
EXPECTED_OUTCOME: dict[str, tuple[str, tuple[str, ...]]] = {
    "offshore/business": ("NO_SUPPORTED_PATH", ()),
    "offshore/diaspora": ("NEEDS_INPUT", ()),
    "offshore/family/CHILD/spNat=ID": ("SUPPORTED_CANDIDATES", ("E31G",)),
    "offshore/family/CHILD/spNat=IT": ("NEEDS_INPUT", ()),
    "offshore/family/DEPENDENT/spNat=ID": ("NO_SUPPORTED_PATH", ()),
    "offshore/family/DEPENDENT/spNat=IT": ("NO_SUPPORTED_PATH", ()),
    "offshore/family/OTHER/spNat=ID": ("NO_SUPPORTED_PATH", ()),
    "offshore/family/OTHER/spNat=IT": ("NO_SUPPORTED_PATH", ()),
    "offshore/family/PARENT/spNat=ID": ("SUPPORTED_CANDIDATES", ("E31C", "E31F")),
    "offshore/family/PARENT/spNat=IT": ("NO_SUPPORTED_PATH", ()),
    "offshore/family/SIBLING/spNat=ID": ("NEEDS_INPUT", ()),
    "offshore/family/SIBLING/spNat=IT": ("NEEDS_INPUT", ()),
    "offshore/family/SPOUSE/spNat=ID": ("SUPPORTED_CANDIDATES", ("E31A",)),
    "offshore/family/SPOUSE/spNat=IT": ("NEEDS_INPUT", ()),
    "offshore/holdsPermit/current/tourism": ("NO_SUPPORTED_PATH", ()),
    "offshore/invest/bank_deposit": ("NEEDS_INPUT", ()),
    "offshore/invest/family": ("NEEDS_INPUT", ()),
    "offshore/invest/merit": ("NEEDS_INPUT", ()),
    "offshore/invest/property": ("NEEDS_INPUT", ()),
    "offshore/invest/pt_pma": ("NEEDS_INPUT", ()),
    "offshore/invest/undecided": ("NEEDS_INPUT", ()),
    "offshore/other": ("NO_SUPPORTED_PATH", ()),
    "offshore/remote": ("NO_SUPPORTED_PATH", ()),
    "offshore/retirement/bank_deposit": ("NO_SUPPORTED_PATH", ()),
    "offshore/retirement/family_sponsor": ("NO_SUPPORTED_PATH", ()),
    "offshore/retirement/passive_income": ("NO_SUPPORTED_PATH", ()),
    "offshore/retirement/property": ("NO_SUPPORTED_PATH", ()),
    "offshore/retirement/undecided": ("NO_SUPPORTED_PATH", ()),
    "offshore/study": ("SUPPORTED_CANDIDATES", ("E30", "E30A")),
    "offshore/tourism": ("NO_SUPPORTED_PATH", ()),
    "offshore/work": ("SUPPORTED_CANDIDATES", ("E23",)),
    "onshore/business": ("NO_SUPPORTED_PATH", ()),
    "onshore/diaspora": ("NEEDS_INPUT", ()),
    "onshore/family": ("NEEDS_INPUT", ()),
    "onshore/holdsPermit/current/tourism": ("NO_SUPPORTED_PATH", ()),
    "onshore/holdsPermit/expired/tourism": ("NO_SUPPORTED_PATH", ()),
    "onshore/invest": ("NO_SUPPORTED_PATH", ()),
    "onshore/other": ("NO_SUPPORTED_PATH", ()),
    "onshore/remote": ("NO_SUPPORTED_PATH", ()),
    "onshore/retirement": ("NO_SUPPORTED_PATH", ()),
    "onshore/study": ("SUPPORTED_CANDIDATES", ("E30", "E30A")),
    "onshore/tourism": ("NO_SUPPORTED_PATH", ()),
    "onshore/work": ("SUPPORTED_CANDIDATES", ("E23",)),
}

#: The state distribution, restated as a total so a reviewer sees the shape of
#: the funnel in one line. Derived from EXPECTED_OUTCOME on purpose: the two
#: can never disagree, and the wave PRs edit one table, not two.
EXPECTED_STATE_CENSUS: dict[str, int] = dict(
    Counter(state for state, _ in EXPECTED_OUTCOME.values())
)

#: Which fact blocks how many walks — the §2.2 table. A cure that moves walks
#: between blocking facts instead of removing the block goes red here even if
#: the total happens to stay the same.
EXPECTED_DEAD_END_FACT_CENSUS: dict[str, int] = {
    "process.wants_onshore_conversion": 6,
    "family.sponsor_status_code": 5,
    "intent.purposes": 2,
}


def _load_walks() -> dict[str, dict[str, Any]]:
    """Read the walk corpus, keyed by label (which must match the file stem
    modulo the ``/``→``_`` filename encoding, so a renamed file cannot smuggle
    another walk's expectations in)."""

    walks: dict[str, dict[str, Any]] = {}
    for path in sorted(CORPUS_DIR.glob("*.json")):
        spec = json.loads(path.read_text(encoding="utf-8"))
        label = str(spec["label"])
        assert label.replace("/", "_").replace("=", "_") == path.stem.replace("=", "_"), (
            f"{path.name}: file name does not encode its own label {label!r}"
        )
        walks[label] = spec
    return walks


def _evaluate_walks(walks: dict[str, dict[str, Any]]) -> dict[str, dict[str, Any]]:
    """Evaluate every walk through ``gold_coverage_eval._evaluate`` — the same
    verify → compile → evaluate → apply_public_policy_adapters path the gold
    replay and the coverage floor use. Never re-implemented here, so this
    census and those gates cannot drift on what "evaluate" means."""

    return {
        label: _evaluate(spec["overrides"], label, as_of=_AS_OF)["actual"]
        for label, spec in sorted(walks.items())
    }


def _outcome_violations(
    outcomes: dict[str, dict[str, Any]],
    expected: dict[str, tuple[str, tuple[str, ...]]] | None = None,
) -> list[str]:
    """Every walk whose (state, candidates) differ from the pinned pair."""

    pins = EXPECTED_OUTCOME if expected is None else expected
    violations: list[str] = []
    for label in sorted(set(outcomes) | set(pins)):
        actual = outcomes.get(label)
        if actual is None:
            violations.append(f"{label}: pinned but absent from the corpus")
            continue
        if label not in pins:
            violations.append(f"{label}: evaluated but not pinned in EXPECTED_OUTCOME")
            continue
        want_state, want_candidates = pins[label]
        got = (actual["state"], tuple(actual["candidates"]))
        if got != (want_state, want_candidates):
            violations.append(
                f"{label}: expected {want_state} {list(want_candidates)}, got {got[0]} {list(got[1])}"
            )
    return violations


def _dead_end_violations(
    outcomes: dict[str, dict[str, Any]],
    allowlist: dict[str, tuple[DeadEnd, ...]] | None = None,
) -> list[str]:
    """The invariant, both ways.

    A NEEDS_INPUT walk must be allowlisted and must block on EXACTLY the
    allowlisted facts (a new blocking fact is a new dead end, not a variant of
    an old one), and an allowlisted walk that no longer dead-ends is a STALE
    row that the curing PR must delete — otherwise the allowlist would outlive
    the defect and quietly re-authorise it.
    """

    rows = WALK_DEAD_END_ALLOWLIST if allowlist is None else allowlist
    violations: list[str] = []
    for label in sorted(outcomes):
        actual = outcomes[label]
        allowed = tuple(sorted(dead_end.fact for dead_end in rows.get(label, ())))
        missing = tuple(actual["missing_facts"])
        if actual["state"] == "NEEDS_INPUT":
            if not allowed:
                violations.append(
                    f"{label}: NEEDS_INPUT on {list(missing)} with no allowlist row — "
                    "the interview cannot ask for a fact it has no reachable question for"
                )
            elif missing != allowed:
                violations.append(
                    f"{label}: dead-ends on {list(missing)}, allowlist says {list(allowed)}"
                )
        elif allowed:
            violations.append(
                f"{label}: allowlisted for {list(allowed)} but now ends {actual['state']} — "
                "stale allowlist row, delete it in the PR that cured it"
            )
    for label in sorted(set(rows) - set(outcomes)):
        violations.append(f"{label}: allowlisted but absent from the corpus")
    return violations


def _scoped_allowlist(*labels: str) -> dict[str, tuple[DeadEnd, ...]]:
    """``WALK_DEAD_END_ALLOWLIST`` restricted to ``labels`` — what a
    single-walk assertion MUST be graded against.

    PR-0 gate finding, 2026-09-06: grading one mutated walk against all 36
    rows made ``_dead_end_violations``' trailing "allowlisted but absent from
    the corpus" loop fire 35 times unconditionally, so the guilt assertions
    below were non-empty no matter what the mutation did — they would have
    passed against an engine that ignored the mutation entirely. Same shape
    for ``_outcome_violations`` and its "pinned but absent" loop. Scoping is
    what restores the guilt: with it, the ONLY thing that can put a violation
    in the list is the walk under test.
    """

    return {
        label: WALK_DEAD_END_ALLOWLIST[label]
        for label in labels
        if label in WALK_DEAD_END_ALLOWLIST
    }


def _scoped_expectation(*labels: str) -> dict[str, tuple[str, tuple[str, ...]]]:
    """``EXPECTED_OUTCOME`` restricted to ``labels`` — see ``_scoped_allowlist``."""

    return {label: EXPECTED_OUTCOME[label] for label in labels if label in EXPECTED_OUTCOME}


@pytest.fixture(scope="module")
def walks() -> dict[str, dict[str, Any]]:
    return _load_walks()


@pytest.fixture(scope="module")
def outcomes(walks: dict[str, dict[str, Any]]) -> dict[str, dict[str, Any]]:
    return _evaluate_walks(walks)


def test_corpus_is_the_43_real_interview_walks(walks: dict[str, dict[str, Any]]) -> None:
    """An empty or shrunken corpus fails loudly: a census that passes because
    nobody fed it any walks is the green-but-dead shape (cicatrix #2)."""

    assert len(walks) == 43, f"expected 43 interview walks, found {len(walks)}"
    assert sorted(walks) == sorted(EXPECTED_OUTCOME), "corpus and EXPECTED_OUTCOME disagree"
    for label, spec in walks.items():
        assert spec["asked"], f"{label}: walk carries no asked-question history"
        assert spec["overrides"], f"{label}: walk carries no wire facts"


def test_every_walk_ends_in_its_pinned_outcome(outcomes: dict[str, dict[str, Any]]) -> None:
    violations = _outcome_violations(outcomes)
    assert not violations, "interview-walk outcomes moved:\n  " + "\n  ".join(violations)


def test_walk_state_census_is_13_dead_ends_23_no_paths_and_7_answers(
    outcomes: dict[str, dict[str, Any]],
) -> None:
    """The headline number of the decisiveness wave. Every PR that changes it
    updates this literal and says which walks moved, in its own body."""

    census = dict(Counter(outcome["state"] for outcome in outcomes.values()))
    assert (
        census
        == EXPECTED_STATE_CENSUS
        == {"NEEDS_INPUT": 13, "NO_SUPPORTED_PATH": 23, "SUPPORTED_CANDIDATES": 7}
    )
    # The count that must never move on its own: the reorder can only push a
    # walk DOWN the precedence table, so an answer appearing here would mean
    # the change failed open.
    assert census["SUPPORTED_CANDIDATES"] == 7
    assert census.get("HUMAN_REVIEW_REQUIRED", 0) == 0


def test_dead_end_fact_census_matches_the_blocking_fact_table(
    outcomes: dict[str, dict[str, Any]],
) -> None:
    census = Counter(
        fact
        for outcome in outcomes.values()
        if outcome["state"] == "NEEDS_INPUT"
        for fact in outcome["missing_facts"]
    )
    assert dict(census) == EXPECTED_DEAD_END_FACT_CENSUS


def test_no_walk_dead_ends_outside_the_allowlist(outcomes: dict[str, dict[str, Any]]) -> None:
    violations = _dead_end_violations(outcomes)
    assert not violations, "walk-census invariant broken:\n  " + "\n  ".join(violations)


def test_allowlist_is_exactly_the_13_remaining_dead_ends() -> None:
    assert len(WALK_DEAD_END_ALLOWLIST) == 13
    assert set(WALK_DEAD_END_ALLOWLIST) <= set(EXPECTED_OUTCOME)


def test_every_allowlisted_dead_end_is_genuinely_unaskable_in_its_own_walk(
    walks: dict[str, dict[str, Any]],
) -> None:
    """The allowlist's REASON, checked against the walk's own history — not
    taken on trust. This is what turns PR-3's four new questions into a red
    row: the moment a branch starts asking `wants_onshore_conversion`, its
    ``QUESTION_NOT_IN_THIS_WALK`` claim is false here."""

    for label, dead_ends in sorted(WALK_DEAD_END_ALLOWLIST.items()):
        asked = set(walks[label]["asked"])
        for dead_end in dead_ends:
            if dead_end.why_unaskable == NO_QUESTION_IN_TREE:
                assert dead_end.source_question is None, f"{label}/{dead_end.fact}"
            elif dead_end.why_unaskable == QUESTION_NOT_IN_THIS_WALK:
                assert dead_end.source_question not in asked, (
                    f"{label}: {dead_end.source_question!r} IS asked in this walk — "
                    f"{dead_end.fact} is no longer unaskable here"
                )
            elif dead_end.why_unaskable == ANSWER_NEVER_CERTIFIED:
                assert dead_end.source_question in asked, (
                    f"{label}: {dead_end.source_question!r} is not asked in this walk, "
                    "so the mapper never gets an answer to refuse"
                )
            else:  # pragma: no cover - a typo in a new row must not pass silently
                raise AssertionError(f"{label}: unknown reason {dead_end.why_unaskable!r}")


def test_guilt_a_cured_dead_end_that_only_moves_the_block_is_caught(
    walks: dict[str, dict[str, Any]],
) -> None:
    """GUILT, on the real engine: hand ``offshore/diaspora`` the very fact it
    dead-ends on (``intent.purposes`` KNOWN, the answer ``CATEGORY_TO_PURPOSE``
    refuses to derive from ``category=diaspora``) and watch the block MOVE
    rather than lift — measured 2026-09-06 on seq-19, the walk stays
    NEEDS_INPUT and now blocks on ``family.relation_to_sponsor`` +
    ``family.sponsor_nationalities`` instead.

    That is the whole reason the allowlist compares FACTS and not a count: the
    state census alone would call this cure a no-op (still NEEDS_INPUT, still
    no candidates), and only the per-fact comparison sees it. Deleting
    ``_dead_end_violations``' ``elif missing != allowed`` branch turns this
    test red and nothing else in the file — verified 2026-09-06.

    (Before the PR-2 reorder this witness rode ``onshore/tourism`` +
    ``sponsor.type``; that walk now ends NO_SUPPORTED_PATH, so the same shape
    is measured on a walk that is still a dead end.)"""

    label = "offshore/diaspora"
    mutated = dict(walks[label]["overrides"])
    mutated["intent.purposes"] = {"status": "KNOWN", "value": ["FAMILY"]}
    actual = _evaluate(mutated, label, as_of=_AS_OF)["actual"]

    assert actual["state"] == "NEEDS_INPUT", (
        "the guilt mutation now lifts the block entirely — it no longer "
        "witnesses a MOVED block, pick another walk"
    )
    assert actual["missing_facts"] != ["intent.purposes"], (
        "the guilt mutation no longer changes what blocks this walk — the "
        "corpus or the pack moved and this test proves nothing"
    )
    assert _dead_end_violations({label: actual}, allowlist=_scoped_allowlist(label))


def test_guilt_a_walk_that_loses_its_answer_is_caught(
    walks: dict[str, dict[str, Any]],
) -> None:
    """GUILT: ``offshore/work`` is one of the 7 walks that DO answer (E23).
    Take its ``work.indonesian_work_sponsor_confirmed`` away and the outcome
    pin must fire.

    Measured 2026-09-06 AFTER the PR-2 reorder, the mutated walk lands on
    NO_SUPPORTED_PATH, not NEEDS_INPUT — E23 is the only product whose
    ELIGIBILITY rules cover EMPLOYMENT, and denying its sponsor gate leaves
    nothing that could ever cover the purpose. Before the reorder this same
    mutation produced a dead end, which is why the pre-PR-0 version of this
    test also asserted ``_dead_end_violations``. It no longer can: a
    NO_SUPPORTED_PATH walk is an ANSWER, and the invariant deliberately says
    nothing about it. That second assertion is therefore replaced by the
    state it actually witnesses, rather than kept as an assertion that only
    passed because it was graded against the whole 36-row allowlist (the
    PR-0 gate's vacuity finding)."""

    mutated = dict(walks["offshore/work"]["overrides"])
    mutated["work.indonesian_work_sponsor_confirmed"] = {"status": "KNOWN", "value": False}
    actual = _evaluate(mutated, "offshore/work", as_of=_AS_OF)["actual"]

    assert actual["state"] == "NO_SUPPORTED_PATH"
    assert actual["candidates"] == []
    assert _outcome_violations(
        {"offshore/work": actual}, expected=_scoped_expectation("offshore/work")
    )
    # ...and the invariant stays SILENT, because losing an answer this way is
    # not a dead end. Scoped, so the silence is about this walk only.
    assert not _dead_end_violations(
        {"offshore/work": actual}, allowlist=_scoped_allowlist("offshore/work")
    )


def test_guilt_a_dead_end_on_an_unlisted_fact_is_caught() -> None:
    """GUILT: a NEEDS_INPUT on a fact nobody allowlisted — the shape a new
    signed rule with ``on_unknown: NEEDS_INPUT`` on an unaskable fact would
    produce — is a violation, and stays one when the allowlist is EMPTY (the
    permanent form of the invariant, after the wave)."""

    # `offshore/work` is one of the 7 ANSWERING walks, so it carries no
    # allowlist row — which is exactly the branch under test here.
    fabricated = {
        "offshore/work": {
            "state": "NEEDS_INPUT",
            "candidates": [],
            "missing_facts": ["work.employer_is_indonesian_entity"],
        }
    }
    assert _dead_end_violations(fabricated, allowlist=_scoped_allowlist("offshore/work"))
    assert _dead_end_violations(
        {"offshore/tourism": {"state": "NEEDS_INPUT", "candidates": [], "missing_facts": []}},
        allowlist={},
    )


def test_guilt_a_stale_allowlist_row_is_caught() -> None:
    """GUILT: the cure lands, the walk answers, and the allowlist row stays —
    the way an allowlist normally outlives its defect. Must be red."""

    cured = {
        "offshore/tourism": {
            "state": "SUPPORTED_CANDIDATES",
            "candidates": ["C1"],
            "missing_facts": [],
        }
    }
    # A row written INLINE rather than scoped out of the live allowlist: the
    # walk this witness needs is one that is BOTH allowlisted and cured, and
    # no live row can stay in that state by construction (the invariant this
    # very test enforces). So the pair is fabricated whole.
    violations = _dead_end_violations(cured, allowlist={"offshore/tourism": (_ONSHORE_CONVERSION,)})
    assert violations and "stale allowlist row" in violations[0]
    assert len(violations) == 1, f"only the stale row may be reported here: {violations}"
