"""Interview-walk decisiveness census: what the PUBLIC funnel actually answers.

``test_gold_coverage_floor.py`` proves the pack can support a product when
every fact arrives. This file proves the opposite half, and it is the half
the user lives in: replay the **43 real interview walks** — every distinct
path through ``flow.ts``'s two-arm spine and ``getCategoryQuestionIds``'
ten categories, each answered through the real ``fact-mapper.ts`` — against
the highest signed PRODUCTION pack, and pin the outcome census.

Measured 2026-09-07 on ``rulepack-prod-020.signed.json``, AFTER the PR-2
evaluator reorder: **11 NEEDS_INPUT / 10 NO_SUPPORTED_PATH / 22
SUPPORTED_CANDIDATES**. The engine is fail-closed and no wrong answer ships —
but 11 of 43 walks still end by asking for a fact the interview HAS NO
QUESTION FOR, which is a dead end, not an answer
(research/visa/2026-09-06-visa-oracle-decisiveness-investigation.md §1-§2).

Two hops got here, and this file has been re-derived at each one — never
hand-edited:

1. **seq-19 → seq-20 (the signed fold, #5867): 36/0/7 → 21/0/22.** Fold edit
   1 raised ``el.c1.tourism-family``'s stay-day bound 60 → 180, so the
   corpus's 121-stay-day walks satisfy C1 and the whole tourism/family arm
   answers. The same widening on ``el.c2.business`` made C2 reachable for the
   business/investment arm, and C2's own ``family.sponsor_confirmed == true``
   premise became the smallest missing-fact set — so 9 walks MOVED their
   block onto a fact no invest/business/other branch asks. Edits 2 and 3
   retired ``review.e33g.income-evidence`` and the eight
   ``family.sponsor_status_code`` rules.
2. **seq-20 → seq-20 + this PR's reorder: 21/0/22 → 11/10/22.** Ten dead ends
   became the honest ``NO_SUPPORTED_PATH``: seven blocked on
   ``process.wants_onshore_conversion``, two on
   ``investment.{investment,paid_up}_capital_idr`` and one on ``sponsor.type``
   — every one of them on behalf of a product whose ELIGIBILITY rules cannot
   cover the declared purposes under ANY fact resolution, which is exactly the
   class the reorder stops from choosing the global question. All three of
   those blocking-fact shapes are gone from the census entirely, so their
   ``DeadEnd`` rows are DELETED below rather than left unused.

**The 22 answers are byte-identical across hop 2, candidates included** —
measured, not argued. The reachable move is ``NEEDS_INPUT`` →
``NO_SUPPORTED_PATH``, never anything → ``SUPPORTED_CANDIDATES``, because the
hoisted block's only possible return is ``UNSUPPORTED``.

The invariant this file exists to arm is one sentence:

    no walk may end in NEEDS_INPUT on a fact for which the interview has no
    reachable question in that walk's own history.

Today it is violated 11 times, so it ships as an EXPLICIT allowlist of the
11 known dead ends. Each subsequent PR of the decisiveness wave deletes the
rows it cures (PR-3's new interview questions remove the rest — the nine
``family.sponsor_confirmed`` rows and the two diaspora ones are its whole
remaining mandate). **When ``WALK_DEAD_END_ALLOWLIST`` is empty the invariant
becomes unconditional** — ``_dead_end_violations`` needs no change for that,
it simply stops finding an excuse for any NEEDS_INPUT walk.

The corpus under ``gold_coverage/fixtures/walks/`` is DATA, generated by driving the
real ``computeNextNode``/``getCategoryQuestionIds``/``mapOracleFactsToApplicantFacts``
(first option answered at every question, 121 stay-days), never hand-written:
each file carries the walk's ``asked`` question ids and the exact wire
``overrides`` that walk produced. The expectations live HERE, in one
reviewable table, so a wave PR that moves an outcome must state which
outcome it moved.

Regenerate the corpus with ``npm run visa-oracle:walk-corpus -w apps/mouth``
(``apps/mouth/scripts/visa-oracle/generate-walk-corpus.ts``, proved byte-for-byte
reproducible by ``walk-corpus-determinism.test.ts``): a PR that changes the
interview tree MUST regenerate it and update ``EXPECTED_OUTCOME`` /
``WALK_DEAD_END_ALLOWLIST`` below in that same PR.
"""

from __future__ import annotations

import json
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pytest

from backend.scripts.visa_engine import gold_coverage_eval
from backend.scripts.visa_engine.gold_coverage_eval import _evaluate
from backend.scripts.visa_engine.gold_replay_driver import (
    PACKS_DIR,
    _parse_utc,
    build_persona_request,
    select_highest_repository_pack,
)
from backend.services.visa_engine import evaluate_path, evaluator
from backend.services.visa_engine.enums import DecisionState
from backend.tests.services.visa_engine.test_evaluator_gold import Persona

CORPUS_DIR = Path(__file__).resolve().parent / "gold_coverage" / "fixtures" / "walks"

# PINNED to the highest signed pack's own `signed_at`, never the wall clock —
# same clock bomb `test_gold_coverage_floor.py` documents at length: the
# selected pack's source_records carry a freshness_policy with as little as a
# 604800s (7-day) window, so evaluating at `datetime.now(UTC)` is guaranteed
# to turn this whole census into HUMAN_REVIEW_REQUIRED seven days after the
# newest source's verified_at, with zero code change. `signed_at` (not
# `payload.created_at`) because the same instant drives `verify_rule_pack`'s
# `observed_at`, which rejects a signature dated after the observation.
_, _HIGHEST_SIGNED_PACK = select_highest_repository_pack(PACKS_DIR)
_AS_OF = _parse_utc(_HIGHEST_SIGNED_PACK["protected"]["signed_at"])

#: Why an allowlisted NEEDS_INPUT is a DEAD END and not a question the funnel
#: could ask. Each value is checked against the walk's own `asked` history.
NO_QUESTION_IN_TREE = "no question in tree.ts can ever set this fact"
QUESTION_NOT_IN_THIS_WALK = "the question exists but this walk's branch never asks it"
ANSWER_NEVER_CERTIFIED = "the question IS asked, and the mapper refuses to certify the answer"


@dataclass(frozen=True)
class DeadEnd:
    """One allowlisted dead end: the blocking fact, its source question in
    ``tree.ts`` (``None`` when no question emits it at all), and the reason
    the funnel cannot supply it."""

    fact: str
    source_question: str | None
    why_unaskable: str


# The two dead-end shapes that survive on seq-20 AFTER the PR-2 reorder, with
# the anchor that explains each. A wave PR retires a shape by deleting its rows
# below, never by loosening a count.
#
# Seq-20's fold retired two of seq-19's seven shapes outright:
# `family.sponsor_status_code` (fold edit 3 made its eight rules NO_EFFECT) and
# `intent.requested_product_code` (fold edit 4 guarded the four BRIDGING rules
# on a `known` premise). This PR's reorder retires three more —
# `process.wants_onshore_conversion` (7 rows), `investment.investment_capital_idr`
# and `investment.paid_up_capital_idr` (2 rows, always paired) and `sponsor.type`
# (1 row) — because every one of those blocks was raised on behalf of a product
# that cannot cover the walk's declared purposes under ANY fact resolution.
# Their DeadEnd rows are gone rather than merely unused: nothing in the census
# blocks on those facts any more.
_DIASPORA_PURPOSE = DeadEnd(
    # `category` IS asked, but CATEGORY_TO_PURPOSE (fact-mapper.ts:255-266)
    # deliberately has no `diaspora` entry, so `mapPurposes` returns
    # unknownFact(NOT_APPLICABLE) — the answer exists and is refused.
    #
    # Untouched by the reorder, and correctly so: the blocker here is not a
    # purpose-infeasible product but the purpose set ITSELF being unknown, so
    # `purposes <= naive_potential_coverage` cannot be decided either way and
    # the gate must still ask. PR-3's mandate.
    "intent.purposes",
    "category",
    ANSWER_NEVER_CERTIFIED,
)
_FAMILY_SPONSOR_CONFIRMED = DeadEnd(
    # NEW on seq-20, and it is a MOVE, not a regression: `el.c2.business`'s
    # stay-day bound went 60 -> 180 (fold edit 1), so C2 became reachable for
    # the business/investment arm at the corpus's 121 days — and C2's own
    # `family.sponsor_confirmed == true` premise is now the smallest missing
    # set, winning `evaluator.py`'s `min(len(missing_facts))` tie-break over
    # the blockers these walks used to report. `family_sponsor_confirmed` is
    # emitted only by the family arm (flow.ts:708) and by retirement
    # (flow.ts:657-659); no invest/business/other branch asks it, so the
    # funnel genuinely cannot supply it here. PR-3's mandate.
    #
    # The reorder does NOT touch this shape either, and that is the point: C2
    # is a product these applicants really are shopping for — its ELIGIBILITY
    # rules do cover their declared purposes — so the question is a real one,
    # not noise raised on behalf of a product that could never be recommended.
    # Measured: answering `family.sponsor_confirmed=true` turns every one of
    # the nine into SUPPORTED_CANDIDATES.
    "family.sponsor_confirmed",
    "family_sponsor_confirmed",
    QUESTION_NOT_IN_THIS_WALK,
)

#: The 11 known dead ends. DELETE rows as the wave cures them; never add one
#: without an anchor showing the fact is genuinely unaskable in that walk.
WALK_DEAD_END_ALLOWLIST: dict[str, tuple[DeadEnd, ...]] = {
    "offshore/diaspora": (_DIASPORA_PURPOSE,),
    "offshore/invest/bank_deposit": (_FAMILY_SPONSOR_CONFIRMED,),
    "offshore/invest/family": (_FAMILY_SPONSOR_CONFIRMED,),
    "offshore/invest/merit": (_FAMILY_SPONSOR_CONFIRMED,),
    "offshore/invest/property": (_FAMILY_SPONSOR_CONFIRMED,),
    "offshore/invest/pt_pma": (_FAMILY_SPONSOR_CONFIRMED,),
    "offshore/invest/undecided": (_FAMILY_SPONSOR_CONFIRMED,),
    "offshore/other": (_FAMILY_SPONSOR_CONFIRMED,),
    "onshore/diaspora": (_DIASPORA_PURPOSE,),
    "onshore/invest": (_FAMILY_SPONSOR_CONFIRMED,),
    "onshore/other": (_FAMILY_SPONSOR_CONFIRMED,),
}

#: Per-walk outcome pin: state plus the candidate products, in rank order.
#: Candidates are pinned too — a pack edit that adds or drops a product for a
#: walk that already had an answer is exactly as much of a shift as a state
#: change, and this table is the only place either becomes visible.
EXPECTED_OUTCOME: dict[str, tuple[str, tuple[str, ...]]] = {
    "offshore/business": ("NO_SUPPORTED_PATH", ()),
    "offshore/diaspora": ("NEEDS_INPUT", ()),
    "offshore/family/CHILD/spNat=ID": ("SUPPORTED_CANDIDATES", ("C1", "E31G")),
    "offshore/family/CHILD/spNat=IT": ("SUPPORTED_CANDIDATES", ("C1",)),
    "offshore/family/DEPENDENT/spNat=ID": ("SUPPORTED_CANDIDATES", ("C1",)),
    "offshore/family/DEPENDENT/spNat=IT": ("SUPPORTED_CANDIDATES", ("C1",)),
    "offshore/family/OTHER/spNat=ID": ("SUPPORTED_CANDIDATES", ("C1",)),
    "offshore/family/OTHER/spNat=IT": ("SUPPORTED_CANDIDATES", ("C1",)),
    "offshore/family/PARENT/spNat=ID": ("SUPPORTED_CANDIDATES", ("C1", "E31C", "E31F")),
    "offshore/family/PARENT/spNat=IT": ("SUPPORTED_CANDIDATES", ("C1",)),
    "offshore/family/SIBLING/spNat=ID": ("SUPPORTED_CANDIDATES", ("C1",)),
    "offshore/family/SIBLING/spNat=IT": ("SUPPORTED_CANDIDATES", ("C1",)),
    "offshore/family/SPOUSE/spNat=ID": ("SUPPORTED_CANDIDATES", ("C1", "E31A")),
    "offshore/family/SPOUSE/spNat=IT": ("SUPPORTED_CANDIDATES", ("C1",)),
    "offshore/holdsPermit/current/tourism": ("SUPPORTED_CANDIDATES", ("C1",)),
    "offshore/invest/bank_deposit": ("NEEDS_INPUT", ()),
    "offshore/invest/family": ("NEEDS_INPUT", ()),
    "offshore/invest/merit": ("NEEDS_INPUT", ()),
    "offshore/invest/property": ("NEEDS_INPUT", ()),
    "offshore/invest/pt_pma": ("NEEDS_INPUT", ()),
    "offshore/invest/undecided": ("NEEDS_INPUT", ()),
    "offshore/other": ("NEEDS_INPUT", ()),
    "offshore/remote": ("NO_SUPPORTED_PATH", ()),
    "offshore/retirement/bank_deposit": ("NO_SUPPORTED_PATH", ()),
    "offshore/retirement/family_sponsor": ("NO_SUPPORTED_PATH", ()),
    "offshore/retirement/passive_income": ("NO_SUPPORTED_PATH", ()),
    "offshore/retirement/property": ("NO_SUPPORTED_PATH", ()),
    "offshore/retirement/undecided": ("NO_SUPPORTED_PATH", ()),
    "offshore/study": ("SUPPORTED_CANDIDATES", ("E30", "E30A")),
    "offshore/tourism": ("SUPPORTED_CANDIDATES", ("C1",)),
    "offshore/work": ("SUPPORTED_CANDIDATES", ("E23",)),
    "onshore/business": ("NO_SUPPORTED_PATH", ()),
    "onshore/diaspora": ("NEEDS_INPUT", ()),
    "onshore/family": ("SUPPORTED_CANDIDATES", ("C1",)),
    "onshore/holdsPermit/current/tourism": ("SUPPORTED_CANDIDATES", ("C1",)),
    "onshore/holdsPermit/expired/tourism": ("SUPPORTED_CANDIDATES", ("C1",)),
    "onshore/invest": ("NEEDS_INPUT", ()),
    "onshore/other": ("NEEDS_INPUT", ()),
    "onshore/remote": ("NO_SUPPORTED_PATH", ()),
    "onshore/retirement": ("NO_SUPPORTED_PATH", ()),
    "onshore/study": ("SUPPORTED_CANDIDATES", ("E30", "E30A")),
    "onshore/tourism": ("SUPPORTED_CANDIDATES", ("C1",)),
    "onshore/work": ("SUPPORTED_CANDIDATES", ("E23",)),
}

#: The state distribution, restated as a total so a reviewer sees the shape of
#: the funnel in one line. Derived from EXPECTED_OUTCOME on purpose: the two
#: can never disagree, and the wave PRs edit one table, not two.
EXPECTED_STATE_CENSUS: dict[str, int] = dict(
    Counter(state for state, _ in EXPECTED_OUTCOME.values())
)

#: Which fact blocks how many walks — the §2.2 table. A cure that moves walks
#: between blocking facts instead of removing the block goes red here even if
#: the total happens to stay the same.
EXPECTED_DEAD_END_FACT_CENSUS: dict[str, int] = {
    "family.sponsor_confirmed": 9,
    "intent.purposes": 2,
}


def _load_walks() -> dict[str, dict[str, Any]]:
    """Read the walk corpus, keyed by label (which must match the file stem
    modulo the ``/``→``_`` filename encoding, so a renamed file cannot smuggle
    another walk's expectations in)."""

    walks: dict[str, dict[str, Any]] = {}
    for path in sorted(CORPUS_DIR.glob("*.json")):
        spec = json.loads(path.read_text(encoding="utf-8"))
        label = str(spec["label"])
        assert label.replace("/", "_").replace("=", "_") == path.stem.replace("=", "_"), (
            f"{path.name}: file name does not encode its own label {label!r}"
        )
        walks[label] = spec
    return walks


def _evaluate_walks(walks: dict[str, dict[str, Any]]) -> dict[str, dict[str, Any]]:
    """Evaluate every walk through ``gold_coverage_eval._evaluate`` — the same
    verify → compile → evaluate → apply_public_policy_adapters path the gold
    replay and the coverage floor use. Never re-implemented here, so this
    census and those gates cannot drift on what "evaluate" means."""

    return {
        label: _evaluate(spec["overrides"], label, as_of=_AS_OF)["actual"]
        for label, spec in sorted(walks.items())
    }


def _outcome_violations(
    outcomes: dict[str, dict[str, Any]],
    expected: dict[str, tuple[str, tuple[str, ...]]] | None = None,
) -> list[str]:
    """Every walk whose (state, candidates) differ from the pinned pair."""

    pins = EXPECTED_OUTCOME if expected is None else expected
    violations: list[str] = []
    for label in sorted(set(outcomes) | set(pins)):
        actual = outcomes.get(label)
        if actual is None:
            violations.append(f"{label}: pinned but absent from the corpus")
            continue
        if label not in pins:
            violations.append(f"{label}: evaluated but not pinned in EXPECTED_OUTCOME")
            continue
        want_state, want_candidates = pins[label]
        got = (actual["state"], tuple(actual["candidates"]))
        if got != (want_state, want_candidates):
            violations.append(
                f"{label}: expected {want_state} {list(want_candidates)}, got {got[0]} {list(got[1])}"
            )
    return violations


def _dead_end_violations(
    outcomes: dict[str, dict[str, Any]],
    allowlist: dict[str, tuple[DeadEnd, ...]] | None = None,
) -> list[str]:
    """The invariant, both ways.

    A NEEDS_INPUT walk must be allowlisted and must block on EXACTLY the
    allowlisted facts (a new blocking fact is a new dead end, not a variant of
    an old one), and an allowlisted walk that no longer dead-ends is a STALE
    row that the curing PR must delete — otherwise the allowlist would outlive
    the defect and quietly re-authorise it.
    """

    rows = WALK_DEAD_END_ALLOWLIST if allowlist is None else allowlist
    violations: list[str] = []
    for label in sorted(outcomes):
        actual = outcomes[label]
        allowed = tuple(sorted(dead_end.fact for dead_end in rows.get(label, ())))
        missing = tuple(actual["missing_facts"])
        if actual["state"] == "NEEDS_INPUT":
            if not allowed:
                violations.append(
                    f"{label}: NEEDS_INPUT on {list(missing)} with no allowlist row — "
                    "the interview cannot ask for a fact it has no reachable question for"
                )
            elif missing != allowed:
                violations.append(
                    f"{label}: dead-ends on {list(missing)}, allowlist says {list(allowed)}"
                )
        elif allowed:
            violations.append(
                f"{label}: allowlisted for {list(allowed)} but now ends {actual['state']} — "
                "stale allowlist row, delete it in the PR that cured it"
            )
    for label in sorted(set(rows) - set(outcomes)):
        violations.append(f"{label}: allowlisted but absent from the corpus")
    return violations


def _decide(overrides: dict[str, Any], label: str) -> tuple[Any, Any, Any]:
    """``(raw_decision, compiled, request)``.

    ``_evaluate`` returns the flattened ``actual`` view (codes only), which
    cannot witness ``rule_ids``/``source_refs``. This reuses that module's own
    verified-pack loader and identity provider so the two never diverge on
    which pack, or which instant, is under test.
    """

    _pack_path, compiled = gold_coverage_eval._verified_compiled_pack(_AS_OF)
    persona = Persona(
        id=0, label=label, overrides=overrides, expected_state=DecisionState.NEEDS_INPUT
    )
    request = build_persona_request(persona)
    decision = evaluator.evaluate(
        request.applicant_facts(),
        compiled,
        effective_at=_AS_OF,
        observed_at=_AS_OF,
        identity_provider=gold_coverage_eval._offline_identity_provider,
    )
    return decision, compiled, request


def _engine_decision(overrides: dict[str, Any], label: str) -> Any:
    """The RAW ``Decision`` — ``evaluator.evaluate``, no public shaping."""

    decision, _compiled, _request = _decide(overrides, label)
    return decision


def _public_decision(overrides: dict[str, Any], label: str) -> Any:
    """The applicant-facing ``Decision`` — the same verify → compile →
    evaluate → ``apply_public_policy_adapters`` path ``_evaluate`` walks."""

    decision, compiled, request = _decide(overrides, label)
    return evaluate_path.apply_public_policy_adapters(
        decision,
        request.applicant_facts(),
        compiled,
        disclosed_review_flags=request.effective_review_flags(),
    )


def _scoped_allowlist(*labels: str) -> dict[str, tuple[DeadEnd, ...]]:
    """``WALK_DEAD_END_ALLOWLIST`` restricted to ``labels`` — what a
    single-walk assertion MUST be graded against.

    PR-0 gate finding, 2026-09-06: grading one mutated walk against the whole
    table made ``_dead_end_violations``' trailing "allowlisted but absent from
    the corpus" loop fire once per OTHER row, unconditionally, so the guilt
    assertions below were non-empty no matter what the mutation did — they
    would have passed against an engine that ignored the mutation entirely.
    Same shape for ``_outcome_violations`` and its "pinned but absent" loop.
    Scoping is what restores the guilt: with it, the ONLY thing that can put a
    violation in the list is the walk under test.
    """

    return {
        label: WALK_DEAD_END_ALLOWLIST[label]
        for label in labels
        if label in WALK_DEAD_END_ALLOWLIST
    }


def _scoped_expectation(*labels: str) -> dict[str, tuple[str, tuple[str, ...]]]:
    """``EXPECTED_OUTCOME`` restricted to ``labels`` — see ``_scoped_allowlist``."""

    return {label: EXPECTED_OUTCOME[label] for label in labels if label in EXPECTED_OUTCOME}


@pytest.fixture(scope="module")
def walks() -> dict[str, dict[str, Any]]:
    return _load_walks()


@pytest.fixture(scope="module")
def outcomes(walks: dict[str, dict[str, Any]]) -> dict[str, dict[str, Any]]:
    return _evaluate_walks(walks)


def test_corpus_is_the_43_real_interview_walks(walks: dict[str, dict[str, Any]]) -> None:
    """An empty or shrunken corpus fails loudly: a census that passes because
    nobody fed it any walks is the green-but-dead shape (cicatrix #2)."""

    assert len(walks) == 43, f"expected 43 interview walks, found {len(walks)}"
    assert sorted(walks) == sorted(EXPECTED_OUTCOME), "corpus and EXPECTED_OUTCOME disagree"
    for label, spec in walks.items():
        assert spec["asked"], f"{label}: walk carries no asked-question history"
        assert spec["overrides"], f"{label}: walk carries no wire facts"


def test_every_walk_ends_in_its_pinned_outcome(outcomes: dict[str, dict[str, Any]]) -> None:
    violations = _outcome_violations(outcomes)
    assert not violations, "interview-walk outcomes moved:\n  " + "\n  ".join(violations)


def test_walk_state_census_is_11_dead_ends_10_no_paths_and_22_answers(
    outcomes: dict[str, dict[str, Any]],
) -> None:
    """The headline number of the decisiveness wave. Every PR that changes it
    updates this literal and says which walks moved, in its own body.

    36/0/7 on seq-19; 21/0/22 once the signed seq-20 bundle's stay-day
    widening landed; 11/10/22 with this PR's reorder on top (module
    docstring)."""

    census = dict(Counter(outcome["state"] for outcome in outcomes.values()))
    assert (
        census
        == EXPECTED_STATE_CENSUS
        == {"NEEDS_INPUT": 11, "NO_SUPPORTED_PATH": 10, "SUPPORTED_CANDIDATES": 22}
    )
    # The count that must never move on its own: the reorder can only push a
    # walk DOWN the precedence table, so an answer appearing here would mean
    # the change failed open. 22 is seq-20's own number, unchanged by this PR.
    assert census["SUPPORTED_CANDIDATES"] == 22
    assert census.get("HUMAN_REVIEW_REQUIRED", 0) == 0


def test_dead_end_fact_census_matches_the_blocking_fact_table(
    outcomes: dict[str, dict[str, Any]],
) -> None:
    census = Counter(
        fact
        for outcome in outcomes.values()
        if outcome["state"] == "NEEDS_INPUT"
        for fact in outcome["missing_facts"]
    )
    assert dict(census) == EXPECTED_DEAD_END_FACT_CENSUS


def test_no_walk_renders_the_same_reason_code_twice(
    outcomes: dict[str, dict[str, Any]],
) -> None:
    """A NO_SUPPORTED_PATH sheet must not print one sentence twice.

    ``engine-adapter.ts`` maps ``no_path_reasons`` 1:1 and looks the copy up by
    CODE alone (``SUPPORT_REASON_COPY``), so two entries sharing a code are two
    identical paragraphs in front of a real person. This PR is what makes that
    reachable — before the reorder ZERO walks reached NO_SUPPORTED_PATH — so
    the guard ships with it.

    Measured 2026-09-07 on seq-20 BEFORE ``_merge_reasons_by_code``: six walks
    (the five ``offshore/retirement/*`` and ``onshore/retirement``) rendered
    ``['AGE_BELOW_55', 'AGE_BELOW_55']``, one entry for
    ``hf.e33e.age-below-55`` and one for ``hf.e33f.age-below-55``. Reverting
    that helper to ``_dedupe_reasons`` turns this test red on all six.

    Stated over EVERY walk and every reason list rather than over the six
    known ones: a new pack that gives two products one code anywhere is the
    same defect, and this catches it without being re-pinned.
    """

    violations = []
    for label, actual in sorted(outcomes.items()):
        for field in ("no_path_reason_codes", "review_reason_codes"):
            codes = list(actual.get(field, ()))
            repeated = sorted({code for code in codes if codes.count(code) > 1})
            if repeated:
                violations.append(f"{label}: {field} repeats {repeated} — rendered as {codes}")
    assert not violations, "a reason code is rendered more than once:\n  " + "\n  ".join(violations)


def test_the_retirement_walk_merges_age_below_55_keeping_both_rules_and_both_refs(
    walks: dict[str, dict[str, Any]],
) -> None:
    """The real-pack witness for the merge, on the walk it was measured on.

    ``offshore/retirement/property`` is excluded by TWO products for the same
    legal reason — E33E and E33F both say the applicant is under 55 — and
    before ``_collapse_reader_reasons`` the sheet carried the code twice.

    All three assertions matter, and the last two are the ones that forbid the
    WRONG fix. A naive dedupe on the code would satisfy the first and fail
    these: ``_dedupe_reasons`` uses ``setdefault``, so it would have kept
    ``hf.e33e``'s entry and silently dropped both ``hf.e33f`` and the source
    record only ``hf.e33f`` cites. Measured 2026-09-07 on
    ``rulepack-prod-020.signed.json``:

        [0] AGE_BELOW_55  ('hf.e33e.age-below-55',)  (9248b1d7,)
        [1] AGE_BELOW_55  ('hf.e33f.age-below-55',)  (6f5135f2, 9248b1d7)

    One ref set happens to be a subset of the other in THIS pair; nothing in
    the contract guarantees that for the next one, which is why the union is
    asserted as a union rather than as 'the longer entry wins'.
    """

    label = "offshore/retirement/property"
    decision = _public_decision(walks[label]["overrides"], label)
    assert decision.state.value == "NO_SUPPORTED_PATH"

    age_reasons = [reason for reason in decision.no_path_reasons if reason.code == "AGE_BELOW_55"]
    assert len(age_reasons) == 1, (
        f"AGE_BELOW_55 must render exactly once, got {len(age_reasons)} entries — "
        f"{[list(reason.rule_ids) for reason in age_reasons]}"
    )

    merged = age_reasons[0]
    assert set(merged.rule_ids) == {"hf.e33e.age-below-55", "hf.e33f.age-below-55"}, (
        "the merge dropped a rule id — both excluding rules must survive the collapse"
    )

    raw = _engine_decision(walks[label]["overrides"], label)
    every_ref = {
        ref
        for reason in raw.no_path_reasons
        if reason.code == "AGE_BELOW_55"
        for ref in reason.source_refs
    }
    assert len(every_ref) == 2, f"expected two distinct citations upstream, got {every_ref}"
    assert set(merged.source_refs) == every_ref, (
        "the merge dropped a citation — the union of every AGE_BELOW_55 source_ref "
        "the ENGINE produced must survive onto the single merged reason"
    )


def test_no_walk_dead_ends_outside_the_allowlist(outcomes: dict[str, dict[str, Any]]) -> None:
    violations = _dead_end_violations(outcomes)
    assert not violations, "walk-census invariant broken:\n  " + "\n  ".join(violations)


def test_allowlist_is_exactly_the_11_known_dead_ends() -> None:
    assert len(WALK_DEAD_END_ALLOWLIST) == 11
    assert set(WALK_DEAD_END_ALLOWLIST) <= set(EXPECTED_OUTCOME)


def test_every_allowlisted_dead_end_is_genuinely_unaskable_in_its_own_walk(
    walks: dict[str, dict[str, Any]],
) -> None:
    """The allowlist's REASON, checked against the walk's own history — not
    taken on trust. This is what turns PR-3's new questions into a red row:
    the moment the invest/business/other branch starts asking
    ``family_sponsor_confirmed``, that row's ``QUESTION_NOT_IN_THIS_WALK``
    claim is false here and the PR must delete it rather than restate it."""

    for label, dead_ends in sorted(WALK_DEAD_END_ALLOWLIST.items()):
        asked = set(walks[label]["asked"])
        for dead_end in dead_ends:
            if dead_end.why_unaskable == NO_QUESTION_IN_TREE:
                assert dead_end.source_question is None, f"{label}/{dead_end.fact}"
            elif dead_end.why_unaskable == QUESTION_NOT_IN_THIS_WALK:
                assert dead_end.source_question not in asked, (
                    f"{label}: {dead_end.source_question!r} IS asked in this walk — "
                    f"{dead_end.fact} is no longer unaskable here"
                )
            elif dead_end.why_unaskable == ANSWER_NEVER_CERTIFIED:
                assert dead_end.source_question in asked, (
                    f"{label}: {dead_end.source_question!r} is not asked in this walk, "
                    "so the mapper never gets an answer to refuse"
                )
            else:  # pragma: no cover - a typo in a new row must not pass silently
                raise AssertionError(f"{label}: unknown reason {dead_end.why_unaskable!r}")


def test_guilt_a_cured_dead_end_that_only_moves_the_block_is_caught(
    walks: dict[str, dict[str, Any]],
) -> None:
    """GUILT, on the real engine: hand ``offshore/invest/pt_pma`` the very fact
    it dead-ends on (``family.sponsor_confirmed`` KNOWN, answered ``false``)
    and watch the block MOVE rather than lift — measured 2026-09-07 on seq-20
    with this PR's reorder applied, the walk stays NEEDS_INPUT and now blocks
    on ``process.wants_onshore_conversion`` instead, because denying C2's
    sponsor premise hands the ``min(len(missing_facts))`` tie-break to D12 —
    which, for an INVESTMENT walk, is a product the reorder deliberately does
    NOT silence.

    Re-anchored twice, each time onto a walk that is still a dead end:
    ``onshore/tourism`` (seq-19's anchor) answers on seq-20, and
    ``onshore/business`` (seq-20's anchor) ends NO_SUPPORTED_PATH under this
    PR, so both mutations would have had nothing left to move.

    That is the whole reason the allowlist compares FACTS and not a count: the
    state census alone would call this cure a no-op (still NEEDS_INPUT, still
    no candidates), and only the per-fact comparison sees it. Deleting
    ``_dead_end_violations``' ``elif missing != allowed`` branch turns this
    test red and nothing else in the file — verified 2026-09-06."""

    label = "offshore/invest/pt_pma"
    mutated = dict(walks[label]["overrides"])
    mutated["family.sponsor_confirmed"] = {"status": "KNOWN", "value": False}
    actual = _evaluate(mutated, label, as_of=_AS_OF)["actual"]

    assert actual["state"] == "NEEDS_INPUT", (
        "the guilt mutation now LIFTS the block instead of moving it — this "
        "test no longer exercises the shape it was written for"
    )
    assert actual["missing_facts"] != ["family.sponsor_confirmed"], (
        "the guilt mutation no longer changes what blocks this walk — the "
        "corpus or the pack moved and this test proves nothing"
    )
    assert _dead_end_violations({label: actual}, allowlist=_scoped_allowlist(label))


def test_guilt_a_walk_that_loses_its_answer_is_caught(
    walks: dict[str, dict[str, Any]],
) -> None:
    """GUILT: ``offshore/work`` is one of the 22 walks that DO answer (E23).
    Take its ``work.indonesian_work_sponsor_confirmed`` away and the outcome
    pin must fire.

    Measured 2026-09-07 on seq-20 WITH this PR's reorder, the mutated walk
    lands on NO_SUPPORTED_PATH, not NEEDS_INPUT — E23 is the only product whose
    ELIGIBILITY rules cover EMPLOYMENT, and denying its sponsor gate leaves
    nothing that could ever cover the purpose. Without the reorder this same
    mutation produced a dead end, which is why the seq-20 version of this test
    also asserted ``_dead_end_violations``. It no longer can: a
    NO_SUPPORTED_PATH walk is an ANSWER, and the invariant deliberately says
    nothing about it. That second assertion is therefore not dropped but
    REPLACED by the two things this mutation actually witnesses — the exact
    state and the invariant's silence — rather than kept as an assertion that
    only passed because it was graded against the whole table (the PR-0 gate's
    vacuity finding)."""

    mutated = dict(walks["offshore/work"]["overrides"])
    mutated["work.indonesian_work_sponsor_confirmed"] = {"status": "KNOWN", "value": False}
    actual = _evaluate(mutated, "offshore/work", as_of=_AS_OF)["actual"]

    assert actual["state"] == "NO_SUPPORTED_PATH"
    assert actual["candidates"] == []
    assert _outcome_violations(
        {"offshore/work": actual}, expected=_scoped_expectation("offshore/work")
    )
    # ...and the invariant stays SILENT, because losing an answer this way is
    # not a dead end. Scoped, so the silence is about this walk only.
    assert not _dead_end_violations(
        {"offshore/work": actual}, allowlist=_scoped_allowlist("offshore/work")
    )


def test_guilt_a_dead_end_on_an_unlisted_fact_is_caught() -> None:
    """GUILT: a NEEDS_INPUT on a fact nobody allowlisted — the shape a new
    signed rule with ``on_unknown: NEEDS_INPUT`` on an unaskable fact would
    produce — is a violation, and stays one when the allowlist is EMPTY (the
    permanent form of the invariant, after the wave)."""

    # `offshore/work` is one of the 22 ANSWERING walks, so it carries no
    # allowlist row — which is exactly the branch under test here.
    fabricated = {
        "offshore/work": {
            "state": "NEEDS_INPUT",
            "candidates": [],
            "missing_facts": ["work.employer_is_indonesian_entity"],
        }
    }
    assert _dead_end_violations(fabricated, allowlist=_scoped_allowlist("offshore/work"))
    assert _dead_end_violations(
        {"offshore/work": {"state": "NEEDS_INPUT", "candidates": [], "missing_facts": []}},
        allowlist={},
    )


def test_guilt_a_stale_allowlist_row_is_caught() -> None:
    """GUILT: the cure lands, the walk answers, and the allowlist row stays —
    the way an allowlist normally outlives its defect. Must be red.

    Re-anchored onto ``offshore/invest/pt_pma``, which IS still allowlisted
    under this PR; seq-19's anchor (``offshore/tourism``) was cured by the
    seq-20 fold and seq-20's (``offshore/business``) by this reorder, so
    reusing either would have made this guilt test pass for the WRONG reason —
    an unlisted walk, not a stale row. The membership assertion below is what
    makes that failure mode loud instead of silent the next time the row moves.

    Graded against the LIVE row through ``_scoped_allowlist``, not a
    hand-written one, so the day PR-3 deletes this row the test goes red rather
    than keeping a fabricated copy alive."""

    label = "offshore/invest/pt_pma"
    assert label in WALK_DEAD_END_ALLOWLIST
    cured = {
        label: {
            "state": "SUPPORTED_CANDIDATES",
            "candidates": ["C2"],
            "missing_facts": [],
        }
    }
    violations = _dead_end_violations(cured, allowlist=_scoped_allowlist(label))
    assert violations and "stale allowlist row" in violations[0]
    assert len(violations) == 1, f"only the stale row may be reported here: {violations}"
