"""Interview-walk decisiveness census: what the PUBLIC funnel actually answers.

``test_gold_coverage_floor.py`` proves the pack can support a product when
every fact arrives. This file proves the opposite half, and it is the half
the user lives in: replay the **43 real interview walks** — every distinct
path through ``flow.ts``'s two-arm spine and ``getCategoryQuestionIds``'
ten categories, each answered through the real ``fact-mapper.ts`` — against
the highest signed PRODUCTION pack, and pin the outcome census.

Measured 2026-09-06 on ``rulepack-prod-020.signed.json``:
**21 NEEDS_INPUT / 22 SUPPORTED_CANDIDATES / 0 NO_SUPPORTED_PATH**. The
engine is fail-closed and no wrong answer ships — but 21 of 43 walks still
end by asking for a fact the interview HAS NO QUESTION FOR, which is a dead
end, not an answer (research/visa/2026-09-06-visa-oracle-decisiveness-investigation.md §1-§2).

Re-pinned from seq-19's **36/7** when the signed seq-20 bundle landed. Two
things moved, both traceable to the fold's edit 1 (the lawful stay-day
totals) rather than to any change in this test:

* **15 walks gained an answer.** ``el.c1.tourism-family``'s bound went
  60 → 180 days, so the corpus's 121-stay-day walks now satisfy C1 and the
  whole tourism/family arm answers instead of dead-ending. Their allowlist
  rows are DELETED below, not loosened.
* **9 walks moved their block to** ``family.sponsor_confirmed``. The same
  widening (60 → 180) on ``el.c2.business`` made C2 reachable for the
  business/investment arm, and C2's own ``family.sponsor_confirmed == true``
  premise is now the smallest missing-fact set, so it wins ``evaluator.py``'s
  ``min(len(missing_facts))`` tie-break ahead of the old blockers. The block
  is genuinely still there: no invest/business/other branch asks
  ``family_sponsor_confirmed`` (flow.ts:708 emits it only in the family arm,
  657-659 in retirement), so this is a NEW dead-end shape, not a cure. Curing
  it is PR-3's mandate.

Edits 2 and 3 of the fold show up here too: ``review.e33g.income-evidence``
is gone and the eight ``family.sponsor_status_code`` rules are ``NO_EFFECT``,
which is why ``onshore/family`` no longer dead-ends on that fact at all.

The invariant this file exists to arm is one sentence:

    no walk may end in NEEDS_INPUT on a fact for which the interview has no
    reachable question in that walk's own history.

Today it is violated 21 times, so it ships as an EXPLICIT allowlist of the
21 known dead ends. Each subsequent PR of the decisiveness wave deletes the
rows it cures (PR-3's four new interview questions remove the rest). **When
``WALK_DEAD_END_ALLOWLIST`` is empty the invariant becomes unconditional** —
``_dead_end_violations`` needs no change for that, it simply stops finding
an excuse for any NEEDS_INPUT walk.

The corpus under ``gold_coverage/fixtures/walks/`` is DATA, generated by driving the
real ``computeNextNode``/``getCategoryQuestionIds``/``mapOracleFactsToApplicantFacts``
(first option answered at every question, 121 stay-days), never hand-written:
each file carries the walk's ``asked`` question ids and the exact wire
``overrides`` that walk produced. The expectations live HERE, in one
reviewable table, so a wave PR that moves an outcome must state which
outcome it moved.

Regenerate the corpus with ``npm run visa-oracle:walk-corpus -w apps/mouth``
(``apps/mouth/scripts/visa-oracle/generate-walk-corpus.ts``, proved byte-for-byte
reproducible by ``walk-corpus-determinism.test.ts``): a PR that changes the
interview tree MUST regenerate it and update ``EXPECTED_OUTCOME`` /
``WALK_DEAD_END_ALLOWLIST`` below in that same PR.
"""

from __future__ import annotations

import json
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pytest

from backend.scripts.visa_engine.gold_coverage_eval import _evaluate
from backend.scripts.visa_engine.gold_replay_driver import (
    PACKS_DIR,
    _parse_utc,
    select_highest_repository_pack,
)

CORPUS_DIR = Path(__file__).resolve().parent / "gold_coverage" / "fixtures" / "walks"

# PINNED to the highest signed pack's own `signed_at`, never the wall clock —
# same clock bomb `test_gold_coverage_floor.py` documents at length: the
# selected pack's source_records carry a freshness_policy with as little as a
# 604800s (7-day) window, so evaluating at `datetime.now(UTC)` is guaranteed
# to turn this whole census into HUMAN_REVIEW_REQUIRED seven days after the
# newest source's verified_at, with zero code change. `signed_at` (not
# `payload.created_at`) because the same instant drives `verify_rule_pack`'s
# `observed_at`, which rejects a signature dated after the observation.
_, _HIGHEST_SIGNED_PACK = select_highest_repository_pack(PACKS_DIR)
_AS_OF = _parse_utc(_HIGHEST_SIGNED_PACK["protected"]["signed_at"])

#: Why an allowlisted NEEDS_INPUT is a DEAD END and not a question the funnel
#: could ask. Each value is checked against the walk's own `asked` history.
NO_QUESTION_IN_TREE = "no question in tree.ts can ever set this fact"
QUESTION_NOT_IN_THIS_WALK = "the question exists but this walk's branch never asks it"
ANSWER_NEVER_CERTIFIED = "the question IS asked, and the mapper refuses to certify the answer"


@dataclass(frozen=True)
class DeadEnd:
    """One allowlisted dead end: the blocking fact, its source question in
    ``tree.ts`` (``None`` when no question emits it at all), and the reason
    the funnel cannot supply it."""

    fact: str
    source_question: str | None
    why_unaskable: str


# The five dead-end shapes measured on seq-20, with the anchor that explains
# each. A wave PR retires a shape by deleting its rows below, never by
# loosening a count. Seq-20 retired two of seq-19's seven shapes outright:
# `family.sponsor_status_code` (fold edit 3 made its eight rules NO_EFFECT)
# and `intent.requested_product_code` (fold edit 4 guarded the four BRIDGING
# rules on a `known` premise), so their DeadEnd rows are gone rather than
# merely unused.
_ONSHORE_CONVERSION = DeadEnd(
    # flow.ts:539-542 emits `wants_onshore_conversion` only when
    # `in_indonesia === "yes"`; every offshore walk is blocked by
    # `hf.d12-onshore-conversion-excluded` (safety_critical, on_unknown:
    # NEEDS_INPUT) on behalf of D12 — a product whose SUPPORT rules all
    # require INVESTMENT purposes and can never cover a tourist.
    "process.wants_onshore_conversion",
    "wants_onshore_conversion",
    QUESTION_NOT_IN_THIS_WALK,
)
_SPONSOR_TYPE = DeadEnd(
    # `sponsor_category` (tree.ts:441-444) is absent from FIXED_CATEGORY_QUESTIONS
    # for tourism/business/other/diaspora (flow.ts:570-606); the blockers are
    # `hf.e33{a,b,c}.sponsor-not-government*` on three products that carry ZERO
    # SUPPORT rules and so can never be candidates under any sponsor value.
    "sponsor.type",
    "sponsor_category",
    QUESTION_NOT_IN_THIS_WALK,
)
_DIASPORA_PURPOSE = DeadEnd(
    # `category` IS asked, but CATEGORY_TO_PURPOSE (fact-mapper.ts:255-266)
    # deliberately has no `diaspora` entry, so `mapPurposes` returns
    # unknownFact(NOT_APPLICABLE) — the answer exists and is refused.
    "intent.purposes",
    "category",
    ANSWER_NEVER_CERTIFIED,
)
_INVESTMENT_CAPITAL = DeadEnd(
    "investment.investment_capital_idr",
    "investment_capital_idr",
    QUESTION_NOT_IN_THIS_WALK,
)
_PAID_UP_CAPITAL = DeadEnd(
    "investment.paid_up_capital_idr",
    "investment_paid_up_capital_idr",
    QUESTION_NOT_IN_THIS_WALK,
)
_FAMILY_SPONSOR_CONFIRMED = DeadEnd(
    # NEW on seq-20, and it is a MOVE, not a regression: `el.c2.business`'s
    # stay-day bound went 60 -> 180 (fold edit 1), so C2 became reachable for
    # the business/investment arm at the corpus's 121 days — and C2's own
    # `family.sponsor_confirmed == true` premise is now the smallest missing
    # set, winning `evaluator.py`'s `min(len(missing_facts))` tie-break over
    # the blockers these walks used to report. `family_sponsor_confirmed` is
    # emitted only by the family arm (flow.ts:708) and by retirement
    # (flow.ts:657-659); no invest/business/other branch asks it, so the
    # funnel genuinely cannot supply it here. PR-3's mandate.
    "family.sponsor_confirmed",
    "family_sponsor_confirmed",
    QUESTION_NOT_IN_THIS_WALK,
)

#: The 21 known dead ends. DELETE rows as the wave cures them; never add one
#: without an anchor showing the fact is genuinely unaskable in that walk.
WALK_DEAD_END_ALLOWLIST: dict[str, tuple[DeadEnd, ...]] = {
    "offshore/business": (_ONSHORE_CONVERSION,),
    "offshore/diaspora": (_DIASPORA_PURPOSE,),
    "offshore/invest/bank_deposit": (_FAMILY_SPONSOR_CONFIRMED,),
    "offshore/invest/family": (_FAMILY_SPONSOR_CONFIRMED,),
    "offshore/invest/merit": (_FAMILY_SPONSOR_CONFIRMED,),
    "offshore/invest/property": (_FAMILY_SPONSOR_CONFIRMED,),
    "offshore/invest/pt_pma": (_FAMILY_SPONSOR_CONFIRMED,),
    "offshore/invest/undecided": (_FAMILY_SPONSOR_CONFIRMED,),
    "offshore/other": (_FAMILY_SPONSOR_CONFIRMED,),
    "offshore/remote": (_ONSHORE_CONVERSION,),
    "offshore/retirement/bank_deposit": (_ONSHORE_CONVERSION,),
    "offshore/retirement/family_sponsor": (_ONSHORE_CONVERSION,),
    "offshore/retirement/passive_income": (_ONSHORE_CONVERSION,),
    "offshore/retirement/property": (_ONSHORE_CONVERSION,),
    "offshore/retirement/undecided": (_ONSHORE_CONVERSION,),
    "onshore/business": (_SPONSOR_TYPE,),
    "onshore/diaspora": (_DIASPORA_PURPOSE,),
    "onshore/invest": (_FAMILY_SPONSOR_CONFIRMED,),
    "onshore/other": (_FAMILY_SPONSOR_CONFIRMED,),
    "onshore/remote": (_INVESTMENT_CAPITAL, _PAID_UP_CAPITAL),
    "onshore/retirement": (_INVESTMENT_CAPITAL, _PAID_UP_CAPITAL),
}

#: Per-walk outcome pin: state plus the candidate products, in rank order.
#: Candidates are pinned too — a pack edit that adds or drops a product for a
#: walk that already had an answer is exactly as much of a shift as a state
#: change, and this table is the only place either becomes visible.
EXPECTED_OUTCOME: dict[str, tuple[str, tuple[str, ...]]] = {
    "offshore/business": ("NEEDS_INPUT", ()),
    "offshore/diaspora": ("NEEDS_INPUT", ()),
    "offshore/family/CHILD/spNat=ID": ("SUPPORTED_CANDIDATES", ("C1", "E31G")),
    "offshore/family/CHILD/spNat=IT": ("SUPPORTED_CANDIDATES", ("C1",)),
    "offshore/family/DEPENDENT/spNat=ID": ("SUPPORTED_CANDIDATES", ("C1",)),
    "offshore/family/DEPENDENT/spNat=IT": ("SUPPORTED_CANDIDATES", ("C1",)),
    "offshore/family/OTHER/spNat=ID": ("SUPPORTED_CANDIDATES", ("C1",)),
    "offshore/family/OTHER/spNat=IT": ("SUPPORTED_CANDIDATES", ("C1",)),
    "offshore/family/PARENT/spNat=ID": ("SUPPORTED_CANDIDATES", ("C1", "E31C", "E31F")),
    "offshore/family/PARENT/spNat=IT": ("SUPPORTED_CANDIDATES", ("C1",)),
    "offshore/family/SIBLING/spNat=ID": ("SUPPORTED_CANDIDATES", ("C1",)),
    "offshore/family/SIBLING/spNat=IT": ("SUPPORTED_CANDIDATES", ("C1",)),
    "offshore/family/SPOUSE/spNat=ID": ("SUPPORTED_CANDIDATES", ("C1", "E31A")),
    "offshore/family/SPOUSE/spNat=IT": ("SUPPORTED_CANDIDATES", ("C1",)),
    "offshore/holdsPermit/current/tourism": ("SUPPORTED_CANDIDATES", ("C1",)),
    "offshore/invest/bank_deposit": ("NEEDS_INPUT", ()),
    "offshore/invest/family": ("NEEDS_INPUT", ()),
    "offshore/invest/merit": ("NEEDS_INPUT", ()),
    "offshore/invest/property": ("NEEDS_INPUT", ()),
    "offshore/invest/pt_pma": ("NEEDS_INPUT", ()),
    "offshore/invest/undecided": ("NEEDS_INPUT", ()),
    "offshore/other": ("NEEDS_INPUT", ()),
    "offshore/remote": ("NEEDS_INPUT", ()),
    "offshore/retirement/bank_deposit": ("NEEDS_INPUT", ()),
    "offshore/retirement/family_sponsor": ("NEEDS_INPUT", ()),
    "offshore/retirement/passive_income": ("NEEDS_INPUT", ()),
    "offshore/retirement/property": ("NEEDS_INPUT", ()),
    "offshore/retirement/undecided": ("NEEDS_INPUT", ()),
    "offshore/study": ("SUPPORTED_CANDIDATES", ("E30", "E30A")),
    "offshore/tourism": ("SUPPORTED_CANDIDATES", ("C1",)),
    "offshore/work": ("SUPPORTED_CANDIDATES", ("E23",)),
    "onshore/business": ("NEEDS_INPUT", ()),
    "onshore/diaspora": ("NEEDS_INPUT", ()),
    "onshore/family": ("SUPPORTED_CANDIDATES", ("C1",)),
    "onshore/holdsPermit/current/tourism": ("SUPPORTED_CANDIDATES", ("C1",)),
    "onshore/holdsPermit/expired/tourism": ("SUPPORTED_CANDIDATES", ("C1",)),
    "onshore/invest": ("NEEDS_INPUT", ()),
    "onshore/other": ("NEEDS_INPUT", ()),
    "onshore/remote": ("NEEDS_INPUT", ()),
    "onshore/retirement": ("NEEDS_INPUT", ()),
    "onshore/study": ("SUPPORTED_CANDIDATES", ("E30", "E30A")),
    "onshore/tourism": ("SUPPORTED_CANDIDATES", ("C1",)),
    "onshore/work": ("SUPPORTED_CANDIDATES", ("E23",)),
}

#: The state distribution, restated as a total so a reviewer sees the shape of
#: the funnel in one line. Derived from EXPECTED_OUTCOME on purpose: the two
#: can never disagree, and the wave PRs edit one table, not two.
EXPECTED_STATE_CENSUS: dict[str, int] = dict(
    Counter(state for state, _ in EXPECTED_OUTCOME.values())
)

#: Which fact blocks how many walks — the §2.2 table. A cure that moves walks
#: between blocking facts instead of removing the block goes red here even if
#: the total happens to stay the same.
EXPECTED_DEAD_END_FACT_CENSUS: dict[str, int] = {
    "family.sponsor_confirmed": 9,
    "process.wants_onshore_conversion": 7,
    "intent.purposes": 2,
    "investment.investment_capital_idr": 2,
    "investment.paid_up_capital_idr": 2,
    "sponsor.type": 1,
}


def _load_walks() -> dict[str, dict[str, Any]]:
    """Read the walk corpus, keyed by label (which must match the file stem
    modulo the ``/``→``_`` filename encoding, so a renamed file cannot smuggle
    another walk's expectations in)."""

    walks: dict[str, dict[str, Any]] = {}
    for path in sorted(CORPUS_DIR.glob("*.json")):
        spec = json.loads(path.read_text(encoding="utf-8"))
        label = str(spec["label"])
        assert label.replace("/", "_").replace("=", "_") == path.stem.replace("=", "_"), (
            f"{path.name}: file name does not encode its own label {label!r}"
        )
        walks[label] = spec
    return walks


def _evaluate_walks(walks: dict[str, dict[str, Any]]) -> dict[str, dict[str, Any]]:
    """Evaluate every walk through ``gold_coverage_eval._evaluate`` — the same
    verify → compile → evaluate → apply_public_policy_adapters path the gold
    replay and the coverage floor use. Never re-implemented here, so this
    census and those gates cannot drift on what "evaluate" means."""

    return {
        label: _evaluate(spec["overrides"], label, as_of=_AS_OF)["actual"]
        for label, spec in sorted(walks.items())
    }


def _outcome_violations(
    outcomes: dict[str, dict[str, Any]],
    expected: dict[str, tuple[str, tuple[str, ...]]] | None = None,
) -> list[str]:
    """Every walk whose (state, candidates) differ from the pinned pair."""

    pins = EXPECTED_OUTCOME if expected is None else expected
    violations: list[str] = []
    for label in sorted(set(outcomes) | set(pins)):
        actual = outcomes.get(label)
        if actual is None:
            violations.append(f"{label}: pinned but absent from the corpus")
            continue
        if label not in pins:
            violations.append(f"{label}: evaluated but not pinned in EXPECTED_OUTCOME")
            continue
        want_state, want_candidates = pins[label]
        got = (actual["state"], tuple(actual["candidates"]))
        if got != (want_state, want_candidates):
            violations.append(
                f"{label}: expected {want_state} {list(want_candidates)}, got {got[0]} {list(got[1])}"
            )
    return violations


def _dead_end_violations(
    outcomes: dict[str, dict[str, Any]],
    allowlist: dict[str, tuple[DeadEnd, ...]] | None = None,
) -> list[str]:
    """The invariant, both ways.

    A NEEDS_INPUT walk must be allowlisted and must block on EXACTLY the
    allowlisted facts (a new blocking fact is a new dead end, not a variant of
    an old one), and an allowlisted walk that no longer dead-ends is a STALE
    row that the curing PR must delete — otherwise the allowlist would outlive
    the defect and quietly re-authorise it.
    """

    rows = WALK_DEAD_END_ALLOWLIST if allowlist is None else allowlist
    violations: list[str] = []
    for label in sorted(outcomes):
        actual = outcomes[label]
        allowed = tuple(sorted(dead_end.fact for dead_end in rows.get(label, ())))
        missing = tuple(actual["missing_facts"])
        if actual["state"] == "NEEDS_INPUT":
            if not allowed:
                violations.append(
                    f"{label}: NEEDS_INPUT on {list(missing)} with no allowlist row — "
                    "the interview cannot ask for a fact it has no reachable question for"
                )
            elif missing != allowed:
                violations.append(
                    f"{label}: dead-ends on {list(missing)}, allowlist says {list(allowed)}"
                )
        elif allowed:
            violations.append(
                f"{label}: allowlisted for {list(allowed)} but now ends {actual['state']} — "
                "stale allowlist row, delete it in the PR that cured it"
            )
    for label in sorted(set(rows) - set(outcomes)):
        violations.append(f"{label}: allowlisted but absent from the corpus")
    return violations


@pytest.fixture(scope="module")
def walks() -> dict[str, dict[str, Any]]:
    return _load_walks()


@pytest.fixture(scope="module")
def outcomes(walks: dict[str, dict[str, Any]]) -> dict[str, dict[str, Any]]:
    return _evaluate_walks(walks)


def test_corpus_is_the_43_real_interview_walks(walks: dict[str, dict[str, Any]]) -> None:
    """An empty or shrunken corpus fails loudly: a census that passes because
    nobody fed it any walks is the green-but-dead shape (cicatrix #2)."""

    assert len(walks) == 43, f"expected 43 interview walks, found {len(walks)}"
    assert sorted(walks) == sorted(EXPECTED_OUTCOME), "corpus and EXPECTED_OUTCOME disagree"
    for label, spec in walks.items():
        assert spec["asked"], f"{label}: walk carries no asked-question history"
        assert spec["overrides"], f"{label}: walk carries no wire facts"


def test_every_walk_ends_in_its_pinned_outcome(outcomes: dict[str, dict[str, Any]]) -> None:
    violations = _outcome_violations(outcomes)
    assert not violations, "interview-walk outcomes moved:\n  " + "\n  ".join(violations)


def test_walk_state_census_is_21_dead_ends_and_22_answers(
    outcomes: dict[str, dict[str, Any]],
) -> None:
    """The headline number of the decisiveness wave. Every PR that changes it
    updates this literal and says which walks moved, in its own body.

    Was 36/7 on seq-19; the signed seq-20 bundle's stay-day widening turned 15
    of the dead ends into answers (module docstring)."""

    census = dict(Counter(outcome["state"] for outcome in outcomes.values()))
    assert census == EXPECTED_STATE_CENSUS == {"NEEDS_INPUT": 21, "SUPPORTED_CANDIDATES": 22}
    assert census.get("NO_SUPPORTED_PATH", 0) == 0
    assert census.get("HUMAN_REVIEW_REQUIRED", 0) == 0


def test_dead_end_fact_census_matches_the_blocking_fact_table(
    outcomes: dict[str, dict[str, Any]],
) -> None:
    census = Counter(
        fact
        for outcome in outcomes.values()
        if outcome["state"] == "NEEDS_INPUT"
        for fact in outcome["missing_facts"]
    )
    assert dict(census) == EXPECTED_DEAD_END_FACT_CENSUS


def test_no_walk_dead_ends_outside_the_allowlist(outcomes: dict[str, dict[str, Any]]) -> None:
    violations = _dead_end_violations(outcomes)
    assert not violations, "walk-census invariant broken:\n  " + "\n  ".join(violations)


def test_allowlist_is_exactly_the_21_known_dead_ends() -> None:
    assert len(WALK_DEAD_END_ALLOWLIST) == 21
    assert set(WALK_DEAD_END_ALLOWLIST) <= set(EXPECTED_OUTCOME)


def test_every_allowlisted_dead_end_is_genuinely_unaskable_in_its_own_walk(
    walks: dict[str, dict[str, Any]],
) -> None:
    """The allowlist's REASON, checked against the walk's own history — not
    taken on trust. This is what turns PR-3's four new questions into a red
    row: the moment a branch starts asking `wants_onshore_conversion`, its
    ``QUESTION_NOT_IN_THIS_WALK`` claim is false here."""

    for label, dead_ends in sorted(WALK_DEAD_END_ALLOWLIST.items()):
        asked = set(walks[label]["asked"])
        for dead_end in dead_ends:
            if dead_end.why_unaskable == NO_QUESTION_IN_TREE:
                assert dead_end.source_question is None, f"{label}/{dead_end.fact}"
            elif dead_end.why_unaskable == QUESTION_NOT_IN_THIS_WALK:
                assert dead_end.source_question not in asked, (
                    f"{label}: {dead_end.source_question!r} IS asked in this walk — "
                    f"{dead_end.fact} is no longer unaskable here"
                )
            elif dead_end.why_unaskable == ANSWER_NEVER_CERTIFIED:
                assert dead_end.source_question in asked, (
                    f"{label}: {dead_end.source_question!r} is not asked in this walk, "
                    "so the mapper never gets an answer to refuse"
                )
            else:  # pragma: no cover - a typo in a new row must not pass silently
                raise AssertionError(f"{label}: unknown reason {dead_end.why_unaskable!r}")


def test_guilt_a_cured_dead_end_that_only_moves_the_block_is_caught(
    walks: dict[str, dict[str, Any]],
) -> None:
    """GUILT, on the real engine: hand ``onshore/business`` the very fact it
    dead-ends on (``sponsor.type`` KNOWN) and watch the block MOVE rather than
    lift — measured 2026-09-06 on seq-20, the walk stays NEEDS_INPUT and now
    blocks on ``investment.{investment,paid_up}_capital_idr`` instead, because
    the next zero-SUPPORT product wins ``evaluator.py``'s
    ``min(len(missing_facts))`` tie-break.

    Re-anchored from ``onshore/tourism`` on seq-20: that walk now ANSWERS
    (C1), so the mutation would have had nothing left to move.

    That is the whole reason the allowlist compares FACTS and not a count: the
    state census alone would call this cure a no-op (still NEEDS_INPUT, still
    no candidates), and only the per-fact comparison sees it."""

    mutated = dict(walks["onshore/business"]["overrides"])
    mutated["sponsor.type"] = {"status": "KNOWN", "value": "NONE"}
    actual = _evaluate(mutated, "onshore/business", as_of=_AS_OF)["actual"]

    assert actual["state"] == "NEEDS_INPUT", (
        "the guilt mutation now LIFTS the block instead of moving it — this "
        "test no longer exercises the shape it was written for"
    )
    assert actual["missing_facts"] != ["sponsor.type"], (
        "the guilt mutation no longer changes what blocks this walk — the "
        "corpus or the pack moved and this test proves nothing"
    )
    assert _dead_end_violations({"onshore/business": actual})


def test_guilt_a_walk_that_loses_its_answer_is_caught(
    walks: dict[str, dict[str, Any]],
) -> None:
    """GUILT: ``offshore/work`` is one of the 22 walks that DO answer (E23).
    Take its ``work.indonesian_work_sponsor_confirmed`` away and both halves
    of the gate must fire — the outcome pin (SUPPORTED → NEEDS_INPUT) and the
    invariant (a dead end with no allowlist row)."""

    mutated = dict(walks["offshore/work"]["overrides"])
    mutated["work.indonesian_work_sponsor_confirmed"] = {"status": "KNOWN", "value": False}
    actual = _evaluate(mutated, "offshore/work", as_of=_AS_OF)["actual"]

    assert _outcome_violations({"offshore/work": actual})
    assert _dead_end_violations({"offshore/work": actual})


def test_guilt_a_dead_end_on_an_unlisted_fact_is_caught() -> None:
    """GUILT: a NEEDS_INPUT on a fact nobody allowlisted — the shape a new
    signed rule with ``on_unknown: NEEDS_INPUT`` on an unaskable fact would
    produce — is a violation, and stays one when the allowlist is EMPTY (the
    permanent form of the invariant, after the wave)."""

    fabricated = {
        "offshore/tourism": {
            "state": "NEEDS_INPUT",
            "candidates": [],
            "missing_facts": ["work.employer_is_indonesian_entity"],
        }
    }
    assert _dead_end_violations(fabricated)
    assert _dead_end_violations(
        {"offshore/tourism": {"state": "NEEDS_INPUT", "candidates": [], "missing_facts": []}},
        allowlist={},
    )


def test_guilt_a_stale_allowlist_row_is_caught() -> None:
    """GUILT: the cure lands, the walk answers, and the allowlist row stays —
    the way an allowlist normally outlives its defect. Must be red.

    Anchored on ``offshore/business``, which IS still allowlisted on seq-20;
    the seq-19 anchor (``offshore/tourism``) was cured by this very fold, so
    reusing it would have made this guilt test pass for the wrong reason —
    an unlisted walk, not a stale row."""

    assert "offshore/business" in WALK_DEAD_END_ALLOWLIST
    cured = {
        "offshore/business": {
            "state": "SUPPORTED_CANDIDATES",
            "candidates": ["C1"],
            "missing_facts": [],
        }
    }
    violations = _dead_end_violations(cured)
    assert violations and "stale allowlist row" in violations[0]
