#!/usr/bin/env python3
"""
Script to add 6 new KBLI gold codes while removing any existing duplicates.
"""

import re

# Read the file
with open('/Users/nuzantara/Desktop/kbli-navigator-rebuild/lib/kbli-gold-content.ts', 'r') as f:
    content = f.read()

# Codes to add/replace
codes_to_update = ['90310', '73201', '74191', '74193', '74199', '74194']

# Remove existing entries for these codes
for code in codes_to_update:
    # Pattern to match the entire code entry including tkaInfo if present
    pattern = rf'  "{code}": \{{[\s\S]*?(?:    }},\n|  }},\n)'
    content = re.sub(pattern, '', content)

# Find the closing of KBLI_GOLD_CONTENT object
closing_pattern = r'(    },\n  },\n)(};)'
match = re.search(closing_pattern, content)

if not match:
    # Try alternative pattern
    closing_pattern = r'(      keduaNote:.*?\n    },\n  },\n)(};)'
    match = re.search(closing_pattern, content)

if match:
    insertion_point = match.start(2)
    
    new_codes = '''
  // ---------------------------------------------------------------------------
  // Creative Industries & Design Services (90xxx, 73xxx, 74xxx)
  // ---------------------------------------------------------------------------

  "90310": {
    whatItMeans:
      "Operation of arts facilities — running galleries, performance venues, concert halls, recording studios, and other physical spaces dedicated to artistic and cultural activities. This is the VENUE OPERATION business, not the art production itself. You provide the space, technical infrastructure, and facility management for artists and performers to create or exhibit their work.",
    whatYouNeed:
      `**BPS_ONLY code — no PP 28/2025 structured licensing data available.**\\n\\n**Minimum requirements:**\\n1. **PT PMA incorporation** — notary deed, AHU registration; minimum IDR 10B stated capital (~3–5 weeks)\\n2. **NIB via OSS** — register on oss.go.id, select 90310; auto-issued (1–3 days)\\n3. **Monitor OSS for updates** — as PP 28/2025 implementation progresses, specific requirements may be added for this code\\n\\n**Additional permits likely required (based on venue type):**\\n- **PBG** (Persetujuan Bangunan Gedung) — building permit for the venue structure\\n- **Izin Keramaian** — public gathering permit from Satpol PP if hosting events with audiences\\n- **Dinas Kebudayaan clearance** — cultural affairs office may require registration or approval for venues operating as cultural centers or museums\\n- **Fire safety certificate** — Dinas Pemadam Kebakaran inspection for public assembly spaces\\n- **AMDAL or UKL-UPL** — environmental assessment if venue includes recording studios or performance spaces with noise/environmental impact\\n\\n**Typical total timeline:** 2–4 months from PT PMA to operational venue (driven by building permits and facility setup, not licensing complexity).\\n**Minimum PT PMA capital:** IDR 10 billion stated capital (Rp 2.5B paid-up).\\n\\n**Authority:** To be determined as OSS updates.\\n**PMA:** Fully open (Terbuka) — 100% foreign ownership.`,
    whatChanged:
      "New code in KBLI 2025 — no direct predecessor in KBLI 2020. Art venue operations were previously scattered across multiple codes or classified under general cultural activities. This dedicated code recognizes the distinct business model of operating cultural spaces as a commercial activity.",
    baliContext:
      "**🎨 Bali's Art Venue Ecosystem (World-Class Scene)**\\n- Ubud is internationally recognized as a cultural hub: ARMA (Agung Rai Museum of Art), Blanco Renaissance Museum, Neka Art Museum, and dozens of independent galleries operate year-round\\n- Seminyak and Canggu have emerged as contemporary art centers: Biasa ArtSpace, TAKSU Bali, and rotating pop-up galleries serve the international collector market\\n- **Performance venues:** Ubud has dedicated performance spaces (Pura Dalem Ubud for traditional dance, Paradiso for contemporary theater); demand exists but supply is limited\\n- **Recording studios:** Bali attracts international musicians for recording retreats; studios like Karma Sound (Ubud) and Ganesha Recording (Sanur) serve this niche\\n\\n---\\n\\n**💡 PMA Opportunities in This Sector**\\n- **Contemporary art gallery + café + workshop space:** The hybrid model works in Bali — a gallery that also functions as a creative co-working space, hosts artist residencies, and runs a café generates multiple revenue streams\\n- **International artist residency program:** Subsidized studio space + exhibition opportunity + Bali immersion = attractive package for mid-career international artists; monetize through exhibition sales, workshop fees, and cultural tourism partnerships\\n- **Boutique concert hall or jazz club:** Bali has a strong live music scene but lacks dedicated mid-size (100–200 capacity) performance venues with professional acoustics; this is a genuine gap\\n\\n---\\n\\n**⚠ Practical Considerations**\\n- **BPS_ONLY status means regulatory uncertainty:** This code has no structured PP 28/2025 data yet. Expect to navigate case-by-case with DPMPTSP and Dinas Kebudayaan. Document everything\\n- **Dinas Kebudayaan relationship is critical:** Cultural affairs offices at kabupaten/kota level have informal influence over cultural venues even when not the formal licensing authority. Build this relationship early\\n- **Noise and neighbor relations:** Performance venues and recording studios face noise complaints. Soundproofing is essential, and choosing a location with commercial zoning (not residential) prevents conflicts\\n- **Event permits are ongoing:** Each public event may require separate Izin Keramaian. Budget for administrative overhead if you're running frequent events",
    youllAlsoNeed:
      "- **56101** — Restaurant or café (if your venue includes F&B)\\n- **90100** — Creative arts production (if you also produce performances, not just host them)\\n- **90200** — Supporting activities for the arts (if you provide artist management, curation, or production services)\\n- **93299** — Other recreational activities (if your venue includes interactive or recreational elements)\\n- **82300** — Event organization (if you organize festivals or curated event series)\\n- **47610** — Retail of books, art supplies (if you sell art-related merchandise)",
    zantaraOpener:
      "Operating an art gallery, performance space, or cultural venue in Bali? 90310 is the new 2025 code for this. It's BPS_ONLY — no structured licensing data yet — so you'll be navigating case-by-case. Let me show you what to expect.",
  },

  "73201": {
    whatItMeans:
      "Market research and public opinion polling — conducting quantitative and qualitative research to understand consumer behavior, market dynamics, competitive positioning, and public sentiment. This includes consumer surveys, focus groups, mystery shopping, brand tracking studies, feasibility studies, competitive analysis, and opinion polling. The output is research data and insights, not strategic consulting (that's 70201).",
    whatYouNeed:
      `**Low risk (Rendah) — all scales.** NIB issued **automatically** (Otomatis). Authority: **OSS Pusat**.\\n\\n*(Note: PP 28/2025 data includes an anomalous "Gubernur Daerah Khusus Jakarta" scale entry. For Bali and national operations, the applicable path is Rendah / OSS Pusat / Otomatis.)*\\n\\n**Step-by-step for a PT PMA market research firm:**\\n1. **PT PMA incorporation** — notary deed, AHU registration; minimum IDR 10B stated capital (~3–5 weeks)\\n2. **NIB via OSS** — register on oss.go.id, select 73201, Rendah path; auto-issued (1–3 days)\\n3. **Data collection compliance** — if conducting research involving Indonesian citizens:\\n   - **Privacy compliance:** Align with UU 27/2022 (Personal Data Protection Law); obtain informed consent for data collection\\n   - **Research ethics:** Follow standard research ethics protocols (anonymization, voluntary participation, right to withdraw)\\n4. **Field researcher hiring** — for on-the-ground data collection (surveys, interviews, mystery shopping), hiring Indonesian enumerators is practically mandatory; foreign researchers conducting fieldwork face visa and cultural barriers\\n5. **Laporan kegiatan usaha** — periodic business activity reports (ongoing obligation)\\n\\n**Typical total timeline:** 1–2 months from PT PMA to first research project (NIB is instant; timeline driven by team setup and client acquisition).\\n**Minimum PT PMA capital:** IDR 10 billion stated capital (Rp 2.5B paid-up).\\n\\n**Authority:** OSS Pusat.\\n**PMA:** Fully open (Terbuka) — 100% foreign ownership.`,
    whatChanged:
      "Direct match from KBLI 2020 (MATCH_LANGSUNG). Market research remains a stable, clearly defined category. PP 28/2025 formalizes the Low risk / OSS Pusat pathway.",
    baliContext:
      "**📊 Market Research in Bali (Hospitality-Driven Demand)**\\n- Bali's hospitality industry generates consistent demand for market research: guest satisfaction surveys, brand positioning studies, location feasibility for new properties, competitive analysis for F&B concepts\\n- **Client base:** International hotel chains, resort developers, restaurant groups, tourism boards, and retail brands entering the Bali market\\n- **Niche opportunity:** Bali-specific tourism research — understanding the evolving tourist demographic (digital nomads vs. traditional tourists, domestic vs. international, luxury vs. budget) is valuable intelligence for hospitality operators\\n\\n---\\n\\n**💡 PMA Advantages in This Sector**\\n- **International methodology + local execution:** A PMA research firm with international research standards (ESOMAR compliance, advanced analytics) combined with local Indonesian field teams is a strong positioning\\n- **Cross-border research:** Serving multinational clients who need Indonesia market research as part of regional ASEAN studies — Bali-based PMA can coordinate Indonesia fieldwork while reporting to Singapore/Bangkok regional offices\\n\\n---\\n\\n**⚠ Practical Considerations**\\n- **Data privacy law is real:** UU 27/2022 (Personal Data Protection) is now enforceable. Research firms collecting personal data must have consent protocols, data storage policies, and breach notification procedures. This is not optional\\n- **Local hiring for fieldwork is essential:** Foreign researchers conducting face-to-face surveys or focus groups in Indonesian will face language barriers and cultural trust issues. Indonesian enumerators are operationally necessary\\n- **Distinction from consulting:** 73201 is research (data collection and analysis). If you also provide strategic recommendations and implementation advice, you may need 70201 (management consulting) as a secondary code\\n- **Mystery shopping legality:** Mystery shopping (evaluating service quality by posing as a customer) is legal but must be disclosed to the business being evaluated if results will be published or used in legal proceedings",
    youllAlsoNeed:
      "- **70201** — Management consulting — if you provide strategic advice based on research findings\\n- **62010** — Software development — if you build proprietary research platforms or data analytics tools\\n- **63110** — Data processing and hosting — if you operate research data infrastructure\\n- **73200** — Advertising research — if you specialize in ad effectiveness and media measurement\\n- **82990** — Other business support services — if you provide ancillary services like transcription or data entry",
    zantaraOpener:
      "Market research business in Bali? 73201 is NIB only, auto-issued, Low risk. The licensing is trivial. The operational challenge is building a credible local field team and navigating Indonesia's new data privacy law. Let me walk you through it.",
  },

  "74191": {
    whatItMeans:
      "Interior design services — space planning, furniture selection and specification, material selection, lighting design, color schemes, and concept development for residential and commercial interiors. This is DESIGN CONSULTING, not construction execution. You produce drawings, specifications, mood boards, and 3D renderings. If you also execute the build-out (install furniture, paint walls, lay flooring), that's 43302 (interior finishing work) — a separate code.",
    whatYouNeed:
      `**BPS_ONLY code — no PP 28/2025 structured licensing data available.**\\n\\n**Minimum requirements:**\\n1. **PT PMA incorporation** — notary deed, AHU registration; minimum IDR 10B stated capital (~3–5 weeks)\\n2. **NIB via OSS** — register on oss.go.id, select 74191; auto-issued (1–3 days)\\n3. **Monitor OSS for updates** — as PP 28/2025 implementation progresses, specific requirements may be added for this code\\n\\n**Professional credibility (not legally required but commercially important):**\\n- **HDII membership** (Himpunan Desainer Interior Indonesia) — Indonesia's interior design association; membership signals professional credibility to clients\\n- **Portfolio and credentials** — international design qualifications (NCIDQ, BIID, etc.) are recognized and valued in Bali's high-end market\\n\\n**Typical total timeline:** 1–2 months from PT PMA to first client project (NIB is instant; timeline driven by studio setup and client acquisition).\\n**Minimum PT PMA capital:** IDR 10 billion stated capital (Rp 2.5B paid-up).\\n\\n**Authority:** To be determined as OSS updates.\\n**PMA:** Fully open (Terbuka) — 100% foreign ownership.`,
    whatChanged:
      "Direct match from KBLI 2020 (MATCH_LANGSUNG). Interior design services remain a stable category. The key distinction in KBLI 2025 is the continued separation between design (74191) and execution (43302) — this has always been the case but is now more explicitly enforced in licensing.",
    baliContext:
      "**🏡 Interior Design in Bali (Massive Market)**\\n- Bali has one of Indonesia's most active interior design markets: villa design, resort interior concepts, F&B space design, boutique hotel interiors, and high-end residential projects\\n- **International designers:** Many international interior designers base themselves in Canggu, Ubud, or Seminyak and serve clients across Indonesia and Southeast Asia from Bali\\n- **Bali aesthetic:** Tropical modernism, natural materials (teak, rattan, stone), indoor-outdoor flow, and integration with landscape — this is the signature Bali design language that clients globally associate with the island\\n\\n---\\n\\n**💡 PMA Opportunities in This Sector**\\n- **Villa design specialist:** Bali's villa market is enormous. A design firm specializing in villa interiors (understanding the short-term rental market, Instagram-friendly aesthetics, and durable tropical materials) has a clear niche\\n- **F&B concept design:** Restaurants, cafés, beach clubs, and bars in Bali are highly design-driven. A firm that understands both aesthetics and operational flow (kitchen layout, service efficiency, outdoor seating) can command premium fees\\n- **Resort and hotel interior design:** Bali's hospitality sector constantly renovates and builds new properties. International design firms with hotel experience can compete for these projects\\n\\n---\\n\\n**⚠ Critical Distinction: Design vs. Execution**\\n- **74191 = design only:** You produce drawings, specifications, and concepts. You do NOT install furniture, paint walls, or lay tiles. That's construction work (43302)\\n- **In practice, many designers do both:** A design firm that also executes the build-out needs BOTH codes: 74191 (design) + 43302 (interior finishing work). This is common in Bali\\n- **Liability separation:** If you design AND execute, ensure your contracts clearly separate design fees from construction costs. Design liability (errors in specification) is different from construction liability (defective workmanship)\\n- **Procurement vs. execution:** Specifying furniture and materials (design) is different from purchasing and installing them (execution). If you're just advising clients on what to buy, that's 74191. If you're buying it on their behalf and installing it, you need 43302",
    youllAlsoNeed:
      "- **43302** — Interior finishing work — if you also execute the design (install, build, finish)\\n- **71101** — Architectural services — if you also design the building structure, not just interiors\\n- **46491** — Wholesale of furniture — if you source and supply furniture to clients\\n- **47591** — Retail of furniture — if you operate a furniture showroom\\n- **74201** — Photography services — if you provide interior photography for portfolio and marketing",
    zantaraOpener:
      "Interior design business in Bali? 74191 is the code for design consulting. It's BPS_ONLY — no structured licensing yet — so it's NIB and monitor OSS. The real question is: are you ONLY designing, or also executing? That determines if you need 43302 as well. Let me explain.",
  },

  "74193": {
    whatItMeans:
      "Design services for film, television, video, and commercial production — set design, production design, art direction, costume design, prop design, and visual concept development for video content. This is DESIGN work (creating the visual concept and specifications), not filming or post-production. If you also operate cameras and edit footage, that's 59110 (film production). If you need filming permits (izin syuting), those are separate regulatory requirements on top of your NIB.",
    whatYouNeed:
      `**BPS_ONLY code — no PP 28/2025 structured licensing data available.**\\n\\n**Minimum requirements:**\\n1. **PT PMA incorporation** — notary deed, AHU registration; minimum IDR 10B stated capital (~3–5 weeks)\\n2. **NIB via OSS** — register on oss.go.id, select 74193; auto-issued (1–3 days)\\n3. **Monitor OSS for updates** — as PP 28/2025 implementation progresses, specific requirements may be added for this code\\n\\n**Additional permits for actual filming (if applicable):**\\n- **Izin syuting** — filming permit from local government (kabupaten/kota) if your design work involves on-location filming in Bali\\n- **Location permits** — specific permits for filming in protected areas, cultural sites, or private property\\n- Note: 74193 covers DESIGN services. If you also produce the film/video content, you need 59110 (film production) as well\\n\\n**Typical total timeline:** 1–2 months from PT PMA to first project (NIB is instant; timeline driven by portfolio development and client acquisition).\\n**Minimum PT PMA capital:** IDR 10 billion stated capital (Rp 2.5B paid-up).\\n\\n**Authority:** To be determined as OSS updates.\\n**PMA:** Fully open (Terbuka) — 100% foreign ownership.`,
    whatChanged:
      "New code in KBLI 2025 — no direct predecessor in KBLI 2020. Film and TV design services were previously classified under general design services (74199) or bundled with film production (59110). This dedicated code recognizes production design as a distinct professional discipline.",
    baliContext:
      "**🎬 Film & TV Production Design in Bali (International Hub)**\\n- Bali is a major location for international film, TV, and commercial production: Hollywood films (Eat Pray Love), Netflix series, luxury brand commercials, and music videos regularly shoot in Bali\\n- **Production design demand:** International productions bring their own directors and cinematographers but often hire local production designers who know Bali's locations, materials, and vendors\\n- **Commercial production:** Bali's visual appeal makes it a top destination for luxury brand commercials (fashion, automotive, hospitality) — these productions need set design and art direction\\n\\n---\\n\\n**💡 PMA Opportunities in This Sector**\\n- **Location-savvy production design:** A PMA design firm that specializes in Bali locations (knowing which villas, beaches, rice fields, and temples are film-friendly) can serve international productions\\n- **Tropical set design:** Designing sets that integrate Bali's natural materials (bamboo, teak, stone) and tropical aesthetics for commercials and films\\n- **Hybrid design + production:** Many production design firms also handle art department logistics (sourcing props, hiring local crew, coordinating with location owners) — this is valuable to international clients who need turnkey solutions\\n\\n---\\n\\n**⚠ Critical Distinctions**\\n- **74193 = design only:** You create the visual concept, design the sets, specify props and costumes. You do NOT operate cameras or edit footage\\n- **59110 = film production:** If you also shoot and produce the video content, you need 59110 as a secondary code\\n- **Izin syuting is separate:** Filming permits in Bali are issued by kabupaten/kota governments and are project-specific. Your NIB under 74193 does not automatically grant filming rights — each shoot needs its own izin syuting\\n- **Cultural sensitivity:** Filming at temples and cultural sites requires special permissions and adherence to adat (customary law). Work with local cultural liaisons",
    youllAlsoNeed:
      "- **59110** — Film and video production — if you also produce the film/video content, not just design it\\n- **74201** — Photography services — if you provide still photography for production\\n- **90200** — Supporting activities for the arts — if you provide production support services (casting, location scouting, crew hiring)\\n- **77393** — Rental of props and costumes — if you also rent out props and costumes\\n- **82300** — Event organization — if you organize film festivals or industry events",
    zantaraOpener:
      "Film and TV production design in Bali? 74193 is the new 2025 code for this. It's BPS_ONLY, so NIB only for now. Key distinction: this is DESIGN work. If you also shoot and produce, you need 59110 as well. And izin syuting is a separate permit per project. Let me explain the setup.",
  },

  "74199": {
    whatItMeans:
      "Other specialized design services not elsewhere classified — the catch-all for design work that doesn't fit into specific categories. This includes fashion design, jewelry design, packaging design, textile design, graphic design for print, exhibition design, and other creative design disciplines. If your design work fits a more specific code (interior = 74191, industrial product = 74103, web/digital = 62010), use that instead.",
    whatYouNeed:
      `**Only Mikro and Kecil scales in PP 28/2025 data.** Low risk (Rendah). NIB issued **automatically** (Otomatis). Authority: **Bupati/Walikota**.\\n\\n**Step-by-step for a PT PMA specialized design firm:**\\n1. **PT PMA incorporation** — notary deed, AHU registration; minimum IDR 10B stated capital (~3–5 weeks)\\n2. **NIB via OSS** — register on oss.go.id, select 74199, Mikro or Kecil scale; auto-issued (1–3 days)\\n3. **Laporan kegiatan usaha** — periodic business activity reports (ongoing obligation)\\n\\n**Note on scale limitation:** PP 28/2025 data only includes Mikro and Kecil scales for this code. If your operation is Menengah or Besar scale, consult with DPMPTSP on the applicable pathway.\\n\\n**Typical total timeline:** 1–2 months from PT PMA to first client project (NIB is instant; timeline driven by portfolio development and client acquisition).\\n**Minimum PT PMA capital:** IDR 10 billion stated capital (Rp 2.5B paid-up).\\n\\n**Authority:** Bupati/Walikota.\\n**PMA:** Fully open (Terbuka) — 100% foreign ownership.`,
    whatChanged:
      "Direct match from KBLI 2020 (MATCH_LANGSUNG). This catch-all design code remains stable. The 2025 update clarifies that more specific design codes (74191 for interior, 74193 for film/TV, 74194 for games) should be used when applicable, leaving 74199 for truly miscellaneous design work.",
    baliContext:
      "**🎨 Specialized Design in Bali (Creative Ecosystem)**\\n- Bali attracts international designers across disciplines: fashion designers creating resort wear and sustainable fashion, jewelry designers working with local silversmiths, graphic designers serving Bali's hospitality and F&B sectors\\n- **Fashion design:** Bali has a thriving sustainable fashion scene (brands like Magali Pascal, Spell & The Gypsy Collective have Bali connections); designers create resort wear, swimwear, and bohemian fashion\\n- **Jewelry design:** Bali is a global center for silver jewelry; international designers collaborate with Balinese artisans in Celuk village to produce custom jewelry lines\\n- **Packaging design:** Bali's organic food, cosmetics, and wellness brands need packaging design that reflects eco-friendly and artisanal positioning\\n\\n---\\n\\n**💡 PMA Opportunities in This Sector**\\n- **Fashion design + local production:** A PMA design firm that designs fashion collections and coordinates production with Bali's garment workshops and textile suppliers\\n- **Jewelry design + artisan collaboration:** Designing jewelry collections and working with Bali's master silversmiths to produce high-end pieces for international markets\\n- **Brand design for Bali hospitality:** Designing visual identities, packaging, and collateral for Bali's hotels, restaurants, and wellness brands\\n\\n---\\n\\n**⚠ Practical Considerations**\\n- **74199 is a catch-all:** Use more specific codes if they apply. Interior design = 74191, industrial product design = 74103, web/app design = 62010. Only use 74199 if your design work truly doesn't fit elsewhere\\n- **Scale limitation:** PP 28/2025 data only covers Mikro and Kecil scales. If you're operating at Menengah or Besar scale, expect to navigate case-by-case with DPMPTSP\\n- **Design vs. production:** 74199 is DESIGN work. If you also manufacture the products you design (fashion, jewelry, packaging), you need manufacturing codes as well (e.g., 14111 for garment manufacturing, 32111 for jewelry manufacturing)\\n- **Intellectual property:** Design work generates IP. Ensure your contracts clearly define IP ownership and usage rights, especially when collaborating with local artisans",
    youllAlsoNeed:
      "- **14111** — Garment manufacturing — if you also produce the fashion you design\\n- **32111** — Jewelry manufacturing — if you also manufacture the jewelry you design\\n- **74201** — Photography services — if you provide product photography for your designs\\n- **47919** — Retail via internet — if you sell your designed products online\\n- **82990** — Other business support services — if you provide design consulting and project management",
    zantaraOpener:
      "Specialized design business in Bali — fashion, jewelry, packaging, or other creative design? 74199 is the catch-all code. It's Low risk, auto-issued, but only Mikro/Kecil scales are in PP 28/2025 data. Let me explain the setup and when to use more specific codes instead.",
  },

  "74194": {
    whatItMeans:
      "Design services for video games and digital interactive content — game mechanics design, level design, character design, UI/UX design for games, narrative design, game balancing, and interactive experience design. This is DESIGN work (creating the game concept and specifications), not programming or publishing. If you also code the game, that's 62199 (software development). If you publish and distribute the game, that's 59201 (software publishing).",
    whatYouNeed:
      `**BPS_ONLY code — no PP 28/2025 structured licensing data available.**\\n\\n**Minimum requirements:**\\n1. **PT PMA incorporation** — notary deed, AHU registration; minimum IDR 10B stated capital (~3–5 weeks)\\n2. **NIB via OSS** — register on oss.go.id, select 74194; auto-issued (1–3 days)\\n3. **Monitor OSS for updates** — as PP 28/2025 implementation progresses, specific requirements may be added for this code\\n\\n**Additional considerations for game content:**\\n- **Age rating classification:** Games distributed in Indonesia may require age rating classification (similar to PEGI/ESRB) if targeting Indonesian users; monitor Kemenkominfo regulations\\n- **Content guidelines:** Games with Indonesian users must comply with Indonesian content regulations (no gambling mechanics that constitute judi, no SARA content, etc.)\\n\\n**Typical total timeline:** 1–2 months from PT PMA to first project (NIB is instant; timeline driven by team setup and client acquisition).\\n**Minimum PT PMA capital:** IDR 10 billion stated capital (Rp 2.5B paid-up).\\n\\n**Authority:** To be determined as OSS updates.\\n**PMA:** Fully open (Terbuka) — 100% foreign ownership.`,
    whatChanged:
      "Brand new code in KBLI 2025 — no direct predecessor in KBLI 2020. Game content design was previously classified under general design services (74199) or software development (62010). This dedicated code recognizes game design as a distinct professional discipline separate from programming.",
    baliContext:
      "**🎮 Game Development in Bali (Nascent but Growing)**\\n- Bali's game development scene is small but emerging: mostly indie developers, mobile game studios, and remote workers serving international game companies\\n- **Digital nomad game designers:** Bali attracts international game designers who work remotely for overseas studios while living in Canggu, Ubud, or Sanur\\n- **Indonesia's game market:** Indonesia is Southeast Asia's largest gaming market by users; mobile gaming dominates (Mobile Legends, PUBG Mobile, Free Fire are massive)\\n\\n---\\n\\n**💡 PMA Opportunities in This Sector**\\n- **Mobile game design for Indonesian market:** Designing mobile games specifically for Indonesian players (local cultural references, Bahasa Indonesia localization, payment methods suited to Indonesian users)\\n- **Game design services for international studios:** A Bali-based PMA providing game design services (level design, UX design, game balancing) to overseas game studios — remote work model with Bali lifestyle\\n- **VR/AR experience design:** Designing VR/AR experiences for Bali's tourism and hospitality sector (virtual tours, immersive cultural experiences, training simulations)\\n\\n---\\n\\n**⚠ Critical Distinction: Design vs. Programming**\\n- **74194 = game content design:** You design the game (mechanics, levels, characters, UX). You create design documents, wireframes, and prototypes\\n- **62199 = game programming/backend:** You code the game engine, implement the mechanics, and build the technical infrastructure\\n- **Full game studio needs both:** A complete game development studio typically needs 74194 (design) + 62199 (programming) + 59201 (publishing, if you also publish the game)\\n- **New code = regulatory uncertainty:** 74194 is brand new in KBLI 2025. Expect OSS to refine requirements as the game industry matures in Indonesia",
    youllAlsoNeed:
      "- **62199** — Other software development — if you also program the game, not just design it\\n- **59201** — Software publishing — if you publish and distribute the game\\n- **74201** — Photography and visual services — if you create game art and visual assets\\n- **73200** — Advertising services — if you provide user acquisition and marketing for games\\n- **63110** — Data processing and hosting — if you operate game servers and backend infrastructure",
    zantaraOpener:
      "Game content design business in Bali? 74194 is brand new in KBLI 2025 — first dedicated game design code. It's BPS_ONLY, so NIB only for now. The key distinction: this is design work, not programming. Full game studio needs 74194 + 62199. Let me explain the setup.",
  },
'''
    
    # Insert new codes before the closing brace
    content = content[:insertion_point] + new_codes + content[insertion_point:]
    
    # Write back
    with open('/Users/nuzantara/Desktop/kbli-navigator-rebuild/lib/kbli-gold-content.ts', 'w') as f:
        f.write(content)
    
    print("Successfully added 6 new KBLI codes")
else:
    print("Could not find insertion point")
