/** Canonical nationality → flag emoji map. Single source of truth for the entire CRM. */
export const NATIONALITY_FLAGS: Record<string, string> = {
  Italian: "🇮🇹",
  Italy: "🇮🇹",
  Russian: "🇷🇺",
  Russia: "🇷🇺",
  Ukrainian: "🇺🇦",
  Ukraine: "🇺🇦",
  American: "🇺🇸",
  USA: "🇺🇸",
  "United States": "🇺🇸",
  British: "🇬🇧",
  UK: "🇬🇧",
  "United Kingdom": "🇬🇧",
  Australian: "🇦🇺",
  Australia: "🇦🇺",
  German: "🇩🇪",
  Germany: "🇩🇪",
  French: "🇫🇷",
  France: "🇫🇷",
  Spanish: "🇪🇸",
  Spain: "🇪🇸",
  Dutch: "🇳🇱",
  Netherlands: "🇳🇱",
  Indonesian: "🇮🇩",
  Indonesia: "🇮🇩",
  Chinese: "🇨🇳",
  China: "🇨🇳",
  Japanese: "🇯🇵",
  Japan: "🇯🇵",
  Korean: "🇰🇷",
  Korea: "🇰🇷",
  "South Korea": "🇰🇷",
  "South Korean": "🇰🇷",
  Indian: "🇮🇳",
  India: "🇮🇳",
  Brazilian: "🇧🇷",
  Brazil: "🇧🇷",
  Canadian: "🇨🇦",
  Canada: "🇨🇦",
  Mexican: "🇲🇽",
  Mexico: "🇲🇽",
  Argentinian: "🇦🇷",
  Argentine: "🇦🇷",
  Argentina: "🇦🇷",
  "South African": "🇿🇦",
  "South Africa": "🇿🇦",
  "New Zealander": "🇳🇿",
  "New Zealand": "🇳🇿",
  Irish: "🇮🇪",
  Ireland: "🇮🇪",
  Portuguese: "🇵🇹",
  Portugal: "🇵🇹",
  Polish: "🇵🇱",
  Poland: "🇵🇱",
  Turkish: "🇹🇷",
  Turkey: "🇹🇷",
  Thai: "🇹🇭",
  Thailand: "🇹🇭",
  THA: "🇹🇭",
  Vietnamese: "🇻🇳",
  Vietnam: "🇻🇳",
  Filipino: "🇵🇭",
  Philippines: "🇵🇭",
  Malaysian: "🇲🇾",
  Malaysia: "🇲🇾",
  Singaporean: "🇸🇬",
  Singapore: "🇸🇬",
  Hellenic: "🇬🇷",
  Greece: "🇬🇷",
  "British Citizen": "🇬🇧",
  Española: "🇪🇸",
  Française: "🇫🇷",
  Emirati: "🇦🇪",
  "United Arab Emirates": "🇦🇪",
  Colombian: "🇨🇴",
  Colombia: "🇨🇴",
  Venezuelan: "🇻🇪",
  Venezuela: "🇻🇪",
  Belgian: "🇧🇪",
  Belgium: "🇧🇪",
  Austrian: "🇦🇹",
  Austria: "🇦🇹",
  Czech: "🇨🇿",
  Romanian: "🇷🇴",
  Romania: "🇷🇴",
  Hungarian: "🇭🇺",
  Hungary: "🇭🇺",
  Croatian: "🇭🇷",
  Croatia: "🇭🇷",
  Serbian: "🇷🇸",
  Serbia: "🇷🇸",
  Bulgarian: "🇧🇬",
  Bulgaria: "🇧🇬",
  Taiwanese: "🇹🇼",
  Taiwan: "🇹🇼",
  Lebanese: "🇱🇧",
  Lebanon: "🇱🇧",
  Israeli: "🇮🇱",
  Israel: "🇮🇱",
  Swiss: "🇨🇭",
  Switzerland: "🇨🇭",
  Swedish: "🇸🇪",
  Sweden: "🇸🇪",
  Norwegian: "🇳🇴",
  Norway: "🇳🇴",
  Danish: "🇩🇰",
  Denmark: "🇩🇰",
  Finnish: "🇫🇮",
  Finland: "🇫🇮",
};

/** Case-insensitive flag lookup with title-case fallback. */
export function getCountryFlag(
  nationality: string | undefined | null,
): string | null {
  if (!nationality) return null;
  // Direct match
  if (NATIONALITY_FLAGS[nationality]) return NATIONALITY_FLAGS[nationality];
  // Title Case attempt
  const titleCase =
    nationality.charAt(0).toUpperCase() + nationality.slice(1).toLowerCase();
  if (NATIONALITY_FLAGS[titleCase]) return NATIONALITY_FLAGS[titleCase];
  // Case-insensitive scan
  const lower = nationality.toLowerCase();
  for (const [key, flag] of Object.entries(NATIONALITY_FLAGS)) {
    if (key.toLowerCase() === lower) return flag;
  }
  return null;
}
