"""
Bridge router — Pro<->Fly bidirectional bridge.

3 endpoints:
- GET  /api/bridge/events           — Pro pulls outbox events
- POST /api/bridge/ingest/article   — Pro pushes a published article
- POST /api/bridge/ingest/enrichment — Pro pushes a KB enrichment

Auth: X-Bridge-Auth header must match BRIDGE_API_KEY env var.

Reference: docs/superpowers/specs/2026-04-14-organism-nervous-system-design.md §4
"""
from __future__ import annotations

import hmac
import logging
import os
from typing import Any

import asyncpg
from fastapi import APIRouter, Depends, Header, HTTPException, Query
from pydantic import BaseModel, Field

from backend.app.deps.database import get_database_pool
from backend.services.bridge.outbox import fetch_outbox_events

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/bridge", tags=["bridge"])


def _check_auth(x_bridge_auth: str | None) -> None:
    """Raise 401 if header doesn't match BRIDGE_API_KEY; 503 if key not configured."""
    expected = os.getenv("BRIDGE_API_KEY", "")
    if not expected:
        logger.error("BRIDGE_API_KEY not set in environment")
        raise HTTPException(status_code=503, detail="Bridge auth not configured")
    if not x_bridge_auth or not hmac.compare_digest(x_bridge_auth, expected):
        raise HTTPException(status_code=401, detail="Invalid bridge credentials")


# ── GET /api/bridge/events ──────────────────────────────────────────────


class EventsResponse(BaseModel):
    events: list[dict[str, Any]]
    last_id: int


@router.get("/events", response_model=EventsResponse)
async def get_events(
    after_id: int = Query(0, ge=0, description="Return events with id > after_id"),
    limit: int = Query(50, ge=1, le=500, description="Max events per request"),
    db_pool: asyncpg.Pool = Depends(get_database_pool),
    x_bridge_auth: str | None = Header(default=None, alias="X-Bridge-Auth"),
) -> EventsResponse:
    """Pro polls this endpoint to pull queued events from the outbox."""
    _check_auth(x_bridge_auth)

    async with db_pool.acquire() as conn:
        events = await fetch_outbox_events(conn, after_id=after_id, limit=limit)

    last_id = events[-1]["id"] if events else after_id
    return EventsResponse(events=events, last_id=last_id)


# ── POST /api/bridge/ingest/article ─────────────────────────────────────


class ArticleIngestRequest(BaseModel):
    article_id: str = Field(..., description="UUID generated by Intel Scraper")
    title: str
    body_mdx: str
    topic: str = ""
    metadata: dict[str, Any] = Field(default_factory=dict)


class ArticleIngestResponse(BaseModel):
    article_id: str
    status: str  # "published" | "queued"


@router.post("/ingest/article", response_model=ArticleIngestResponse)
async def ingest_article(
    body: ArticleIngestRequest,
    x_bridge_auth: str | None = Header(default=None, alias="X-Bridge-Auth"),
) -> ArticleIngestResponse:
    """Pro pushes a published article. Currently logs and queues — full
    CMS integration deferred to Phase 1.5 (post-MVP).
    """
    _check_auth(x_bridge_auth)
    logger.info(
        "Bridge ingest article: id=%s title=%s len=%d",
        body.article_id,
        body.title[:80],
        len(body.body_mdx),
    )
    return ArticleIngestResponse(article_id=body.article_id, status="queued")


# ── POST /api/bridge/ingest/enrichment ──────────────────────────────────


class EnrichmentIngestRequest(BaseModel):
    kb_entry_id: str
    content: str
    source: str
    metadata: dict[str, Any] = Field(default_factory=dict)


class EnrichmentIngestResponse(BaseModel):
    kb_entry_id: str
    status: str  # "indexed" | "queued"


@router.post("/ingest/enrichment", response_model=EnrichmentIngestResponse)
async def ingest_enrichment(
    body: EnrichmentIngestRequest,
    x_bridge_auth: str | None = Header(default=None, alias="X-Bridge-Auth"),
) -> EnrichmentIngestResponse:
    """Pro pushes a KB enrichment for the RAG. Currently queued — full
    Qdrant write deferred to Phase 2 (RAG enrichment agent).
    """
    _check_auth(x_bridge_auth)
    logger.info(
        "Bridge ingest enrichment: id=%s source=%s len=%d",
        body.kb_entry_id,
        body.source,
        len(body.content),
    )
    return EnrichmentIngestResponse(kb_entry_id=body.kb_entry_id, status="queued")
