"""
Bridge router — Pro<->Fly bidirectional bridge.

4 endpoints:
- GET  /api/bridge/events           — Pro pulls outbox events
- POST /api/bridge/ingest/article   — Pro pushes a published article
- POST /api/bridge/ingest/enrichment — Pro pushes a KB enrichment
- GET  /api/bridge/skills           — Pro pulls cell:skills Redis stream (TICKET G.1)

Auth:
- X-Bridge-Auth header must match BRIDGE_API_KEY env var (events + ingest).
- X-Bridge-Skills-Auth header must match BRIDGE_SKILLS_API_KEY env var
  (skills). Dedicated key per TICKET G CORR-G3 — isolates HGT skill payloads
  from generic bridge auth blast radius.

References:
- docs/superpowers/specs/2026-04-14-organism-nervous-system-design.md §4
- research/symbiosis/2026-05-13-ticket-G-narrow-spec.md (skills endpoint)
"""

from __future__ import annotations

import hmac
import json
import logging
import os
from typing import Any

import asyncpg
from fastapi import APIRouter, Depends, Header, HTTPException, Query, Request
from pydantic import BaseModel, Field

from backend.app.deps.database import get_database_pool
from backend.services.bridge.outbox import fetch_outbox_events
from backend.services.events import outbox as events_outbox

_WA_MEDIA_PENDING_CHANNEL = "whatsapp_media_pending"

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/bridge", tags=["bridge"])


def _check_auth(x_bridge_auth: str | None) -> None:
    """Raise 401 if header doesn't match BRIDGE_API_KEY; 503 if key not configured."""
    expected = os.getenv("BRIDGE_API_KEY", "")
    if not expected:
        logger.error("BRIDGE_API_KEY not set in environment")
        raise HTTPException(status_code=503, detail="Bridge auth not configured")
    if not x_bridge_auth or not hmac.compare_digest(x_bridge_auth, expected):
        raise HTTPException(status_code=401, detail="Invalid bridge credentials")


def _check_skills_auth(x_bridge_skills_auth: str | None) -> None:
    """Dedicated auth for /api/bridge/skills endpoint (TICKET G CORR-G3).

    Separated from BRIDGE_API_KEY to isolate the blast radius of skill-stream
    credentials (HGT payloads may carry CRM-derived structural metadata).
    """
    expected = os.getenv("BRIDGE_SKILLS_API_KEY", "")
    if not expected:
        logger.error("BRIDGE_SKILLS_API_KEY not set in environment")
        raise HTTPException(status_code=503, detail="Bridge skills auth not configured")
    if not x_bridge_skills_auth or not hmac.compare_digest(x_bridge_skills_auth, expected):
        raise HTTPException(status_code=401, detail="Invalid bridge skills credentials")


def _stream_id_lt(a: str, b: str) -> bool:
    """Return True if Redis stream ID a < b. Format: 'ms-seq'."""
    a_ms, _, a_seq = a.partition("-")
    b_ms, _, b_seq = b.partition("-")
    try:
        a_ms_i = int(a_ms) if a_ms else 0
        b_ms_i = int(b_ms) if b_ms else 0
    except ValueError:
        return False
    if a_ms_i != b_ms_i:
        return a_ms_i < b_ms_i
    try:
        return int(a_seq or 0) < int(b_seq or 0)
    except ValueError:
        return False


# ── GET /api/bridge/events ──────────────────────────────────────────────


class EventsResponse(BaseModel):
    events: list[dict[str, Any]]
    last_id: int


@router.get("/events", response_model=EventsResponse)
async def get_events(
    after_id: int = Query(0, ge=0, description="Return events with id > after_id"),
    limit: int = Query(50, ge=1, le=500, description="Max events per request"),
    db_pool: asyncpg.Pool = Depends(get_database_pool),
    x_bridge_auth: str | None = Header(default=None, alias="X-Bridge-Auth"),
) -> EventsResponse:
    """Pro polls this endpoint to pull queued events from the outbox."""
    _check_auth(x_bridge_auth)

    async with db_pool.acquire() as conn:
        events = await fetch_outbox_events(conn, after_id=after_id, limit=limit)

    last_id = events[-1]["id"] if events else after_id
    return EventsResponse(events=events, last_id=last_id)


# ── POST /api/bridge/ingest/article ─────────────────────────────────────


class ArticleIngestRequest(BaseModel):
    article_id: str = Field(..., description="UUID generated by Intel Scraper")
    title: str
    body_mdx: str
    topic: str = ""
    metadata: dict[str, Any] = Field(default_factory=dict)


class ArticleIngestResponse(BaseModel):
    article_id: str
    status: str  # "published" | "queued"


@router.post("/ingest/article", response_model=ArticleIngestResponse)
async def ingest_article(
    body: ArticleIngestRequest,
    x_bridge_auth: str | None = Header(default=None, alias="X-Bridge-Auth"),
) -> ArticleIngestResponse:
    """Pro pushes a published article. Currently logs and queues — full
    CMS integration deferred to Phase 1.5 (post-MVP).
    """
    _check_auth(x_bridge_auth)
    logger.info(
        "Bridge ingest article: id=%s title=%s len=%d",
        body.article_id,
        body.title[:80],
        len(body.body_mdx),
    )
    return ArticleIngestResponse(article_id=body.article_id, status="queued")


# ── POST /api/bridge/ingest/enrichment ──────────────────────────────────


class EnrichmentIngestRequest(BaseModel):
    kb_entry_id: str
    content: str
    source: str
    metadata: dict[str, Any] = Field(default_factory=dict)


class EnrichmentIngestResponse(BaseModel):
    kb_entry_id: str
    status: str  # "indexed" | "queued"


@router.post("/ingest/enrichment", response_model=EnrichmentIngestResponse)
async def ingest_enrichment(
    body: EnrichmentIngestRequest,
    x_bridge_auth: str | None = Header(default=None, alias="X-Bridge-Auth"),
) -> EnrichmentIngestResponse:
    """Pro pushes a KB enrichment for the RAG. Currently queued — full
    Qdrant write deferred to Phase 2 (RAG enrichment agent).
    """
    _check_auth(x_bridge_auth)
    logger.info(
        "Bridge ingest enrichment: id=%s source=%s len=%d",
        body.kb_entry_id,
        body.source,
        len(body.content),
    )
    return EnrichmentIngestResponse(kb_entry_id=body.kb_entry_id, status="queued")


# ── GET /api/bridge/skills (TICKET G.1) ──────────────────────────────────


class SkillsResponse(BaseModel):
    events: list[dict[str, Any]]
    last_stream_id: str
    events_orphaned: bool = False
    stream_lowest_id: str | None = None


async def _get_skills_redis_client(request: Request) -> Any:
    """Return an async Redis client for the cell:skills stream.

    Tries `app.state.redis_manager.get_async_client()` first (rag process group,
    full init). Falls back to a fresh `redis.asyncio.from_url(REDIS_URL)` client
    on the api process group (light init, no RedisManager singleton — see
    `service_initializer.initialize_services_light` which omits the manager).

    Returns the client or raises HTTPException(503) on failure.

    Empirical context (2026-05-13 03:58 WITA, post-deploy of PR #647):
    Fly api machine `7847d95ce257d8` logged "redis_manager unavailable" for
    every /api/bridge/skills request — light init doesn't wire the manager.
    This helper restores Redis access without changing the light init contract.
    """
    redis_manager = getattr(request.app.state, "redis_manager", None)
    if redis_manager is not None and getattr(redis_manager, "available", False):
        client = redis_manager.get_async_client()
        if client is not None:
            return client
    # Light-init fallback: build ad-hoc async client from REDIS_URL env var.
    redis_url = os.getenv("REDIS_URL", "")
    if not redis_url:
        logger.warning("Bridge skills: no redis_manager AND REDIS_URL unset")
        raise HTTPException(status_code=503, detail="Redis unavailable")
    try:
        import redis.asyncio as aioredis

        client = aioredis.from_url(redis_url, decode_responses=False)
        return client
    except Exception as e:
        logger.exception("Bridge skills: ad-hoc redis client init failed")
        raise HTTPException(status_code=503, detail=f"Redis init failed: {e}")


@router.get("/skills", response_model=SkillsResponse)
async def get_skills(
    request: Request,
    after_id: str = Query("0-0", description="XREAD start ID (default 0-0 for full read)"),
    count: int = Query(100, ge=1, le=500, description="Max events per request"),
    x_bridge_skills_auth: str | None = Header(default=None, alias="X-Bridge-Skills-Auth"),
) -> SkillsResponse:
    """Pro polls this endpoint to pull cell:skills Redis stream entries from Fly Upstash.

    Per TICKET G spec v2 (research/symbiosis/2026-05-13-ticket-G-narrow-spec.md):
    - CORR-G1 (fixed 2026-05-13 post-deploy): redis client via
      `_get_skills_redis_client(request)` which prefers app.state.redis_manager
      but falls back to ad-hoc REDIS_URL client on light-init api process.
    - CORR-G3: dedicated BRIDGE_SKILLS_API_KEY
    - CORR-G4: XINFO STREAM gap detection — events_orphaned=true if
      after_id < stream lowest entry ID (Pro should reset last_id to "$")
    """
    _check_skills_auth(x_bridge_skills_auth)

    client = await _get_skills_redis_client(request)
    # Track ad-hoc client so we can close it cleanly at the end
    is_adhoc = getattr(request.app.state, "redis_manager", None) is None or not getattr(
        getattr(request.app.state, "redis_manager", None), "available", False
    )

    events_orphaned = False
    stream_lowest_id: str | None = None
    if after_id not in ("0-0", "$"):
        try:
            info = await client.xinfo_stream("cell:skills")
            first_entry = info.get(b"first-entry") or info.get("first-entry")
            if first_entry:
                raw = first_entry[0]
                stream_lowest_id = raw.decode() if isinstance(raw, bytes) else raw
                if _stream_id_lt(after_id, stream_lowest_id):
                    events_orphaned = True
                    logger.warning(
                        "Bridge skills: gap detected — after_id=%s < stream_lowest=%s",
                        after_id,
                        stream_lowest_id,
                    )
        except Exception as e:
            logger.debug("XINFO STREAM cell:skills failed (non-fatal): %s", e)

    try:
        result = await client.xread({"cell:skills": after_id}, count=count)
    except Exception as e:
        if is_adhoc:
            try:
                await client.aclose()
            except Exception:
                pass
        logger.exception("Bridge skills: XREAD failed")
        raise HTTPException(status_code=503, detail=f"Stream read failed: {e}")

    events: list[dict[str, Any]] = []
    last_id = after_id
    if result:
        for _stream_name, entries in result:
            for entry_id, fields in entries:
                last_id = entry_id.decode() if isinstance(entry_id, bytes) else entry_id
                decoded_fields = {
                    (k.decode() if isinstance(k, bytes) else k): (
                        v.decode() if isinstance(v, bytes) else v
                    )
                    for k, v in fields.items()
                }
                events.append({"id": last_id, "fields": decoded_fields})

    if is_adhoc:
        try:
            await client.aclose()
        except Exception:
            pass

    logger.info(
        "Bridge skills: returned %d events (after_id=%s last_id=%s orphaned=%s adhoc=%s)",
        len(events),
        after_id,
        last_id,
        events_orphaned,
        is_adhoc,
    )
    return SkillsResponse(
        events=events,
        last_stream_id=last_id,
        events_orphaned=events_orphaned,
        stream_lowest_id=stream_lowest_id,
    )


# ── WhatsApp media PULL hand-off (Anello 1, Law 2) ───────────────────────
#
# The Fly webhook publishes metadata-only rows to events_outbox
# (channel whatsapp_media_pending) — see whatsapp_chat._ingest_meta_inbox_media.
# The sovereign Pro worker pulls those rows here, downloads the media from Meta
# ITSELF (token held only on the Pro), stores the blob locally, then acks. NO
# PII bytes ever cross these endpoints — only media_id + provenance.


class WaMediaPendingItem(BaseModel):
    outbox_id: int
    media_id: str
    mime_type: str | None = None
    message_type: str | None = None
    filename: str | None = None
    declared_sha256: str | None = None
    wa_message_id: str | None = None
    from_phone: str | None = None
    phone_number_id: str | None = None
    sender_name: str | None = None
    created_at: str


class WaMediaPendingResponse(BaseModel):
    items: list[WaMediaPendingItem]
    last_id: int


def _unwrap_payload(raw: Any, row_id: int) -> dict[str, Any]:
    """events_outbox.payload is jsonb (dict via codec) — defensive str unwrap.

    Mirrors the CICATRIX 2026-05-21 double-encoding guard in
    services/bridge/outbox.fetch_outbox_events: a legacy/stale code path could
    leave a string in the column; never let that crash the pull.
    """
    if isinstance(raw, dict):
        return raw
    if isinstance(raw, str):
        try:
            parsed = json.loads(raw)
            return parsed if isinstance(parsed, dict) else {}
        except (TypeError, ValueError):
            logger.warning("wa-media pending row id=%s malformed payload", row_id)
    return {}


@router.get("/wa-media/pending", response_model=WaMediaPendingResponse)
async def get_wa_media_pending(
    since: int = Query(0, ge=0, description="Return rows with id > since"),
    limit: int = Query(50, ge=1, le=200, description="Max rows per request"),
    db_pool: asyncpg.Pool = Depends(get_database_pool),
    x_bridge_auth: str | None = Header(default=None, alias="X-Bridge-Auth"),
) -> WaMediaPendingResponse:
    """Pro worker pulls unconsumed whatsapp_media_pending rows (metadata only)."""
    _check_auth(x_bridge_auth)

    async with db_pool.acquire() as conn:
        rows = await conn.fetch(
            """
            SELECT id, payload, created_at
              FROM events_outbox
             WHERE channel = $1
               AND consumed_at IS NULL
               AND id > $2
             ORDER BY id ASC
             LIMIT $3
            """,
            _WA_MEDIA_PENDING_CHANNEL,
            int(since),
            int(limit),
        )

    items: list[WaMediaPendingItem] = []
    for r in rows:
        p = _unwrap_payload(r["payload"], int(r["id"]))
        items.append(
            WaMediaPendingItem(
                outbox_id=int(r["id"]),
                media_id=str(p.get("media_id", "")),
                mime_type=p.get("mime_type"),
                message_type=p.get("message_type"),
                filename=p.get("filename"),
                declared_sha256=p.get("declared_sha256"),
                wa_message_id=p.get("wa_message_id"),
                from_phone=p.get("from_phone"),
                phone_number_id=p.get("phone_number_id"),
                sender_name=p.get("sender_name"),
                created_at=r["created_at"].isoformat(),
            )
        )

    last_id = items[-1].outbox_id if items else int(since)
    return WaMediaPendingResponse(items=items, last_id=last_id)


class WaMediaAckRequest(BaseModel):
    outbox_ids: list[int] = Field(..., description="outbox row ids the Pro stored locally")


class WaMediaAckResponse(BaseModel):
    acked: list[int]


@router.post("/wa-media/ack", response_model=WaMediaAckResponse)
async def ack_wa_media(
    body: WaMediaAckRequest,
    db_pool: asyncpg.Pool = Depends(get_database_pool),
    x_bridge_auth: str | None = Header(default=None, alias="X-Bridge-Auth"),
) -> WaMediaAckResponse:
    """Pro worker acks rows it has downloaded + enqueued locally. Idempotent."""
    _check_auth(x_bridge_auth)

    acked: list[int] = []
    async with db_pool.acquire() as conn:
        for oid in body.outbox_ids:
            ok = await events_outbox.acknowledge(
                conn, int(oid), consumer_id="wa_media_pull_worker"
            )
            if ok:
                acked.append(int(oid))
    return WaMediaAckResponse(acked=acked)
