"""Proposal dataclass for the HGT coordinator audit log.

Plain dataclass (no Pydantic) for parity with the rest of cell-core, which
keeps cell definitions as plain dicts (see ``admission_test.py`` doc).
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Literal

# Recommended action enum — kept as a typing.Literal so callers don't need
# to import an Enum class. The audit log persists this as a TEXT column.
RecommendedAction = Literal["propose", "defer", "reject"]


@dataclass(frozen=True)
class Proposal:
    """A coordinator-emitted candidate for cross-cell skill transfer.

    Attributes:
        skill_name: Stable identifier of the skill (matches the ``skill_id``
            field on the Redis Stream entry, before the ``hgt_`` prefix that
            consumers add to inherited variants).
        source_cells: Cells that have published this skill above threshold.
        target_cell_candidates: Cells in matching domains that have NOT
            yet adopted the skill (no ``hgt_<skill_name>`` in their genome).
        domain: Canonical domain (legal, fiscal, ops, etc.) — propagated
            from the publish event so consumers can filter.
        total_uses: Aggregated count of HGT publish events in window.
        avg_confidence: Mean confidence across all observed publishes.
        std_confidence: Standard deviation of confidence (signal of noise).
        confidence: Coordinator's own composite signal — usually
            ``avg_confidence`` clamped to [0, 1].
        transfer_rationale: One-sentence human-readable why-this-now,
            generated by the Python observer (the OpenClaw LLM may
            override this when writing back via ``mark_resolved``).
        recommended_action: ``propose`` (above threshold), ``defer``
            (close to threshold, keep observing), ``reject`` (above
            threshold but flagged — e.g. low-distinct-cells).
        observation_window_days: Window used to aggregate the stats.
        observed_at: UTC timestamp at coordinator run.
        audit_log_id: Filled after ``record_proposal`` writes the row.
    """

    skill_name: str
    source_cells: tuple[str, ...]
    target_cell_candidates: tuple[str, ...]
    domain: str
    total_uses: int
    avg_confidence: float
    std_confidence: float
    confidence: float
    transfer_rationale: str
    recommended_action: RecommendedAction
    observation_window_days: int
    observed_at: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    audit_log_id: int | None = None

    def to_dict(self) -> dict[str, object]:
        """Serialisable form for OpenClaw CLI stdout / SQLite JSON columns."""
        return {
            "skill_name": self.skill_name,
            "source_cells": list(self.source_cells),
            "target_cell_candidates": list(self.target_cell_candidates),
            "domain": self.domain,
            "total_uses": self.total_uses,
            "avg_confidence": self.avg_confidence,
            "std_confidence": self.std_confidence,
            "confidence": self.confidence,
            "transfer_rationale": self.transfer_rationale,
            "recommended_action": self.recommended_action,
            "observation_window_days": self.observation_window_days,
            "observed_at": self.observed_at.isoformat(),
            "audit_log_id": self.audit_log_id,
        }
