#!/usr/bin/env python3
"""Census which repo-root ``scripts/`` files are reachable from the trees
tests.yml's six heavy jobs execute, so ``change_map.py`` can route a
``scripts/`` path by COUPLING instead of by directory guess (cicatrix
superscar #3, under-match — see the PREFIX_RULES comment this replaces:
~19+ scripts/*.py modules are silently imported by apps/backend-rag/backend/
tests/** via a sys.path shim in that tree's own conftest.py, with no naming
or directory pattern in common).

METHOD. A ref is anything that would import or subprocess-invoke a
repo-root ``scripts/`` file from a file in the six jobs' own trees (or
``tests.yml`` itself): ``scripts.<dotted>`` (import form — package ref,
module ref, or a deeper attribute chain) or a literal ``scripts/<path>.py``
/ ``.sh`` path. A ref only RESOLVES if it names a real repo-root file today
— that alone discards refs naming an app-local ``scripts`` package under an
app subtree (e.g. ``apps/backend-rag/scripts/``, which shadows the same
dotted name once that app's own root is on sys.path): no repo-root file, no
resolution, no special-casing needed. A bare package ref (``scripts.
sentinel_lib``, no attribute) that is not itself a ``.py`` file widens to
every ``.py`` file under that package directory.

Hits under a subtree ``change_map.py`` already routes via ``PREFIX_RULES``
(``scripts/ci/``, the ten fleet_ops directories) are real but moot —
``_domains_for_path`` returns on that match first — so they are excluded
from the generated constant to save PR churn.

USAGE
  python3 scripts/ci/scripts_coupling_census.py            # print counts
  python3 scripts/ci/scripts_coupling_census.py --write     # rewrite the
                                                              marker block
  python3 scripts/ci/scripts_coupling_census.py --check     # exit 1 if stale
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

import change_map as cm  # sibling module; python puts this script's dir on sys.path[0]

REPO_ROOT = Path(__file__).resolve().parents[2]
CHANGE_MAP_PATH = REPO_ROOT / "scripts" / "ci" / "change_map.py"

# The exact corpus the six tests.yml jobs execute code from, plus the
# workflow file itself (a job's own YAML can subprocess-invoke a script).
TREES = [
    "apps/backend-rag",
    "apps/nuzantara-mcp",
    "apps/evaluator",
    "apps/mouth",
    "apps/admin-dashboard",
    "apps/wa-mirror",
    "packages/core",
    ".github/workflows/tests.yml",
]

REF_PATTERN = (
    r"(?<![\w.])scripts\.[A-Za-z0-9_]+(\.[A-Za-z0-9_]+)*"
    r"|(?<![\w/])scripts/[A-Za-z0-9_./-]+\.(py|sh)(?![\w])"
)

# Every scripts/ prefix change_map.py's PREFIX_RULES already routes
# (scripts/ci/ + the ten fleet_ops directories) — a hit under any of them
# is real but moot for SCRIPTS_COUPLING (_domains_for_path returns on that
# earlier match first), so this prunes the generated constant. Read
# straight from PREFIX_RULES rather than duplicated by hand, so it can
# never drift from what actually pre-empts the rule.
PREEMPTED_PREFIXES = tuple(
    prefix for prefix, _ in cm.PREFIX_RULES if prefix.startswith("scripts/")
)

BEGIN_MARKER = (
    "# BEGIN SCRIPTS_COUPLING "
    "(generated by scripts/ci/scripts_coupling_census.py — do not edit)"
)
END_MARKER = "# END SCRIPTS_COUPLING"
MAX_LINE_WIDTH = 400


def _git(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", "-C", str(REPO_ROOT), *args], capture_output=True, text=True, check=False
    )


def _run_git_grep() -> list[str]:
    result = _git("grep", "-h", "-o", "-P", REF_PATTERN, "--", *TREES, ":!**/node_modules/**")
    # Exit 1 = no matches (valid outcome). Anything else means the
    # invocation itself broke — most likely `-P` unsupported by this build.
    if result.returncode not in (0, 1):
        stderr = result.stderr.strip()
        hint = " (this git binary appears to lack PCRE support)" if (
            "perl-regexp" in stderr.lower() or "unsupport" in stderr.lower()
        ) else ""
        print(f"scripts_coupling_census: `git grep -P` failed{hint}: {stderr}", file=sys.stderr)
        sys.exit(2)
    return sorted(set(line for line in result.stdout.splitlines() if line))


def _module_and_sh_sets() -> tuple[set[str], set[str]]:
    modules = set(_git("ls-files", "scripts/*.py", "scripts/**/*.py").stdout.split())
    sh_files = set(_git("ls-files", "scripts/*.sh", "scripts/**/*.sh").stdout.split())
    return modules, sh_files


def _resolve(
    refs: list[str], modules: set[str], sh_files: set[str]
) -> tuple[set[str], list[str]]:
    """Resolve raw refs to real repo-root ``scripts/`` files.

    Returns (coupled_paths, unresolved_refs). ``coupled_paths`` may contain
    more than one path per ref (bare-package widening).
    """

    coupled: set[str] = set()
    unresolved: list[str] = []
    for ref in refs:
        if ref.startswith("scripts/"):
            # Literal path form — resolves only if it names a real file.
            if ref in modules or ref in sh_files:
                coupled.add(ref)
            else:
                unresolved.append(ref)
            continue

        # Dotted import form: scripts.<c1>.<c2>...<cn>. Walk from the
        # longest prefix down — the deepest resolvable file wins, mirroring
        # how Python itself would resolve `from scripts.a.b import c`.
        remainder = ref[len("scripts.") :]
        parts = remainder.split(".")
        resolved = False
        for k in range(len(parts), 0, -1):
            stem = "/".join(parts[:k])
            candidate_file = f"scripts/{stem}.py"
            if candidate_file in modules:
                coupled.add(candidate_file)
                resolved = True
                break
            candidate_dir = f"scripts/{stem}/"
            dir_members = {m for m in modules if m.startswith(candidate_dir)}
            if dir_members:
                coupled.update(dir_members)
                resolved = True
                break
        if not resolved:
            unresolved.append(ref)
    return coupled, unresolved


def _census() -> tuple[set[str], list[str], set[str]]:
    """Returns (all_coupled_paths, unresolved_refs, embedded_paths)."""
    modules, sh_files = _module_and_sh_sets()
    coupled, unresolved = _resolve(_run_git_grep(), modules, sh_files)
    embedded = {p for p in coupled if not p.startswith(PREEMPTED_PREFIXES)}
    return coupled, unresolved, embedded


def _render_block(paths: set[str]) -> str:
    ordered = sorted(paths)
    lines = [BEGIN_MARKER, "SCRIPTS_COUPLING: frozenset[str] = frozenset("]
    if not ordered:
        lines.append("    ()")
    else:
        lines.append("    (")
        current = "        "
        for path in ordered:
            token = f'"{path}", '
            if len(current) + len(token) > MAX_LINE_WIDTH and current.strip():
                lines.append(current.rstrip())
                current = "        "
            current += token
        if current.strip():
            lines.append(current.rstrip())
        lines.append("    )")
    lines.append(")")
    lines.append(END_MARKER)
    return "\n".join(lines) + "\n"


def _existing_block(text: str) -> str | None:
    try:
        start = text.index(BEGIN_MARKER)
        end = text.index(END_MARKER, start) + len(END_MARKER)
    except ValueError:
        return None
    return text[start:end] + "\n"


def _write(embedded: set[str]) -> None:
    text = CHANGE_MAP_PATH.read_text(encoding="utf-8")
    try:
        start = text.index(BEGIN_MARKER)
        end = text.index(END_MARKER, start) + len(END_MARKER)
    except ValueError:
        print(
            f"scripts_coupling_census: no marker block found in {CHANGE_MAP_PATH} "
            "— add it once by hand, then re-run --write.",
            file=sys.stderr,
        )
        sys.exit(2)
    updated = text[:start] + _render_block(embedded).rstrip("\n") + text[end:]
    CHANGE_MAP_PATH.write_text(updated, encoding="utf-8")
    print(f"scripts_coupling_census: wrote {len(embedded)} paths to {CHANGE_MAP_PATH}")


def _check(embedded: set[str]) -> int:
    text = CHANGE_MAP_PATH.read_text(encoding="utf-8")
    existing = _existing_block(text)
    fresh = _render_block(embedded)
    if existing is None:
        print(
            f"scripts_coupling_census: no marker block found in {CHANGE_MAP_PATH} "
            "— run --write.",
            file=sys.stderr,
        )
        return 1
    if existing.strip() == fresh.strip():
        print("scripts_coupling_census: SCRIPTS_COUPLING is up to date.")
        return 0
    existing_paths = {
        line.strip().strip('",')
        for line in existing.splitlines()
        if line.strip().startswith('"')
    }
    fresh_paths = {
        line.strip().strip('",')
        for line in fresh.splitlines()
        if line.strip().startswith('"')
    }
    added = sorted(fresh_paths - existing_paths)
    removed = sorted(existing_paths - fresh_paths)
    print(
        "scripts_coupling_census: SCRIPTS_COUPLING is STALE — run "
        "`python3 scripts/ci/scripts_coupling_census.py --write`.",
        file=sys.stderr,
    )
    for label, paths in (("+ newly coupled", added), ("- no longer coupled", removed)):
        if paths:
            print(f"  {label} ({len(paths)}): {paths[:10]}{' …' if len(paths) > 10 else ''}", file=sys.stderr)
    return 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="rewrite the marker block")
    mode.add_argument("--check", action="store_true", help="exit 1 if the block is stale")
    args = parser.parse_args(argv)

    coupled, unresolved, embedded = _census()

    if args.write:
        _write(embedded)
        return 0
    if args.check:
        return _check(embedded)

    per_dir: dict[str, int] = {}
    for path in coupled:
        key = path.split("/")[1] if path.count("/") >= 2 else "(top-level)"
        per_dir[key] = per_dir.get(key, 0) + 1
    print(
        f"refs_found={len(coupled) + len(set(unresolved))} "
        f"coupled={len(coupled)} unresolved={len(set(unresolved))} "
        f"embedded={len(embedded)} preempted={len(coupled) - len(embedded)}"
    )
    for key, count in sorted(per_dir.items(), key=lambda kv: -kv[1]):
        print(f"  {key}: {count}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
