#!/usr/bin/env python3
"""Census which repo-root ``scripts/`` files are reachable from the trees
tests.yml's six heavy jobs execute, so ``change_map.py`` can route a
``scripts/`` path by COUPLING instead of by directory guess (cicatrix
superscar #3, under-match — see the PREFIX_RULES comment this replaces:
~19+ scripts/*.py modules are silently imported by apps/backend-rag/backend/
tests/** via a sys.path shim in that tree's own conftest.py, with no naming
or directory pattern in common).

METHOD. A ref is anything that would import or subprocess-invoke a
repo-root ``scripts/`` file from a file in the six jobs' own trees (or
``tests.yml`` itself): ``scripts.<dotted>`` (import form — package ref,
module ref, or a deeper attribute chain) or a literal ``scripts/<path>.py``
/ ``.sh`` path. A ref only RESOLVES if it names a real repo-root file today
— that alone discards refs naming an app-local ``scripts`` package under an
app subtree (e.g. ``apps/backend-rag/scripts/``, which shadows the same
dotted name once that app's own root is on sys.path): no repo-root file, no
resolution, no special-casing needed. A bare package ref (``scripts.
sentinel_lib``, no attribute) that is not itself a ``.py`` file widens to
every ``.py`` file under that package directory.

Hits under a subtree ``change_map.py`` already routes via ``PREFIX_RULES``
(``scripts/ci/``, the ten fleet_ops directories) are real but moot —
``_domains_for_path`` returns on that match first — so they are excluded
from the generated constant to save PR churn.

USAGE
  python3 scripts/ci/scripts_coupling_census.py                # print counts
  python3 scripts/ci/scripts_coupling_census.py --write         # rewrite the marker block
  python3 scripts/ci/scripts_coupling_census.py --check         # exit 1 if stale
  python3 scripts/ci/scripts_coupling_census.py --check --warn-only
      # --warn-only: never exit nonzero; print a WARNING verdict instead of
      # STALE. Added 2026-09-05 for a caller that must observe staleness as a
      # fleet-wide data-freshness fact WITHOUT treating it as this specific
      # run's own failure (tests.yml's flat trusted-classifier corpus).
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

import change_map as cm  # sibling module; python puts this script's dir on sys.path[0]

REPO_ROOT = Path(__file__).resolve().parents[2]
CHANGE_MAP_PATH = REPO_ROOT / "scripts" / "ci" / "change_map.py"

# The exact corpus the six tests.yml jobs execute code from, plus the
# workflow file itself (a job's own YAML can subprocess-invoke a script).
TREES = [
    "apps/backend-rag",
    "apps/nuzantara-mcp",
    "apps/evaluator",
    "apps/mouth",
    "apps/admin-dashboard",
    # NOT covered by "apps/admin-dashboard" above — a different tree whose
    # name merely starts with it. Its vitest suite runs inside the REQUIRED
    # `(mouth, true)` leg of frontend-tests (tests.yml, "Run
    # admin-dashboard-local tests"), so code it executes belongs in the
    # census corpus. Held by test_census_trees_cover_every_app_tests_yml_runs.
    "apps/admin-dashboard-local",
    "apps/wa-mirror",
    "packages/core",
    ".github/workflows/tests.yml",
]

REF_PATTERN = (
    r"(?<![\w.])scripts\.[A-Za-z0-9_]+(\.[A-Za-z0-9_]+)*"
    r"|(?<![\w/])scripts/[A-Za-z0-9_./-]+\.(py|sh)(?![\w])"
)

# Every scripts/ prefix change_map.py's PREFIX_RULES already routes
# (scripts/ci/ + the ten fleet_ops directories) — a hit under any of them
# is real but moot for SCRIPTS_COUPLING (_domains_for_path returns on that
# earlier match first), so this prunes the generated constant. Read
# straight from PREFIX_RULES rather than duplicated by hand, so it can
# never drift from what actually pre-empts the rule.
PREEMPTED_PREFIXES = tuple(
    prefix for prefix, _ in cm.PREFIX_RULES if prefix.startswith("scripts/")
)

BEGIN_MARKER = (
    "# BEGIN SCRIPTS_COUPLING "
    "(generated by scripts/ci/scripts_coupling_census.py — do not edit)"
)
END_MARKER = "# END SCRIPTS_COUPLING"
MAX_LINE_WIDTH = 400


def _git(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", "-C", str(REPO_ROOT), *args], capture_output=True, text=True, check=False
    )


def _run_git_grep() -> list[str]:
    result = _git("grep", "-h", "-o", "-P", REF_PATTERN, "--", *TREES, ":!**/node_modules/**")
    # Exit 1 = no matches (valid outcome). Anything else means the
    # invocation itself broke — most likely `-P` unsupported by this build.
    if result.returncode not in (0, 1):
        stderr = result.stderr.strip()
        hint = " (this git binary appears to lack PCRE support)" if (
            "perl-regexp" in stderr.lower() or "unsupport" in stderr.lower()
        ) else ""
        print(f"scripts_coupling_census: `git grep -P` failed{hint}: {stderr}", file=sys.stderr)
        sys.exit(2)
    return sorted(set(line for line in result.stdout.splitlines() if line))


def _module_and_sh_sets() -> tuple[set[str], set[str]]:
    modules = set(_git("ls-files", "scripts/*.py", "scripts/**/*.py").stdout.split())
    sh_files = set(_git("ls-files", "scripts/*.sh", "scripts/**/*.sh").stdout.split())
    return modules, sh_files


def _resolve(
    refs: list[str], modules: set[str], sh_files: set[str]
) -> tuple[set[str], list[str]]:
    """Resolve raw refs to real repo-root ``scripts/`` files.

    Returns (coupled_paths, unresolved_refs). ``coupled_paths`` may contain
    more than one path per ref (bare-package widening).
    """

    coupled: set[str] = set()
    unresolved: list[str] = []
    for ref in refs:
        if ref.startswith("scripts/"):
            # Literal path form — resolves only if it names a real file.
            if ref in modules or ref in sh_files:
                coupled.add(ref)
            else:
                unresolved.append(ref)
            continue

        # Dotted import form: scripts.<c1>.<c2>...<cn>. Walk from the
        # longest prefix down — the deepest resolvable file wins, mirroring
        # how Python itself would resolve `from scripts.a.b import c`.
        remainder = ref[len("scripts.") :]
        parts = remainder.split(".")
        resolved = False
        for k in range(len(parts), 0, -1):
            stem = "/".join(parts[:k])
            candidate_file = f"scripts/{stem}.py"
            if candidate_file in modules:
                coupled.add(candidate_file)
                resolved = True
                break
            candidate_dir = f"scripts/{stem}/"
            dir_members = {m for m in modules if m.startswith(candidate_dir)}
            if dir_members:
                coupled.update(dir_members)
                resolved = True
                break
        if not resolved:
            unresolved.append(ref)
    return coupled, unresolved


def _census() -> tuple[set[str], list[str], set[str]]:
    """Returns (all_coupled_paths, unresolved_refs, embedded_paths)."""
    modules, sh_files = _module_and_sh_sets()
    coupled, unresolved = _resolve(_run_git_grep(), modules, sh_files)
    embedded = {p for p in coupled if not p.startswith(PREEMPTED_PREFIXES)}
    return coupled, unresolved, embedded


def _render_block(paths: set[str]) -> str:
    ordered = sorted(paths)
    lines = [BEGIN_MARKER, "SCRIPTS_COUPLING: frozenset[str] = frozenset("]
    if not ordered:
        lines.append("    ()")
    else:
        lines.append("    (")
        current = "        "
        for path in ordered:
            token = f'"{path}", '
            if len(current) + len(token) > MAX_LINE_WIDTH and current.strip():
                lines.append(current.rstrip())
                current = "        "
            current += token
        if current.strip():
            lines.append(current.rstrip())
        lines.append("    )")
    lines.append(")")
    lines.append(END_MARKER)
    return "\n".join(lines) + "\n"


_QUOTED_TOKEN = re.compile(r'"([^"]+)"')


def _block_paths(block: str) -> set[str]:
    """Every ``scripts/`` path quoted inside a rendered marker block.

    ``_render_block`` PACKS as many paths per line as fit in
    ``MAX_LINE_WIDTH``, so reading one path per line is wrong: it yields a
    single bogus token per line with ``", "`` embedded in it, identical on
    both sides of the comparison. That is what made a one-path delta render
    as ~100 items churning in both directions, and it is why the whole
    diagnostic was unreadable at the moment it was needed.
    """

    return {
        token
        for line in block.splitlines()
        for token in _QUOTED_TOKEN.findall(line)
        if token.startswith("scripts/")
    }


def _existing_block(text: str) -> str | None:
    try:
        start = text.index(BEGIN_MARKER)
        end = text.index(END_MARKER, start) + len(END_MARKER)
    except ValueError:
        return None
    return text[start:end] + "\n"


def _write(embedded: set[str]) -> None:
    text = CHANGE_MAP_PATH.read_text(encoding="utf-8")
    try:
        start = text.index(BEGIN_MARKER)
        end = text.index(END_MARKER, start) + len(END_MARKER)
    except ValueError:
        print(
            f"scripts_coupling_census: no marker block found in {CHANGE_MAP_PATH} "
            "— add it once by hand, then re-run --write.",
            file=sys.stderr,
        )
        sys.exit(2)
    updated = text[:start] + _render_block(embedded).rstrip("\n") + text[end:]
    CHANGE_MAP_PATH.write_text(updated, encoding="utf-8")
    print(f"scripts_coupling_census: wrote {len(embedded)} paths to {CHANGE_MAP_PATH}")


def _check(embedded: set[str], *, warn_only: bool = False) -> int:
    text = CHANGE_MAP_PATH.read_text(encoding="utf-8")
    existing = _existing_block(text)
    fresh = _render_block(embedded)
    ok_exit, stale_exit = 0, (0 if warn_only else 1)
    if existing is None:
        print(
            f"scripts_coupling_census: no marker block found in {CHANGE_MAP_PATH} "
            "— run --write.",
            file=sys.stderr,
        )
        return stale_exit
    if existing.strip() == fresh.strip():
        print("scripts_coupling_census: SCRIPTS_COUPLING is up to date.")
        return ok_exit
    existing_paths = _block_paths(existing)
    fresh_paths = _block_paths(fresh)
    added = sorted(fresh_paths - existing_paths)
    removed = sorted(existing_paths - fresh_paths)
    verdict = "WARNING" if warn_only else "STALE"
    print(
        f"scripts_coupling_census: SCRIPTS_COUPLING is {verdict} — run "
        "`python3 scripts/ci/scripts_coupling_census.py --write`.",
        file=sys.stderr,
    )
    if not added and not removed:
        # The verdict above stays TEXT-based on purpose: the block is a
        # generated artifact and must be byte-identical to what --write
        # emits. But "stale with an identical set" is a different fact from
        # "stale because a path moved", and saying nothing at all here made
        # the two indistinguishable.
        print(
            f"  the coupled SET is identical ({len(fresh_paths)} paths) — only the "
            "line layout of the generated block differs (rewrap at "
            f"MAX_LINE_WIDTH={MAX_LINE_WIDTH}). Run --write.",
            file=sys.stderr,
        )
    for label, paths in (("+ newly coupled", added), ("- no longer coupled", removed)):
        if paths:
            shown = ", ".join(paths[:10])
            more = f" … (+{len(paths) - 10} more)" if len(paths) > 10 else ""
            print(f"  {label} ({len(paths)}): {shown}{more}", file=sys.stderr)
    return stale_exit


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="rewrite the marker block")
    mode.add_argument("--check", action="store_true", help="exit 1 if the block is stale")
    parser.add_argument(
        "--warn-only",
        action="store_true",
        help="with --check: never exit nonzero, print a WARNING verdict instead of STALE",
    )
    args = parser.parse_args(argv)
    if args.warn_only and not args.check:
        parser.error("--warn-only requires --check")

    coupled, unresolved, embedded = _census()

    if args.write:
        _write(embedded)
        return 0
    if args.check:
        return _check(embedded, warn_only=args.warn_only)

    per_dir: dict[str, int] = {}
    for path in coupled:
        key = path.split("/")[1] if path.count("/") >= 2 else "(top-level)"
        per_dir[key] = per_dir.get(key, 0) + 1
    print(
        f"refs_found={len(coupled) + len(set(unresolved))} "
        f"coupled={len(coupled)} unresolved={len(set(unresolved))} "
        f"embedded={len(embedded)} preempted={len(coupled) - len(embedded)}"
    )
    for key, count in sorted(per_dir.items(), key=lambda kv: -kv[1]):
        print(f"  {key}: {count}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
