from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from unittest.mock import patch


SCRIPTS_DIR = Path(__file__).parent.parent.parent / "scripts"
sys.path.insert(0, str(SCRIPTS_DIR))

import claude_cli_enricher as enricher  # type: ignore  # noqa: E402


def _payload(provider: str) -> dict[str, object]:
    return {
        "headline": f"Generated by {provider}",
        "thirty_second_brief": {
            "what": "An official update was published.",
            "why_it_matters": "It affects foreign residents and investors.",
            "who": "Foreign residents and investors",
            "risk_level": "medium",
        },
        "the_facts": "The public source reports a material dated update.",
        "bali_zero_take": "Readers should distinguish facts from interpretation.",
        "in_practice": "Affected readers should review the official publication.",
        "next_steps": "Verify the effective date and obtain professional advice.",
        "faq": [{"question": "What changed?", "answer": "The official rule changed."}],
        "liveness_tier": "developing",
        "live_news_reasons": ["official update dated today"],
        "metadata": {
            "suggested_slug": "official-update",
            "tags": ["indonesia", "regulation"],
            "priority": "medium",
            "reading_time_minutes": 3,
        },
    }


def _json_result(provider: str) -> subprocess.CompletedProcess[str]:
    return subprocess.CompletedProcess([], 0, json.dumps(_payload(provider)), "")


def _provider(command: list[str]) -> str:
    return "ollama" if "ollama" in command[0] else "claude"


def test_timeout_opens_batch_circuit_and_falls_back_to_local() -> None:
    calls: list[str] = []
    circuit: set[str] = set()

    def fake_run(command: list[str], **_: object) -> subprocess.CompletedProcess[str]:
        provider = _provider(command)
        calls.append(provider)
        if provider == "claude":
            raise subprocess.TimeoutExpired(command, 150)
        return _json_result(provider)

    with patch.object(enricher.subprocess, "run", side_effect=fake_run):
        first = enricher.enrich_article_claude_cli({"title": "One"}, circuit_open=circuit)
        second = enricher.enrich_article_claude_cli({"title": "Two"}, circuit_open=circuit)

    assert first["success"] is True
    assert first["provider"] == "ollama"
    assert second["success"] is True
    assert calls == ["claude", "ollama", "ollama"]


def test_invalid_or_error_json_opens_circuit_and_falls_through() -> None:
    calls: list[str] = []
    circuit: set[str] = set()

    def fake_run(command: list[str], **_: object) -> subprocess.CompletedProcess[str]:
        provider = _provider(command)
        calls.append(provider)
        if provider == "claude":
            return subprocess.CompletedProcess([], 0, '{"error":"quota"}', "")
        return _json_result(provider)

    with patch.object(enricher.subprocess, "run", side_effect=fake_run):
        first = enricher.enrich_article_claude_cli({"title": "One"}, circuit_open=circuit)
        second = enricher.enrich_article_claude_cli({"title": "Two"}, circuit_open=circuit)

    assert first["provider"] == "ollama"
    assert second["provider"] == "ollama"
    assert calls == ["claude", "ollama", "ollama"]


def test_partial_and_empty_objects_never_count_as_enrichment() -> None:
    invalid_outputs = [
        "{}",
        '{"headline":"only one field"}',
        '{"error":"rate limited"}',
        '{"headline": 123}',
    ]
    for output in invalid_outputs:
        with patch.object(
            enricher.subprocess,
            "run",
            return_value=subprocess.CompletedProcess([], 0, output, ""),
        ):
            result = enricher.enrich_article_claude_cli({"title": "Invalid"})
        assert result["success"] is False


def test_provider_contract_is_subscription_local_only_and_secret_minimal(
    monkeypatch,
) -> None:
    monkeypatch.setenv("OPENAI_API_KEY", "must-not-leak")
    monkeypatch.setenv("ANTHROPIC_API_KEY", "must-not-leak")
    monkeypatch.setenv("DATABASE_URL", "must-not-leak")
    monkeypatch.setenv("TELEGRAM_BOT_TOKEN", "must-not-leak")
    monkeypatch.setenv("SCRAPER_API_KEY", "must-not-leak")
    monkeypatch.setenv("CLAUDE_CODE_OAUTH_TOKEN", "oauth-seat")
    observed: list[tuple[list[str], dict[str, object]]] = []

    def fake_run(command: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
        observed.append((command, kwargs))
        return _json_result(_provider(command))

    with patch.object(enricher.subprocess, "run", side_effect=fake_run):
        result = enricher.enrich_article_claude_cli({"title": "Public title"})

    assert result["success"] is True
    command, kwargs = observed[0]
    assert "Public title" not in command
    assert "--tools" in command and command[command.index("--tools") + 1] == ""
    assert "--no-session-persistence" in command
    assert kwargs["cwd"] == "/tmp"
    assert kwargs["timeout"] == 150
    assert kwargs["input"] and "Public title" in str(kwargs["input"])
    child_env = kwargs["env"]
    assert isinstance(child_env, dict)
    assert child_env["CLAUDE_CODE_OAUTH_TOKEN"] == "oauth-seat"
    for secret_name in (
        "OPENAI_API_KEY",
        "ANTHROPIC_API_KEY",
        "DATABASE_URL",
        "TELEGRAM_BOT_TOKEN",
        "SCRAPER_API_KEY",
    ):
        assert secret_name not in child_env


def test_batch_seat_token_is_mapped_to_canonical_child_name(monkeypatch) -> None:
    monkeypatch.delenv("CLAUDE_CODE_OAUTH_TOKEN", raising=False)
    monkeypatch.setenv("CLAUDE_CODE_OAUTH_TOKEN_3", "batch-seat-oauth")

    child_env = enricher._provider_env("claude")

    assert child_env["CLAUDE_CODE_OAUTH_TOKEN"] == "batch-seat-oauth"
    assert "CLAUDE_CODE_OAUTH_TOKEN_3" not in child_env


def test_batch_circuit_resets_between_batches() -> None:
    calls: list[str] = []

    def fake_run(command: list[str], **_: object) -> subprocess.CompletedProcess[str]:
        provider = _provider(command)
        calls.append(provider)
        if provider == "claude":
            raise subprocess.TimeoutExpired(command, 150)
        return _json_result(provider)

    with patch.object(enricher.subprocess, "run", side_effect=fake_run):
        first = enricher.batch_enrich_articles([{"title": "One"}])
        second = enricher.batch_enrich_articles([{"title": "Two"}])

    assert first[0]["enrichment_provider"] == "ollama"
    assert second[0]["enrichment_provider"] == "ollama"
    assert calls == ["claude", "ollama", "claude", "ollama"]
