#!/usr/bin/env python3
"""
Post-publish poller v3 — Resilient unified pipeline with step tracking.

Runs every 5 minutes via LaunchAgent (com.balizero.post-publish-poller).
Reads from PostgreSQL-backed queue on backend, processes each article:
  - SEO/GEO metadata optimization (agy — Antigravity CLI, Gemini 3.1 Pro;
    falls back to Codex when agy is unreachable. `gemini` CLI is DEPRECATED —
    Google discontinued the free-tier CLI, confirmed 2026-07-18)
  - Translation to 4 languages (Ollama local)
  - Cover image generation (bz_image_style + Codex $imagegen / gpt-image-2,
    two formats: 21:9 hero + 16:10 homepage card)
  - Git commit + push

Resilience features:
  - Step tracking: completed_steps JSONB — only re-runs failed steps on retry
  - Max 5 attempts: after that, item moves to 'dead' status
  - Telegram alert on failure (after 2+ attempts)
  - SEO/image steps are pre-flight health-checked (agy_healthy, codex_healthy)
    — a dead CLI leaves the step queued, never a corrupted/fabricated result

Sources:
  - 'intel': MDX articles from intel scraper (full pipeline: SEO + translate + image)
  - 'news':  news_items from /api/news (image generation only)
"""
import base64
import json
import os
import re
import subprocess
import sys
import tempfile
import urllib.parse
import urllib.request
from datetime import datetime
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
_venv = SCRIPT_DIR.parent / ".venv" / "bin" / "python3"
VENV_PYTHON = _venv if _venv.exists() else SCRIPT_DIR.parent / "venv" / "bin" / "python3"
LOG_DIR = Path.home() / ".openclaw" / "workspace" / "logs"
LOG_DIR.mkdir(parents=True, exist_ok=True)
LOG_FILE = LOG_DIR / f"post_publish_poller_{datetime.now().strftime('%Y%m%d')}.log"

BACKEND_URL = os.environ.get("BACKEND_URL", "https://nuzantara-rag.fly.dev")
API_KEY = os.environ.get("SCRAPER_API_KEY", "internal-scraper-key")
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_OWNER_CHAT_ID", "1125336968")

GITHUB_OWNER = "Balizero1987"
GITHUB_REPO = "Teman2"
IMAGE_GH_DIR = "apps/mouth/public/static/news"

# ── Codex $imagegen cover engine ─────────────────────────────────────────────
# Cover images are generated by Codex CLI's built-in $imagegen skill (gpt-image-2,
# OAuth Pro quota — no per-call billing). The poller runs on Pro via LaunchAgent;
# `node` + `codex` live in /opt/homebrew/bin which is NOT in the cron PATH by
# default, so we prepend it explicitly. Two formats per article: a 21:9 hero and
# a 16:10 homepage card (see bz_image_style.build_codex_cover_prompts).
CODEX_BIN_DIR = "/opt/homebrew/bin"
CODEX_TIMEOUT = 480  # seconds per image (smoke test ~3min, headroom for retries)
CODEX_HEALTH_TIMEOUT = 60

# ── agy (Antigravity CLI) — SEO/GEO text generation ──────────────────────────
# Replaces the deprecated `gemini` CLI. Confirmed live 2026-07-18:
# `gemini -m gemini-2.5-pro` returns `IneligibleTierError: This client is no
# longer supported for Gemini Code Assist for individuals ... migrate to the
# Antigravity suite` — Google discontinued the free-tier CLI outright. This is
# a PERMANENT break (auth-tier removed, not a PATH/model mismatch) — every
# SEO tick was silently eating this error as "no JSON in Gemini response".
# agy runs on the Google AI Ultra OAuth seat; the model string matches what
# scripts/agy_swarm_commander.py resolves its "pro-high" alias to.
AGY_BIN_DIR = str(Path.home() / ".local" / "bin")
AGY_MODEL = "Gemini 3.1 Pro (High)"
AGY_HEALTH_TIMEOUT = 60
SEO_LLM_TIMEOUT = 120  # per-call budget for the SEO JSON completion (agy or codex)


def _agy_env() -> dict:
    """Env for agy subprocess: ensure ~/.local/bin (where agy lives — not
    guaranteed on the cron PATH) is present, strip paid-API keys (defense-in-
    depth — agy runs on Google AI Ultra OAuth quota, never a billed key).
    Mirrors _codex_env() below.
    """
    env = dict(os.environ)
    path = env.get("PATH", "")
    if AGY_BIN_DIR not in path.split(":"):
        env["PATH"] = f"{AGY_BIN_DIR}:{path}" if path else AGY_BIN_DIR
    for key in (
        "ANTHROPIC_API_KEY",
        "OPENAI_API_KEY",
        "GEMINI_API_KEY",
        "GOOGLE_API_KEY",
        "FIREWORKS_API_KEY",
    ):
        env.pop(key, None)
    return env


_AGY_AUTH_DEAD_RE = re.compile(
    r"authentication required|authentication failed|please sign in|"
    r"not authenticated|log ?in to|token_revoked|401|unauthor",
    re.I,
)


def agy_healthy() -> bool:
    """Pre-flight: is the Antigravity CLI (agy) reachable and authed?

    agy needs an interactive Google/Antigravity re-auth on its own schedule
    (auth_sentinel.py family B — a human-only gesture per CLAUDE.md's
    credential boundary, NOT something this poller can fix headlessly).
    Confirmed live 2026-07-18 via `auth_sentinel.py --json`: agy status=
    "action", "sessione Antigravity/Google scaduta o non risponde". If
    unreachable, the caller leaves the SEO step queued for a later tick
    instead of silently giving up (or corrupting frontmatter).
    """
    try:
        proc = subprocess.run(
            ["agy", "--print-timeout", "45s", "--print", "reply with exactly: pong"],
            capture_output=True, text=True,
            timeout=AGY_HEALTH_TIMEOUT, env=_agy_env(), cwd="/tmp",
        )
        out = (proc.stdout or "") + (proc.stderr or "")
        if proc.returncode == 0 and "pong" in out.lower():
            return True
        if _AGY_AUTH_DEAD_RE.search(out):
            log(f"  ⚠ agy auth FAIL: {out.strip()[-160:]}")
        else:
            log(f"  ⚠ agy health unclear rc={proc.returncode}: {out.strip()[-160:]}")
        return False
    except FileNotFoundError:
        log("  ⚠ agy CLI not found on PATH")
        return False
    except subprocess.TimeoutExpired:
        log("  ⚠ agy health-check timed out")
        return False
    except Exception as e:
        log(f"  ⚠ agy health-check error: {e}")
        return False


def agy_generate_text(prompt: str, timeout: int = SEO_LLM_TIMEOUT) -> str | None:
    """Run one non-interactive agy turn, return raw stdout (None on
    timeout/error). `--sandbox` disables tool/shell actions — this call wants
    a plain text/JSON completion, not an agentic session."""
    try:
        proc = subprocess.run(
            ["agy", "--model", AGY_MODEL, "--sandbox",
             "--print-timeout", f"{timeout}s", "--print", prompt],
            capture_output=True, text=True,
            timeout=timeout + 15, env=_agy_env(), cwd="/tmp",
        )
    except subprocess.TimeoutExpired:
        log("    ❌ agy generation timed out")
        return None
    except Exception as e:
        log(f"    ❌ agy generation error: {e}")
        return None
    if proc.returncode != 0:
        tail = (proc.stderr or proc.stdout or "")[-200:]
        log(f"    ❌ agy generation rc={proc.returncode}: {tail}")
        return None
    return proc.stdout or ""


def codex_generate_text(prompt: str, timeout: int = SEO_LLM_TIMEOUT) -> str | None:
    """Run `codex exec` for a plain-text/JSON completion (read-only sandbox —
    no file writes needed). Fallback path for SEO generation when agy is
    unreachable; reuses the same ChatGPT Pro OAuth quota already spent on
    cover images in this file."""
    try:
        proc = subprocess.run(
            ["codex", "exec", "--skip-git-repo-check", "--sandbox", "read-only", "-"],
            input=prompt, capture_output=True, text=True,
            timeout=timeout, env=_codex_env(), cwd="/tmp",
        )
    except subprocess.TimeoutExpired:
        log("    ❌ codex text generation timed out")
        return None
    except Exception as e:
        log(f"    ❌ codex text generation error: {e}")
        return None
    if proc.returncode != 0:
        tail = (proc.stderr or proc.stdout or "")[-200:]
        log(f"    ❌ codex text generation rc={proc.returncode}: {tail}")
        return None
    return proc.stdout or ""


def _seo_llm_complete(prompt: str) -> tuple[str | None, str]:
    """Get a raw completion for the SEO prompt from the first healthy CLI:
    agy (primary — CLAUDE.md-mandated replacement for the deprecated `gemini`
    CLI) then codex (fallback — already wired into this file for cover
    images). Returns (None, "") if neither is reachable; the caller MUST
    leave the item queued rather than fabricate metadata.
    """
    if agy_healthy():
        out = agy_generate_text(prompt)
        if out is not None:
            return out, "agy"
        log("  ⚠ SEO: agy healthy but generation failed — trying codex")
    if codex_healthy():
        out = codex_generate_text(prompt)
        if out is not None:
            return out, "codex"
    return None, ""


def _iter_json_objects(text: str):
    """Yield every syntactically-balanced {...} substring in `text`, in
    appearance order. More robust than a single greedy regex span (which
    would swallow from the first '{' anywhere — e.g. an echoed prompt —
    straight through to the very last '}' and then fail to parse)."""
    depth = 0
    start = None
    for i, ch in enumerate(text):
        if ch == "{":
            if depth == 0:
                start = i
            depth += 1
        elif ch == "}":
            if depth > 0:
                depth -= 1
                if depth == 0 and start is not None:
                    yield text[start:i + 1]
                    start = None


def _extract_seo_json(raw: str) -> dict | None:
    """Tolerant JSON extraction for the SEO completion: scan every balanced
    {...} candidate, last-first (the model's real answer is usually the LAST
    object printed, after any reasoning/prompt-echo prose), and accept the
    first one that both parses AND carries an expected key."""
    for blob in reversed(list(_iter_json_objects(raw))):
        try:
            obj = json.loads(blob)
        except json.JSONDecodeError:
            continue
        if isinstance(obj, dict) and ("seoTitle" in obj or "seoDescription" in obj):
            return obj
    return None


def _codex_env() -> dict:
    """Env for codex subprocess: ensure node+codex on PATH, strip paid-API keys.

    Codex uses OAuth Pro quota for gpt-image-2 — provider API keys must NOT leak
    into the subprocess (would open a per-call billing path). Mirrors the
    defense-in-depth strip in backend codex_image_gen._safe_env.
    """
    env = dict(os.environ)
    path = env.get("PATH", "")
    if CODEX_BIN_DIR not in path.split(":"):
        env["PATH"] = f"{CODEX_BIN_DIR}:{path}" if path else CODEX_BIN_DIR
    for key in (
        "ANTHROPIC_API_KEY",
        "OPENAI_API_KEY",
        "GEMINI_API_KEY",
        "GOOGLE_API_KEY",
        "FIREWORKS_API_KEY",
    ):
        env.pop(key, None)
    return env


def codex_healthy() -> bool:
    """Pre-flight: is Codex CLI reachable and authed? Cheap read-only ping.

    Codex OAuth can silently go 401 token_revoked in cron (documented scar). If
    this returns False the caller leaves the article queued for a later tick
    rather than publishing a cover-less article — no silent degradation.
    """
    try:
        proc = subprocess.run(
            ["codex", "exec", "--skip-git-repo-check", "--sandbox", "read-only",
             "reply with exactly: pong"],
            input="", capture_output=True, text=True,
            timeout=CODEX_HEALTH_TIMEOUT, env=_codex_env(), cwd="/tmp",
        )
        out = (proc.stdout or "") + (proc.stderr or "")
        if proc.returncode == 0 and "pong" in out.lower():
            return True
        # token revoked / not logged in surfaces in stderr
        if any(s in out.lower() for s in ("token_revoked", "not logged in", "401", "unauthorized")):
            log(f"  ⚠ Codex auth FAIL: {out.strip()[-160:]}")
        else:
            log(f"  ⚠ Codex health unclear rc={proc.returncode}: {out.strip()[-160:]}")
        return False
    except FileNotFoundError:
        log("  ⚠ Codex CLI not found on PATH")
        return False
    except subprocess.TimeoutExpired:
        log("  ⚠ Codex health-check timed out")
        return False
    except Exception as e:
        log(f"  ⚠ Codex health-check error: {e}")
        return False


def codex_generate_image(prompt: str, out_path: Path) -> bool:
    """Generate ONE image via `codex exec $imagegen`, saved to out_path.

    Prompt is piped via stdin (verified-working invocation), `--skip-git-repo-check`
    set because /tmp is not a git repo. Returns True iff a real (>5KB) file lands.
    """
    framed = f"$imagegen {prompt}\n\nSave the generated image to: {out_path}"
    try:
        proc = subprocess.run(
            ["codex", "exec", "--skip-git-repo-check", "--sandbox", "danger-full-access", "-"],
            input=framed, capture_output=True, text=True,
            timeout=CODEX_TIMEOUT, env=_codex_env(), cwd=str(out_path.parent),
        )
    except subprocess.TimeoutExpired:
        log(f"    ❌ Codex timed out after {CODEX_TIMEOUT}s")
        return False
    except Exception as e:
        log(f"    ❌ Codex error: {e}")
        return False

    if out_path.exists() and out_path.stat().st_size > 5000:
        log(f"    ✅ {out_path.stat().st_size} bytes")
        return True

    # Fallback: Codex sometimes saves under a slightly different name — grab the
    # newest png/jpg in the dir if our exact target didn't materialize.
    try:
        candidates = sorted(
            (p for p in out_path.parent.glob("*") if p.suffix.lower() in (".png", ".jpg", ".jpeg")
             and p.stat().st_size > 5000),
            key=lambda p: p.stat().st_mtime, reverse=True,
        )
        if candidates and candidates[0] != out_path:
            candidates[0].rename(out_path)
            log(f"    ✅ {out_path.stat().st_size} bytes (renamed from {candidates[0].name})")
            return True
    except OSError:
        pass

    tail = (proc.stderr or proc.stdout or "")[-200:]
    log(f"    ❌ no image produced rc={proc.returncode}: {tail}")
    return False


# ── GitHub batch-branch/PR commit mechanism ──────────────────────────────────
# Direct PUT-to-main via the Contents API is rejected by branch protection (25
# required status checks, enforce_admins=true, since ~2026-05-22) — every
# generated cover image / SEO update was silently discarded (last successful
# direct commit b19de9bf5a). Writes are staged in-memory during a poller tick
# and flushed once, per kind, into ONE branch + auto-merged PR.
_PENDING_COMMITS: list[dict] = []  # {"kind", "gh_path", "content_b64", "message"}


def _log_gh_failure(op: str, result: "subprocess.CompletedProcess[str]") -> None:
    """Never a bare 'X failed' — always the tail of what `gh` actually said."""
    tail = (result.stderr or result.stdout or "").strip()[-200:]
    log(f"  ❌ gh failure ({op}) rc={result.returncode}: {tail}")


def _stage_commit(kind: str, gh_path: str, content_bytes: bytes, message: str) -> None:
    """Queue a file write for the end-of-tick batch flush (see flush_*_batch)."""
    _PENDING_COMMITS.append({
        "kind": kind,
        "gh_path": gh_path,
        "content_b64": base64.b64encode(content_bytes).decode("utf-8"),
        "message": message,
    })


def _github_default_branch_sha() -> str | None:
    """SHA of `main` HEAD, to branch a bot branch off of."""
    try:
        result = subprocess.run(
            ["gh", "api", f"repos/{GITHUB_OWNER}/{GITHUB_REPO}/git/refs/heads/main", "--jq", ".object.sha"],
            capture_output=True, text=True, timeout=15,
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip()
        _log_gh_failure("get main HEAD sha", result)
        return None
    except Exception as e:
        log(f"  ❌ get main HEAD sha error: {e}")
        return None


def _create_bot_branch(branch: str) -> bool:
    sha = _github_default_branch_sha()
    if not sha:
        return False
    try:
        result = subprocess.run(
            ["gh", "api", f"repos/{GITHUB_OWNER}/{GITHUB_REPO}/git/refs", "--method", "POST", "--input", "-"],
            input=json.dumps({"ref": f"refs/heads/{branch}", "sha": sha}),
            capture_output=True, text=True, timeout=30,
        )
        if result.returncode != 0:
            _log_gh_failure(f"create-ref {branch}", result)
            return False
        return True
    except Exception as e:
        log(f"  ❌ create-ref error ({branch}): {e}")
        return False


def _commit_to_branch(gh_path: str, content_b64: str, message: str, branch: str) -> bool:
    """PUT one file to `branch` (create or update — resolves existing sha on that branch)."""
    existing_sha = ""
    try:
        check = subprocess.run(
            ["gh", "api", f"repos/{GITHUB_OWNER}/{GITHUB_REPO}/contents/{gh_path}",
             "-f", f"ref={branch}", "--jq", ".sha"],
            capture_output=True, text=True, timeout=15,
        )
        existing_sha = check.stdout.strip() if check.returncode == 0 else ""
    except Exception:
        existing_sha = ""

    payload = {"message": message, "content": content_b64, "branch": branch}
    if existing_sha:
        payload["sha"] = existing_sha
    try:
        result = subprocess.run(
            ["gh", "api", f"repos/{GITHUB_OWNER}/{GITHUB_REPO}/contents/{gh_path}",
             "--method", "PUT", "--input", "-"],
            input=json.dumps(payload), capture_output=True, text=True, timeout=60,
        )
        if result.returncode != 0:
            _log_gh_failure(f"PUT {gh_path}@{branch}", result)
            return False
        return True
    except Exception as e:
        log(f"  ❌ commit error ({gh_path}@{branch}): {e}")
        return False


def _open_and_arm_pr(branch: str, title: str, body: str) -> bool:
    try:
        pr_result = subprocess.run(
            ["gh", "pr", "create", "--repo", f"{GITHUB_OWNER}/{GITHUB_REPO}",
             "--head", branch, "--base", "main", "--title", title, "--body", body],
            capture_output=True, text=True, timeout=30,
        )
    except Exception as e:
        log(f"  ❌ pr create error ({branch}): {e}")
        return False
    if pr_result.returncode != 0:
        _log_gh_failure(f"pr create {branch}", pr_result)
        return False
    log(f"  ✅ PR opened: {pr_result.stdout.strip()}")

    try:
        merge_result = subprocess.run(
            ["gh", "pr", "merge", "--auto", "--squash", "--repo", f"{GITHUB_OWNER}/{GITHUB_REPO}", branch],
            capture_output=True, text=True, timeout=30,
        )
    except Exception as e:
        log(f"  ⚠ pr merge --auto arm error ({branch}): {e}")
        return True  # PR exists even if arming failed — not a hard failure
    if merge_result.returncode != 0:
        _log_gh_failure(f"pr merge --auto {branch}", merge_result)
    else:
        log(f"  ✅ auto-merge armed for {branch}")
    return True


def _flush_batch(kind: str, branch_prefix: str, title_template: str) -> bool:
    """Flush all pending commits of `kind` into ONE bot branch + auto-merged PR.

    Returns True iff the batch was empty, or branch+commits+PR all succeeded
    (a failed auto-merge arm is logged but not treated as a hard failure — the
    PR still exists for manual merge).
    """
    global _PENDING_COMMITS
    batch = [c for c in _PENDING_COMMITS if c["kind"] == kind]
    if not batch:
        return True
    _PENDING_COMMITS = [c for c in _PENDING_COMMITS if c["kind"] != kind]

    branch = f"{branch_prefix}-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
    log(f"▶ Flushing {len(batch)} {kind} change(s) → branch {branch}")

    if not _create_bot_branch(branch):
        # The queue items behind this batch were already marked step-done in the
        # DB (staging succeeds independently of the flush) — a lost batch here
        # needs a manual re-push, not an automatic retry. The Telegram alert in
        # main() is what surfaces this instead of it failing silently.
        log(f"  ❌ Could not create branch {branch} — {len(batch)} staged {kind} change(s) lost, needs manual re-push")
        return False

    all_ok = True
    for item in batch:
        if _commit_to_branch(item["gh_path"], item["content_b64"], item["message"], branch):
            log(f"  ✅ staged → {item['gh_path']} @ {branch}")
        else:
            all_ok = False

    date_str = datetime.now().strftime("%Y-%m-%d")
    title = title_template.format(date=date_str, n=len(batch))
    body = (
        f"Automated {kind} batch — {len(batch)} file(s) via the post-publish poller.\n\n"
        "Files:\n" + "\n".join(f"- `{c['gh_path']}`" for c in batch) +
        "\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)"
    )
    if not _open_and_arm_pr(branch, title, body):
        return False
    return all_ok


def flush_image_batch() -> bool:
    return _flush_batch("image", "bot/news-covers", "feat(images): news covers {date} ({n} files)")


def flush_seo_batch() -> bool:
    return _flush_batch("seo", "bot/seo-metadata", "fix(seo): GEO/AEO metadata {date} ({n} files)")


def flush_layout_batch() -> bool:
    return _flush_batch("layout", "bot/homepage-layout", "chore(homepage): hero rotation {date}")


def flush_translation_batch() -> bool:
    return _flush_batch("translation", "bot/articles-translations",
                         "feat(articles): add translations {date} ({n} files)")


_FLUSH_THRESHOLD = 8


def maybe_flush_all_batches(threshold: int = _FLUSH_THRESHOLD) -> bool:
    """Mid-run flush: once staged GitHub writes reach `threshold`, flush image+seo+
    layout batches immediately instead of waiting for the end-of-run sweep in main().

    Crash-exposure fix (2026-07-17): a run that dies mid-tick (translate hang,
    killer unknown, no traceback — live incident: the 16:56 run died ~22:20 with
    ~2 dozen covers staged and lost) previously kept every staged write in RAM
    for the FULL run — 5-10h with the current backlog. This shrinks the exposure
    window to ~`threshold` items (~30-40min). Same flush functions + same
    Telegram-alert-on-failure condition as the final sweep in main() — more
    flushes per run (more bot PRs) is intentional, not a bug.

    Returns True iff a flush was actually triggered this call.
    """
    if len(_PENDING_COMMITS) < threshold:
        return False
    log(f"🔁 Mid-run flush triggered ({len(_PENDING_COMMITS)} staged ≥ {threshold})")
    img_ok = flush_image_batch()
    seo_ok = flush_seo_batch()
    layout_ok = flush_layout_batch()
    if not img_ok or not seo_ok or not layout_ok:
        send_telegram_alert(
            "⚠️ *Post-publish poller*\n"
            f"GitHub batch flush failed (image={img_ok}, seo={seo_ok}, "
            f"layout={layout_ok}) — see log"
        )
    return True


def _image_exists_on_github(gh_path: str) -> bool:
    try:
        check = subprocess.run(
            ["gh", "api", f"repos/{GITHUB_OWNER}/{GITHUB_REPO}/contents/{gh_path}", "--jq", ".sha"],
            capture_output=True, text=True, timeout=15,
        )
        return bool(check.returncode == 0 and check.stdout.strip())
    except Exception:
        return False


def log(msg: str):
    line = f"[{datetime.now().strftime('%H:%M:%S')}] {msg}"
    print(line, flush=True)
    with open(LOG_FILE, "a") as f:
        f.write(line + "\n")


def api_get(path: str) -> dict:
    req = urllib.request.Request(
        f"{BACKEND_URL}{path}",
        headers={"X-API-Key": API_KEY},
    )
    with urllib.request.urlopen(req, timeout=15) as resp:
        return json.loads(resp.read())


def api_post(path: str, data: dict) -> dict:
    body = json.dumps(data).encode()
    req = urllib.request.Request(
        f"{BACKEND_URL}{path}",
        data=body,
        headers={"X-API-Key": API_KEY, "Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=15) as resp:
        return json.loads(resp.read())


def mark_step_done(slug: str, step: str):
    """Report a completed step to the backend."""
    try:
        api_post("/api/intel/post-publish-queue/step-done", {"slug": slug, "step": step})
    except Exception as e:
        log(f"  ⚠ Failed to mark step '{step}' done: {e}")


def send_telegram_alert(message: str):
    """Send alert to Telegram owner chat."""
    if not TELEGRAM_BOT_TOKEN:
        return
    try:
        url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
        data = json.dumps({"chat_id": TELEGRAM_CHAT_ID, "text": message, "parse_mode": "Markdown"}).encode()
        req = urllib.request.Request(url, data=data, headers={"Content-Type": "application/json"}, method="POST")
        urllib.request.urlopen(req, timeout=10)
    except Exception:
        pass  # Alert failure is not critical


def wait_for_ollama_free(max_wait: int = 60 * 15) -> bool:
    """Wait until no other translate_articles.py is running (max 15 min)."""
    import time
    waited = 0
    while waited < max_wait:
        check = subprocess.run(["pgrep", "-f", "translate_articles.py"], capture_output=True, text=True)
        if check.returncode != 0:
            return True
        log("⏳ Ollama busy — waiting 60s...")
        time.sleep(60)
        waited += 60
    log("⚠ Timeout waiting for Ollama")
    return False


# ─── SEO/GEO ──────────────────────────────────────────────────────────────────

def run_seo(slug: str, category: str) -> bool:
    """Optimize SEO/GEO metadata of published MDX via agy (fallback: codex).

    Pre-flight health-checked (see _seo_llm_complete): if neither CLI is
    reachable, the step is left queued for a later tick rather than silently
    giving up — or worse, corrupting frontmatter with a garbage response.
    """
    ARTICLES_PATH = "apps/mouth/src/content/articles"
    mdx_path = f"{ARTICLES_PATH}/{category}/{slug}.mdx"

    log(f"  ▶ SEO/GEO for {slug}")

    try:
        result = subprocess.run(
            ["gh", "api", f"repos/{GITHUB_OWNER}/{GITHUB_REPO}/contents/{mdx_path}"],
            capture_output=True, text=True, timeout=30,
        )
        if result.returncode != 0:
            log("  ⏭ SEO: MDX not on GitHub — skip")
            return True
        data = json.loads(result.stdout)
        content = base64.b64decode(data["content"]).decode("utf-8")
    except Exception as e:
        log(f"  ⚠ SEO: GitHub read error: {e}")
        return False

    match = re.match(r"^---\n(.*?)\n---\n(.*)$", content, re.DOTALL)
    if not match:
        log("  ⏭ SEO: no frontmatter — skip")
        return True

    fm_raw = match.group(1)
    body = match.group(2)

    # Already optimized?
    if "answerSnippet" in fm_raw and "Check article for specific dates" not in fm_raw and "mean for expats in Bali?" not in fm_raw:
            log("  ⏭ SEO already optimized")
            return True

    title_match = re.search(r'^title:\s*["\']?(.*?)["\']?\s*$', fm_raw, re.MULTILINE)
    title = title_match.group(1) if title_match else slug

    prompt = f"""You are an expert SEO and AI Search Optimization (GEO/AEO) specialist for Bali Zero, an immigration and business setup agency in Bali.

Analyze this article and return ONLY a JSON object with optimized metadata. No explanations, no markdown, just the JSON.

Article title: {title}
Category: {category}
Article body (first 2000 chars):
{body[:2000]}

Return this exact JSON structure:
{{
  "seoTitle": "<60 chars, keyword-first, include year 2026 if relevant>",
  "seoDescription": "<150-155 chars, include primary keyword + action>",
  "aiOptimization": {{
    "answerSnippet": "<2 clear declarative sentences answering the article's main question. Factual and specific.>",
    "primaryQuestion": "<The main question this article answers, phrased as users would search it>",
    "entityMentions": ["<key entity 1>", "<key entity 2>", "<key entity 3>"]
  }}
}}"""

    raw, tool_used = _seo_llm_complete(prompt)
    if raw is None:
        log("  ⏸ SEO: no LLM reachable (agy + codex both down) — leaving queued")
        return False

    seo = _extract_seo_json(raw)
    if seo is None:
        log(f"  ⚠ SEO: no JSON in {tool_used} response")
        return False

    def set_fm_field(fm: str, key: str, value: str) -> str:
        value_escaped = value.replace('"', '\\"')
        pattern = rf'^{re.escape(key)}:.*$'
        replacement = f'{key}: "{value_escaped}"'
        new_fm = re.sub(pattern, replacement, fm, flags=re.MULTILINE)
        if new_fm == fm:
            new_fm = fm + f'\n{key}: "{value_escaped}"'
        return new_fm

    ai_opt = seo.get("aiOptimization", {})
    fm_raw = set_fm_field(fm_raw, "seoTitle", seo.get("seoTitle", ""))
    fm_raw = set_fm_field(fm_raw, "seoDescription", seo.get("seoDescription", ""))

    if ai_opt.get("answerSnippet"):
        answer = ai_opt["answerSnippet"].replace('"', '\\"')
        fm_raw = re.sub(r'(answerSnippet:\s*)["\']?.*?["\']?\s*$', f'\\1"{answer}"', fm_raw, flags=re.MULTILINE)
    if ai_opt.get("primaryQuestion"):
        question = ai_opt["primaryQuestion"].replace('"', '\\"')
        fm_raw = re.sub(r'(primaryQuestion:\s*)["\']?.*?["\']?\s*$', f'\\1"{question}"', fm_raw, flags=re.MULTILINE)

    new_content = f"---\n{fm_raw}\n---\n{body}"

    # Direct PUT-to-main is rejected by branch protection (see module note on
    # _PENDING_COMMITS) — stage for the end-of-tick batch-branch/PR flush instead.
    _stage_commit("seo", mdx_path, new_content.encode("utf-8"),
                  f"feat(seo): optimize GEO/AEO metadata for '{title[:50]}'")
    log(f"  📦 SEO/GEO metadata staged for batch commit (via {tool_used})")
    return True


# ─── TRANSLATION ───────────────────────────────────────────────────────────────

def run_translate(slug: str, category: str) -> bool:
    wait_for_ollama_free()
    translate_script = SCRIPT_DIR.parent.parent.parent / "scripts" / "translate-articles.py"
    log(f"  ▶ Translating {slug} (4 langs)")

    # Ensure the MDX file exists locally before translating.
    # The news-room pushes to GitHub but the local repo may lag behind.
    repo_root = SCRIPT_DIR.parent.parent.parent
    mdx_local = repo_root / "apps" / "mouth" / "src" / "content" / "articles" / category / f"{slug}.mdx"
    if not mdx_local.exists():
        log("  ⚠ MDX not found locally — pulling from GitHub")
        try:
            import base64 as _b64
            gh_result = subprocess.run(
                ["gh", "api", f"repos/{GITHUB_OWNER}/{GITHUB_REPO}/contents/apps/mouth/src/content/articles/{category}/{slug}.mdx"],
                capture_output=True, text=True, timeout=30,
            )
            if gh_result.returncode == 0:
                import json as _json
                data = _json.loads(gh_result.stdout)
                content = _b64.b64decode(data["content"]).decode("utf-8")
                mdx_local.parent.mkdir(parents=True, exist_ok=True)
                mdx_local.write_text(content, encoding="utf-8")
                log(f"  ✅ MDX pulled from GitHub ({len(content)} chars)")
            else:
                log("  ❌ MDX not on GitHub either — cannot translate")
                return False
        except Exception as e:
            log(f"  ❌ GitHub pull error: {e}")
            return False
    try:
        result = subprocess.run(
            [str(VENV_PYTHON), str(translate_script), "--slug", slug, "--category", category, "--lang", "all"],
            capture_output=True, text=True, timeout=15 * 60,
        )
    except subprocess.TimeoutExpired as e:
        # Live incident (8x in post_publish_poller.err): translate-articles.py
        # wedges past the 15min budget — this used to propagate uncaught and
        # crash the ENTIRE poller run (every remaining queue item abandoned
        # mid-tick). Caught here, logged, and reported as a failed step so the
        # reaper picks the item back up next tick instead of the run dying.
        stderr_tail = e.stderr
        if isinstance(stderr_tail, bytes):
            stderr_tail = stderr_tail.decode("utf-8", errors="replace")
        log(f"  ❌ translate timed out after {15 * 60}s: "
            f"{stderr_tail[-200:] if stderr_tail else '(no stderr captured)'}")
        return False
    except Exception as e:
        log(f"  ❌ translate error: {e}")
        return False

    ok = result.returncode == 0
    log(f"  {'✅' if ok else '❌'} translate exit={result.returncode}")
    if not ok and result.stderr:
        log(f"    stderr: {result.stderr[-200:]}")
    return ok


# ─── COVER IMAGE ───────────────────────────────────────────────────────────────

def _fetch_mdx_meta(slug: str, category: str) -> tuple[str | None, str | None]:
    """Pull (title, summary) from the article MDX on GitHub. Best-effort."""
    import base64
    import re

    try:
        result = subprocess.run(
            ["gh", "api", f"repos/{GITHUB_OWNER}/{GITHUB_REPO}/contents/apps/mouth/src/content/articles/{category}/{slug}.mdx"],
            capture_output=True, text=True, timeout=30,
        )
        if result.returncode != 0:
            return None, None
        mdx_content = base64.b64decode(json.loads(result.stdout)["content"]).decode("utf-8")
    except Exception:
        return None, None

    title_match = re.search(r'^title:\s*["\']?(.*?)["\']?\s*$', mdx_content, re.MULTILINE)
    title = title_match.group(1) if title_match else None

    # Summary: prefer excerpt/description frontmatter, else first prose paragraph
    summary = None
    for key in ("excerpt", "description", "summary"):
        m = re.search(rf'^{key}:\s*["\']?(.*?)["\']?\s*$', mdx_content, re.MULTILINE)
        if m and m.group(1).strip():
            summary = m.group(1).strip()
            break
    if not summary:
        body = re.split(r'^---\s*$', mdx_content, maxsplit=2, flags=re.MULTILINE)
        prose = body[-1] if len(body) >= 3 else mdx_content
        for para in prose.split("\n\n"):
            clean = para.strip().lstrip("#").strip()
            if len(clean) > 60 and not clean.startswith(("import", "<", "export")):
                summary = clean[:500]
                break
    return title, summary


def run_image(slug: str, category: str, title: str | None = None, article_id: str | None = None) -> bool:
    """Generate TWO cover images via Codex $imagegen (gpt-image-2), stage for GitHub.

    hero  → {slug}.jpg       (21:9, article top hero — frontmatter coverImage)
    card  → {slug}_card.jpg  (16:10, homepage news card — frontmatter cardImage)

    Codex-total (no Fireworks). Pre-flight health-check: if Codex is unreachable
    the item stays queued (returns False → retried next tick) rather than
    publishing a cover-less article. Idempotent: skips if both already on GitHub
    (main only — re-staging onto the bot branch if a PR is already in flight is
    harmless, see flush_image_batch). Actual GitHub write happens at end-of-tick
    via flush_image_batch(), batched with every other image staged this run.
    """
    hero_gh_path = f"{IMAGE_GH_DIR}/{slug}.jpg"
    card_gh_path = f"{IMAGE_GH_DIR}/{slug}_card.jpg"
    log(f"  ▶ Cover images (hero+card) for {slug}")

    # Idempotency: both already published?
    hero_done = _image_exists_on_github(hero_gh_path)
    card_done = _image_exists_on_github(card_gh_path)
    if hero_done and card_done:
        log("  ⏭ Both covers already on GitHub")
        if article_id:
            _update_news_image_url(article_id, f"/static/news/{slug}.jpg")
        return True

    # Recover title + summary from MDX for a strong Codex concept
    mdx_title, summary = _fetch_mdx_meta(slug, category)
    title = title or mdx_title or slug

    # Pre-flight: Codex reachable & authed? Otherwise leave queued (no cover-less publish).
    if not codex_healthy():
        log("  ⏸ Codex unavailable — leaving item queued for next tick")
        send_telegram_alert(f"⚠️ Cover gen skipped (Codex down): {slug}")
        return False

    # Build the two brand-railed prompts
    try:
        sys.path.insert(0, str(SCRIPT_DIR))
        from bz_image_style import build_codex_cover_prompts
        prompts = build_codex_cover_prompts(title, category, summary=summary)
    except Exception as e:
        log(f"  ⚠ bz_image_style error: {e}")
        base = (f"Cinematic hyper-realistic Bali editorial photograph, {category} theme, "
                f"teal and amber color grading, golden hour, no text no logo. Subject: {title[:80]}")
        prompts = {
            "hero": base + " Ultra-wide 21:9 cinematic panorama, subject centred.",
            "card": base + " Landscape 16:10, framed tighter on the subject.",
        }

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp = Path(tmpdir)
        all_ok = True
        hero_staged = False

        for kind, gh_path, already in (
            ("hero", hero_gh_path, hero_done),
            ("card", card_gh_path, card_done),
        ):
            if already:
                log(f"    ⏭ {kind} already on GitHub")
                continue
            log(f"    🎨 Codex {kind}")
            img_path = tmp / Path(gh_path).name
            if not codex_generate_image(prompts[kind], img_path):
                log(f"  ❌ {kind} generation failed")
                all_ok = False
                continue
            _stage_commit("image", gh_path, img_path.read_bytes(),
                          f"feat(image): cover for '{title[:50]}'")
            log(f"  📦 {kind} staged → {gh_path}")
            if kind == "hero":
                hero_staged = True

        # hero is what coverImage/news points at; only update DB once it's staged
        # (the PR landing — flush_image_batch, auto-merged — is what makes it live)
        if (hero_done or hero_staged) and article_id:
            _update_news_image_url(article_id, f"/static/news/{slug}.jpg")

        return all_ok


def _update_news_image_url(article_id: str, image_url: str):
    try:
        api_post(f"/api/news/{article_id}/image", {"image_url": image_url})
    except Exception as e:
        log(f"  ⚠ news_items.image_url update failed: {e}")


# ─── HERO ROTATION ────────────────────────────────────────────────────────────

HOMEPAGE_LAYOUT_PATH = "apps/mouth/src/content/homepage-layout.json"
HERO_KEYS = ["hero_main", "hero_2", "hero_3", "hero_4", "hero_5"]
LATEST_KEYS = ["latest_1", "latest_2", "latest_3", "latest_4", "latest_5"]


def rotate_hero(new_slug: str) -> bool:
    """Rotate homepage-layout.json: push new_slug to hero_main, cascade others down.
    Old hero_5 moves to latest_1, shifting latest_* down (latest_5 dropped).

    Stages the write for the end-of-tick batch flush (`flush_layout_batch`) instead
    of PUT-ing straight to main — direct PUTs are rejected by branch protection
    (see the "GitHub batch-branch/PR commit mechanism" note above `_stage_commit`).
    """
    import base64 as _b64

    log(f"  ▶ Hero rotation: {new_slug}")

    # Read current layout from GitHub (source of truth)
    try:
        result = subprocess.run(
            ["gh", "api", f"repos/{GITHUB_OWNER}/{GITHUB_REPO}/contents/{HOMEPAGE_LAYOUT_PATH}"],
            capture_output=True, text=True, timeout=30,
        )
        if result.returncode != 0:
            log("  ⚠ Hero: cannot read homepage-layout.json from GitHub")
            return False
        data = json.loads(result.stdout)
        layout = json.loads(_b64.b64decode(data["content"]).decode("utf-8"))
    except Exception as e:
        log(f"  ⚠ Hero: read error: {e}")
        return False

    # Skip if already hero_main
    if layout.get("hero_main") == new_slug:
        log("  ⏭ Hero: already hero_main")
        return True

    # Skip if slug not yet in layout at all (might not have MDX on GitHub yet)
    # We proceed regardless — the new article is being published right now.

    # Cascade: old hero_main→hero_2→…→hero_5 → latest_1→…→latest_5
    old_heros = [layout.get(k) for k in HERO_KEYS]  # current [main, 2, 3, 4, 5]
    old_latests = [layout.get(k) for k in LATEST_KEYS]

    # New hero list: new slug at front, old heroes shift down (drop last)
    new_heros = [new_slug] + [s for s in old_heros if s and s != new_slug][:len(HERO_KEYS) - 1]
    # New latest: old hero_5 at front, shift down (drop last)
    evicted = old_heros[-1] if old_heros[-1] and old_heros[-1] != new_slug else None
    if evicted:
        new_latests = [evicted] + [s for s in old_latests if s and s != evicted][:len(LATEST_KEYS) - 1]
    else:
        new_latests = old_latests

    for i, key in enumerate(HERO_KEYS):
        if i < len(new_heros):
            layout[key] = new_heros[i]
    for i, key in enumerate(LATEST_KEYS):
        if i < len(new_latests):
            layout[key] = new_latests[i]

    # Stage the write for the end-of-tick layout batch flush (see flush_layout_batch)
    new_content = json.dumps(layout, indent=2, ensure_ascii=False) + "\n"
    _stage_commit(
        "layout", HOMEPAGE_LAYOUT_PATH, new_content.encode("utf-8"),
        f"feat(homepage): rotate hero → {new_slug[:50]}",
    )
    log(f"  ✅ Hero rotation staged (hero_main={new_slug[:40]})")
    return True


# ─── GIT OPERATIONS ───────────────────────────────────────────────────────────

def git_pull_monorepo():
    repo_root = SCRIPT_DIR.parent.parent.parent
    try:
        result = subprocess.run(["git", "pull", "--ff-only"], capture_output=True, text=True, cwd=str(repo_root), timeout=60)
        if result.returncode == 0:
            log("✅ git pull OK")
        else:
            # Try stash + pull + pop
            subprocess.run(["git", "stash"], capture_output=True, cwd=str(repo_root), timeout=10)
            subprocess.run(["git", "pull", "--ff-only"], capture_output=True, cwd=str(repo_root), timeout=60)
            subprocess.run(["git", "stash", "pop"], capture_output=True, cwd=str(repo_root), timeout=10)
            log("✅ git pull OK (via stash)")
    except Exception as e:
        log(f"⚠ git pull error: {e}")


def git_commit_and_push_translations(slugs: list[str]) -> bool:
    """Stage translation .mdx files and flush via the same batch-branch/PR
    mechanism as flush_image_batch/flush_seo_batch/flush_layout_batch (see the
    "GitHub batch-branch/PR commit mechanism" module note above `_stage_commit`).

    Direct `git push origin main` (the old mechanism) is rejected by branch
    protection EVERY time — and it doesn't fail loudly: the commit lands on the
    main checkout regardless (git commit succeeds locally), then the push is
    bounced, leaving an orphan local commit that blocks the next `git pull
    --ff-only` for every subsequent tick until someone rescues it by hand
    (live incident 2026-07-18: commits e2c3951c/be43e312d, both rescued
    manually twice in one day). This function NEVER runs `git add`/`git
    commit`/`git push` on the main checkout — files are read straight off disk
    (translate_articles.py already wrote them there) and committed via the
    GitHub Contents API on a bot branch, exactly like every other write path
    in this module.

    On any failure (branch create, PUT, PR create) `_flush_batch` logs the gh
    failure and this returns False. Nothing was ever `git add`-ed, so the
    local .mdx files are simply left untracked on disk — the next tick's
    rglob picks them straight back up and re-stages them. No local git state
    to unwind, no orphan commit possible.
    """
    repo_root = SCRIPT_DIR.parent.parent.parent
    articles_dir = repo_root / "apps" / "mouth" / "src" / "content" / "articles"

    translation_files: list[Path] = []
    for slug in slugs:
        for f in articles_dir.rglob(f"{slug}.*.mdx"):
            translation_files.append(f)

    if not translation_files:
        log("⚠ No translation files to commit")
        return True

    message = f"feat(articles): add translations for {', '.join(slugs[:3])}{'...' if len(slugs) > 3 else ''}"
    log(f"▶ Staging {len(translation_files)} translation file(s) for batch commit")
    for f in translation_files:
        gh_path = str(f.relative_to(repo_root))
        try:
            content = f.read_bytes()
        except OSError as e:
            log(f"  ⚠ Could not read {gh_path}: {e}")
            continue
        _stage_commit("translation", gh_path, content, message)
        log(f"  📦 staged → {gh_path}")

    return flush_translation_batch()


# ─── MAIN ──────────────────────────────────────────────────────────────────────

def process_item(item: dict) -> tuple[bool, list[str]]:
    """Process a single queue item. Returns (all_done, failed_steps)."""
    slug = item["slug"]
    category = item.get("category", "business")
    source = item.get("source", "intel")
    article_id = item.get("article_id")
    title = item.get("title")
    done = item.get("completed_steps", {})
    failed_steps = []

    if source == "intel":
        # SEO
        if not done.get("seo"):
            if run_seo(slug, category):
                mark_step_done(slug, "seo")
            else:
                failed_steps.append("seo")
        # Translate
        if not done.get("translate"):
            if run_translate(slug, category):
                mark_step_done(slug, "translate")
                # Auto-rotate hero after successful translate
                rotate_hero(slug)
            else:
                failed_steps.append("translate")
        # Image — NEVER skip based on completed_steps alone (2026-07-17 fix): the
        # flag can lie if a prior run died mid-tick before flushing (see
        # maybe_flush_all_batches). run_image()'s own idempotency check
        # (_image_exists_on_github against main) makes calling it unconditionally
        # a cheap no-op (~2 `gh api` calls) when the covers genuinely exist, and
        # regenerates them when the flag lied.
        if run_image(slug, category, title=title):
            mark_step_done(slug, "image")
        else:
            failed_steps.append("image")

        return (len(failed_steps) == 0, failed_steps)

    elif source == "news":
        # Image — same "never skip on completed_steps alone" rule as the intel
        # branch above (see comment there).
        if run_image(slug, category, title=title, article_id=article_id):
            mark_step_done(slug, "image")
        else:
            failed_steps.append("image")
        return (len(failed_steps) == 0, failed_steps)

    else:
        log(f"⚠ Unknown source '{source}'")
        return (True, [])


def main():
    log("=" * 50)
    log("🔄 Post-publish poller v3 started")

    try:
        result = api_get("/api/intel/post-publish-queue/pending")
        pending = result.get("pending", [])
    except Exception as e:
        log(f"❌ Queue read error: {e}")
        return

    if not pending:
        log("✅ No articles in queue")
        return

    log(f"📋 {len(pending)} articles in queue")
    git_pull_monorepo()

    done_slugs = []
    failed_items = []
    translated_slugs = []

    for item in pending:
        slug = item["slug"]
        attempts = item.get("attempts", 1)
        log(f"📄 [{item.get('source','?')}] {item.get('category','?')}/{slug} (attempt {attempts})")

        all_ok, failed_steps = process_item(item)

        if all_ok:
            done_slugs.append(slug)
            # Check if translate was done (for git push)
            completed = item.get("completed_steps", {})
            if completed.get("translate") or item.get("source") == "news":
                pass  # already committed or not needed
            else:
                translated_slugs.append(slug)
        else:
            failed_items.append({"slug": slug, "steps": failed_steps, "attempts": attempts})
            # Still push translations if translate succeeded
            completed = item.get("completed_steps", {})
            if "translate" not in failed_steps and item.get("source") == "intel":
                translated_slugs.append(slug)

        # Periodic mid-run flush (crash exposure fix) — see maybe_flush_all_batches.
        maybe_flush_all_batches()

    # Final sweep: flush this tick's staged GitHub writes (images + SEO + homepage layout) —
    # ONE bot branch + auto-merged PR per kind, replacing the direct-to-main
    # PUTs branch protection has been rejecting since ~2026-05-22.
    img_flush_ok = flush_image_batch()
    seo_flush_ok = flush_seo_batch()
    layout_flush_ok = flush_layout_batch()
    if not img_flush_ok or not seo_flush_ok or not layout_flush_ok:
        send_telegram_alert(
            "⚠️ *Post-publish poller*\n"
            f"GitHub batch flush failed (image={img_flush_ok}, seo={seo_flush_ok}, "
            f"layout={layout_flush_ok}) — see log"
        )

    # Commit translations — staged + flushed via the same batch-branch/PR
    # mechanism as image/seo/layout (see git_commit_and_push_translations).
    if translated_slugs:
        if not git_commit_and_push_translations(translated_slugs):
            send_telegram_alert(
                "⚠️ *Post-publish poller*\n"
                f"Translation batch flush failed for: {', '.join(translated_slugs[:5])}"
            )

    # Mark done
    if done_slugs:
        try:
            api_post("/api/intel/post-publish-queue/done", {"slugs": done_slugs})
            log(f"✅ Done: {done_slugs}")
        except Exception as e:
            log(f"⚠ Error marking done: {e}")

    # Mark failed (will retry on next poll, up to 5 attempts)
    for item in failed_items:
        slug = item["slug"]
        steps = item["steps"]
        attempts = item["attempts"]
        try:
            api_post("/api/intel/post-publish-queue/failed", {
                "slugs": [slug],
                "error": f"Failed steps: {', '.join(steps)}",
            })
            log(f"⚠ Failed: {slug} (steps: {steps}, attempt {attempts}/5)")
        except Exception as e:
            log(f"⚠ Error marking failed: {e}")

        # Telegram alert after 2+ attempts
        if attempts >= 2:
            send_telegram_alert(
                f"⚠️ *Post-publish pipeline*\n"
                f"Article: `{slug}`\n"
                f"Failed steps: {', '.join(steps)}\n"
                f"Attempt: {attempts}/5\n"
                f"{'🔴 Will be dead-lettered after 5' if attempts >= 4 else '🔄 Will retry'}"
            )

    log("🏁 Poller completed")


if __name__ == "__main__":
    main()
