"""AUTO-GENERATED — DO NOT EDIT MANUALLY.

Source: apps/mata-garuda/data/nb_round1_candidates_2026-05-07.json
Regenerator: apps/mata-garuda/scripts/build_registry_from_manifest.py
Last regenerated: 2026-05-07

This file is REGENERATED after EACH NLM transition during APOPTOSIS
to guarantee crash-safety. Do not import anything beyond `typing.Final`.
"""
from __future__ import annotations

from typing import Final

REGISTRY_DATA: Final[dict[str, dict]] = {
    "1ed02e54-542f-426a-94f8-53c5ffde4b7d": {
        "name": "NB-INTEL-Immigration",
        "family": "NB-INTEL",
        "legacy_key": "immigration",
        "status": "ACTIVE",
        "cluster": None,
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "305f5f2e-d2f4-4f77-a771-c2b7aa0867e4": {
        "name": "Mata Garuda Self-Evolving Research",
        "family": None,
        "legacy_key": "self_evolving",
        "status": "ACTIVE",
        "cluster": None,
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "7fb12c9c-4e12-4a8d-9bd1-c5b857bf310f": {
        "name": "NB-INTEL-Tax",
        "family": "NB-INTEL",
        "legacy_key": "tax",
        "status": "ACTIVE",
        "cluster": None,
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "9d262101-abeb-4e15-af9c-c38e028c62fe": {
        "name": "NB-INTEL-Press",
        "family": "NB-INTEL",
        "legacy_key": "press",
        "status": "ACTIVE",
        "cluster": None,
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "a17f134e-b9ab-42d9-bfc2-5bbc45165c76": {
        "name": "NB-INTEL-Regulation",
        "family": "NB-INTEL",
        "legacy_key": "regulation",
        "status": "ACTIVE",
        "cluster": None,
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000001": {
        "name": "Innervation Research — LLM Autonomic Computing",
        "family": None,
        "legacy_key": None,
        "status": "KILL_PENDING",
        "cluster": "placeholder_empty",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": "ORPHAN_REVIEW",
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000002": {
        "name": "CELL Organism — Autonomous Living Agent",
        "family": None,
        "legacy_key": None,
        "status": "KILL_PENDING",
        "cluster": "placeholder_empty",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": "ORPHAN_REVIEW",
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000003": {
        "name": "Google Drive Automation — Deep Research 2026",
        "family": None,
        "legacy_key": None,
        "status": "KILL_PENDING",
        "cluster": "placeholder_empty",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": "ORPHAN_REVIEW",
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000004": {
        "name": "Guida alla Migrazione KBLI 2025",
        "family": None,
        "legacy_key": None,
        "status": "EXPORT_PENDING",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": "ORPHAN_REVIEW",
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000005": {
        "name": "Guida Fiscale Indonesia 2026",
        "family": None,
        "legacy_key": None,
        "status": "EXPORT_PENDING",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": "ORPHAN_REVIEW",
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000006": {
        "name": "Guida agli Investimenti Immobiliari a Bali 2026",
        "family": None,
        "legacy_key": None,
        "status": "EXPORT_PENDING",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": "ORPHAN_REVIEW",
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000007": {
        "name": "Guida alla Costituzione Societaria PT PMA Indonesia 2026",
        "family": None,
        "legacy_key": None,
        "status": "EXPORT_PENDING",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": "ORPHAN_REVIEW",
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000008": {
        "name": "Guida alla Costituzione di una PT PMA in Indonesia 2026",
        "family": None,
        "legacy_key": None,
        "status": "EXPORT_PENDING",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": "ORPHAN_REVIEW",
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000009": {
        "name": "Panduan Visa dan Pajak Indonesia 2026",
        "family": None,
        "legacy_key": None,
        "status": "EXPORT_PENDING",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": "ORPHAN_REVIEW",
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000010": {
        "name": "Panduan Visa Indonesia dan Ketentuan Izin Tinggal 2026",
        "family": None,
        "legacy_key": None,
        "status": "EXPORT_PENDING",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": "ORPHAN_REVIEW",
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000011": {
        "name": "Panduan Investasi Properti Bali 2026",
        "family": None,
        "legacy_key": None,
        "status": "EXPORT_PENDING",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": "ORPHAN_REVIEW",
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000012": {
        "name": "Panduan Navigasi Pajak dan Investasi Asing Indonesia 2026",
        "family": None,
        "legacy_key": None,
        "status": "EXPORT_PENDING",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": "ORPHAN_REVIEW",
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000013": {
        "name": "Panduan Lengkap Pendirian PT PMA Indonesia 2026",
        "family": None,
        "legacy_key": None,
        "status": "EXPORT_PENDING",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": "ORPHAN_REVIEW",
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000014": {
        "name": "Bali Zero — Mengapa Memberi Makan KITA Membuat Kita Lebih Kuat (Apr 2026)",
        "family": None,
        "legacy_key": None,
        "status": "EXPORT_PENDING",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": "ORPHAN_REVIEW",
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000015": {
        "name": "Bali 2026: La Via del Mare tra Aeroporto e Canggu",
        "family": None,
        "legacy_key": None,
        "status": "EXPORT_PENDING",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": "ORPHAN_REVIEW",
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000016": {
        "name": "Nuove Procedure di Verifica OTP per Visti Imigrasi",
        "family": None,
        "legacy_key": None,
        "status": "EXPORT_PENDING",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": "ORPHAN_REVIEW",
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000017": {
        "name": "BZ Morning News — Multi-Domain Briefing",
        "family": None,
        "legacy_key": None,
        "status": "EXPORT_PENDING",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": "ORPHAN_REVIEW",
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000018": {
        "name": "Unidentified NB orphan 1",
        "family": None,
        "legacy_key": None,
        "status": "ORPHAN_REVIEW",
        "cluster": "orphan_unclear",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000019": {
        "name": "Unidentified NB orphan 2",
        "family": None,
        "legacy_key": None,
        "status": "ORPHAN_REVIEW",
        "cluster": "orphan_unclear",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000020": {
        "name": "Unidentified NB orphan 3",
        "family": None,
        "legacy_key": None,
        "status": "ORPHAN_REVIEW",
        "cluster": "orphan_unclear",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000021": {
        "name": "Unidentified NB orphan 4",
        "family": None,
        "legacy_key": None,
        "status": "ORPHAN_REVIEW",
        "cluster": "orphan_unclear",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000022": {
        "name": "Unidentified NB orphan 5",
        "family": None,
        "legacy_key": None,
        "status": "ORPHAN_REVIEW",
        "cluster": "orphan_unclear",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000023": {
        "name": "Unidentified NB orphan 6",
        "family": None,
        "legacy_key": None,
        "status": "ORPHAN_REVIEW",
        "cluster": "orphan_unclear",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000024": {
        "name": "Unidentified NB orphan 7",
        "family": None,
        "legacy_key": None,
        "status": "ORPHAN_REVIEW",
        "cluster": "orphan_unclear",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000025": {
        "name": "Unidentified NB orphan 8",
        "family": None,
        "legacy_key": None,
        "status": "ORPHAN_REVIEW",
        "cluster": "orphan_unclear",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000026": {
        "name": "Claude Code optimization research 2026-04-21",
        "family": None,
        "legacy_key": None,
        "status": "ORPHAN_REVIEW",
        "cluster": "research_heavy",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000027": {
        "name": "Digital Sovereignty & Ancestral Wisdom AI",
        "family": None,
        "legacy_key": None,
        "status": "ORPHAN_REVIEW",
        "cluster": "research_heavy",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000028": {
        "name": "Analisi Video AI Agency",
        "family": None,
        "legacy_key": None,
        "status": "ORPHAN_REVIEW",
        "cluster": "research_heavy",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000029": {
        "name": "World Models 2026 — Comprehensive Survey",
        "family": None,
        "legacy_key": None,
        "status": "ORPHAN_REVIEW",
        "cluster": "research_heavy",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000030": {
        "name": "Nexus — Palantir Architecture",
        "family": None,
        "legacy_key": None,
        "status": "ORPHAN_REVIEW",
        "cluster": "research_heavy",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000031": {
        "name": "NB-SUBHI Onboarding Frontend SEO CRO 2026-04-30",
        "family": None,
        "legacy_key": None,
        "status": "ORPHAN_REVIEW",
        "cluster": "subhi_merge",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000032": {
        "name": "NB-SUBHI Misi 60 Hari Probation 2026-04-30",
        "family": None,
        "legacy_key": None,
        "status": "ORPHAN_REVIEW",
        "cluster": "subhi_merge",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000033": {
        "name": "NB-NLM-ELEVATION SOTA research & brainstorm 2026-04-25",
        "family": None,
        "legacy_key": None,
        "status": "ORPHAN_REVIEW",
        "cluster": "subhi_merge",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000034": {
        "name": "NB-CRM-VIP Top Clients Bali Zero",
        "family": None,
        "legacy_key": None,
        "status": "ORPHAN_REVIEW",
        "cluster": "subhi_merge",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000035": {
        "name": "Indonesia Restaurant Investment Regulatory Guide 2026",
        "family": None,
        "legacy_key": None,
        "status": "ORPHAN_REVIEW",
        "cluster": "zero_value_orphan",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "aaaaaaaa-aaaa-aaaa-aaaa-aaaa00000036": {
        "name": "Indonesian Foreign Investment Real Estate & Tax",
        "family": None,
        "legacy_key": None,
        "status": "ORPHAN_REVIEW",
        "cluster": "zero_value_orphan",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "dc5d01cd-e99f-4c8f-aae4-75060b43d0de": {
        "name": "NB-INTEL-AIResearch",
        "family": "NB-INTEL",
        "legacy_key": "ai_research",
        "status": "ACTIVE",
        "cluster": None,
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
}
