"""AUTO-GENERATED — DO NOT EDIT MANUALLY.

Source: apps/mata-garuda/data/nb_round1_candidates_2026-05-07.json
Regenerator: apps/mata-garuda/scripts/build_registry_from_manifest.py
Last regenerated: 2026-05-07

This file is REGENERATED after EACH NLM transition during APOPTOSIS
to guarantee crash-safety. Do not import anything beyond `typing.Final`.
"""
from __future__ import annotations

from typing import Final

REGISTRY_DATA: Final[dict[str, dict]] = {
    "04c5901d-398e-42df-85f0-d6acaf681cb7": {
        "name": "Panduan Investasi Properti Bali 2026: Regulasi dan Kepemilikan Asing",
        "family": None,
        "legacy_key": None,
        "status": "APOPTOSIS_DONE",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "1542c35c-5cca-4125-b150-8daeefed0e67": {
        "name": "Panduan Navigasi Pajak dan Investasi Asing Indonesia 2026",
        "family": None,
        "legacy_key": None,
        "status": "APOPTOSIS_DONE",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "1ed02e54-542f-426a-94f8-53c5ffde4b7d": {
        "name": "NB-INTEL-Immigration",
        "family": "NB-INTEL",
        "legacy_key": "immigration",
        "status": "ACTIVE",
        "cluster": None,
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "201b4b94-deda-40a9-9fcb-0e67a3f81e52": {
        "name": "Digital Sovereignty & Ancestral Wisdom AI",
        "family": None,
        "legacy_key": None,
        "status": "MERGED",
        "cluster": "research_heavy",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "2779f061-155e-4063-a052-cc36ac0a1479": {
        "name": "Google Drive Automation Deep Research 2026",
        "family": None,
        "legacy_key": None,
        "status": "APOPTOSIS_DONE",
        "cluster": "placeholder_empty",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "2aaaa564-1bf9-4df0-b1d7-2516b9e3f6b1": {
        "name": "Guida agli Investimenti Immobiliari a Bali 2026",
        "family": None,
        "legacy_key": None,
        "status": "APOPTOSIS_DONE",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "2d602f12-3370-4834-afca-52c0f7922fe9": {
        "name": "Panduan Lengkap Pendirian PT PMA Indonesia 2026",
        "family": None,
        "legacy_key": None,
        "status": "APOPTOSIS_DONE",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "305f5f2e-d2f4-4f77-a771-c2b7aa0867e4": {
        "name": "Mata Garuda Self-Evolving Research",
        "family": None,
        "legacy_key": "self_evolving",
        "status": "ACTIVE",
        "cluster": None,
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "404d0985-d7fa-4aa9-a4f0-92f07d3cfc2b": {
        "name": "Bali 2026: La Via del Mare tra Aeroporto e Canggu",
        "family": None,
        "legacy_key": None,
        "status": "APOPTOSIS_DONE",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "46b4dfe0-2be9-4fe4-97cd-3d44ef28a8ab": {
        "name": "NB-NLM-ELEVATION — SOTA research & brainstorm 2026-04-25",
        "family": None,
        "legacy_key": None,
        "status": "DELETED",
        "cluster": "subhi_merge",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "4a8f3162-6f63-4876-9fe9-642dd9ae0606": {
        "name": "Analisi Video AI Agency",
        "family": None,
        "legacy_key": None,
        "status": "DELETED",
        "cluster": "research_heavy",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "50396b3e-b2f9-4903-8df5-65c2b9709eba": {
        "name": "Claude Code optimization research 2026-04-21",
        "family": None,
        "legacy_key": None,
        "status": "MERGED",
        "cluster": "research_heavy",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "552072ab-7f09-4cda-a13c-0988f414d36d": {
        "name": "NB-SUBHI Onboarding Frontend SEO CRO 2026-04-30",
        "family": None,
        "legacy_key": None,
        "status": "DELETE_VERIFIED_NOT_LIVE",
        "cluster": "subhi_merge",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "57482a88-5d80-4bcc-8c8d-85834e56d47a": {
        "name": "Guida alla Migrazione KBLI 2025: Conformità e Nuovi Codici Indonesianiof",
        "family": None,
        "legacy_key": None,
        "status": "APOPTOSIS_DONE",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "5a034b71-a426-4976-953a-b07d989edd78": {
        "name": "Nuove Procedure di Verifica OTP per Visti Imigrasi",
        "family": None,
        "legacy_key": None,
        "status": "APOPTOSIS_DONE",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "7f12203a-fc7a-4ef9-b918-07c395a39d71": {
        "name": "BZ Morning News — Multi-Domain Briefing",
        "family": None,
        "legacy_key": None,
        "status": "APOPTOSIS_DONE",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "7fb12c9c-4e12-4a8d-9bd1-c5b857bf310f": {
        "name": "NB-INTEL-Tax",
        "family": "NB-INTEL",
        "legacy_key": "tax",
        "status": "ACTIVE",
        "cluster": None,
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "917a1300-61ac-4fdb-8d94-8a42503c0442": {
        "name": "World Models 2026 — Comprehensive Survey (Genie, Waypoint, GameNGen, SORA)",
        "family": None,
        "legacy_key": None,
        "status": "MERGED",
        "cluster": "research_heavy",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "91fd4fd1-0ff4-436e-81ed-e3488762ae32": {
        "name": "Innervation Research — LLM Autonomic Computing 2024-2026",
        "family": None,
        "legacy_key": None,
        "status": "APOPTOSIS_DONE",
        "cluster": "placeholder_empty",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "9530b58d-cb7b-4bda-b5c2-c68e723b8118": {
        "name": "Indonesia Restaurant Investment and Regulatory Guide 2026",
        "family": None,
        "legacy_key": None,
        "status": "DELETE_VERIFIED_NOT_LIVE",
        "cluster": "zero_value_orphan",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "9a866adc-988c-407f-9920-60dabf5ab164": {
        "name": "NB-SUBHI Misi 60 Hari Probation 2026-04-30",
        "family": None,
        "legacy_key": None,
        "status": "DELETE_VERIFIED_NOT_LIVE",
        "cluster": "subhi_merge",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "9d262101-abeb-4e15-af9c-c38e028c62fe": {
        "name": "NB-INTEL-Press",
        "family": "NB-INTEL",
        "legacy_key": "press",
        "status": "ACTIVE",
        "cluster": None,
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "a17f134e-b9ab-42d9-bfc2-5bbc45165c76": {
        "name": "NB-INTEL-Regulation",
        "family": "NB-INTEL",
        "legacy_key": "regulation",
        "status": "ACTIVE",
        "cluster": None,
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "b249bf4c-52fb-448a-b09b-0f29b1184c8d": {
        "name": "Guida alla Costituzione Societaria PT PMA Indonesia 2026",
        "family": None,
        "legacy_key": None,
        "status": "APOPTOSIS_DONE",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "ccf76d52-243a-4ed3-942a-ff8ab48ee8e3": {
        "name": "Guida Fiscale Indonesia 2026: Strategie e Conformità per Stranieri",
        "family": None,
        "legacy_key": None,
        "status": "APOPTOSIS_DONE",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "d97ff70b-9c14-42a3-8813-5416039b24f7": {
        "name": "Nexus — Palantir Architecture Deep Research",
        "family": None,
        "legacy_key": None,
        "status": "MERGED",
        "cluster": "research_heavy",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "da94d615-0140-4b46-8484-f24a423a91ce": {
        "name": "NB-CRM-VIP — Top Clients Bali Zero",
        "family": None,
        "legacy_key": None,
        "status": "DELETE_VERIFIED_NOT_LIVE",
        "cluster": "subhi_merge",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "dab1aa9f-02fa-473e-9e7a-1859d90b9067": {
        "name": "Bali Zero — Mengapa Memberi Makan KITA Membuat Kita Lebih Kuat (April 2026)",
        "family": None,
        "legacy_key": None,
        "status": "APOPTOSIS_DONE",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "dc1d15ee-a1ca-4f1b-b088-74d902dac75d": {
        "name": "CELL Organism - Autonomous Living Agent Research",
        "family": None,
        "legacy_key": None,
        "status": "APOPTOSIS_DONE",
        "cluster": "placeholder_empty",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "dc5d01cd-e99f-4c8f-aae4-75060b43d0de": {
        "name": "NB-INTEL-AIResearch",
        "family": "NB-INTEL",
        "legacy_key": "ai_research",
        "status": "ACTIVE",
        "cluster": None,
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "dd8ad7fe-7ad2-4b42-bb02-1d8c7039a349": {
        "name": "Guida alla Costituzione di una PT PMA in Indonesia 2026",
        "family": None,
        "legacy_key": None,
        "status": "APOPTOSIS_DONE",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "e2e26ad8-db55-42ee-96ce-52294ae9776c": {
        "name": "Panduan Visa dan Pajak Indonesia 2026",
        "family": None,
        "legacy_key": None,
        "status": "APOPTOSIS_DONE",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
    "f2422359-df5e-44f9-b730-7222644cf8bf": {
        "name": "Panduan Visa Indonesia dan Ketentuan Izin Tinggal 2026",
        "family": None,
        "legacy_key": None,
        "status": "APOPTOSIS_DONE",
        "cluster": "playbook_artifact",
        "created_at": None,
        "last_audited": "2026-05-07",
        "action_pending": None,
        "peer_uuids": [],
    },
}
