#!/usr/bin/env python3
"""lesson_harvester.py — P7 FASE-6 safe slice: the LEARN loop, in SHADOW MODE.

P7's cardinal paradox (§0): closing a self-modifying LEARN loop is *more*
dangerous than leaving it open WHEN the verifier is imperfect (P1) — a wrong
lesson becomes a permanent hook that blocks correct code. The resolution is to
**decouple PROPOSAL from APPLICATION**: the loop may close on *generating*
candidate rules, but adoption stays gated + reversible (shadow-mode + human-gate
+ kill-switch).

This slice implements ONLY the safe half — the *proposal* generator — and
NOTHING of the application half. It:

  • reads the cicatrix scar ledger (the rich, already-abundant objective signal
    that breaks the starvation cascade §3.3),
  • keeps ONLY scars anchored to an OBJECTIVE EXTERNAL EVENT (commit SHA / PR# /
    CI run / failing test / exit code) — gate G1, breaking the hallucination
    echo-chamber (§3.1),
  • clusters scars by recurrence (explicit `Family:` tags + repeated W-numbers)
    and emits a mechanical-pipeline candidate ONLY for patterns recurring ≥3
    times — gate G4 (§3.5); everything else is routed to the consultive
    judgment pipeline,
  • writes a SHADOW report (JSON + markdown) of *proposals* — it NEVER creates a
    hook, NEVER edits settings.json, NEVER promotes anything to enforcement.
    Gate G2 (proposal ≠ application) is satisfied structurally: this script has
    no code path that activates a rule.

Kill-switch (gate G3): `LESSON_HARVESTER_OFF=1` → the script exits 0 doing
nothing. Because it has zero enforcement power, "disable" is trivially complete.

Usage:
    python3 agent-library/learn/lesson_harvester.py            # write shadow report
    python3 agent-library/learn/lesson_harvester.py --check    # exit 1 if report stale
    python3 agent-library/learn/lesson_harvester.py --stdout    # print JSON only
    python3 agent-library/learn/lesson_harvester.py --self-test # internal assertions

Standard library only. No network, no DB, no PII, no LLM call. Pure read of a
tracked text ledger -> a tracked JSON/MD proposal artifact.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from pathlib import Path

_SCRIPT = Path(__file__).resolve()
# agent-library/learn/lesson_harvester.py -> repo root is two parents up.
REPO_ROOT = _SCRIPT.parent.parent.parent
SCAR_LEDGER = REPO_ROOT / ".claude" / "rules" / "cicatrix-scars.md"
OUT_JSON = REPO_ROOT / "agent-library" / "learn" / "proposals" / "lesson-proposals.json"
OUT_MD = REPO_ROOT / "agent-library" / "learn" / "proposals" / "lesson-proposals.md"

RECURRENCE_THRESHOLD = 3  # gate G4: <3 occurrences stays consultive

GENERATED_HEADER = (
    "SHADOW-MODE proposals — GENERATED by agent-library/learn/lesson_harvester.py. "
    "These are PROPOSALS ONLY. Nothing here is enforced. No hook is created, no "
    "settings.json is touched. Human-gate + shadow promotion required before any "
    "rule becomes active (P7 §3.4, gates G2/G3)."
)

# --- objective-anchor detection (gate G1) -----------------------------------
# A scar qualifies as an objective-signal lesson ONLY if its Reference / body
# cites a verifiable external event. We do NOT trust agent interpretation alone.
_ANCHOR_PATTERNS = [
    re.compile(r"\bcommit\s+`?[0-9a-f]{7,40}`?", re.IGNORECASE),
    re.compile(r"\bPR\s*#\s*\d+", re.IGNORECASE),
    re.compile(r"\b(?:gh|CI)\s+run\s+\d+", re.IGNORECASE),
    re.compile(r"\brun\s+\d{6,}", re.IGNORECASE),
    re.compile(r"\btest_[A-Za-z0-9_]+\.py", re.IGNORECASE),
    re.compile(r"\bexit\s*(?:code\s*)?[=:]?\s*[0-9]", re.IGNORECASE),
    re.compile(r"REAL_LINT_EXIT", re.IGNORECASE),
    re.compile(r"\bmigration\s+\d+", re.IGNORECASE),
]

_W_NUMBER = re.compile(r"\bW(\d+)\b")
_FAMILY = re.compile(r"[Ff]amily[:)]?\s*([^.\n]+)")
_SEVERITY = re.compile(r"Severity:\s*\*{0,2}(P[0-3]|RESOLVED|INFO)", re.IGNORECASE)
_HEADER = re.compile(r"^###\s+(.*)$")


class Scar:
    __slots__ = ("title", "body", "severity", "w_numbers", "families", "has_anchor")

    def __init__(self, title: str, body: str):
        self.title = title.strip()
        self.body = body
        sev = _SEVERITY.search(body)
        self.severity = sev.group(1).upper() if sev else "UNKNOWN"
        self.w_numbers = sorted({f"W{m}" for m in _W_NUMBER.findall(title + body)})
        self.families = [f.strip().lower() for f in _FAMILY.findall(body)]
        self.has_anchor = any(p.search(body) for p in _ANCHOR_PATTERNS)


def parse_scars(text: str) -> list[Scar]:
    """Split the ledger into scar entries on `### ` headers. The archive section
    at the bottom is excluded (it's a list, not live scars)."""
    # cut off the "## Archived" tail — those are pointers, not full scars.
    archived_idx = text.find("\n## Archived")
    if archived_idx != -1:
        text = text[:archived_idx]
    scars: list[Scar] = []
    cur_title: str | None = None
    cur_lines: list[str] = []
    for line in text.splitlines():
        m = _HEADER.match(line)
        if m:
            if cur_title is not None:
                scars.append(Scar(cur_title, "\n".join(cur_lines)))
            cur_title = m.group(1)
            cur_lines = []
        elif cur_title is not None:
            cur_lines.append(line)
    if cur_title is not None:
        scars.append(Scar(cur_title, "\n".join(cur_lines)))
    return scars


def _recurrence_counts(scars: list[Scar]) -> tuple[Counter, Counter]:
    """Count how often each W-number and each family appears across ALL scars.
    A pattern that recurs is the objective recurrence signal (G4)."""
    w_counter: Counter = Counter()
    fam_counter: Counter = Counter()
    for s in scars:
        for w in s.w_numbers:
            w_counter[w] += 1
        for fam in s.families:
            # normalize family label to a short key (first 6 words)
            key = " ".join(fam.split()[:6])
            fam_counter[key] += 1
    return w_counter, fam_counter


def harvest(scars: list[Scar]) -> dict:
    """Produce the shadow proposal set. Each scar is classified:
    - rejected_no_anchor: fails G1 (no objective event) -> not eligible.
    - mechanical_candidate: anchored AND part of a recurring (>=3) pattern.
    - consultive: anchored but single-occurrence -> judgment pipeline (G4).
    """
    w_counter, fam_counter = _recurrence_counts(scars)

    recurring_w = {w for w, c in w_counter.items() if c >= RECURRENCE_THRESHOLD}
    recurring_fam = {f for f, c in fam_counter.items() if c >= RECURRENCE_THRESHOLD}

    mechanical: list[dict] = []
    consultive: list[dict] = []
    rejected: list[dict] = []

    for s in scars:
        if not s.has_anchor:
            rejected.append({"title": s.title, "reason": "no objective anchor (G1)"})
            continue
        # does this scar belong to a recurring pattern?
        matched_w = sorted(set(s.w_numbers) & recurring_w)
        matched_fam = sorted(
            f
            for f in {" ".join(x.split()[:6]) for x in s.families}
            if f in recurring_fam
        )
        record = {
            "title": s.title,
            "severity": s.severity,
            "w_numbers": s.w_numbers,
            "recurring_via": {"w": matched_w, "family": matched_fam},
        }
        if matched_w or matched_fam:
            record["pipeline"] = "mechanical"
            record["note"] = (
                "Recurring objective pattern (>=3). Candidate for an EXECUTABLE "
                "antibody via scar_replay -> test -> SHADOW -> (human-gate) -> "
                "enforcement. NOT auto-applied."
            )
            mechanical.append(record)
        else:
            record["pipeline"] = "consultive"
            record["note"] = (
                "Single-occurrence (count<3). Routed to the judgment pipeline as "
                "a consultive checklist item, NOT a hook (G4)."
            )
            consultive.append(record)

    return {
        "_generated": True,
        "_header": GENERATED_HEADER,
        "_mode": "shadow",
        "_enforcement": "none",
        "recurrence_threshold": RECURRENCE_THRESHOLD,
        "totals": {
            "scars_scanned": len(scars),
            "mechanical_candidates": len(mechanical),
            "consultive": len(consultive),
            "rejected_no_anchor": len(rejected),
        },
        "recurring_patterns": {
            "w_numbers": {
                w: c for w, c in sorted(w_counter.items()) if c >= RECURRENCE_THRESHOLD
            },
            "families": {
                f: c
                for f, c in sorted(fam_counter.items())
                if c >= RECURRENCE_THRESHOLD
            },
        },
        "mechanical_candidates": sorted(mechanical, key=lambda r: r["title"]),
        "consultive": sorted(consultive, key=lambda r: r["title"]),
        "rejected_no_anchor": sorted(rejected, key=lambda r: r["title"]),
    }


def render_json(report: dict) -> str:
    return json.dumps(report, indent=2, ensure_ascii=False, sort_keys=False) + "\n"


def render_md(report: dict) -> str:
    t = report["totals"]
    lines = [
        "<!-- " + GENERATED_HEADER + " -->",
        "# LEARN — Shadow Lesson Proposals (P7 FASE-6)",
        "",
        "> **SHADOW MODE — zero enforcement.** This report PROPOSES; it does not",
        "> apply. No hook is created, no `settings.json` touched. Promotion to an",
        "> active rule requires shadow-period + zero false-positives + human-gate",
        "> (P7 §3.4). Kill-switch: `LESSON_HARVESTER_OFF=1`.",
        "",
        f"- scars scanned: **{t['scars_scanned']}**",
        f"- mechanical candidates (recurring ≥{report['recurrence_threshold']}): "
        f"**{t['mechanical_candidates']}**",
        f"- consultive (single-occurrence): **{t['consultive']}**",
        f"- rejected (no objective anchor, G1): **{t['rejected_no_anchor']}**",
        "",
        "## Recurring patterns (the objective recurrence signal, G4)",
        "",
    ]
    rp = report["recurring_patterns"]
    if rp["w_numbers"]:
        lines.append("**W-numbers seen ≥3×:**")
        for w, c in rp["w_numbers"].items():
            lines.append(f"- `{w}` × {c}")
        lines.append("")
    if rp["families"]:
        lines.append("**Families cited ≥3×:**")
        for f, c in rp["families"].items():
            lines.append(f"- {f} × {c}")
        lines.append("")
    if not rp["w_numbers"] and not rp["families"]:
        lines.append("_(no pattern reached the recurrence threshold this run)_")
        lines.append("")

    lines.append("## Mechanical candidates (→ scar_replay pipeline, gated)")
    lines.append("")
    if report["mechanical_candidates"]:
        for r in report["mechanical_candidates"]:
            via = r["recurring_via"]
            why = ", ".join(via["w"] + via["family"]) or "—"
            lines.append(f"- **{r['title']}** [{r['severity']}] — recurring via: {why}")
    else:
        lines.append("_(none — no anchored scar is part of a ≥3 recurring pattern)_")
    lines.append("")

    lines.append("## Consultive (→ judgment pipeline, NOT a hook)")
    lines.append("")
    if report["consultive"]:
        for r in report["consultive"]:
            lines.append(f"- {r['title']} [{r['severity']}]")
    else:
        lines.append("_(none)_")
    lines.append("")

    lines.append("## Rejected — no objective anchor (gate G1)")
    lines.append("")
    if report["rejected_no_anchor"]:
        for r in report["rejected_no_anchor"]:
            lines.append(f"- {r['title']} — {r['reason']}")
    else:
        lines.append("_(none — every scanned scar had an objective anchor)_")
    lines.append("")
    return "\n".join(lines)


def write_report(report: dict) -> None:
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(render_json(report), encoding="utf-8")
    OUT_MD.write_text(render_md(report), encoding="utf-8")


def _rel(p: Path) -> str:
    try:
        return str(p.relative_to(REPO_ROOT))
    except ValueError:
        return str(p)


def check_report(report: dict) -> int:
    want_json = render_json(report)
    want_md = render_md(report)
    stale = []
    if not OUT_JSON.exists() or OUT_JSON.read_text(encoding="utf-8") != want_json:
        stale.append(_rel(OUT_JSON))
    if not OUT_MD.exists() or OUT_MD.read_text(encoding="utf-8") != want_md:
        stale.append(_rel(OUT_MD))
    if stale:
        print(
            "lesson-proposals STALE — regenerate with lesson_harvester.py:\n  "
            + "\n  ".join(stale),
            file=sys.stderr,
        )
        return 1
    print(
        f"lesson-proposals OK — {report['totals']['scars_scanned']} scars, "
        f"{report['totals']['mechanical_candidates']} mechanical candidates"
    )
    return 0


def build_report() -> dict:
    if not SCAR_LEDGER.exists():
        return harvest([])
    scars = parse_scars(SCAR_LEDGER.read_text(encoding="utf-8"))
    return harvest(scars)


def _self_test() -> int:
    """Falsifiable internal assertions for G1 + G4 classification."""
    ok = True
    # G1: a scar with a commit SHA anchor is eligible; one with only prose is not.
    anchored = Scar(
        "X",
        "**Reference**: commit 6206f0cf4 fixed it. Family: foo bar baz qux quux corge",
    )
    unanchored = Scar(
        "Y", "**Reference**: discovered during a vibe check, no event cited"
    )
    if not anchored.has_anchor:
        print("SELF-TEST FAIL: anchored scar not detected", file=sys.stderr)
        ok = False
    if unanchored.has_anchor:
        print("SELF-TEST FAIL: unanchored scar falsely flagged", file=sys.stderr)
        ok = False
    # G4: a W-number appearing 3x is recurring; appearing 1x is not.
    scars = [
        Scar("a W99", "**Reference**: PR #1 ... W99"),
        Scar("b W99", "**Reference**: run 123456 ... W99"),
        Scar("c W99", "**Reference**: commit abcdef0 ... W99"),
        Scar("d W11", "**Reference**: PR #2 ... W11"),
    ]
    rep = harvest(scars)
    if rep["recurring_patterns"]["w_numbers"].get("W99") != 3:
        print("SELF-TEST FAIL: W99 not counted as recurring x3", file=sys.stderr)
        ok = False
    mech_titles = {r["title"] for r in rep["mechanical_candidates"]}
    if not {"a W99", "b W99", "c W99"} <= mech_titles:
        print(
            "SELF-TEST FAIL: recurring scars not in mechanical pipeline",
            file=sys.stderr,
        )
        ok = False
    if any(r["title"] == "d W11" for r in rep["mechanical_candidates"]):
        print(
            "SELF-TEST FAIL: single-occurrence W11 wrongly mechanical", file=sys.stderr
        )
        ok = False
    # G2 structural: the report must declare zero enforcement.
    if rep["_enforcement"] != "none" or rep["_mode"] != "shadow":
        print(
            "SELF-TEST FAIL: report not declared shadow/no-enforcement", file=sys.stderr
        )
        ok = False
    if ok:
        print("lesson_harvester self-test: OK")
        return 0
    return 1


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="LEARN shadow lesson harvester (P7).")
    ap.add_argument("--check", action="store_true", help="fail if report stale")
    ap.add_argument("--stdout", action="store_true", help="print JSON only")
    ap.add_argument("--self-test", action="store_true", help="internal assertions")
    args = ap.parse_args(argv)

    # Kill-switch (gate G3) — zero enforcement power means disable is complete.
    import os

    if os.environ.get("LESSON_HARVESTER_OFF") == "1":
        print("lesson_harvester: DISABLED via LESSON_HARVESTER_OFF=1 — no-op")
        return 0

    if args.self_test:
        return _self_test()

    report = build_report()

    if args.stdout:
        sys.stdout.write(render_json(report))
        return 0
    if args.check:
        return check_report(report)

    write_report(report)
    t = report["totals"]
    print(
        f"lesson_harvester (SHADOW) — {t['scars_scanned']} scars → "
        f"{t['mechanical_candidates']} mechanical / {t['consultive']} consultive / "
        f"{t['rejected_no_anchor']} rejected. NOTHING enforced."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
