import Combine
import SwiftUI

/// Bilingual UI strings (English / Bahasa Indonesia). Slim fork of WR2's LanguageManager —
/// only KBLI Navigator keys. Default EN, toggle EN/ID in toolbar. (Italian dropped 2026-06-24.)
@MainActor
final class LanguageManager: ObservableObject {
    enum Lang: String, CaseIterable { case en, id }
    @Published var lang: Lang = .en

    func t(_ key: String) -> String {
        let table = Self.strings[lang] ?? Self.strings[.en]!
        return table[key] ?? Self.strings[.en]?[key] ?? key
    }

    static let strings: [Lang: [String: String]] = [
        .en: [
            "app.title": "KBLI Navigator",
            "nav.search": "Search",
            "nav.media": "Media",
            "nav.chat": "Zantara",
            "nav.togglelist": "Show / hide the code list",
            "nav.list": "Codes",
            "nav.section.codes": "Codes",
            "nav.section.library": "Library",
            "nav.section.assistant": "Assistant",
            "search.placeholder": "Search code or activity…",
            "search.results": "results",
            "search.truncated": "first %d of %d — refine your search",
            "search.empty": "No results",
            "search.pick": "Select a code to see details",
            "detail.national": "National PMA",
            "detail.bali": "Bali status",
            "detail.moratorium": "Bali moratorium",
            "detail.description": "Description",
            "detail.scope": "Scope (ruang lingkup)",
            "detail.licensing": "Licensing per scale",
            "detail.risk": "Risk",
            "detail.permit": "Permit",
            "detail.term": "Term",
            "detail.duties": "Obligations",
            "detail.authority": "Authority",
            "detail.ask": "Ask Zantara",
            "chat.you": "You",
            "chat.thinking": "Zantara is typing…",
            "chat.suggest1": "Can I open a PT PMA for this code in Bali?",
            "chat.suggest2": "What minimum capital is required?",
            "chat.suggest3": "Is this code blocked by the moratorium?",
            "rich.gold": "Gold-Tier Intel",
            "rich.verdict.open": "YOU CAN DO THIS — the verdict",
            "rich.verdict.blocked": "HEADS UP — the verdict",
            "rich.fact.pma": "Max foreign",
            "rich.fact.risk": "Risk",
            "rich.fact.scales": "Scales",
            "rich.fact.sector": "Sector",
            "rich.meaning": "What it means",
            "rich.bali": "Bali context — reality check",
            "rich.whofor": "Who it's for",
            "rich.related": "Related codes",
            "rich.changed": "What changed in 2025",
            "rich.cta.title": "Ask Zantara about this code",
            "dossier.authority": "Authority & legal basis",
            "dossier.dasarhukum": "Dasar Hukum — legal basis",
            "dossier.kewenangan": "Kewenangan — licensing authority",
            "dossier.pbumku": "PB UMKU — ancillary licenses",
            "dossier.regulasi": "Regulasi — governing rules",
            "dossier.verified": "Verified",
            "dossier.holding.blocked": "A PT PMA cannot register this code in Bali.",
            "dossier.holding.open": "Open to foreign ownership.",
            "media.articles": "Articles",
            "media.chapters": "Book chapters",
            "media.book": "Book (PDF)",
            "chat.title": "Zantara — KBLI 2025",
            "chat.lead": "KBLI & Bali-moratorium expert. Answers grounded on Bali Zero sources.",
            "chat.placeholder": "Ask about a code, an activity, the moratorium…",
            "chat.send": "Send",
            "chat.reset": "New chat",
            // Phase 2 (2026-08-19, design §4): host/vendor-free by design — the message names no
            // internal infrastructure regardless of WHY the brain is unavailable (no seat, wrong
            // codex version, BKPM policy gate, ...).
            "chat.unavailable": "Chat requires the assistant seat on this Mac — the navigator's pages remain fully available.",
            "chat.narrow": "Please narrow the comparison to at most 3 KBLI codes.",
            "chat.tooLong": "That question is too long — please shorten it and try again.",
            "chat.unverifiable": "The assistant produced an unverifiable answer — try rephrasing.",
            "chat.internalError": "Something went wrong preparing this answer — please try again.",
            "data.missing": "KBLI dataset missing — rebuild the bundle (build.sh).",
            // D4 "Anima Indonesiana" (2026-08-11)
            "empty.hint.trySearch": "Try “villa”, “coffee” or a code — e.g. 55203",
            "empty.hint.spelling": "Check the spelling, or search by code",
            "about.title": "About KBLI Navigator",
            "about.tagline": "Bali Zero · KBLI 2025",
            "about.provenance": "1,559 codes · dataset verified %@ · Perpres 10/2021 & 49/2021 · PP 28/2025",
            "about.closing": "Menuju Indonesia Emas 2045",
        ],
        .id: [
            "app.title": "KBLI Navigator",
            "nav.search": "Cari",
            "nav.media": "Media",
            "nav.chat": "Zantara",
            "nav.togglelist": "Tampilkan / sembunyikan daftar kode",
            "nav.list": "Kode",
            "nav.section.codes": "Kode",
            "nav.section.library": "Pustaka",
            "nav.section.assistant": "Asisten",
            "search.placeholder": "Cari kode atau kegiatan…",
            "search.results": "hasil",
            "search.truncated": "%d pertama dari %d — persempit pencarian",
            "search.empty": "Tidak ada hasil",
            "search.pick": "Pilih kode untuk melihat detail",
            "detail.national": "PMA nasional",
            "detail.bali": "Status Bali",
            "detail.moratorium": "Moratorium Bali",
            "detail.description": "Deskripsi",
            "detail.scope": "Ruang lingkup",
            "detail.licensing": "Perizinan per skala",
            "detail.risk": "Risiko",
            "detail.permit": "Perizinan",
            "detail.term": "Jangka waktu",
            "detail.duties": "Kewajiban",
            "detail.authority": "Kewenangan",
            "detail.ask": "Tanya Zantara",
            "chat.you": "Anda",
            "chat.thinking": "Zantara sedang mengetik…",
            "chat.suggest1": "Bisakah saya buka PT PMA untuk kode ini di Bali?",
            "chat.suggest2": "Berapa modal minimum yang dibutuhkan?",
            "chat.suggest3": "Apakah kode ini diblokir moratorium?",
            "rich.gold": "Gold-Tier Intel",
            "rich.verdict.open": "BISA — putusan",
            "rich.verdict.blocked": "PERHATIAN — putusan",
            "rich.fact.pma": "Maks asing",
            "rich.fact.risk": "Risiko",
            "rich.fact.scales": "Skala",
            "rich.fact.sector": "Sektor",
            "rich.meaning": "Apa artinya",
            "rich.bali": "Konteks Bali — reality check",
            "rich.whofor": "Untuk siapa",
            "rich.related": "Kode terkait",
            "rich.changed": "Yang berubah di 2025",
            "rich.cta.title": "Tanya Zantara tentang kode ini",
            "dossier.authority": "Kewenangan & dasar hukum",
            "dossier.dasarhukum": "Dasar Hukum",
            "dossier.kewenangan": "Kewenangan — otoritas perizinan",
            "dossier.pbumku": "PB UMKU — izin penunjang",
            "dossier.regulasi": "Regulasi — aturan terkait",
            "dossier.verified": "Diverifikasi",
            "dossier.holding.blocked": "PT PMA tidak dapat mendaftarkan kode ini di Bali.",
            "dossier.holding.open": "Terbuka untuk kepemilikan asing.",
            "media.articles": "Artikel",
            "media.chapters": "Bab buku",
            "media.book": "Buku (PDF)",
            "chat.title": "Zantara — KBLI 2025",
            "chat.lead": "Ahli KBLI & moratorium Bali. Menjawab berdasarkan sumber Bali Zero.",
            "chat.placeholder": "Tanya tentang kode, kegiatan, moratorium…",
            "chat.send": "Kirim",
            "chat.reset": "Chat baru",
            "chat.unavailable": "Chat memerlukan seat asisten di Mac ini — halaman navigator tetap tersedia sepenuhnya.",
            "chat.narrow": "Mohon batasi perbandingan pada maksimal 3 kode KBLI.",
            "chat.tooLong": "Pertanyaan terlalu panjang — mohon persingkat dan coba lagi.",
            "chat.unverifiable": "Asisten menghasilkan jawaban yang tidak dapat diverifikasi — coba ungkapkan ulang.",
            "chat.internalError": "Terjadi kesalahan saat menyiapkan jawaban ini — silakan coba lagi.",
            "data.missing": "Dataset KBLI hilang — bangun ulang bundle (build.sh).",
            // D4 "Anima Indonesiana" (2026-08-11)
            "empty.hint.trySearch": "Coba “vila”, “kopi” atau kode — mis. 55203",
            "empty.hint.spelling": "Periksa ejaan, atau cari dengan kode",
            "about.title": "Tentang KBLI Navigator",
            "about.tagline": "Bali Zero · KBLI 2025",
            "about.provenance": "1.559 kode · dataset diverifikasi %@ · Perpres 10/2021 & 49/2021 · PP 28/2025",
            "about.closing": "Menuju Indonesia Emas 2045",
        ],
    ]
}
