-- 151_observed_shell_events.sql
--
-- Observed-shell tier — Sprint 0 Track C2
-- Reference: brainstorm 2026-05-02 round 2 § "Codex observed-shell tier"
--
-- Purpose: lightweight observability sink for non-cell automations
-- (translation hourly, BI exchange-rate, regulatory monitors, backup,
-- NLM refresh, webhook ingest) that DON'T need full cell-core
-- infrastructure but DO need a durable trace of "did it run? did it
-- succeed?" so monitoring catches silent failures.
--
-- Distinct from events_outbox (mig 144): events_outbox is for cell IPC
-- (every event MUST be replayed by the EventBus listener on reconnect).
-- observed_shell_events is fire-and-store ONLY — consumers (dashboards,
-- alerters) poll or subscribe via dedicated channel.
--
-- Schema:
--   * id BIGINT IDENTITY  : monotonic ordering
--   * automation_name TEXT NOT NULL : e.g. 'translate-hourly', 'wr2.hardening.run'
--   * status TEXT NOT NULL CHECK : ok | error | warning | skipped
--   * payload JSONB        : free-form, opaque to schema. Recommended keys:
--                            duration_ms, item_count, error_class
--   * trace_id TEXT NULL   : tie to upstream trace if available
--   * created_at           : default now()
--
-- Indexes:
--   * (automation_name, created_at DESC) — fast "last 7 days for X"
--   * (status, created_at DESC) WHERE status != 'ok' — fast "errors today"
--
-- Pruning policy: NOT enforced by this migration. A cron LaunchAgent on
-- Pro should DELETE WHERE created_at < NOW() - INTERVAL '90 days' nightly.
-- Tracked as Sprint 1 follow-up.

CREATE TABLE IF NOT EXISTS observed_shell_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    automation_name TEXT NOT NULL,
    status      TEXT NOT NULL CHECK (status IN ('ok', 'error', 'warning', 'skipped')),
    payload     JSONB NOT NULL DEFAULT '{}'::jsonb,
    trace_id    TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes below: brand-new empty table, no lock contention possible.
-- Concurrent index creation buys nothing on a 0-row table. Squawk warnings
-- for require-concurrent-index-creation, require-timeout-settings,
-- ban-drop-table, ban-drop-column, require-concurrent-index-deletion are
-- excluded at the workflow level (.github/workflows/migration-lint.yml)
-- because squawk-cli 2.50.0 does not recognize per-statement
-- `-- squawk-ignore: <rule>` comments (they generate spurious
-- `unused-ignore` warnings).
CREATE INDEX IF NOT EXISTS ix_observed_shell_events_name_ts
    ON observed_shell_events (automation_name, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_observed_shell_events_status_ts
    ON observed_shell_events (status, created_at DESC)
    WHERE status != 'ok';

COMMENT ON TABLE observed_shell_events IS
    'Lightweight observability sink for non-cell automations (translation, '
    'BI feeds, regulatory monitors, backups, webhooks). Distinct from '
    'events_outbox (mig 144) which is for cell IPC. Fire-and-store; no '
    'replay semantics. Sprint 0 Track C2 (brainstorm 2026-05-02 round 2).';

COMMENT ON COLUMN observed_shell_events.automation_name IS
    'Slug for the automation. Convention: <domain>.<verb>, e.g. '
    '"wr2.hardening.run", "translate.hourly", "bi.exchange-rate.daily".';

COMMENT ON COLUMN observed_shell_events.status IS
    'ok | error | warning | skipped. Mirrors the launchctl-style success '
    'taxonomy. "skipped" covers no-op runs (nothing to do); "warning" is '
    'a partial success (e.g. 9/10 items processed).';

-- === ROLLBACK ===
-- Reverts the table and its indexes. Safe to run on any DB state because
-- DROP statements use IF EXISTS. Rolling back loses the observability log
-- but does NOT affect any other migration: no other table references
-- observed_shell_events, no other consumer reads from it (Sprint 0 wave —
-- this migration ships the schema; consumers come in Sprint 1+).
DROP INDEX IF EXISTS ix_observed_shell_events_status_ts;
DROP INDEX IF EXISTS ix_observed_shell_events_name_ts;
DROP TABLE IF EXISTS observed_shell_events;
