-- Migration 161: wr2_supervisor_heartbeat
--
-- Sprint B B3 (2026-05-08): observability table for the WR2 supervisor
-- daemon. Each tick (60s default) the supervisor inserts one row with
-- the wall-clock + a freeform `note`; a sibling watchdog reads the
-- latest row and, if older than 5 minutes, pages Telegram (P0).
--
-- Why a dedicated table (not abuse system_settings or war_room_metrics):
--   - The watchdog needs <ms read latency and ORDER BY DESC LIMIT 1
--     semantics; a typed table with an index on (written_at DESC) is
--     ideal. system_settings is a generic key/value store with no
--     temporal index.
--   - war_room_metrics is reserved for pipeline business metrics
--     (drafts/day, success rate); mixing in process-liveness signal
--     would muddy queries.
--   - Append-only: the watchdog ALWAYS reads the most recent row; old
--     rows are pruned by a daily retention cron (out of scope here,
--     tracked as a Sprint C follow-up). 1440 rows/day × 30 days =
--     ~43k rows steady state — negligible.
--
-- Decisions:
--   - written_at is TIMESTAMPTZ DEFAULT NOW() so the supervisor can
--     omit it in INSERT (one fewer round-trip).
--   - note is TEXT (not enum) so the supervisor can label intermittent
--     events ("startup", "post-reconnect", "drain") without a future
--     migration. Bounded to 200 chars in code, but no SQL CHECK.
--   - id BIGINT IDENTITY (not UUID) — append-only, insert-heavy,
--     never referenced by FK.

-- =====================================================================
-- 1. Table
-- =====================================================================

CREATE TABLE IF NOT EXISTS wr2_supervisor_heartbeat (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    written_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    note        TEXT
);

-- =====================================================================
-- 2. Index for watchdog reads (latest row + lag query)
-- =====================================================================
-- Squawk: brand-new empty table → CREATE INDEX (non-CONCURRENTLY) is
-- safe; there are no concurrent writers contending for the lock.
-- The lint defaults flag this regardless, so suppress explicitly.

-- squawk-ignore: prefer-big-int
-- squawk-ignore: require-concurrent-index-creation
CREATE INDEX IF NOT EXISTS idx_wr2_supervisor_heartbeat_written_at
    ON wr2_supervisor_heartbeat (written_at DESC);

COMMENT ON TABLE wr2_supervisor_heartbeat IS
  'WR2 supervisor liveness probe; latest row drives the watchdog P0 alert.';
COMMENT ON COLUMN wr2_supervisor_heartbeat.written_at IS
  'Wall-clock when the supervisor wrote the row.';
COMMENT ON COLUMN wr2_supervisor_heartbeat.note IS
  'Free-text label (startup|tick|post-reconnect|drain) for forensic.';

-- === ROLLBACK ===
-- Soft rollback: drop the table + index. No referential integrity
-- impact; the table is observability-only and consumers (watchdog,
-- supervisor) handle missing-table gracefully (degraded mode).

DROP INDEX IF EXISTS idx_wr2_supervisor_heartbeat_written_at;
DROP TABLE IF EXISTS wr2_supervisor_heartbeat;
