-- migration 171_intel_item_nb_pushes
-- Junction table tracking each (intel_item, nb_uuid) push attempt.
-- Resolves the N:M problem: 1 intel_item may target multiple NB-INTEL UUIDs;
-- success on UUID-A + failure on UUID-B must not double-push A or false-mark B.
-- Tri-LLM round 1 review (Codex + DeepSeek) flagged the v1 design's
-- `nb_pushed_at` column on intel_items as broken for this exact reason.
-- Consumed by the Pro-local intel-lake-nb-pusher cron (Tier 1.5).

CREATE TABLE IF NOT EXISTS intel_item_nb_pushes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id UUID NOT NULL REFERENCES intel_items(id) ON DELETE CASCADE,
    nb_uuid UUID NOT NULL,
    content_hash TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending','pushed','failed_transient','failed_permanent','quarantined')),
    attempts BIGINT NOT NULL DEFAULT 0,
    pushed_at TIMESTAMPTZ,
    last_error TEXT,
    last_error_class TEXT,
    push_method TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_intel_item_nb_pushes UNIQUE (item_id, nb_uuid, content_hash)
);

-- Empty table, no lock contention possible → CONCURRENTLY not needed.
-- prefer-bigint-over-int + require-concurrent-index-creation are excluded
-- globally via CLI; no inline ignore directives needed.
CREATE INDEX IF NOT EXISTS idx_intel_item_nb_pushes_pending
    ON intel_item_nb_pushes (created_at)
    WHERE status IN ('pending','failed_transient');

CREATE INDEX IF NOT EXISTS idx_intel_item_nb_pushes_item
    ON intel_item_nb_pushes (item_id);

COMMENT ON TABLE intel_item_nb_pushes IS
    'Tracks each (intel_item, NB-INTEL UUID) push attempt. One row per target NB. '
    'Status transitions: pending → pushed | failed_transient → pending (retry) | '
    'failed_transient → failed_permanent (max attempts) | * → quarantined (manual). '
    'Created by Pro-local intel-lake-nb-pusher cron 2026-05-13.';

COMMENT ON COLUMN intel_item_nb_pushes.last_error_class IS
    'auth_expired | rate_limit | quota | not_found | timeout | network | unknown';

COMMENT ON COLUMN intel_item_nb_pushes.push_method IS
    'url | text — which envelope was used for the successful push (NULL if not yet pushed)';

-- === ROLLBACK ===
DROP TABLE IF EXISTS intel_item_nb_pushes;
