-- migration 189: clients.strategic_recap (separate from machine notes)
-- The `notes` column has become a machine log of [Auto-enriched ...] appends.
-- This migration adds:
--   strategic_recap        — human-curated summary, also auto-updateable by an
--                            on-demand Ollama summarizer (Phase 4). MAX ~2000 chars.
--   strategic_recap_updated_at, strategic_recap_source
--
-- The CRM client page should display strategic_recap as the primary "client story"
-- field, and notes should be shown collapsed (machine logs) for audit only.
-- Source: research/operations/2026-05-20-wa-chat-flow-synthesis.md (Phase 4 Situation Card)

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                 WHERE table_name='clients' AND column_name='strategic_recap') THEN
    ALTER TABLE clients
      ADD COLUMN strategic_recap TEXT DEFAULT NULL,
      ADD COLUMN strategic_recap_updated_at TIMESTAMPTZ DEFAULT NULL,
      ADD COLUMN strategic_recap_source TEXT DEFAULT NULL
        CHECK (strategic_recap_source IN ('manual','ollama_local','wa_auto','human_curated') OR strategic_recap_source IS NULL);
  END IF;
END$$;

COMMENT ON COLUMN clients.strategic_recap IS
  'Curated client summary (1-3 paragraphs). Auto-generated by local Ollama from WA conversation + practices + interactions, then editable by team. Max ~2000 chars. Source separated from machine log notes.';

COMMENT ON COLUMN clients.strategic_recap_source IS
  'manual = team typed it, ollama_local = qwen3.5:9b auto-summary, wa_auto = first inbound block, human_curated = corrected by team after auto.';

-- === ROLLBACK ===

ALTER TABLE clients
  DROP COLUMN IF EXISTS strategic_recap,
  DROP COLUMN IF EXISTS strategic_recap_updated_at,
  DROP COLUMN IF EXISTS strategic_recap_source;
