-- migration 200_wa_copilot_infrastructure
-- WA Copilot infrastructure: conversations + extractions append-only + entity_links
-- + practice_candidates + team_promises + action_queue + col additive on
-- whatsapp_message_context (BASE TABLE) + user notification prefs.
--
-- Tri-LLM panel synthesis 2026-05-25 (Gemini 3.1 Pro + Codex GPT-5.5 +
-- DeepSeek V4 Pro reasoning_effort=high, 2 rounds 3/3 convergent on
-- schema design). Decision document:
--   research/operations/2026-05-25-wa-corpus-monetization-tri-llm-synthesis.md
--
-- CRITICAL DISCOVERY 2026-05-25 first-apply attempt:
-- whatsapp_message_context_enriched is a VIEW (computed), not a BASE TABLE.
-- Base table is whatsapp_message_context (41 columns already). View is
-- generated by a CREATE VIEW elsewhere in the schema. ALTER additions
-- MUST go on whatsapp_message_context (base), then view auto-reflects
-- on next refresh OR view definition needs SELECT extension.
--
-- Columns already present in whatsapp_message_context (DO NOT re-add):
-- - client_id, practice_id, direction, source, team_member_email,
--   phone_number, counterpart_lid (existing)
-- Columns NEW from this migration:
-- - conversation_id, source_system, external_message_id, sender_role,
--   team_member_id, identity_confidence, identity_method, language_primary,
--   has_sensitive_pii, retention_class, legal_hold, body_redacted, body_hash,
--   ingest_batch_id, schema_version

BEGIN;

-- A0. WhatsApp export/backfill staging tables.
-- These are used by scripts/whatsapp_export_backfill/import_staging.py and
-- provide the FK target for whatsapp_message_context.ingest_batch_id below.
CREATE TABLE IF NOT EXISTS whatsapp_export_batches (
    id BIGSERIAL PRIMARY KEY,
    source_root TEXT NOT NULL,
    source_label TEXT NOT NULL,
    source_hash TEXT NOT NULL UNIQUE,
    chat_title TEXT,
    canonical_chat_path TEXT,
    status TEXT NOT NULL DEFAULT 'parsed',
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_by TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_wa_export_batches_status_created
    ON whatsapp_export_batches (status, created_at DESC);

CREATE TABLE IF NOT EXISTS whatsapp_export_messages_staging (
    id BIGSERIAL PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES whatsapp_export_batches(id) ON DELETE CASCADE,
    source_relpath TEXT NOT NULL,
    message_index INTEGER NOT NULL,
    message_date TIMESTAMPTZ,
    sender_display_name TEXT,
    body TEXT,
    body_excerpt TEXT,
    has_attachments BOOLEAN NOT NULL DEFAULT false,
    attachment_relpaths JSONB NOT NULL DEFAULT '[]'::jsonb,
    review_status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (batch_id, source_relpath, message_index)
);
CREATE INDEX IF NOT EXISTS idx_wa_export_msg_date
    ON whatsapp_export_messages_staging (message_date DESC);
CREATE INDEX IF NOT EXISTS idx_wa_export_msg_review
    ON whatsapp_export_messages_staging (review_status, created_at DESC);

CREATE TABLE IF NOT EXISTS whatsapp_export_documents_staging (
    id BIGSERIAL PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES whatsapp_export_batches(id) ON DELETE CASCADE,
    source_relpath TEXT NOT NULL,
    file_name TEXT,
    file_ext TEXT,
    file_size_bytes BIGINT,
    sha256 TEXT,
    document_category TEXT,
    match_reasons JSONB NOT NULL DEFAULT '[]'::jsonb,
    contains_sensitive_data BOOLEAN NOT NULL DEFAULT true,
    review_status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (batch_id, source_relpath)
);
CREATE INDEX IF NOT EXISTS idx_wa_export_doc_review
    ON whatsapp_export_documents_staging (review_status, document_category);
CREATE INDEX IF NOT EXISTS idx_wa_export_doc_sha256
    ON whatsapp_export_documents_staging (sha256)
    WHERE sha256 IS NOT NULL;

CREATE TABLE IF NOT EXISTS whatsapp_export_contacts_staging (
    id BIGSERIAL PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES whatsapp_export_batches(id) ON DELETE CASCADE,
    source_relpath TEXT NOT NULL,
    display_name TEXT,
    phone_raw TEXT,
    phone_canonical TEXT,
    waid TEXT,
    match_reasons JSONB NOT NULL DEFAULT '[]'::jsonb,
    review_status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uix_wa_export_contacts_batch_rel_phone
    ON whatsapp_export_contacts_staging (batch_id, source_relpath, COALESCE(phone_canonical, ''));
CREATE INDEX IF NOT EXISTS idx_wa_export_contacts_phone
    ON whatsapp_export_contacts_staging (phone_canonical)
    WHERE phone_canonical IS NOT NULL;

-- A. whatsapp_conversations
CREATE TABLE IF NOT EXISTS whatsapp_conversations (
    conversation_id BIGSERIAL PRIMARY KEY,
    client_id BIGINT REFERENCES clients(id),
    practice_id BIGINT REFERENCES practices(id),
    phone_e164 TEXT NOT NULL,
    lid TEXT,
    source_group_id TEXT,
    service_line TEXT,
    lifecycle_stage TEXT,
    outcome TEXT,
    owner_team_member TEXT,
    started_at TIMESTAMPTZ,
    last_customer_at TIMESTAMPTZ,
    last_team_at TIMESTAMPTZ,
    confidence NUMERIC(3, 2),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_wa_conv_phone ON whatsapp_conversations (phone_e164);
CREATE INDEX IF NOT EXISTS idx_wa_conv_client_stage ON whatsapp_conversations (client_id, lifecycle_stage);
CREATE INDEX IF NOT EXISTS idx_wa_conv_practice ON whatsapp_conversations (practice_id);
CREATE INDEX IF NOT EXISTS idx_wa_conv_last_cust ON whatsapp_conversations (last_customer_at DESC);

-- B. whatsapp_extractions (append-only)
CREATE TABLE IF NOT EXISTS whatsapp_extractions (
    extraction_id BIGSERIAL PRIMARY KEY,
    message_id BIGINT NOT NULL,
    conversation_id BIGINT REFERENCES whatsapp_conversations(conversation_id),
    client_id BIGINT REFERENCES clients(id),
    practice_id BIGINT REFERENCES practices(id),
    fact_type TEXT NOT NULL,
    fact_value JSONB NOT NULL,
    mention_text TEXT NOT NULL,
    span_start INTEGER,
    span_end INTEGER,
    language_hint TEXT,
    confidence NUMERIC(3, 2) CHECK (confidence BETWEEN 0 AND 1),
    extractor_name TEXT NOT NULL,
    extractor_version TEXT NOT NULL,
    model TEXT NOT NULL,
    prompt_version TEXT NOT NULL,
    review_status TEXT DEFAULT 'pending',
    reviewed_by TEXT,
    reviewed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_wa_extr_msg_fact ON whatsapp_extractions (message_id, fact_type);
CREATE INDEX IF NOT EXISTS idx_wa_extr_conv_fact ON whatsapp_extractions (conversation_id, fact_type, confidence DESC);
CREATE INDEX IF NOT EXISTS idx_wa_extr_practice ON whatsapp_extractions (practice_id, fact_type);

-- C. whatsapp_entity_links (N:M kg_nodes)
CREATE TABLE IF NOT EXISTS whatsapp_entity_links (
    link_id BIGSERIAL PRIMARY KEY,
    extraction_id BIGINT REFERENCES whatsapp_extractions(extraction_id) ON DELETE CASCADE,
    entity_id TEXT NOT NULL,
    link_confidence NUMERIC(3, 2) CHECK (link_confidence BETWEEN 0 AND 1),
    link_method TEXT NOT NULL,
    reviewer_status TEXT DEFAULT 'unreviewed',
    reviewed_by TEXT,
    reviewed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (extraction_id, entity_id)
);
CREATE INDEX IF NOT EXISTS idx_wa_links_entity ON whatsapp_entity_links (entity_id);

-- D. whatsapp_practice_candidates (probabilistic)
CREATE TABLE IF NOT EXISTS whatsapp_practice_candidates (
    candidate_id BIGSERIAL PRIMARY KEY,
    conversation_id BIGINT REFERENCES whatsapp_conversations(conversation_id),
    message_id BIGINT,
    practice_id BIGINT NOT NULL REFERENCES practices(id),
    confidence NUMERIC(3, 2) NOT NULL,
    signals JSONB NOT NULL,
    status TEXT DEFAULT 'pending_review',
    reviewer_id TEXT,
    reviewed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_wa_pcand_conv ON whatsapp_practice_candidates (conversation_id, confidence DESC);
CREATE INDEX IF NOT EXISTS idx_wa_pcand_pending ON whatsapp_practice_candidates (status) WHERE status = 'pending_review';

-- E. team_promises
CREATE TABLE IF NOT EXISTS team_promises (
    promise_id BIGSERIAL PRIMARY KEY,
    message_id BIGINT NOT NULL,
    conversation_id BIGINT REFERENCES whatsapp_conversations(conversation_id),
    client_id BIGINT REFERENCES clients(id),
    promise_text TEXT NOT NULL,
    promise_type TEXT,
    due_at TIMESTAMPTZ,
    resolved BOOLEAN DEFAULT false,
    resolved_at TIMESTAMPTZ,
    resolved_by_message_id BIGINT,
    created_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_team_promises_unresolved ON team_promises (resolved, due_at) WHERE resolved = false;

-- F. action_queue (THE UI surface)
CREATE TABLE IF NOT EXISTS action_queue (
    action_id BIGSERIAL PRIMARY KEY,
    client_id BIGINT REFERENCES clients(id),
    practice_id BIGINT REFERENCES practices(id),
    conversation_id BIGINT REFERENCES whatsapp_conversations(conversation_id),
    action_type TEXT NOT NULL,
    reason TEXT NOT NULL,
    recommended_action TEXT NOT NULL,
    suggested_message_draft TEXT,
    due_at TIMESTAMPTZ,
    evidence JSONB NOT NULL,
    owner TEXT,
    priority INTEGER DEFAULT 5,
    status TEXT DEFAULT 'open',
    snoozed_until TIMESTAMPTZ,
    dismiss_reason TEXT,
    dedup_key TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    resolved_at TIMESTAMPTZ,
    resolution_notes TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS uix_action_queue_open_dedup
    ON action_queue (dedup_key)
    WHERE status IN ('open', 'snoozed');
CREATE INDEX IF NOT EXISTS idx_action_queue_owner ON action_queue (owner, status, priority DESC, due_at);
CREATE INDEX IF NOT EXISTS idx_action_queue_status_due ON action_queue (status, due_at);

-- G. ALTER whatsapp_message_context (BASE TABLE — NOT enriched view)
-- Skip already-existing columns: client_id, practice_id, direction, source,
-- team_member_email, phone_number, counterpart_lid
ALTER TABLE whatsapp_message_context
    ADD COLUMN IF NOT EXISTS conversation_id BIGINT REFERENCES whatsapp_conversations(conversation_id),
    ADD COLUMN IF NOT EXISTS source_system TEXT,
    ADD COLUMN IF NOT EXISTS external_message_id TEXT,
    ADD COLUMN IF NOT EXISTS sender_role TEXT,
    ADD COLUMN IF NOT EXISTS team_member_id BIGINT,
    ADD COLUMN IF NOT EXISTS identity_confidence NUMERIC(3, 2),
    ADD COLUMN IF NOT EXISTS identity_method TEXT,
    ADD COLUMN IF NOT EXISTS language_primary TEXT,
    ADD COLUMN IF NOT EXISTS has_sensitive_pii BOOLEAN DEFAULT false,
    ADD COLUMN IF NOT EXISTS retention_class TEXT,
    ADD COLUMN IF NOT EXISTS legal_hold BOOLEAN DEFAULT false,
    ADD COLUMN IF NOT EXISTS body_redacted TEXT,
    ADD COLUMN IF NOT EXISTS body_hash TEXT,
    ADD COLUMN IF NOT EXISTS ingest_batch_id BIGINT REFERENCES whatsapp_export_batches(id),
    ADD COLUMN IF NOT EXISTS schema_version TEXT DEFAULT 'v1.0';
CREATE INDEX IF NOT EXISTS idx_wa_msg_conv ON whatsapp_message_context (conversation_id);
CREATE INDEX IF NOT EXISTS idx_wa_msg_sender_role ON whatsapp_message_context (sender_role);
CREATE INDEX IF NOT EXISTS idx_wa_msg_identity ON whatsapp_message_context (identity_method, identity_confidence DESC);

-- H. team_members notification prefs
-- NOTE: real table is team_members (not users — Bali Zero stack uses
-- team_members since legacy Node.js backend, mapped via SQLAlchemy
-- User class in apps/backend-rag/backend/app/modules/identity/models.py).
-- Existing notification_prefs table (migration 135) uses user_id UUID
-- but team_members.id is VARCHAR(36) — FK complexity. Inline 4 cols
-- on team_members (9-10 users, trivial cost).
ALTER TABLE team_members
    ADD COLUMN IF NOT EXISTS telegram_chat_id TEXT,
    ADD COLUMN IF NOT EXISTS notify_in_app BOOLEAN DEFAULT true,
    ADD COLUMN IF NOT EXISTS notify_telegram BOOLEAN DEFAULT false,
    ADD COLUMN IF NOT EXISTS notify_email_digest BOOLEAN DEFAULT true;
CREATE INDEX IF NOT EXISTS idx_team_members_telegram_chat_id
    ON team_members (telegram_chat_id)
    WHERE telegram_chat_id IS NOT NULL;

COMMIT;

-- === ROLLBACK ===
-- Inline rollback per W42 lint requirement (cicatrix RESOLVED 2026-05-23).
-- Drops new tables CASCADE + removes additive columns from whatsapp_message_context
-- and team_members. Indexes drop with parent tables.
-- BEGIN;
--
-- DROP INDEX IF EXISTS idx_team_members_telegram_chat_id;
-- ALTER TABLE team_members
--     DROP COLUMN IF EXISTS notify_email_digest,
--     DROP COLUMN IF EXISTS notify_telegram,
--     DROP COLUMN IF EXISTS notify_in_app,
--     DROP COLUMN IF EXISTS telegram_chat_id;
--
-- ALTER TABLE whatsapp_message_context
--     DROP COLUMN IF EXISTS schema_version,
--     DROP COLUMN IF EXISTS ingest_batch_id,
--     DROP COLUMN IF EXISTS body_hash,
--     DROP COLUMN IF EXISTS body_redacted,
--     DROP COLUMN IF EXISTS legal_hold,
--     DROP COLUMN IF EXISTS retention_class,
--     DROP COLUMN IF EXISTS has_sensitive_pii,
--     DROP COLUMN IF EXISTS language_primary,
--     DROP COLUMN IF EXISTS identity_method,
--     DROP COLUMN IF EXISTS identity_confidence,
--     DROP COLUMN IF EXISTS team_member_id,
--     DROP COLUMN IF EXISTS sender_role,
--     DROP COLUMN IF EXISTS external_message_id,
--     DROP COLUMN IF EXISTS source_system,
--     DROP COLUMN IF EXISTS conversation_id;
--
-- DROP TABLE IF EXISTS action_queue CASCADE;
-- DROP TABLE IF EXISTS team_promises CASCADE;
-- DROP TABLE IF EXISTS whatsapp_practice_candidates CASCADE;
-- DROP TABLE IF EXISTS whatsapp_entity_links CASCADE;
-- DROP TABLE IF EXISTS whatsapp_extractions CASCADE;
-- DROP TABLE IF EXISTS whatsapp_conversations CASCADE;
-- DROP TABLE IF EXISTS whatsapp_export_contacts_staging CASCADE;
-- DROP TABLE IF EXISTS whatsapp_export_documents_staging CASCADE;
-- DROP TABLE IF EXISTS whatsapp_export_messages_staging CASCADE;
-- DROP TABLE IF EXISTS whatsapp_export_batches CASCADE;
--
-- COMMIT;
