#!/usr/bin/env python3
"""brand_api_gen.py — P8 FASE-5 safe slice: generate the unified component
build-artifact (`components.json` + human catalog) from the React `.tsx`
sources, deterministically, with ZERO cloud and ZERO PII.

This is the *fonte unificata GENERATA* of P8 §3.1: a build-artifact derived
from the `.tsx` files, NOT a hand-written God-object. Re-running it after a
`.tsx` change re-derives the artifact, so it cannot silently diverge (gate G6).

Design choices (verified disk-state, not the spec's stale Explore):
- The spec said "12 components"; the real tree has 23 `.tsx` (12 top-level +
  11 under `apps/`). We parse ALL of them so the artifact never inherits the
  spec's undercount.
- The monorepo is `npm` workspaces, NOT pnpm, and `react-docgen-typescript`
  is not a dependency. Adding a TS-compiler-backed docgen would be a heavy new
  dep + a JS toolchain dependency. So this slice uses a *pure-Python*
  deterministic parser: it extracts the component name, its `Props` interface
  fields, the import path, and a synthesized usage example. `useWhen` keywords
  are derived heuristically from the name/props (honest + bounded), or left
  empty — never invented.

The output is intentionally minimal and falsifiable:
- `components.json` carries a `_generated` header block (gate G6).
- It is byte-deterministic given the same inputs (sorted keys, stable order),
  so `--check` can assert "regenerating produces no diff" in CI.

Usage:
    python3 scripts/brand_api_gen.py            # write artifacts
    python3 scripts/brand_api_gen.py --check    # exit 1 if artifacts stale
    python3 scripts/brand_api_gen.py --stdout    # print components.json only

No network, no DB, no third-party imports. Standard library only.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# --- repo-relative roots (resolved from this file, never hardcoded abs) ------
_SCRIPT = Path(__file__).resolve()
REPO_ROOT = _SCRIPT.parent.parent
COMPONENTS_ROOT = REPO_ROOT / "packages" / "core" / "components"
OUT_JSON = REPO_ROOT / "packages" / "design-system" / "brand-api" / "components.json"
OUT_CATALOG = REPO_ROOT / "docs" / "design" / "components-catalog.md"

# Import alias the components are published under (matches spec §3.1 example).
IMPORT_PREFIX = "@balizero/core/components"

GENERATED_HEADER = "GENERATED by scripts/brand_api_gen.py — do not edit by hand"

# Heuristic name-stem -> useWhen keywords. Honest + bounded: we only emit a
# keyword when the component name literally contains the stem. Anything not
# matched yields [] (we do NOT fabricate intent we can't read).
_USEWHEN_STEMS: dict[str, list[str]] = {
    "deadline": ["deadline", "expiry", "status urgency"],
    "badge": ["status", "label"],
    "logo": ["branding", "header"],
    "nav": ["navigation", "shell", "layout"],
    "shell": ["layout", "page frame"],
    "command": ["command palette", "search", "keyboard"],
    "context": ["side panel", "detail", "context"],
    "matter": ["case", "matter", "client record"],
    "funnel": ["funnel", "conversion", "stage"],
    "progress": ["progress", "ring", "percent"],
    "theme": ["theme", "dark mode", "provider"],
    "trust": ["trust", "social proof"],
    "whatsapp": ["whatsapp", "contact cta"],
    "cta": ["call to action", "handoff"],
    "wizard": ["multi-step", "wizard", "form flow"],
    "timeline": ["timeline", "result", "history"],
    "hero": ["hero", "landing form"],
    "share": ["share", "social"],
    "stamp": ["stamp", "reveal", "celebration"],
    "email": ["email opt-in", "lead capture"],
    "branch": ["branch selector", "choice"],
    "frame": ["frame", "container"],
    "sentence": ["sentence builder", "compose"],
}


def _iter_tsx() -> list[Path]:
    """All component .tsx, excluding test/spec files, sorted for determinism."""
    if not COMPONENTS_ROOT.is_dir():
        return []
    files = [
        p
        for p in COMPONENTS_ROOT.rglob("*.tsx")
        if not p.name.endswith((".test.tsx", ".spec.tsx"))
    ]
    return sorted(files, key=lambda p: str(p.relative_to(COMPONENTS_ROOT)))


def _component_name(src: str, path: Path) -> str:
    """Prefer the exported component identifier; fall back to filename stem."""
    # `export const Foo: FC<...>` or `export function Foo(`
    m = re.search(r"export\s+const\s+([A-Z][A-Za-z0-9]*)\s*[:=]", src)
    if m:
        return m.group(1)
    m = re.search(r"export\s+function\s+([A-Z][A-Za-z0-9]*)\s*\(", src)
    if m:
        return m.group(1)
    return path.stem


def _props_block(src: str, comp: str) -> str | None:
    """Return the raw body of `interface <X>Props { ... }` or
    `type <X>Props = { ... }`, whichever is present. None if no Props type."""
    # interface form
    m = re.search(
        r"(?:export\s+)?interface\s+[A-Za-z0-9]*Props\s*(?:extends[^\{]+)?\{",
        src,
    )
    if m:
        return _balanced_braces(src, m.end() - 1)
    # type form: type XProps = { ... }
    m = re.search(r"(?:export\s+)?type\s+[A-Za-z0-9]*Props\s*=\s*\{", src)
    if m:
        return _balanced_braces(src, m.end() - 1)
    return None


def _balanced_braces(src: str, open_idx: int) -> str | None:
    """Given index of an opening `{`, return inner text up to its match."""
    depth = 0
    for i in range(open_idx, len(src)):
        c = src[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return src[open_idx + 1 : i]
    return None


_PROP_LINE = re.compile(
    r"""^\s*
        (?P<name>[A-Za-z_][A-Za-z0-9_]*)   # prop name
        (?P<opt>\?)?                        # optional marker
        \s*:\s*
        (?P<type>[^;]+?)                    # type (non-greedy, up to ; or EOL)
        \s*;?\s*$
    """,
    re.VERBOSE,
)


def _parse_props(block: str | None) -> dict[str, str]:
    """Parse `name: type;` lines into {name: type}. Skips comments/blank.
    Multi-line union types collapse to a single spaced string."""
    if not block:
        return {}
    props: dict[str, str] = {}
    # Strip line + block comments so they don't pollute parsing.
    block = re.sub(r"//[^\n]*", "", block)
    block = re.sub(r"/\*.*?\*/", "", block, flags=re.DOTALL)
    for raw in block.split("\n"):
        line = raw.strip()
        if not line or line in ("{", "}"):
            continue
        m = _PROP_LINE.match(line)
        if not m:
            continue
        name = m.group("name")
        opt = bool(m.group("opt"))
        ptype = re.sub(r"\s+", " ", m.group("type").strip())
        props[name] = (ptype + " | undefined") if opt else ptype
    return props


def _use_when(name: str, props: dict[str, str]) -> list[str]:
    """Derive useWhen keywords from the component name stems. Honest: only
    emits for stems literally present; never fabricates."""
    low = name.lower()
    out: list[str] = []
    for stem, kws in _USEWHEN_STEMS.items():
        if stem in low:
            for kw in kws:
                if kw not in out:
                    out.append(kw)
    return out


def _example(name: str, props: dict[str, str]) -> str:
    """Synthesize a minimal JSX usage example from required props only."""
    required = [k for k, v in props.items() if "| undefined" not in v]
    if not required:
        return f"<{name} />"
    attrs = " ".join(f"{k}={{/* {props[k]} */}}" for k in required[:3])
    return f"<{name} {attrs} />"


def _import_path(path: Path) -> str:
    rel = path.relative_to(COMPONENTS_ROOT).with_suffix("")
    return f"{IMPORT_PREFIX}/{rel.as_posix()}"


def build_components() -> list[dict]:
    out: list[dict] = []
    for path in _iter_tsx():
        src = path.read_text(encoding="utf-8")
        comp = _component_name(src, path)
        props = _parse_props(_props_block(src, comp))
        out.append(
            {
                "name": comp,
                "import": _import_path(path),
                "source": path.relative_to(REPO_ROOT).as_posix(),
                "props": props,
                "useWhen": _use_when(comp, props),
                "example": _example(comp, props),
            }
        )
    # stable order by name then source for byte-determinism
    out.sort(key=lambda c: (c["name"], c["source"]))
    return out


def build_artifact() -> dict:
    components = build_components()
    return {
        "_generated": True,
        "_generator": "scripts/brand_api_gen.py",
        "_header": GENERATED_HEADER,
        "_note": (
            "Build-artifact derived from packages/core/components/*.tsx. "
            "Re-run `npm run bz:brand:api` to regenerate. Editing by hand is "
            "pointless — the next build overwrites it."
        ),
        "schema_version": 1,
        "component_count": len(components),
        "components": components,
    }


def render_json(artifact: dict) -> str:
    return json.dumps(artifact, indent=2, ensure_ascii=False, sort_keys=False) + "\n"


def render_catalog(artifact: dict) -> str:
    lines = [
        "<!-- " + GENERATED_HEADER + " -->",
        "# Bali Zero — Component Catalog (brand-api)",
        "",
        "> **GENERATED build-artifact.** Do not edit by hand — run "
        "`npm run bz:brand:api`. Derived from `packages/core/components/*.tsx`.",
        "",
        f"**{artifact['component_count']} components** "
        f"(schema v{artifact['schema_version']}).",
        "",
    ]
    for c in artifact["components"]:
        lines.append(f"## `{c['name']}`")
        lines.append("")
        lines.append(f"- **import**: `{c['import']}`")
        lines.append(f"- **source**: `{c['source']}`")
        if c["useWhen"]:
            lines.append(f"- **use when**: {', '.join(c['useWhen'])}")
        if c["props"]:
            lines.append("- **props**:")
            for pname, ptype in c["props"].items():
                lines.append(f"  - `{pname}`: `{ptype}`")
        else:
            lines.append("- **props**: _(none parsed)_")
        lines.append(f"- **example**: `{c['example']}`")
        lines.append("")
    return "\n".join(lines)


def write_artifacts(artifact: dict) -> None:
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_CATALOG.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(render_json(artifact), encoding="utf-8")
    OUT_CATALOG.write_text(render_catalog(artifact), encoding="utf-8")


def _rel(p: Path) -> str:
    """repo-relative path string, with a safe fallback when p is outside the
    repo (e.g. a tmp_path under test) so we never raise on a display call."""
    try:
        return str(p.relative_to(REPO_ROOT))
    except ValueError:
        return str(p)


def check_artifacts(artifact: dict) -> int:
    """Return 0 if on-disk artifacts match a fresh generation, else 1."""
    want_json = render_json(artifact)
    want_cat = render_catalog(artifact)
    stale = []
    if not OUT_JSON.exists() or OUT_JSON.read_text(encoding="utf-8") != want_json:
        stale.append(_rel(OUT_JSON))
    if not OUT_CATALOG.exists() or OUT_CATALOG.read_text(encoding="utf-8") != want_cat:
        stale.append(_rel(OUT_CATALOG))
    if stale:
        print(
            "brand-api STALE — regenerate with `npm run bz:brand:api`:\n  "
            + "\n  ".join(stale),
            file=sys.stderr,
        )
        return 1
    print(f"brand-api OK — {artifact['component_count']} components, artifacts fresh")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Generate the brand-api build-artifact.")
    ap.add_argument("--check", action="store_true", help="fail if artifacts stale")
    ap.add_argument("--stdout", action="store_true", help="print components.json only")
    args = ap.parse_args(argv)

    artifact = build_artifact()

    if artifact["component_count"] == 0:
        print(
            f"ERROR: no components found under {COMPONENTS_ROOT.relative_to(REPO_ROOT)}",
            file=sys.stderr,
        )
        return 2

    if args.stdout:
        sys.stdout.write(render_json(artifact))
        return 0
    if args.check:
        return check_artifacts(artifact)

    write_artifacts(artifact)
    print(
        f"brand-api generated — {artifact['component_count']} components → "
        f"{OUT_JSON.relative_to(REPO_ROOT)} + "
        f"{OUT_CATALOG.relative_to(REPO_ROOT)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
