"""
Mata Garuda — Meta-Agent Tools.

5 tool che il meta-agent usa per gestire il registry:
1. list_agents — query del registry
2. create_agent — genera un nuovo .py sotto agents/, valida con import
3. delete_agent — rimuove file agente
4. run_agent — esegue un agente per nome con una query
5. execute_command — fallback shell (con restrizioni di sicurezza)

Pattern: HKUDS/AutoAgent tools/meta/edit_agents.py semplificato.
Riferimento: docs/mata-garuda/40d-AUTOAGENT-PATTERNS.md Pattern 2
"""
from __future__ import annotations

import json
import logging
import os
import subprocess
import sys
from pathlib import Path
from string import Formatter
from textwrap import dedent

from mata_garuda.registry import register_tool, registry
from mata_garuda.security.path_firewall import (
    PathFirewallError,
    validate_agent_creation,
    validate_agent_name,
    validate_write_path,
)

logger = logging.getLogger("mata_garuda.tools")

AGENTS_DIR = Path(__file__).parent.parent / "agents"


@register_tool(name="list_agents")
def list_agents(context_variables: dict | None = None) -> str:
    """List all registered agents with their metadata."""
    info = registry.display_agents_info()
    if not info:
        return "No agents registered."

    lines = [f"Registered agents ({len(info)}):"]
    for name, meta in info.items():
        lines.append(f"  - {name} (func: {meta.get('func_name', '?')})")
        if meta.get("docstring"):
            first_line = meta["docstring"].strip().split("\n")[0]
            lines.append(f"    {first_line}")
    return "\n".join(lines)


@register_tool(name="create_agent")
def create_agent(
    agent_name: str,
    agent_description: str,
    agent_instructions: str,
    agent_tools: list[str] | None = None,
    context_variables: dict | None = None,
) -> str:
    """Create a new Mata Garuda agent file from a specification.

    Args:
        agent_name: Display name (e.g., "KBLI News Agent")
        agent_description: One-line description
        agent_instructions: System prompt for the agent
        agent_tools: List of tool function names to import (optional)
        context_variables: Shared state (injected by loop)
    """
    if agent_tools is None:
        agent_tools = []

    # Validate via path firewall
    try:
        target_path = validate_agent_creation(agent_name)
    except PathFirewallError as e:
        return f"[BLOCKED] {e}"

    # Check if already exists
    if target_path.exists():
        return f"[ERROR] Agent file already exists: {target_path}"

    # Build agent code
    safe_name = agent_name.lower().replace(" ", "_").replace("-", "_")
    func_name = f"get_{safe_name}"
    genome_path = f"{safe_name}_GENOME.md"

    # Handle format keys in instructions
    has_format_keys = any(
        t[1] is not None for t in Formatter().parse(agent_instructions)
    )

    if has_format_keys:
        format_keys = [
            t[1]
            for t in Formatter().parse(agent_instructions)
            if t[1] is not None
        ]
        kvals = ", ".join(
            f"{k}=context_variables.get('{k}', '')" for k in format_keys
        )
        instr_return = f"return {repr(agent_instructions)}.format({kvals})"
    else:
        instr_return = f"return {repr(agent_instructions)}"

    # Tool imports
    tool_imports_line = ""
    tool_list_str = "[]"
    if agent_tools:
        tool_imports_line = (
            "from mata_garuda.tools.meta_tools import "
            + ", ".join(agent_tools)
        )
        tool_list_str = "[" + ", ".join(agent_tools) + "]"

    lines = [
        '"""',
        f"Mata Garuda — {agent_name}.",
        "",
        f"{agent_description}",
        "Auto-generated by meta-agent.",
        '"""',
        "from __future__ import annotations",
        "",
        "from pathlib import Path",
        "",
        "from mata_garuda.registry import register_agent",
        "from mata_garuda.types import Agent",
    ]
    if tool_imports_line:
        lines.append(tool_imports_line)
    lines += [
        "",
        "",
        f'GENOME_FILE = str(Path(__file__).parent / "{genome_path}")',
        "",
        "",
        f'@register_agent(name="{agent_name}", func_name="{func_name}")',
        f"def {func_name}(model: str = \"claude\") -> Agent:",
        f'    """{agent_description}"""',
        "",
        "    def instructions(context_variables: dict) -> str:",
        f"        {instr_return}",
        "",
        "    return Agent(",
        f'        name="{agent_name}",',
        "        model=model,",
        "        instructions=instructions,",
        f"        functions={tool_list_str},",
        "        genome_path=GENOME_FILE,",
        "    )",
        "",
    ]
    code = "\n".join(lines)

    # Write agent file
    target_path.write_text(code)
    logger.info(f"[create_agent] Wrote {target_path}")

    # Write minimal GENOME.md
    genome_file = AGENTS_DIR / genome_path
    genome_content = dedent(f"""\
        # GENOME — {agent_name}

        ## Identity
        {agent_description}

        ## Constraints
        - Created by meta-agent
        - MUST terminate with case_resolved or case_not_resolved
        - NEVER make external API calls (CLI-only)
        - NEVER touch frontend/client/team data (OSINT blindato)

        ## Fitness
        - Success rate: N/A (new agent)
        - Mutations: 0
    """)
    genome_file.write_text(genome_content)
    logger.info(f"[create_agent] Wrote {genome_file}")

    # Validate by attempting import
    validation = subprocess.run(
        [
            sys.executable,
            "-c",
            f"import mata_garuda.agents.{safe_name}",
        ],
        capture_output=True,
        text=True,
        cwd=str(Path(__file__).parent.parent.parent),
    )

    if validation.returncode != 0:
        # Rollback: delete invalid files
        target_path.unlink(missing_ok=True)
        genome_file.unlink(missing_ok=True)
        return (
            f"[ERROR] Validation failed for {agent_name}. "
            f"Import error: {validation.stderr.strip()}\n"
            f"Agent file removed."
        )

    return (
        f"[SUCCESS] Created agent '{agent_name}' at {target_path}\n"
        f"GENOME at {genome_file}\n"
        f"Validated: import OK"
    )


@register_tool(name="delete_agent")
def delete_agent(
    agent_name: str, context_variables: dict | None = None
) -> str:
    """Delete an agent by removing its .py file and GENOME.md.

    Args:
        agent_name: Display name of the agent to delete
    """
    try:
        validate_agent_name(agent_name)
    except PathFirewallError as e:
        return f"[BLOCKED] {e}"

    safe_name = agent_name.lower().replace(" ", "_").replace("-", "_")

    # Protect core agents
    protected = {"dummy_agent", "meta_agent"}
    if safe_name in protected:
        return f"[BLOCKED] Cannot delete protected agent: {agent_name}"

    agent_file = AGENTS_DIR / f"{safe_name}.py"
    genome_file = AGENTS_DIR / f"{safe_name}_GENOME.md"

    if not agent_file.exists():
        return f"[ERROR] Agent file not found: {agent_file}"

    # Remove files
    agent_file.unlink()
    genome_file.unlink(missing_ok=True)

    # Remove from registry (runtime)
    func_name = f"get_{safe_name}"
    registry._registry["agents"].pop(func_name, None)
    registry._registry_info["agents"].pop(agent_name, None)

    logger.info(f"[delete_agent] Deleted {agent_name}")
    return f"[SUCCESS] Deleted agent '{agent_name}' and its GENOME.md"


@register_tool(name="run_agent")
def run_agent(
    agent_name: str,
    query: str,
    context_variables: dict | None = None,
) -> str:
    """Run a registered agent with a query.

    Args:
        agent_name: Display name of the agent to run
        query: The task/query to send to the agent
    """
    # Find the agent in registry
    info = registry.agents_info.get(agent_name)
    if info is None:
        available = ", ".join(registry.agents_info.keys())
        return f"[ERROR] Agent '{agent_name}' not found. Available: {available}"

    # Instantiate the agent
    agent_fn = info.func
    agent = agent_fn()

    # Run via MetaChain loop
    from mata_garuda.runtime.loop import run_agent_loop

    ctx = context_variables or {}
    response = run_agent_loop(agent=agent, query=query, context_variables=ctx)

    # Extract final output
    if response.messages:
        last_content = response.messages[-1].get("content", "")
        return f"[{agent_name}] {last_content}"

    return f"[{agent_name}] No output"


@register_tool(name="execute_command")
def execute_command(
    command: str, context_variables: dict | None = None
) -> str:
    """Execute a shell command (restricted to safe operations).

    Args:
        command: Shell command to execute
    """
    # Blocklist dangerous commands
    dangerous = [
        "rm -rf",
        "sudo",
        "chmod",
        "chown",
        "mkfs",
        "dd ",
        "curl",
        "wget",
        "> /dev",
        "kill",
        "pkill",
        "shutdown",
        "reboot",
    ]
    cmd_lower = command.lower()
    for d in dangerous:
        if d in cmd_lower:
            return f"[BLOCKED] Dangerous command rejected: contains '{d}'"

    try:
        result = subprocess.run(
            command,
            shell=True,
            capture_output=True,
            text=True,
            timeout=30,
            cwd=str(Path(__file__).parent.parent.parent),
        )
        output = result.stdout.strip()
        if result.returncode != 0:
            output += f"\n[STDERR] {result.stderr.strip()}"
        return output or "(no output)"
    except subprocess.TimeoutExpired:
        return "[ERROR] Command timed out after 30s"
