"""
Official Visa Types Seed 2026 - Series A-F
Based on verified text file: visa_indonesia_corrected_EN.txt
"""

import asyncio
import json
import os
import asyncpg

VISA_TYPES = [
    {
        "code": "A1",
        "name": "Visa-Free Tourism",
        "category": "Visa Free/VOA",
        "duration": "30 days",
        "cost_visa": "See description",
        "requirements": [],
        "description": "For tourism, visiting family, attending meetings, incentives, conventions, and exhibitions (MICE), or similar events, as well as transit in Indonesia to another country.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Visa-Free Facility is a category intended for nationals of certain countries for a single entry into Indonesia with a maximum stay permit of 30 days, calculated from the date of arrival. This stay permit cannot be extended and cannot be converted into another type of stay permit."},
    },
    {
        "code": "A4",
        "name": "Visa-Free Government Assignment",
        "category": "Visa Free/VOA",
        "duration": "30 days",
        "cost_visa": "See description",
        "requirements": [],
        "description": "To carry out government duties, visit a specific location, or conduct activities within the framework of official government duties. With this visa-free facility, you may also engage in tourism and visit friends and family.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Visa-Free Facility A4 is intended for nationals of certain countries for a single entry into Indonesia with a maximum stay permit of 30 days, calculated from the date of arrival. This stay permit cannot be extended or converted."},
    },
    {
        "code": "A36",
        "name": "Visa-Free Ship and Aircraft Crew",
        "category": "Visa Free/VOA",
        "duration": "30 days",
        "cost_visa": "See description",
        "requirements": [],
        "description": "Serving on a transport vehicle as a captain, pilot, or crew member (active crew). With this facility, you may also engage in tourism, purchase goods, and visit friends and family.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Visa-Free Facility A36 is intended for captains, pilots, or crew members for a single entry with a maximum stay of 30 days. Non-extendable and non-convertible."},
    },
    {
        "code": "A37",
        "name": "Visa-Free Ship Crew in Indonesian Waters",
        "category": "Visa Free/VOA",
        "duration": "30 days",
        "cost_visa": "See description",
        "requirements": [],
        "description": "Serving as a captain, crew member, or foreign expert on a sea vessel or floating facility that comes directly with its transport vehicle to operate in Indonesian archipelagic waters, territorial seas, continental shelf, and/or Exclusive Economic Zone. Includes tourism and visiting family.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Single entry, max 30 days, non-extendable."},
    },
    {
        "code": "B1",
        "name": "Tourism Visit Visa (Visa on Arrival)",
        "category": "VOA",
        "duration": "30 days",
        "cost_visa": "*   Visa Fee: Rp 500,000.",
        "requirements": [],
        "description": "Tourism, visiting family, attending meetings, incentives, conventions, and exhibitions (MICE), or transit.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "B1 is a Visit Visa Upon Arrival (Visa on Arrival / VoA) for eligible nationals. Single entry, initial stay of 30 days.\n*   Can be extended once.\n*   Can be converted to another stay permit type via the bridging visa mechanism."},
    },
    {
        "code": "B4",
        "name": "Government Assignment Visit Visa (VoA)",
        "category": "VOA",
        "duration": "30 days",
        "cost_visa": "Rp 500,000.  ================================================================================",
        "requirements": [],
        "description": "Carrying out government duties, official visits, or government-related activities. Includes tourism and family visits.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Visa on Arrival (B4). Single entry, 30 days initial, extendable once."},
    },
    {
        "code": "F1",
        "name": "Tourism Visit Visa (Special 7-Day VoA)",
        "category": "Visa Free/VOA",
        "duration": "See details",
        "cost_visa": "Rp 250,000.",
        "requirements": [],
        "description": "Tourism, family visits, MICE, transit.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Specific Visa on Arrival granted **only** at Seaports in the Riau Islands (Batam, Tanjung Pinang, Tanjung Uban, Tanjung Balai Karimun).\n*   **Duration:** 7 days.\n*   **Extension:** Cannot be extended.\n*   **Conversion:** Cannot be converted."},
    },
    {
        "code": "F4",
        "name": "Government Assignment Visit Visa (Special 7-Day VoA)",
        "category": "Visa Free/VOA",
        "duration": "See details",
        "cost_visa": "See description",
        "requirements": [],
        "description": "Government duties/assignments in the specific Riau Islands region.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": ""},
    },
    {
        "code": "C1",
        "name": "Tourism Visit Visa (Pre-Arranged)",
        "category": "Visit",
        "duration": "60 days",
        "cost_visa": "Rp 1,000,000 (plus verification fees if applicable).",
        "requirements": ["Passport valid for at least 6 months.", "Proof of living costs (bank statement, last 3 months) min. USD 2,000.", "Return ticket.", "Recent color photo.", "No sponsor required (unless stateless or from specific calling-visa countries)."],
        "description": "Tourism, personal development, studying tourism attractions, cruise ship travel. Also attending MICE as a participant, conducting business discussions/negotiations, signing agreements, field surveys (offices/factories/mining sites), or medical-related activities.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Visit Visa (Single Entry).\n*   **Initial Stay:** 60 days.\n*   **Extensions:** Can be extended multiple times up to a total of 180 days.\n*   **Conversion:** Can be converted to a Limited Stay Permit (ITAS)."},
    },
    {
        "code": "C2",
        "name": "Business Visit Visa",
        "category": "Visit",
        "duration": "60 days",
        "cost_visa": "Visa Fee: Rp 1,000,000 + Verification Fee: Rp 1,000,000. Total: Rp 2,000,000.",
        "requirements": ["Passport (min. 6 months validity).", "Proof of funds (bank statement).", "**Invitation letter/correspondence** from a government agency or private institution explaining the relationship."],
        "description": "Conducting business, attending meetings, purchasing goods, discussions, negotiations, signing agreements. Inspecting goods at offices/factories. Includes tourism and family visits.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Visit Visa (Single Entry). 60 days initial stay. Extendable up to 180 days total. Convertible to ITAS."},
    },
    {
        "code": "C3",
        "name": "Medical Treatment Visit Visa",
        "category": "Visit",
        "duration": "60 days",
        "cost_visa": "Rp 1,000,000.",
        "requirements": ["Sponsor letter.", "Passport.", "Proof of funds.", "Statement from a government or private institution/hospital confirming the medical treatment plan."],
        "description": "Undergoing medical treatment in Indonesia. Includes tourism/family visits.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Single Entry, 60 days initial. Extendable up to 180 days. Convertible to ITAS."},
    },
    {
        "code": "C4",
        "name": "Government Assignment Visit Visa",
        "category": "Visit",
        "duration": "60 days",
        "cost_visa": "Rp 2,000,000 (Visa Rp 1m + Verification Rp 1m).",
        "requirements": ["Invitation/statement letter from a Government Agency."],
        "description": "Government duties. Includes tourism/family visits.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Single Entry, 60 days initial. Extendable up to 12 months (1 year) total. Convertible to ITAS."},
    },
    {
        "code": "C5",
        "name": "Journalism / Media Visit Visa",
        "category": "Visit",
        "duration": "60 days",
        "cost_visa": "Rp 2,000,000.",
        "requirements": ["Press ID card.", "Invitation letter/statement from Government Agency, interview transcripts agreed by sources, or letter from Indonesian representative abroad regarding coverage plans."],
        "description": "Journalistic visits, media coverage. Includes tourism/family visits.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Single Entry, 60 days initial. Extendable up to 180 days. Convertible to ITAS."},
    },
    {
        "code": "C6",
        "name": "Social Activity Visit Visa",
        "category": "Visit",
        "duration": "60 days",
        "cost_visa": "Rp 2,000,000.",
        "requirements": ["Statement from Government/Private institution explaining details of activities."],
        "description": "Social activities (e.g., charity, humanitarian). Includes tourism/family visits.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Single Entry, 60 days initial. Extendable up to 180 days. Convertible to ITAS."},
    },
    {
        "code": "C7",
        "name": "Arts and Culture Performance Visit Visa",
        "category": "Visit",
        "duration": "30 days",
        "cost_visa": "Rp 1,500,000.",
        "requirements": ["Sponsor letter from organizer.", "Invitation letter (for general performers) OR contract/letter from impresario (for musicians/supporters).", "**Allowed to receive compensation/facilities** but prohibited from employment relationships (regular employment)."],
        "description": "Performing arts and culture (shows, music, theater, circus). Includes tourism/family visits.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Single Entry, **Maximum 30 days**. **Cannot be extended.**"},
    },
    {
        "code": "C7A",
        "name": "Music Performance Visit Visa",
        "category": "Visit",
        "duration": "30 days",
        "cost_visa": "Rp 1,500,000.",
        "requirements": ["Sponsor required.", "Guarantee letter and application from impresario/contract.", "Allowed to receive compensation/facilities for the performance."],
        "description": "Music performances.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Single Entry, Max 30 days. Non-extendable."},
    },
    {
        "code": "C7B",
        "name": "Music Performance Crew Visit Visa",
        "category": "Visit",
        "duration": "30 days",
        "cost_visa": "Rp 1,500,000.  ================================================================================",
        "requirements": [],
        "description": "Crew supporting foreign music performers.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Single Entry, Max 30 days. Non-extendable."},
    },
    {
        "code": "C8A",
        "name": "Athlete Visit Visa",
        "category": "Visit",
        "duration": "60 days",
        "cost_visa": "Rp 2,000,000.",
        "requirements": ["Sponsor required.", "Invitation letter from event organizer.", "Allowed to receive prizes/facilities but not employment salary."],
        "description": "Non-commercial sports activities (government invitation, international championships, international sports organizations).",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Single Entry, 60 days initial. Extendable up to 180 days. Convertible to ITAS."},
    },
    {
        "code": "C9",
        "name": "Short Course / Short Study Visit Visa",
        "category": "Visit",
        "duration": "60 days",
        "cost_visa": "Rp 2,000,000.",
        "requirements": ["Proof of registration/student status from the organizing institution."],
        "description": "Comparative study, short courses, short training.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Single Entry, 60 days initial. Extendable up to 180 days. Convertible to ITAS."},
    },
    {
        "code": "C10",
        "name": "Business Speaker / Lecturer Visit Visa",
        "category": "Visit",
        "duration": "60 days",
        "cost_visa": "Rp 2,000,000.",
        "requirements": ["Invitation letter detailing the agenda.", "Allowed to receive honorarium/compensation but not employment."],
        "description": "Speaker, lecturer, or presenter at MICE or similar events.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Single Entry, 60 days initial. Extendable up to 180 days. Convertible to ITAS."},
    },
    {
        "code": "C11",
        "name": "Exhibition / Product Promotion Visa (Exhibitor)",
        "category": "Visit",
        "duration": "60 days",
        "cost_visa": "Rp 2,000,000.",
        "requirements": ["Sponsor required.", "Invitation from organizer.", "**Prohibited from selling goods directly** (retail transaction) unless essential to the exhibition (bazaar/fair context rules apply)."],
        "description": "Participating in MICE events to market goods or services (Exhibitor).",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Single Entry, 60 days initial. Extendable up to 180 days. Convertible to ITAS."},
    },
    {
        "code": "C12",
        "name": "Pre-Investment Visit Visa",
        "category": "Visit",
        "duration": "60 days",
        "cost_visa": "See description",
        "requirements": ["Sponsor required.", "Proof of funds (USD 2,000).", "Documents clarifying the business relationship/intent."],
        "description": "Pre-investment visits, starting a business, field surveys, feasibility studies.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Single Entry.\n*   Option A: 60 days (Cost Rp 3,000,000).\n*   Option B: 180 days (Cost Rp 4,000,000).\n*   Extendable up to 12 months total. Convertible to ITAS."},
    },
    {
        "code": "C13",
        "name": "Vessel Joiner Visa",
        "category": "Visit",
        "duration": "60 days",
        "cost_visa": "Rp 2,000,000.",
        "requirements": ["Sponsor required.", "Letter stating intent to join vessel."],
        "description": "Joining a transport vehicle (ship/vessel) currently in Indonesian territory.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Single Entry, 60 days initial. Extendable. Convertible to ITAS."},
    },
    {
        "code": "C14",
        "name": "Film Production Visit Visa",
        "category": "Visit",
        "duration": "60 days",
        "cost_visa": "Rp 2,000,000.",
        "requirements": ["Sponsor required.", "**Filming Permit** from the relevant Government Agency."],
        "description": "Filmmaking, music videos, reality shows, documentaries, TV/radio, etc. using locations in Indonesia.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Single Entry, 60 days initial. Extendable up to 180 days. Convertible to ITAS."},
    },
    {
        "code": "C15",
        "name": "Emergency Work Visit Visa",
        "category": "Visit",
        "duration": "60 days",
        "cost_visa": "Rp 3,000,000.",
        "requirements": ["Sponsor required.", "Statement of urgency explaining why the foreign expert is needed immediately."],
        "description": "Emergency and urgent work that cannot be delegated (e.g., natural disaster recovery, machine repair, riot control).",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Single Entry, 60 days initial. Extendable. Convertible to ITAS."},
    },
    {
        "code": "C16",
        "name": "Industrial Instructor Visit Visa",
        "category": "Visit",
        "duration": "60 days",
        "cost_visa": "Rp 3,000,000.  ================================================================================",
        "requirements": [],
        "description": "Providing guidance, counseling, and training in industrial technology innovation/application.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Single Entry, 60 days initial. Extendable up to 180 days. Convertible to ITAS."},
    },
    {
        "code": "C17",
        "name": "Audit / Quality Control Visa",
        "category": "Visit",
        "duration": "60 days",
        "cost_visa": "Rp 3,000,000.  ================================================================================",
        "requirements": [],
        "description": "Auditing, production quality control, or inspection at a company branch in Indonesia.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Single Entry, 60 days initial. Extendable up to 180 days. Convertible to ITAS."},
    },
    {
        "code": "C18",
        "name": "Foreign Worker Competency Test Visa",
        "category": "Visit",
        "duration": "See details",
        "cost_visa": "Rp 4,000,000.",
        "requirements": ["Sponsor required.", "Invitation for competency test."],
        "description": "Testing proficiency/skills for work (trial).",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Single Entry, **Maximum 90 days**. **Cannot be extended.**"},
    },
    {
        "code": "C19",
        "name": "After-Sales Service Visa",
        "category": "Visit",
        "duration": "60 days",
        "cost_visa": "Rp 3,000,000.  ================================================================================",
        "requirements": [],
        "description": "Providing after-sales service for goods/products sold to consumers in Indonesia.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Single Entry, 60 days initial. Extendable. Convertible to ITAS."},
    },
    {
        "code": "C20",
        "name": "Machinery Installation/Repair Visa",
        "category": "Visit",
        "duration": "60 days",
        "cost_visa": "Rp 3,000,000.  ================================================================================",
        "requirements": [],
        "description": "Installation and repair of machinery as part of a purchase agreement from abroad.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Single Entry, 60 days initial. Extendable. Convertible to ITAS."},
    },
    {
        "code": "D1",
        "name": "Multiple Entry Tourism Visa",
        "category": "Multiple Entry",
        "duration": "5 Years",
        "cost_visa": "*   1 Year: Rp 4,000,000. *   2 Years: Rp 6,000,000. *   5 Years: Rp 11,000,000.",
        "requirements": ["Proof of funds (USD 2,000).", "Statement letter from relative (if visiting family) or invitation."],
        "description": "Tourism, family visits, MICE (attendee), transit.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Multiple Entry.\n*   **Stay per entry:** Max 60 days.\n*   **Validity:** 1, 2, or 5 Years.\n*   **Extendable:** Yes.\n*   **Convertible:** No."},
    },
    {
        "code": "D2",
        "name": "Multiple Entry Business Visa",
        "category": "Multiple Entry",
        "duration": "5 Years",
        "cost_visa": "*   1 Year: Rp 4,000,000. *   2 Years: Rp 6,000,000. *   5 Years: Rp 11,000,000.",
        "requirements": ["Invitation letter/correspondence from partner.", "Prohibited from continuous supervision of production."],
        "description": "Business, meetings, purchasing goods, negotiations.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Multiple Entry. Max 60 days per visit.\n*   **Validity:** 1, 2, or 5 Years."},
    },
    {
        "code": "D12",
        "name": "Multiple Entry Pre-Investment Visa",
        "category": "Multiple Entry",
        "duration": "See details",
        "cost_visa": "*   1 Year: Rp 5,000,000. *   2 Years: Rp 7,000,000.",
        "requirements": ["Proof of funds (USD 5,000)."],
        "description": "Pre-investment, business setup, surveys.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Multiple Entry.\n*   **Stay per entry:** Max 180 days.\n*   **Validity:** 1 or 2 Years.\n*   **Convertible:** No."},
    },
    {
        "code": "E23",
        "name": "Work Visa (Working KITAS)",
        "category": "KITAS",
        "duration": "See details",
        "cost_visa": "See description",
        "requirements": [],
        "description": "Working in Indonesia.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Limited Stay Visa (ITAS).\n\n================================================================================"},
    },
    {
        "code": "E28A",
        "name": "Investor Visa (1 or 2 Years)",
        "category": "KITAS",
        "duration": "See details",
        "cost_visa": "*   1 Year: Rp 7,000,000. *   2 Years: Rp 9,500,000.",
        "requirements": ["Proof of share ownership (min. Rp 10 billion) in the sponsor company.", "If shares are lower, must apply for a Work Visa."],
        "description": "Investing, managing a company (Director/Commissioner), establishing a company.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Limited Stay Visa (ITAS).\n*   **Duration:** 1 or 2 Years."},
    },
    {
        "code": "E28B",
        "name": "Investor Golden Visa (5 or 10 Years)",
        "category": "KITAS",
        "duration": "See details",
        "cost_visa": "*   5 Years: Rp 13,000,000. *   10 Years: Rp 19,500,000.",
        "requirements": ["**5 Years:** Establishment of a company with investment value min. USD 2,500,000.", "**10 Years:** Establishment of a company with investment value min. USD 5,000,000.", "Must be fulfilled within 90 days of arrival."],
        "description": "High-value investment/Golden Visa. Establishing a company.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Limited Stay Visa (ITAS).\n*   **Duration:** 5 or 10 Years."},
    },
    {
        "code": "E33",
        "name": "Second Home Visa (5 Years)",
        "category": "KITAS",
        "duration": "5 Years",
        "cost_visa": "Rp 13,000,000.",
        "requirements": ["Proof of funds/Guarantee (Proof of Funds) of min. **USD 130,000** (approx. Rp 2 Billion) deposited in a state-owned bank account OR purchase of property (apartment) worth min. **USD 1,000,000**.", "Must be fulfilled within 90 days."],
        "description": "Long-term stay for business, investment, or retirement.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Limited Stay Visa (ITAS).\n*   **Duration:** 5 Years."},
    },
    {
        "code": "E33G",
        "name": "Remote Worker Visa (Digital Nomad)",
        "category": "KITAS",
        "duration": "1 Year",
        "cost_visa": "Rp 7,000,000.",
        "requirements": ["Proof of income/salary min. **USD 60,000 per year**.", "Employment contract with a company outside Indonesia."],
        "description": "Staying in Indonesia while working remotely for a company **outside** Indonesia.",
        "benefits": [],
        "metadata": {"source": "official_pdf_2026", "raw_type_info": "Limited Stay Visa (ITAS).\n*   **Duration:** 1 Year."},
    },

]

async def seed_visa_types():
    """Seed all visa types into database"""
    # Connect to database - handle missing env var for local testing
    db_url = os.environ.get("DATABASE_URL")
    if not db_url:
        print("DATABASE_URL not set. Printing logic only.")
        return

    conn = await asyncpg.connect(db_url)

    try:
        print("Seeding Official 2026 Visa Types...")

        for visa in VISA_TYPES:
            # Check if exists
            exists = await conn.fetchval("SELECT 1 FROM visa_types WHERE code = $1", visa["code"])
            
            if exists:
                print(f"  ~ Updating {visa['code']}")
                await conn.execute(
                    """
                    UPDATE visa_types SET
                        name = $2,
                        category = $3,
                        duration = $4,
                        cost_visa = $5,
                        requirements = $6,
                        description = $7,
                        metadata = $8,
                        last_updated = NOW()
                    WHERE code = $1
                    """,
                    visa["code"], visa["name"], visa["category"], visa["duration"],
                    visa["cost_visa"], visa["requirements"], visa["description"],
                    json.dumps(visa["metadata"])
                )
            else:
                print(f"  + Inserting {visa['code']}")
                await conn.execute(
                    """
                    INSERT INTO visa_types (
                        code, name, category, duration, cost_visa, requirements, description, metadata, created_at, last_updated
                    ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW())
                    """,
                    visa["code"], visa["name"], visa["category"], visa["duration"],
                    visa["cost_visa"], visa["requirements"], visa["description"],
                    json.dumps(visa["metadata"])
                )

        print("Done.")

    finally:
        await conn.close()

if __name__ == "__main__":
    asyncio.run(seed_visa_types())
