import asyncio
import json
import os
import asyncpg

VISA_TYPES = [
    {'code': 'A1', 'name': 'Bebas Visa Wisata', 'category': 'Visa Free/VOA', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'For tourism, visiting family, attending meetings, incentives, conventions, and exhibitions (MICE), or similar events, as well as transit in Indonesia to another country.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'A4', 'name': 'Bebas Visa Penugasan Pemerintah', 'category': 'Visa Free/VOA', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'To carry out government duties, visit a specific location, or conduct activities within the framework of official government duties. With this visa-free facility, you may also engage in tourism and visit friends and family.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'A36', 'name': 'Bebas Visa Kru Kapal dan Pesawat', 'category': 'Visa Free/VOA', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Serving on a transport vehicle as a captain, pilot, or crew member (active crew). With this facility, you may also engage in tourism, purchase goods, and visit friends and family.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'A37', 'name': 'Bebas Visa Kru Kapal di Perairan Indonesia', 'category': 'Visa Free/VOA', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Serving as a captain, crew member, or foreign expert on a sea vessel or floating facility that comes directly with its transport vehicle to operate in Indonesian archipelagic waters, territorial seas, continental shelf, and/or Exclusive Economic Zone. Includes tourism and visiting family.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'B1', 'name': 'Visa Kunjungan Wisata', 'category': 'VOA', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Tourism, visiting family, attending meetings, incentives, conventions, and exhibitions (MICE), or transit.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False, 'government_fee_internal': '*   Visa Fee: Rp 500,000.'}},
    {'code': 'B4', 'name': 'Visa Kunjungan Penugasan Pemerintahan', 'category': 'VOA', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Carrying out government duties, official visits, or government-related activities. Includes tourism and family visits.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False, 'government_fee_internal': 'Rp 500,000.  ================================================================================'}},
    {'code': 'F1', 'name': 'Visa Kunjungan Wisata', 'category': 'Visa Free/VOA', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Tourism, family visits, MICE, transit.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False, 'government_fee_internal': 'Rp 250,000.'}},
    {'code': 'F4', 'name': 'Visa Kunjungan Penugasan Pemerintahan', 'category': 'Visa Free/VOA', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Government duties/assignments in the specific Riau Islands region.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'C1', 'name': 'Visa Kunjungan Wisata', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'IDR 2.300.000 (All-inclusive pricing)', 'requirements': ['Passport valid for at least 6 months.', 'Proof of living costs (bank statement, last 3 months) min. USD 2,000.', 'Return ticket.', 'Recent color photo.', 'No sponsor required (unless stateless or from specific calling-visa countries).'], 'description': 'Tourism, personal development, studying tourism attractions, cruise ship travel. Also attending MICE as a participant, conducting business discussions/negotiations, signing agreements, field surveys (offices/factories/mining sites), or medical-related activities.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': True, 'government_fee_internal': 'Rp 1,000,000 (plus verification fees if applicable).'}},
    {'code': 'C2', 'name': 'Visa Kunjungan Bisnis', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'IDR 3.600.000 (All-inclusive pricing)', 'requirements': ['Passport (min. 6 months validity).', 'Proof of funds (bank statement).', ''], 'description': 'Conducting business, attending meetings, purchasing goods, discussions, negotiations, signing agreements. Inspecting goods at offices/factories. Includes tourism and family visits.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': True, 'government_fee_internal': 'Visa Fee: Rp 1,000,000 + Verification Fee: Rp 1,000,000. Total: Rp 2,000,000.'}},
    {'code': 'C3', 'name': 'Visa Kunjungan Perawatan Kesehatan', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': ['Sponsor letter.', 'Passport.', 'Proof of funds.', 'Statement from a government or private institution/hospital confirming the medical treatment plan.'], 'description': 'Undergoing medical treatment in Indonesia. Includes tourism/family visits.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False, 'government_fee_internal': 'Rp 1,000,000.'}},
    {'code': 'C4', 'name': 'Visa Kunjungan Penugasan Pemerintah', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': ['Invitation/statement letter from a Government Agency.'], 'description': 'Government duties. Includes tourism/family visits.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False, 'government_fee_internal': 'Rp 2,000,000 (Visa Rp 1m + Verification Rp 1m).'}},
    {'code': 'C5', 'name': 'Visa Kunjungan Media dan Pers', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': ['Press ID card.', 'Invitation letter/statement from Government Agency, interview transcripts agreed by sources, or letter from Indonesian representative abroad regarding coverage plans.'], 'description': 'Journalistic visits, media coverage. Includes tourism/family visits.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False, 'government_fee_internal': 'Rp 2,000,000.'}},
    {'code': 'C5A', 'name': 'Visa Kunjungan Konten Kreator', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kunjungan Konten Kreator', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'C6', 'name': 'Visa Kunjungan Kegiatan Sosial', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': ['Statement from Government/Private institution explaining details of activities.'], 'description': 'Social activities (e.g., charity, humanitarian). Includes tourism/family visits.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False, 'government_fee_internal': 'Rp 2,000,000.'}},
    {'code': 'C7', 'name': 'Visa Kunjungan Penampilan Seni dan Budaya', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'IDR 4.500.000', 'requirements': ['Sponsor letter from organizer.', 'Invitation letter (for general performers) OR contract/letter from impresario (for musicians/supporters).', ''], 'description': 'Performing arts and culture (shows, music, theater, circus). Includes tourism/family visits.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': True, 'government_fee_internal': 'Rp 1,500,000.'}},
    {'code': 'C7A', 'name': 'Visa Kunjungan Penampilan Musik', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': ['Sponsor required.', 'Guarantee letter and application from impresario/contract.', 'Allowed to receive compensation/facilities for the performance.'], 'description': 'Music performances.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False, 'government_fee_internal': 'Rp 1,500,000.'}},
    {'code': 'C7B', 'name': 'Visa Kunjungan Kru Penampilan Musik', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Crew supporting foreign music performers.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False, 'government_fee_internal': 'Rp 1,500,000.  ================================================================================'}},
    {'code': 'C7C', 'name': 'Visa Kunjungan Penampilan Bakat dan Seni', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kunjungan Penampilan Bakat dan Seni', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'C8', 'name': 'Visa Kunjungan Kegiatan Olahraga', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kunjungan Kegiatan Olahraga', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'C8A', 'name': 'Visa Kunjungan Atlet Olahraga', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': ['Sponsor required.', 'Invitation letter from event organizer.', 'Allowed to receive prizes/facilities but not employment salary.'], 'description': 'Non-commercial sports activities (government invitation, international championships, international sports organizations).', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False, 'government_fee_internal': 'Rp 2,000,000.'}},
    {'code': 'C8B', 'name': 'Visa Kunjungan Ofisial Olahraga', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kunjungan Ofisial Olahraga', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'C9', 'name': 'Visa Kunjungan Studi Singkat', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': ['Proof of registration/student status from the organizing institution.'], 'description': 'Comparative study, short courses, short training.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False, 'government_fee_internal': 'Rp 2,000,000.'}},
    {'code': 'C9A', 'name': 'Visa Kunjungan Pelatihan Singkat Keagamaan', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kunjungan Pelatihan Singkat Keagamaan', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'C9B', 'name': 'Visa Kunjungan Pelatihan Singkat Bahasa Indonesia', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kunjungan Pelatihan Singkat Bahasa Indonesia', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'C10', 'name': 'Visa Kunjungan Narasumber Kegiatan Bisnis', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': ['Invitation letter detailing the agenda.', 'Allowed to receive honorarium/compensation but not employment.'], 'description': 'Speaker, lecturer, or presenter at MICE or similar events.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False, 'government_fee_internal': 'Rp 2,000,000.'}},
    {'code': 'C10A', 'name': 'Visa Kunjungan Penceramah Agama', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kunjungan Penceramah Agama', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'C11', 'name': 'Visa Kunjungan Promosi Produk dan Jasa', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': ['Sponsor required.', 'Invitation from organizer.', ''], 'description': 'Participating in MICE events to market goods or services (Exhibitor).', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False, 'government_fee_internal': 'Rp 2,000,000.'}},
    {'code': 'C11A', 'name': 'Visa Kunjungan Promosi Produk dan Jasa', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kunjungan Promosi Produk dan Jasa', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'C12', 'name': 'Visa Kunjungan Pra-Investasi', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': ['Sponsor required.', 'Proof of funds (USD 2,000).', 'Documents clarifying the business relationship/intent.'], 'description': 'Pre-investment visits, starting a business, field surveys, feasibility studies.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'C13', 'name': 'Visa Kunjungan Awak Bergabung dengan Alat Angkut', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': ['Sponsor required.', 'Letter stating intent to join vessel.'], 'description': 'Joining a transport vehicle (ship/vessel) currently in Indonesian territory.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False, 'government_fee_internal': 'Rp 2,000,000.'}},
    {'code': 'C14', 'name': 'Visa Kunjungan Pembuatan dan Produksi Film', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': ['Sponsor required.', ''], 'description': 'Filmmaking, music videos, reality shows, documentaries, TV/radio, etc. using locations in Indonesia.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False, 'government_fee_internal': 'Rp 2,000,000.'}},
    {'code': 'C15', 'name': 'Visa Kunjungan Penanganan Keadaan Darurat', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': ['Sponsor required.', 'Statement of urgency explaining why the foreign expert is needed immediately.'], 'description': 'Emergency and urgent work that cannot be delegated (e.g., natural disaster recovery, machine repair, riot control).', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False, 'government_fee_internal': 'Rp 3,000,000.'}},
    {'code': 'C16', 'name': 'Visa Kunjungan Instruktur Pengembangan Industri', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Providing guidance, counseling, and training in industrial technology innovation/application.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False, 'government_fee_internal': 'Rp 3,000,000.  ================================================================================'}},
    {'code': 'C17', 'name': 'Visa Kunjungan Audit, Kendali Mutu, dan Inspeksi Perusahaan', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Auditing, production quality control, or inspection at a company branch in Indonesia.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False, 'government_fee_internal': 'Rp 3,000,000.  ================================================================================'}},
    {'code': 'C18', 'name': 'Visa Kunjungan Uji Kemampuan Tenaga Kerja Asing', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'IDR 5.500.000', 'requirements': ['Sponsor required.', 'Invitation for competency test.'], 'description': 'Testing proficiency/skills for work (trial).', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': True, 'government_fee_internal': 'Rp 4,000,000.'}},
    {'code': 'C19', 'name': 'Visa Kunjungan Layanan Purna Jual', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Providing after-sales service for goods/products sold to consumers in Indonesia.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False, 'government_fee_internal': 'Rp 3,000,000.  ================================================================================'}},
    {'code': 'C20', 'name': 'Visa Kunjungan Pemasangan dan Perbaikan Mesin', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Installation and repair of machinery as part of a purchase agreement from abroad.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False, 'government_fee_internal': 'Rp 3,000,000.  ================================================================================'}},
    {'code': 'C21', 'name': 'Visa Kunjungan Menghadiri Proses Peradilan', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kunjungan Menghadiri Proses Peradilan', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'C22', 'name': 'Visa Kunjungan Pemagangan', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kunjungan Pemagangan', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'C22A', 'name': 'Visa Kunjungan Pemagangan Akademik', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'IDR 4.800.000', 'requirements': [], 'description': 'Official title: Visa Kunjungan Pemagangan Akademik', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': True}},
    {'code': 'C22B', 'name': 'Visa Kunjungan Pemagangan Kompetensi', 'category': 'Visit Visa', 'duration': 'See details', 'cost_visa': 'IDR 4.800.000', 'requirements': [], 'description': 'Official title: Visa Kunjungan Pemagangan Kompetensi', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': True}},
    {'code': 'D1', 'name': 'Visa Kunjungan Wisata', 'category': 'Multiple Entry', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': ['Proof of funds (USD 2,000).', 'Statement letter from relative (if visiting family) or invitation.'], 'description': 'Tourism, family visits, MICE (attendee), transit.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False, 'government_fee_internal': '*   1 Year: Rp 4,000,000. *   2 Years: Rp 6,000,000. *   5 Years: Rp 11,000,000.'}},
    {'code': 'D2', 'name': 'Visa Kunjungan Bisnis', 'category': 'Multiple Entry', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': ['Invitation letter/correspondence from partner.', 'Prohibited from continuous supervision of production.'], 'description': 'Business, meetings, purchasing goods, negotiations.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False, 'government_fee_internal': '*   1 Year: Rp 4,000,000. *   2 Years: Rp 6,000,000. *   5 Years: Rp 11,000,000.'}},
    {'code': 'D3', 'name': 'Visa Kunjungan Perawatan Kesehatan', 'category': 'Multiple Entry', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kunjungan Perawatan Kesehatan', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'D4', 'name': 'Visa Kunjungan Penugasan Pemerintah', 'category': 'Multiple Entry', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kunjungan Penugasan Pemerintah', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'D7', 'name': 'Visa Kunjungan Penampilan Seni dan Budaya', 'category': 'Multiple Entry', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kunjungan Penampilan Seni dan Budaya', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'D8', 'name': 'Visa Kunjungan Kegiatan Olahraga', 'category': 'Multiple Entry', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kunjungan Kegiatan Olahraga', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'D12', 'name': 'Visa Kunjungan Pra-Investasi', 'category': 'Multiple Entry', 'duration': 'See details', 'cost_visa': 'IDR 7.500.000', 'requirements': ['Proof of funds (USD 5,000).'], 'description': 'Pre-investment, business setup, surveys.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': True, 'government_fee_internal': '*   1 Year: Rp 5,000,000. *   2 Years: Rp 7,000,000.'}},
    {'code': 'D14', 'name': 'Visa Kunjungan Pembuatan and Produksi Film', 'category': 'Multiple Entry', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kunjungan Pembuatan and Produksi Film', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'D17', 'name': 'Visa Kunjungan Audit, Kendali Mutu, dan Inspeksi Perusahaan', 'category': 'Multiple Entry', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kunjungan Audit, Kendali Mutu, dan Inspeksi Perusahaan', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E23', 'name': 'Visa Kerja', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'IDR 34.500.000 (Offshore) / 36.000.000 (Onshore)', 'requirements': [], 'description': 'Working in Indonesia.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': True}},
    {'code': 'E23A', 'name': 'Visa Kerja Kawasan Ekonomi Khusus', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'IDR 34.500.000 (Offshore) / 36.000.000 (Onshore)', 'requirements': [], 'description': 'Official title: Visa Kerja Kawasan Ekonomi Khusus', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': True, 'inherited_from': 'E23'}},
    {'code': 'E23U', 'name': 'Visa Kerja Asisten Rumah Tangga Diplomat Asing', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'IDR 34.500.000 (Offshore) / 36.000.000 (Onshore)', 'requirements': [], 'description': 'Official title: Visa Kerja Asisten Rumah Tangga Diplomat Asing', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': True, 'inherited_from': 'E23'}},
    {'code': 'E23V', 'name': 'Visa Kerja Kantor Dagang dan Ekonomi', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'IDR 34.500.000 (Offshore) / 36.000.000 (Onshore)', 'requirements': [], 'description': 'Official title: Visa Kerja Kantor Dagang dan Ekonomi', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': True, 'inherited_from': 'E23'}},
    {'code': 'E23X', 'name': 'Visa Kerja Tenaga Ahli Pemerintah Indonesia', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'IDR 34.500.000 (Offshore) / 36.000.000 (Onshore)', 'requirements': [], 'description': 'Official title: Visa Kerja Tenaga Ahli Pemerintah Indonesia', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': True, 'inherited_from': 'E23'}},
    {'code': 'E23Y', 'name': 'Visa Kerja Tenaga Ahli Bidang Digital', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'IDR 34.500.000 (Offshore) / 36.000.000 (Onshore)', 'requirements': [], 'description': 'Official title: Visa Kerja Tenaga Ahli Bidang Digital', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': True, 'inherited_from': 'E23'}},
    {'code': 'E25', 'name': 'Visa Kerja Komisaris dan Eksekutif Perusahaan', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kerja Komisaris dan Eksekutif Perusahaan', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E25A', 'name': 'Visa Kerja Komisaris Perusahaan', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kerja Komisaris Perusahaan', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E25B', 'name': 'Visa Kerja Direktur Perusahaan', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kerja Direktur Perusahaan', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E25C', 'name': 'Visa Kerja Wakil Direktur Perusahaan', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kerja Wakil Direktur Perusahaan', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E25D', 'name': 'Visa Kerja Manajer Umum Perusahaan', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kerja Manajer Umum Perusahaan', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E25E', 'name': 'Visa Kerja Manajer Perusahaan', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kerja Manajer Perusahaan', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E25F', 'name': 'Visa Kerja Supervisor Perusahaan', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kerja Supervisor Perusahaan', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E26', 'name': 'Visa Kerja Awak Kapal, Alat Apung, dan Instalasi Lepas Pantai', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kerja Awak Kapal, Alat Apung, dan Instalasi Lepas Pantai', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E27', 'name': 'Visa Kerja Rohaniwan', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kerja Rohaniwan', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E29', 'name': 'Visa Kerja Peneliti', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kerja Peneliti', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E28', 'name': 'Visa Investor', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Investor', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E28A', 'name': 'Visa Investor', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'IDR 17.000.000 (Offshore) / 19.000.000 (Onshore)', 'requirements': ['Proof of share ownership (min. Rp 10 billion) in the sponsor company.', 'If shares are lower, must apply for a Work Visa.'], 'description': 'Investing, managing a company (Director/Commissioner), establishing a company.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': True, 'government_fee_internal': '*   1 Year: Rp 7,000,000. *   2 Years: Rp 9,500,000.'}},
    {'code': 'E28B', 'name': 'Visa Investor Pendirian Perusahaan Golden Visa', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [''], 'description': 'High-value investment/Golden Visa. Establishing a company.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False, 'government_fee_internal': '*   5 Years: Rp 13,000,000. *   10 Years: Rp 19,500,000.'}},
    {'code': 'E28C', 'name': 'Visa Investor Pasar Modal Golden Visa', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Investor Pasar Modal Golden Visa', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E28D', 'name': 'Visa Investor Pendirian Cabang atau Anak Perusahaan Golden Visa', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Investor Pendirian Cabang atau Anak Perusahaan Golden Visa', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E28E', 'name': 'Visa Investor Kawasan Ekonomi Khusus', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Investor Kawasan Ekonomi Khusus', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E28F', 'name': 'Visa Investor Pendirian Cabang atau Anak Perusahaan di Ibu Kota Nusantara', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Investor Pendirian Cabang atau Anak Perusahaan di Ibu Kota Nusantara', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E28G', 'name': 'Visa Investor Perwakilan Perusahaan Induk', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Investor Perwakilan Perusahaan Induk', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E30', 'name': 'Visa Pendidikan', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Pendidikan', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E30A', 'name': 'Visa Pendidikan Dasar dan Menengah', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Pendidikan Dasar dan Menengah', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E30B', 'name': 'Visa Pendidikan Tinggi', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Pendidikan Tinggi', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E30E', 'name': 'Visa Pendidikan Kawasan Ekonomi Khusus', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Pendidikan Kawasan Ekonomi Khusus', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E30F', 'name': 'Visa Pertukaran Pelajar', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Pertukaran Pelajar', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E31', 'name': 'Visa Keluarga', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Keluarga', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E31A', 'name': 'Visa Keluarga Suami/Istri WNI', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'IDR 11.000.000 (1 Year) / 15.000.000 (2 Years)', 'requirements': [], 'description': 'Official title: Visa Keluarga Suami/Istri WNI', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': True}},
    {'code': 'E31B', 'name': 'Visa Keluarga Suami/Istri Pemegang ITAS/ITAP', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'IDR 11.000.000 (1 Year) / 15.000.000 (2 Years)', 'requirements': [], 'description': 'Official title: Visa Keluarga Suami/Istri Pemegang ITAS/ITAP', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': True}},
    {'code': 'E31C', 'name': 'Visa Keluarga Anak Hasil Perkawinan Sah WNA-WNI', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Keluarga Anak Hasil Perkawinan Sah WNA-WNI', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E31D', 'name': 'Visa Keluarga Anak Bawaan WNA Perkawinan Sah WNA-WNI', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Keluarga Anak Bawaan WNA Perkawinan Sah WNA-WNI', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E31E', 'name': 'Visa Keluarga Anak Pemegang ITAS/ITAP', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Keluarga Anak Pemegang ITAS/ITAP', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E31F', 'name': 'Visa Keluarga Anak Dengan Orang Tua WNI', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'IDR 11.000.000 (1 Year) / 15.000.000 (2 Years)', 'requirements': [], 'description': 'Official title: Visa Keluarga Anak Dengan Orang Tua WNI', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': True}},
    {'code': 'E31G', 'name': 'Visa Keluarga Orang Tua dari Anak WNI', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Keluarga Orang Tua dari Anak WNI', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E31H', 'name': 'Visa Keluarga Orang Tua dari Anak Pemegang ITAS/ITAP', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Keluarga Orang Tua dari Anak Pemegang ITAS/ITAP', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E31J', 'name': 'Visa Keluarga Anak yang Bergabung dengan Saudara Kandung Pemegang ITAS/ITAP', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Keluarga Anak yang Bergabung dengan Saudara Kandung Pemegang ITAS/ITAP', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E32', 'name': 'Visa Repatriasi dan Keturunan EX-WNI', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Repatriasi dan Keturunan EX-WNI', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E32A', 'name': 'Visa Repatriasi 5 Tahun', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Repatriasi 5 Tahun', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E32B', 'name': 'Visa Keturunan EX-WNI 5 Atau 10 Tahun Golden Visa', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Keturunan EX-WNI 5 Atau 10 Tahun Golden Visa', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E32C', 'name': 'Visa Repatriasi 2 Tahun', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Repatriasi 2 Tahun', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E32D', 'name': 'Visa Repatriasi 1 Tahun Golden Visa', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Repatriasi 1 Tahun Golden Visa', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E32E', 'name': 'Visa Repatriasi Tinggal Tetap Global Citizen of Indonesia', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Repatriasi Tinggal Tetap Global Citizen of Indonesia', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E32F', 'name': 'Visa Repatriasi Keahlian Khusus Global Citizen of Indonesia', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Repatriasi Keahlian Khusus Global Citizen of Indonesia', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E32G', 'name': 'Visa Keturunan EX-WNI Tinggal Tetap Global Citizen of Indonesia', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Keturunan EX-WNI Tinggal Tetap Global Citizen of Indonesia', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E32H', 'name': 'Visa Keturunan EX-WNI Keahlian Khusus Global Citizen of Indonesia', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Keturunan EX-WNI Keahlian Khusus Global Citizen of Indonesia', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E33', 'name': 'Visa Rumah Kedua', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': ['Proof of funds/Guarantee (Proof of Funds) of min.'], 'description': 'Long-term stay for business, investment, or retirement.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False, 'government_fee_internal': 'Rp 13,000,000.'}},
    {'code': 'E33A', 'name': 'Visa Rumah Kedua Tenaga Ahli Undangan Pemerintah', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Rumah Kedua Tenaga Ahli Undangan Pemerintah', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E33B', 'name': 'Visa Rumah Kedua Kolaborasi Keahlian Khusus Golden Visa', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Rumah Kedua Kolaborasi Keahlian Khusus Golden Visa', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E33C', 'name': 'Visa Rumah Kedua Tokoh Dunia Undangan Pemerintah', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Rumah Kedua Tokoh Dunia Undangan Pemerintah', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E33D', 'name': 'Visa Rumah Kedua Tokoh Dunia Pendirian Perusahaan', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Rumah Kedua Tokoh Dunia Pendirian Perusahaan', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E33E', 'name': 'Visa Rumah Kedua Lansia Untuk 5 Tahun Golden Visa', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'IDR 14.000.000 (Offshore) / 16.000.000 (Onshore)', 'requirements': [], 'description': 'Official title: Visa Rumah Kedua Lansia Untuk 5 Tahun Golden Visa', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': True}},
    {'code': 'E33F', 'name': 'Visa Rumah Kedua Lansia Untuk 1 Tahun', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'IDR 14.000.000 (Offshore) / 16.000.000 (Onshore)', 'requirements': [], 'description': 'Official title: Visa Rumah Kedua Lansia Untuk 1 Tahun', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': True}},
    {'code': 'E33G', 'name': 'Visa Rumah Kedua Pekerja Jarak Jauh Golden Visa', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'IDR 13.000.000 (Offshore) / 14.000.000 (Onshore)', 'requirements': ['Proof of income/salary min.'], 'description': 'Staying in Indonesia while working remotely for a company', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': True, 'government_fee_internal': 'Rp 7,000,000.'}},
    {'code': 'E34', 'name': 'Visa Perawatan Kesehatan', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Perawatan Kesehatan', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E35', 'name': 'Visa Kemudahan Bekerja Saat Berlibur', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kemudahan Bekerja Saat Berlibur', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': True}},
    {'code': 'E35A', 'name': 'Visa Kemudahan Bekerja Saat Berlibur Australia', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'Contact for Quote', 'requirements': [], 'description': 'Official title: Visa Kemudahan Bekerja Saat Berlibur Australia', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': False}},
    {'code': 'E23-FREELANCE', 'name': 'Freelance KITAS (E23)', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'IDR 25.800.000 (Offshore) / 27.500.000 (Onshore)', 'requirements': [], 'description': 'Working in Indonesia.', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': True}},
    {'code': 'EPO', 'name': 'EPO (Exit Permit Only)', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'IDR 700.000', 'requirements': [], 'description': 'Official title: EPO (Exit Permit Only)', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': True}},
    {'code': 'ERP', 'name': 'ERP (Exit Re-entry Permit)', 'category': 'KITAS/Limited Stay', 'duration': 'See details', 'cost_visa': 'IDR 800.000', 'requirements': [], 'description': 'Official title: ERP (Exit Re-entry Permit)', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': True}},
    {'code': 'SKTT', 'name': 'SKTT Registration', 'category': 'Immigration Service', 'duration': 'See details', 'cost_visa': 'IDR 1.500.000', 'requirements': [], 'description': 'Official title: SKTT Registration', 'metadata': {'source': 'zantara_curated_2026', 'is_agency_product': True}},

]

async def seed_visa_types():
    db_url = os.environ.get("DATABASE_URL")
    conn = await asyncpg.connect(db_url)
    try:
        print(f"Seeding {len(VISA_TYPES)} Curated Visa Types...")
        await conn.execute("CREATE TABLE IF NOT EXISTS visa_types (code TEXT PRIMARY KEY, name TEXT, category TEXT, description TEXT, duration TEXT, cost_visa TEXT, requirements TEXT[], metadata JSONB, created_at TIMESTAMP DEFAULT NOW(), last_updated TIMESTAMP DEFAULT NOW())")
        try: await conn.execute("ALTER TABLE visa_types ADD COLUMN IF NOT EXISTS description TEXT;")
        except: pass
        
        for visa in VISA_TYPES:
            exists = await conn.fetchval("SELECT 1 FROM visa_types WHERE code = $1", visa["code"])
            if exists:
                await conn.execute("UPDATE visa_types SET name=$2, category=$3, description=$4, duration=$5, cost_visa=$6, requirements=$7, metadata=$8, last_updated=NOW() WHERE code=$1", 
                    visa["code"], visa["name"], visa["category"], visa["description"], visa["duration"], visa["cost_visa"], visa["requirements"], json.dumps(visa["metadata"]))
            else:
                await conn.execute("INSERT INTO visa_types (code, name, category, description, duration, cost_visa, requirements, metadata) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)", 
                    visa["code"], visa["name"], visa["category"], visa["description"], visa["duration"], visa["cost_visa"], visa["requirements"], json.dumps(visa["metadata"]))
        print("Done.")
    finally: await conn.close()

if __name__ == "__main__":
    asyncio.run(seed_visa_types())
