"""Actuator: open PR to consolidate a single redundancy from redundancies.yaml.

L3 actuator — IRREVERSIBLE (shared-infra effect). Consiglio gate requires
3/4 approval before dispatch. The actuator itself opens a draft PR; the
actual merge is a separate human-in-the-loop step (W4 auto-merge when CI
green only applies to feature-branch PRs, not infra consolidation).

Each call consolidates ONE redundancy (by `id`) — this is deliberate:
multiple parallel PRs = reviewable independently.
"""
from __future__ import annotations

import asyncio
import logging
from pathlib import Path
import yaml
from organism.actuators.base import ActuatorBase


log = logging.getLogger(__name__)

REDUNDANCIES_YAML_PATH = Path(__file__).resolve().parents[1] / "redundancies.yaml"


class ConsolidateRedundancy(ActuatorBase):
    name = "consolidate_redundancy"

    def __init__(self, *, yaml_path: Path | None = None):
        self.yaml_path = yaml_path or REDUNDANCIES_YAML_PATH

    async def _execute(self, params: dict) -> dict:
        redundancy_id = params["redundancy_id"]
        entry = self._load_entry(redundancy_id)
        if entry is None:
            return {"success": False, "error": f"unknown redundancy_id: {redundancy_id}"}
        branch = f"organism/consolidate-{redundancy_id}"
        plan_md = self._render_plan_md(entry)
        # Branch creation + push + PR are all shell-outs to git + gh
        branch_result = await self._create_branch_and_plan_file(branch, redundancy_id, plan_md)
        if not branch_result["ok"]:
            return {
                "success": False,
                "error": branch_result.get("error", "branch_create_failed"),
                "redundancy_id": redundancy_id,
            }
        push_result = await self._git_push(branch)
        if not push_result["ok"]:
            return {
                "success": False,
                "error": push_result.get("error", "push_failed"),
                "redundancy_id": redundancy_id,
                "branch": branch,
            }
        pr_result = await self._gh_pr_create(branch, entry)
        return {
            "redundancy_id": redundancy_id,
            "branch": branch,
            "pr_url": pr_result.get("url"),
            "pr_created": pr_result.get("ok", False),
        }

    async def _dry_run(self, params: dict) -> dict:
        redundancy_id = params.get("redundancy_id")
        if redundancy_id:
            entry = self._load_entry(redundancy_id)
            if entry is None:
                return {"error": f"unknown redundancy_id: {redundancy_id}"}
            return {
                "would_open_pr_for": redundancy_id,
                "strategy": entry.get("strategy"),
                "targets": entry.get("targets", []),
                "branch": f"organism/consolidate-{redundancy_id}",
            }
        # No specific ID — list all available consolidations
        entries = self._load_all()
        return {
            "available_consolidations": [
                {"id": e["id"], "strategy": e.get("strategy"), "target_count": len(e.get("targets", []))}
                for e in entries
            ],
        }

    def _load_all(self) -> list[dict]:
        try:
            data = yaml.safe_load(self.yaml_path.read_text(encoding="utf-8"))
            return data.get("redundancies", [])
        except Exception:
            log.exception("consolidate_redundancy: failed to load redundancies.yaml")
            return []

    def _load_entry(self, redundancy_id: str) -> dict | None:
        for entry in self._load_all():
            if entry.get("id") == redundancy_id:
                return entry
        return None

    @staticmethod
    def _render_plan_md(entry: dict) -> str:
        targets = "\n".join(f"- {t}" for t in entry.get("targets", []))
        prefer = entry.get("prefer", "")
        prefer_line = f"\n**Keep:** `{prefer}`\n" if prefer else ""
        return f"""# Consolidation proposal: {entry['id']}

**Description:** {entry['description']}

**Strategy:** {entry['strategy']}
{prefer_line}

## Targets
{targets}

## Severity
{entry.get('severity', 'medium')}

## Actions required
Human reviewer must decide:
1. Audit each target for callers / schedulers
2. Produce consolidated implementation (separate commit)
3. Remove the redundant ones once the consolidated path is verified

Generated by organism `consolidate_redundancy` actuator.
"""

    async def _create_branch_and_plan_file(
        self, branch: str, redundancy_id: str, plan_md: str,
    ) -> dict:
        rc, _, err = await self._run(["git", "checkout", "-b", branch])
        if rc != 0:
            return {"ok": False, "error": f"checkout -b {branch}: {err[:200]}"}
        plan_path = Path(f"docs/organism/consolidations/{redundancy_id}.md")
        try:
            plan_path.parent.mkdir(parents=True, exist_ok=True)
            plan_path.write_text(plan_md, encoding="utf-8")
        except OSError as exc:
            return {"ok": False, "error": f"write plan: {exc}"}
        rc, _, err = await self._run(["git", "add", str(plan_path)])
        if rc != 0:
            return {"ok": False, "error": f"git add: {err[:200]}"}
        rc, _, err = await self._run([
            "git", "commit",
            "-m", f"docs(organism): propose consolidation for {redundancy_id}",
        ])
        if rc != 0:
            return {"ok": False, "error": f"commit: {err[:200]}"}
        return {"ok": True, "plan_path": str(plan_path)}

    async def _git_push(self, branch: str) -> dict:
        rc, _, err = await self._run(["git", "push", "-u", "origin", branch])
        if rc != 0:
            return {"ok": False, "error": f"push: {err[:200]}"}
        return {"ok": True}

    async def _gh_pr_create(self, branch: str, entry: dict) -> dict:
        title = f"docs(organism): consolidate {entry['id']}"
        body = self._render_plan_md(entry)
        rc, out, err = await self._run([
            "gh", "pr", "create",
            "--title", title,
            "--body", body,
            "--head", branch,
            "--draft",
        ])
        if rc != 0:
            return {"ok": False, "error": f"pr create: {err[:200]}"}
        return {"ok": True, "url": out.strip()}

    @staticmethod
    async def _run(cmd: list[str]) -> tuple[int, str, str]:
        try:
            proc = await asyncio.create_subprocess_exec(
                *cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            out, err = await asyncio.wait_for(proc.communicate(), timeout=30.0)
            return (
                proc.returncode or 0,
                out.decode("utf-8", errors="replace"),
                err.decode("utf-8", errors="replace"),
            )
        except (asyncio.TimeoutError, FileNotFoundError, OSError) as exc:
            return (-1, "", str(exc)[:200])
