from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from PIL import Image

from backend.services.multimodal.pdf_vision_service import *  # noqa: F403
from backend.services.multimodal.pdf_vision_service import PDFVisionService

# Test Suite for pdf_vision_service.py
# Generated by Overlord Test Forge


# ---------------------------------------------------------------------------
# PII-sovereignty gate on the Gemini fallback (SYMBIOSIS Law 2 / UU PDP Art.56)
# ---------------------------------------------------------------------------


class TestAnalyzeViaGeminiPIIGate:
    @pytest.mark.asyncio
    async def test_blocked_returns_none_without_touching_client(self) -> None:
        """When cloud vision is NOT allowed, _analyze_via_gemini returns None and
        never constructs/calls the genai client (no PII leaves the machine)."""
        svc = PDFVisionService(api_key="dummy")
        # If the gate failed open, this spy would be called → test would catch it.
        spy_get_client = MagicMock(side_effect=AssertionError("client must NOT be built when blocked"))
        with (
            patch(
                "backend.services.multimodal.cloud_vision_gate.cloud_vision_allowed",
                return_value=False,
            ),
            patch(
                "backend.services.multimodal.cloud_vision_gate.note_cloud_ocr_blocked",
            ) as note,
            patch.object(svc, "_get_genai_client", spy_get_client),
        ):
            result = await svc._analyze_via_gemini("prompt", "Zm9v")  # "foo" b64
        assert result is None
        note.assert_called_once()
        # the context string identifies the chokepoint
        assert "pdf_vision_service" in note.call_args.args[0]

    @pytest.mark.asyncio
    async def test_allowed_but_no_client_returns_none(self) -> None:
        """When allowed but the genai client is unavailable, returns None via the
        normal path (proves the gate doesn't change happy/empty behavior)."""
        svc = PDFVisionService(api_key="dummy")
        with (
            patch(
                "backend.services.multimodal.cloud_vision_gate.cloud_vision_allowed",
                return_value=True,
            ),
            patch.object(svc, "_get_genai_client", MagicMock(return_value=None)),
        ):
            result = await svc._analyze_via_gemini("prompt", "Zm9v")
        assert result is None


@pytest.mark.asyncio
async def test_analyze_page_prefers_local_ollama_result() -> None:
    svc = PDFVisionService(api_key="dummy")
    svc._render_page_to_image = MagicMock(return_value=Image.new("RGB", (1, 1)))
    svc._analyze_via_ollama = AsyncMock(return_value="local OCR")
    svc._analyze_via_gemini = AsyncMock(return_value="cloud OCR")

    result = await svc.analyze_page("/tmp/doc.pdf", 1, prompt="extract")

    assert result == "local OCR"
    svc._render_page_to_image.assert_called_once_with("/tmp/doc.pdf", 1)
    svc._analyze_via_ollama.assert_awaited_once()
    svc._analyze_via_gemini.assert_not_called()


@pytest.mark.asyncio
async def test_extract_kbli_table_analyzes_each_page_without_drive_download() -> None:
    svc = PDFVisionService(api_key="dummy")
    svc.analyze_page = AsyncMock(side_effect=["page one", "page two"])

    result = await svc.extract_kbli_table("/tmp/kbli.pdf", (1, 2), is_drive_file=False)

    assert result == "--- Page 1 ---\npage one\n--- Page 2 ---\npage two"
    assert svc.analyze_page.await_args_list[0].args[:2] == ("/tmp/kbli.pdf", 1)
    assert svc.analyze_page.await_args_list[1].args[:2] == ("/tmp/kbli.pdf", 2)


@pytest.mark.asyncio
async def test_extract_text_delegates_to_injected_ai_client() -> None:
    ai_client = MagicMock()
    ai_client.extract_pdf_text = AsyncMock(return_value="delegated text")
    svc = PDFVisionService(api_key="dummy", ai_client=ai_client)

    result = await svc.extract_text(b"%PDF")

    assert result == "delegated text"
    ai_client.extract_pdf_text.assert_awaited_once_with(b"%PDF")


@pytest.mark.asyncio
async def test_analyze_vision_delegates_to_injected_ai_client() -> None:
    ai_client = MagicMock()
    ai_client.analyze_pdf_vision = AsyncMock(return_value={"text": "vision text"})
    svc = PDFVisionService(api_key="dummy", ai_client=ai_client)

    result = await svc.analyze_vision(b"%PDF")

    assert result == {"text": "vision text"}
    ai_client.analyze_pdf_vision.assert_awaited_once_with(b"%PDF")


@pytest.mark.asyncio
async def test_analyze_vision_falls_back_to_text_structure() -> None:
    svc = PDFVisionService(api_key="dummy")
    svc.extract_text = AsyncMock(return_value="plain text")

    result = await svc.analyze_vision(b"%PDF")

    assert result == {
        "text": "plain text",
        "structure": {"pages": 1, "sections": 0},
    }
