"""Denial-shaped tool observations: minted here, recognised here.

WHY THIS MODULE EXISTS (measured in prod, 2026-08-10)
-----------------------------------------------------
`tool_executor` hands the LLM a string when an authorizer refuses a tool call.
`_reasoning_evidence` then decides whether any "trusted tool" produced real
content — and it decided that by scanning the observation's PROSE for failure
words (``"error"``, ``"not found"``, ``"no relevant"``) plus a length floor of
50 characters.

The anonymous denial string is 54 characters long and, by deliberate design,
"names no tool, no control, no internal system" — it was written that way in
P0-DENY (2026-07-25) so the model would have nothing interesting to narrate to
a client. That same blandness is exactly what makes it invisible to a
failure-word scan. Four characters over the floor, zero failure words: a
REFUSED tool call scored as a SUCCESSFUL one.

Live consequence, from the prod log of a WhatsApp-shaped query
("Any deadlines I should worry about for my clients this week?"):

    tool_authz decision=deny ... principal_present=False
    🔧 [Trusted Tools] crm_query used successfully (obs_len=54), bypassing
       keyword evidence check
    🛡️ [Evidence] Trusted tools used: score=0.85

0.85 is the highest evidence score the system can assign, and it bypasses the
keyword evidence path entirely — so a denial was buying an answer the same
confidence as a satisfied query. Neither lane was wrong on its own; they were
never compared (cicatrix #9 / W114: "the two sides never agreed").

THE RULE
--------
The set of denial-shaped observations is CLOSED and generated by ONE function.
So it is recognised by ONE predicate, matching what the mint produced — never
by guessing at prose. That is the cicatrix #3 antidote applied literally:
judge the ENTITY (this string was minted as a denial), not the FORM (this
string looks like it failed).

Kept dependency-free on purpose: both `tool_executor` (which mints) and
`_reasoning_evidence` (which recognises) import it at module level, and
neither can drag the other into an import cycle.
"""

from __future__ import annotations

from typing import Any

# The fixed, non-diagnostic observation handed to a caller with NO principal
# (client / unknown WA sender / public blog-ask). Names no tool and no control
# — see the P0-DENY comment in tool_executor.py for why that matters.
ANONYMOUS_DENIAL_OBSERVATION = "This capability is not available in this conversation."

# The informative form, for a resolved agent_role (authenticated/team caller).
# A named constant rather than an inline f-string so the mint and the
# recogniser cannot drift apart in a later edit.
DENIAL_PREFIX = "Tool execution denied: "


def denial_observation(agent_role: Any | None, detail: str) -> str:
    """Render a denial-shaped tool observation, audience-aware.

    `detail` is always the full, informative reason (never pre-redacted by the
    caller). With a resolved `agent_role` this returns the
    ``"Tool execution denied: {detail}"`` shape; with `agent_role=None` it
    returns the fixed neutral string, dropping `detail` entirely.
    """
    if agent_role is None:
        return ANONYMOUS_DENIAL_OBSERVATION
    return f"{DENIAL_PREFIX}{detail}"


def is_denial_observation(observation: str | None) -> bool:
    """True iff `observation` was minted by :func:`denial_observation`.

    Deliberately narrow. This answers "did an authorizer refuse this call?",
    NOT "does this text look like a failure" — a legitimate tool result that
    happens to discuss a denial (a KB chunk about visa refusals, say) is not a
    denial and must keep granting trust. `test_tool_denial_is_not_evidence.py`
    pins both directions.
    """
    if not observation:
        return False
    return observation == ANONYMOUS_DENIAL_OBSERVATION or observation.startswith(
        DENIAL_PREFIX
    )
